### ISSUE TITLE
500 Internal Server Error when trying to apply RSS changes

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#1005]
I have several RSS feeds and regularly adjust them, mostly adding new keywords to reject. When pressing "apply changes" today, this error message appeared:

    500 Internal Server Error

    The server encountered an unexpected condition which prevented it from fulfilling the request.

    Traceback (most recent call last):
       File "/home/abc/.sabnzbd/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/home/abc/.sabnzbd/cherrypy/lib/encoding.py", line 220, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/home/abc/.sabnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
         return self.callable(*self.args, **self.kwargs)
      File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 1812, in index
        ignoreFirst=self.__refresh_ignore, readout=readout)
      File "/home/abc/.sabnzbd/sabnzbd/rss.py", line 65, in run_feed
        return __RSS.run_feed(feed, download, ignoreFirst, force=force, readout=readout)
      File "/home/abc/.sabnzbd/sabnzbd/decorators.py", line 30, in newFunction
        return f(*args, **kw)
      File "/home/abc/.sabnzbd/sabnzbd/rss.py", line 319, in run_feed for entry in entries:
    TypeError: 'NoneType' object is not iterable

    Powered by CherryPy 8.1.2

This happened for the first time AFAICT. I'm on 2.3.0-develop (up to date), Linux machine. Python is 2.7.13 (default, Mar 22 2017, 12:31:17) [GCC] [UTF-8], OpenSSL 1.0.2j-fips 26 Sep 2016   [TLS v1.2, TLS v1.1, TLS v1, SSL v3], MulticorPar2 is enabled.

**Comment by Safihre** [comment]
Fixed!

**Comment by anonvoy** [comment]
That was fast, thx.
