### ISSUE TITLE
"Cryptography module... NOT found!" on Ubuntu/Debian ... make it required package?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1018]
pinging @jcfp 

**Short**
What do you think of adding `python-cryptography` to the list of required packages on Ubuntu/Debian?

**Long**
I did an install of sabnzbd aka sabnzbdplus (2.2.1, via PPA) on a fresh Ubuntu. After starting SAB, I got:

`2017-09-01 14:21:12,481::INFO::[sabnzbdplus:412] Cryptography module... NOT found!
`

Ah, not good. Solution:
`sudo apt-get install python-cryptography`

... and all good:
`2017-09-01 14:31:06,427::INFO::[sabnzbdplus:410] Cryptography module (v1.2.3)... found!`

So ... add it is a required (recommended?) package?

**Comment by jcfp** [comment]
It already is a recommended dependency (unless I made some dumb mistake since):
```
sabnzbdplus (1.1.1-0ubuntu1~jcfp1~xenial) xenial; urgency=medium

  * New upstream release.
  * Control: recommend python-cryptography, needed for certs and
    rarfile encryption detection. Xenial and newer only, needs version
    1.2 or newer according to upstream docs.
```

**Comment by sanderjo** [comment]
And recommended packages are installed automatically, aren't they?

If so: why didn't it happen on my Ubuntu 16.04.3 LTS Xenial, on ARM64 ?

FWIW: my sequence was:
```
sudo apt-get install sabnzbdplus
sabnzbdplus -s 0.0.0.0 -b0
rm -rf .sabnzbd/
sudo add-apt-repository ppa:jcfp/ppa
sudo add-apt-repository ppa:jcfp/sab-addons
sudo apt-get update && sudo apt-get dist-upgrade
sabnzbdplus -s 0.0.0.0 -b0
sudo apt-get install sabnzbdplus python-sabyenc
sabnzbdplus -s 0.0.0.0 -b0
```
and then:
```
sudo apt-get install python-cryptography
```

I'll check if I can reproduce in a Docker container.

**Comment by sanderjo** [comment]
Hmmmm ... I can't reproducte in a Docker (on x86): python-cryptography already got installed while installing default sabnzbdplus 0.7.2 (???!!!)

So I'll close this.

```
apt-get update
apt-get install sabnzbdplus
python
sabnzbdplus -s 0.0.0.0 -b0
rm -rf /root/.sabnzbd/
add-apt-repository ppa:jcfp/ppa
apt-get install software-properties-common
add-apt-repository ppa:jcfp/ppa
add-apt-repository ppa:jcfp/sab-addons
apt-get update
apt-get upgrade
sabnzbdplus -s 0.0.0.0 -b0
apt-get install sabnzbdplus python-sabyenc
sabnzbdplus -s 0.0.0.0 -b0
```

**Comment by jcfp** [comment]
iirc the default setting these days (at least on desktop releases) is to install recommended deps. Could be different for server or minimal installs though. Wasn't always that way either which is why I put this in the ppa thread on the forums as the install command:
`apt-get -o APT::Install-Recommends=1 install sabnzbdplus`

**Comment by thezoggy** [comment]
@sandero why are you installing Sab before adding the PPA?

**Comment by sanderjo** [comment]
@jcfp I had to do a fresh install of my armbian Ubuntu on ARM64, so I tried again, and I can confirm my findings: python-cryptography not installed with the plain commands

First things:
```
sudo apt-get update
sudo apt-get upgrade
sudo add-apt-repository ppa:jcfp/ppa
sudo add-apt-repository ppa:jcfp/sab-addons
sudo apt-get update && sudo apt-get dist-upgrade
```

Check:
```
sander@nanopineo2:~$ python -c "import cryptography"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography
sander@nanopineo2:~$ 
```
... that's OK.

Then sab:
```
sander@nanopineo2:~$ sudo apt-get install sabnzbdplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libjs-bootstrap libjs-excanvas libjs-jquery libjs-jquery-ui libjs-mochikit libjs-moment python-cheetah python-configobj python-six
  python-yenc
Suggested packages:
  libjs-jquery-ui-docs python-markdown python-pygments python-memcache python-configobj-doc python-gtk2 python-notify
Recommended packages:
  javascript-common consolekit libavahi-compat-libdnssd1 p7zip-full par2 | par2-mt | par2-tbb python-cryptography python-dbus unrar | rar
The following NEW packages will be installed:
  libjs-bootstrap libjs-excanvas libjs-jquery libjs-jquery-ui libjs-mochikit libjs-moment python-cheetah python-configobj python-six
  python-yenc sabnzbdplus
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 2608 kB of archives.
After this operation, 12.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ports.ubuntu.com xenial/universe arm64 libjs-bootstrap all 3.3.6+dfsg-1 [227 kB]
Get:2 http://ppa.launchpad.net/jcfp/ppa/ubuntu xenial/main arm64 sabnzbdplus all 2.2.1-0ubuntu1~jcfp1~16.04 [1110 kB]
Get:3 http://ports.ubuntu.com xenial/universe arm64 libjs-excanvas all 0.r3-4 [45.2 kB]
Get:4 http://ports.ubuntu.com xenial/main arm64 libjs-jquery all 1.11.3+dfsg-4 [161 kB]
Get:5 http://ports.ubuntu.com xenial/universe arm64 libjs-jquery-ui all 1.10.1+dfsg-1 [458 kB]
Get:6 http://ports.ubuntu.com xenial/universe arm64 libjs-mochikit all 1.4.2-4fakesync1 [359 kB]
Get:7 http://ports.ubuntu.com xenial/universe arm64 libjs-moment all 2.11.0+ds-1 [38.4 kB]
Get:8 http://ports.ubuntu.com xenial/universe arm64 python-cheetah arm64 2.4.4-3.fakesyncbuild1 [143 kB]
Get:9 http://ports.ubuntu.com xenial/main arm64 python-six all 1.10.0-3 [10.9 kB]
Get:10 http://ports.ubuntu.com xenial/main arm64 python-configobj all 5.0.6-2 [34.2 kB]
Get:11 http://ports.ubuntu.com xenial/universe arm64 python-yenc arm64 0.4.0-1 [21.5 kB]
Fetched 2608 kB in 0s (3237 kB/s)      
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package libjs-bootstrap.
(Reading database ... 50769 files and directories currently installed.)
Preparing to unpack .../libjs-bootstrap_3.3.6+dfsg-1_all.deb ...
Unpacking libjs-bootstrap (3.3.6+dfsg-1) ...
Selecting previously unselected package libjs-excanvas.
Preparing to unpack .../libjs-excanvas_0.r3-4_all.deb ...
Unpacking libjs-excanvas (0.r3-4) ...
Selecting previously unselected package libjs-jquery.
Preparing to unpack .../libjs-jquery_1.11.3+dfsg-4_all.deb ...
Unpacking libjs-jquery (1.11.3+dfsg-4) ...
Selecting previously unselected package libjs-jquery-ui.
Preparing to unpack .../libjs-jquery-ui_1.10.1+dfsg-1_all.deb ...
Unpacking libjs-jquery-ui (1.10.1+dfsg-1) ...
Selecting previously unselected package libjs-mochikit.
Preparing to unpack .../libjs-mochikit_1.4.2-4fakesync1_all.deb ...
Unpacking libjs-mochikit (1.4.2-4fakesync1) ...
Selecting previously unselected package libjs-moment.
Preparing to unpack .../libjs-moment_2.11.0+ds-1_all.deb ...
Unpacking libjs-moment (2.11.0+ds-1) ...
Selecting previously unselected package python-cheetah.
Preparing to unpack .../python-cheetah_2.4.4-3.fakesyncbuild1_arm64.deb ...
Unpacking python-cheetah (2.4.4-3.fakesyncbuild1) ...
Selecting previously unselected package python-six.
Preparing to unpack .../python-six_1.10.0-3_all.deb ...
Unpacking python-six (1.10.0-3) ...
Selecting previously unselected package python-configobj.
Preparing to unpack .../python-configobj_5.0.6-2_all.deb ...
Unpacking python-configobj (5.0.6-2) ...
Selecting previously unselected package python-yenc.
Preparing to unpack .../python-yenc_0.4.0-1_arm64.deb ...
Unpacking python-yenc (0.4.0-1) ...
Selecting previously unselected package sabnzbdplus.
Preparing to unpack .../sabnzbdplus_2.2.1-0ubuntu1~jcfp1~16.04_all.deb ...
Preinst: good, no link at /usr/share/sabnzbdplus/interfaces/Config/templates/staticcfg/bootstrap
Preinst: good, no link at /usr/share/sabnzbdplus/interfaces/Glitter/templates/static/bootstrap
Unpacking sabnzbdplus (2.2.1-0ubuntu1~jcfp1~16.04) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up libjs-bootstrap (3.3.6+dfsg-1) ...
Setting up libjs-excanvas (0.r3-4) ...
Setting up libjs-jquery (1.11.3+dfsg-4) ...
Setting up libjs-jquery-ui (1.10.1+dfsg-1) ...
Setting up libjs-mochikit (1.4.2-4fakesync1) ...
Setting up libjs-moment (2.11.0+ds-1) ...
Setting up python-cheetah (2.4.4-3.fakesyncbuild1) ...
Setting up python-six (1.10.0-3) ...
Setting up python-configobj (5.0.6-2) ...
Setting up python-yenc (0.4.0-1) ...
Setting up sabnzbdplus (2.2.1-0ubuntu1~jcfp1~16.04) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
sander@nanopineo2:~$ 
````
... so python-cryptography is recommended, but ... : 
```
sander@nanopineo2:~$ python -c "import cryptography"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography
sander@nanopineo2:~$ 
```
... not installed.

**Comment by sanderjo** [comment]
Now your method with `apt-get -o APT::Install-Recommends=1 install sabnzbdplus` ... which indeed works!

Remove Sab first to get a clean setup:

```
sander@nanopineo2:~$ sudo apt-get remove sabnzbdplus 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libjs-bootstrap libjs-excanvas libjs-jquery libjs-jquery-ui libjs-mochikit libjs-moment python-cheetah python-configobj python-six
  python-yenc
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  sabnzbdplus
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 5584 kB disk space will be freed.
Do you want to continue? [Y/n] 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 51924 files and directories currently installed.)
Removing sabnzbdplus (2.2.1-0ubuntu1~jcfp1~16.04) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
sander@nanopineo2:~$ 

```

Then install with your command:
```
sander@nanopineo2:~$ 
sander@nanopineo2:~$ sudo apt-get -o APT::Install-Recommends=1 install sabnzbdplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  avahi-daemon consolekit libavahi-client3 libavahi-common-data libavahi-common3 libavahi-compat-libdnssd1 libavahi-core7 libck-connector0
  libnss-mdns libpam-ck-connector libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 p7zip-full par2 python-cffi-backend python-cryptography
  python-dbus python-enum34 python-gi python-idna python-ipaddress python-pkg-resources python-pyasn1 unrar
Suggested packages:
  p7zip-rar python-cryptography-doc python-cryptography-vectors python-dbus-doc python-dbus-dbg python-enum34-doc python-gi-cairo
  python-setuptools doc-base python-gtk2 python-notify
The following NEW packages will be installed:
  avahi-daemon consolekit libavahi-client3 libavahi-common-data libavahi-common3 libavahi-compat-libdnssd1 libavahi-core7 libck-connector0
  libnss-mdns libpam-ck-connector libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 p7zip-full par2 python-cffi-backend python-cryptography
  python-dbus python-enum34 python-gi python-idna python-ipaddress python-pkg-resources python-pyasn1 sabnzbdplus unrar
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 2684 kB/3794 kB of archives.
After this operation, 18.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ports.ubuntu.com xenial/main arm64 libxau6 arm64 1:1.0.8-1 [7590 B]
Get:2 http://ports.ubuntu.com xenial/universe arm64 libck-connector0 arm64 0.4.6-5 [8156 B]
Get:3 http://ports.ubuntu.com xenial/main arm64 libxdmcp6 arm64 1:1.1.2-1.1 [10.1 kB]
Get:4 http://ports.ubuntu.com xenial/main arm64 libxcb1 arm64 1.11.1-1ubuntu1 [33.3 kB]
Get:5 http://ports.ubuntu.com xenial/main arm64 libx11-data all 2:1.6.3-1ubuntu2 [113 kB]
Get:6 http://ppa.launchpad.net/jcfp/sab-addons/ubuntu xenial/main arm64 par2 arm64 0.7.2-0ubuntu1~jcfp1~xenial [93.6 kB]
Get:7 http://ports.ubuntu.com xenial/main arm64 libx11-6 arm64 2:1.6.3-1ubuntu2 [512 kB]
Get:8 http://ports.ubuntu.com xenial/main arm64 libavahi-common-data arm64 0.6.32~rc+dfsg-1ubuntu2 [21.7 kB]
Get:9 http://ports.ubuntu.com xenial/main arm64 libavahi-common3 arm64 0.6.32~rc+dfsg-1ubuntu2 [18.0 kB]
Get:10 http://ports.ubuntu.com xenial/main arm64 libavahi-core7 arm64 0.6.32~rc+dfsg-1ubuntu2 [63.8 kB]
Get:11 http://ports.ubuntu.com xenial/main arm64 avahi-daemon arm64 0.6.32~rc+dfsg-1ubuntu2 [55.5 kB]
Get:12 http://ports.ubuntu.com xenial/universe arm64 consolekit arm64 0.4.6-5 [71.7 kB]
Get:13 http://ports.ubuntu.com xenial/main arm64 libavahi-client3 arm64 0.6.32~rc+dfsg-1ubuntu2 [21.0 kB]
Get:14 http://ports.ubuntu.com xenial/main arm64 libavahi-compat-libdnssd1 arm64 0.6.32~rc+dfsg-1ubuntu2 [13.8 kB]
Get:15 http://ports.ubuntu.com xenial/main arm64 libnss-mdns arm64 0.10-7 [19.8 kB]
Get:16 http://ports.ubuntu.com xenial/universe arm64 libpam-ck-connector arm64 0.4.6-5 [7384 B]
Get:17 http://ports.ubuntu.com xenial/universe arm64 p7zip-full arm64 9.20.1~dfsg.1-4.2 [798 kB]
Get:18 http://ports.ubuntu.com xenial/main arm64 python-cffi-backend arm64 1.5.2-1ubuntu1 [51.8 kB]
Get:19 http://ports.ubuntu.com xenial/main arm64 python-enum34 all 1.1.2-1 [35.8 kB]
Get:20 http://ports.ubuntu.com xenial/main arm64 python-idna all 2.0-3 [35.1 kB]
Get:21 http://ports.ubuntu.com xenial/main arm64 python-ipaddress all 1.0.16-1 [18.0 kB]
Get:22 http://ports.ubuntu.com xenial/main arm64 python-pkg-resources all 20.7.0-1 [108 kB]
Get:23 http://ports.ubuntu.com xenial/main arm64 python-pyasn1 all 0.1.9-1 [45.1 kB]
Get:24 http://ports.ubuntu.com xenial-security/main arm64 python-cryptography arm64 1.2.3-1ubuntu0.1 [151 kB]
Get:25 http://ports.ubuntu.com xenial/main arm64 python-dbus arm64 1.2.0-3 [76.4 kB]
Get:26 http://ports.ubuntu.com xenial/main arm64 python-gi arm64 3.20.0-0ubuntu1 [175 kB]
Get:27 http://ports.ubuntu.com xenial/multiverse arm64 unrar arm64 1:5.3.2-1 [119 kB]
Fetched 2684 kB in 0s (3410 kB/s)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_TIME = "nl_NL.UTF-8",
	LC_MONETARY = "nl_NL.UTF-8",
	LC_ADDRESS = "nl_NL.UTF-8",
	LC_TELEPHONE = "nl_NL.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LC_NAME = "nl_NL.UTF-8",
	LC_MEASUREMENT = "nl_NL.UTF-8",
	LC_IDENTIFICATION = "nl_NL.UTF-8",
	LC_NUMERIC = "nl_NL.UTF-8",
	LC_PAPER = "nl_NL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package libxau6:arm64.
(Reading database ... 51462 files and directories currently installed.)
Preparing to unpack .../libxau6_1%3a1.0.8-1_arm64.deb ...
Unpacking libxau6:arm64 (1:1.0.8-1) ...
Selecting previously unselected package libck-connector0:arm64.
Preparing to unpack .../libck-connector0_0.4.6-5_arm64.deb ...
Unpacking libck-connector0:arm64 (0.4.6-5) ...
Selecting previously unselected package libxdmcp6:arm64.
Preparing to unpack .../libxdmcp6_1%3a1.1.2-1.1_arm64.deb ...
Unpacking libxdmcp6:arm64 (1:1.1.2-1.1) ...
Selecting previously unselected package libxcb1:arm64.
Preparing to unpack .../libxcb1_1.11.1-1ubuntu1_arm64.deb ...
Unpacking libxcb1:arm64 (1.11.1-1ubuntu1) ...
Selecting previously unselected package libx11-data.
Preparing to unpack .../libx11-data_2%3a1.6.3-1ubuntu2_all.deb ...
Unpacking libx11-data (2:1.6.3-1ubuntu2) ...
Selecting previously unselected package libx11-6:arm64.
Preparing to unpack .../libx11-6_2%3a1.6.3-1ubuntu2_arm64.deb ...
Unpacking libx11-6:arm64 (2:1.6.3-1ubuntu2) ...
Selecting previously unselected package libavahi-common-data:arm64.
Preparing to unpack .../libavahi-common-data_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking libavahi-common-data:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package libavahi-common3:arm64.
Preparing to unpack .../libavahi-common3_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking libavahi-common3:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package libavahi-core7:arm64.
Preparing to unpack .../libavahi-core7_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking libavahi-core7:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package avahi-daemon.
Preparing to unpack .../avahi-daemon_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking avahi-daemon (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package consolekit.
Preparing to unpack .../consolekit_0.4.6-5_arm64.deb ...
Unpacking consolekit (0.4.6-5) ...
Selecting previously unselected package libavahi-client3:arm64.
Preparing to unpack .../libavahi-client3_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking libavahi-client3:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package libavahi-compat-libdnssd1:arm64.
Preparing to unpack .../libavahi-compat-libdnssd1_0.6.32~rc+dfsg-1ubuntu2_arm64.deb ...
Unpacking libavahi-compat-libdnssd1:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Selecting previously unselected package libnss-mdns:arm64.
Preparing to unpack .../libnss-mdns_0.10-7_arm64.deb ...
Unpacking libnss-mdns:arm64 (0.10-7) ...
Selecting previously unselected package libpam-ck-connector:arm64.
Preparing to unpack .../libpam-ck-connector_0.4.6-5_arm64.deb ...
Unpacking libpam-ck-connector:arm64 (0.4.6-5) ...
Selecting previously unselected package p7zip-full.
Preparing to unpack .../p7zip-full_9.20.1~dfsg.1-4.2_arm64.deb ...
Unpacking p7zip-full (9.20.1~dfsg.1-4.2) ...
Selecting previously unselected package par2.
Preparing to unpack .../par2_0.7.2-0ubuntu1~jcfp1~xenial_arm64.deb ...
Unpacking par2 (0.7.2-0ubuntu1~jcfp1~xenial) ...
Selecting previously unselected package python-cffi-backend.
Preparing to unpack .../python-cffi-backend_1.5.2-1ubuntu1_arm64.deb ...
Unpacking python-cffi-backend (1.5.2-1ubuntu1) ...
Selecting previously unselected package python-enum34.
Preparing to unpack .../python-enum34_1.1.2-1_all.deb ...
Unpacking python-enum34 (1.1.2-1) ...
Selecting previously unselected package python-idna.
Preparing to unpack .../python-idna_2.0-3_all.deb ...
Unpacking python-idna (2.0-3) ...
Selecting previously unselected package python-ipaddress.
Preparing to unpack .../python-ipaddress_1.0.16-1_all.deb ...
Unpacking python-ipaddress (1.0.16-1) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../python-pkg-resources_20.7.0-1_all.deb ...
Unpacking python-pkg-resources (20.7.0-1) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../python-pyasn1_0.1.9-1_all.deb ...
Unpacking python-pyasn1 (0.1.9-1) ...
Selecting previously unselected package python-cryptography.
Preparing to unpack .../python-cryptography_1.2.3-1ubuntu0.1_arm64.deb ...
Unpacking python-cryptography (1.2.3-1ubuntu0.1) ...
Selecting previously unselected package python-dbus.
Preparing to unpack .../python-dbus_1.2.0-3_arm64.deb ...
Unpacking python-dbus (1.2.0-3) ...
Selecting previously unselected package python-gi.
Preparing to unpack .../python-gi_3.20.0-0ubuntu1_arm64.deb ...
Unpacking python-gi (3.20.0-0ubuntu1) ...
Selecting previously unselected package sabnzbdplus.
Preparing to unpack .../sabnzbdplus_2.2.1-0ubuntu1~jcfp1~16.04_all.deb ...
Preinst: good, no link at /usr/share/sabnzbdplus/interfaces/Config/templates/staticcfg/bootstrap
Preinst: good, no link at /usr/share/sabnzbdplus/interfaces/Glitter/templates/static/bootstrap
Unpacking sabnzbdplus (2.2.1-0ubuntu1~jcfp1~16.04) ...
Selecting previously unselected package unrar.
Preparing to unpack .../unrar_1%3a5.3.2-1_arm64.deb ...
Unpacking unrar (1:5.3.2-1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for dbus (1.10.6-1ubuntu3.3) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up libxau6:arm64 (1:1.0.8-1) ...
Setting up libck-connector0:arm64 (0.4.6-5) ...
Setting up libxdmcp6:arm64 (1:1.1.2-1.1) ...
Setting up libxcb1:arm64 (1.11.1-1ubuntu1) ...
Setting up libx11-data (2:1.6.3-1ubuntu2) ...
Setting up libx11-6:arm64 (2:1.6.3-1ubuntu2) ...
Setting up libavahi-common-data:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up libavahi-common3:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up libavahi-core7:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up avahi-daemon (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up consolekit (0.4.6-5) ...
Setting up libavahi-client3:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up libavahi-compat-libdnssd1:arm64 (0.6.32~rc+dfsg-1ubuntu2) ...
Setting up libnss-mdns:arm64 (0.10-7) ...
First installation detected...
Checking NSS setup...
Setting up libpam-ck-connector:arm64 (0.4.6-5) ...
locale: Cannot set LC_ALL to default locale: No such file or directory
Setting up p7zip-full (9.20.1~dfsg.1-4.2) ...
Setting up par2 (0.7.2-0ubuntu1~jcfp1~xenial) ...
Setting up python-cffi-backend (1.5.2-1ubuntu1) ...
Setting up python-enum34 (1.1.2-1) ...
Setting up python-idna (2.0-3) ...
Setting up python-ipaddress (1.0.16-1) ...
Setting up python-pkg-resources (20.7.0-1) ...
Setting up python-pyasn1 (0.1.9-1) ...
Setting up python-cryptography (1.2.3-1ubuntu0.1) ...
Setting up python-dbus (1.2.0-3) ...
Remove stale byte-compiled files...
Setting up python-gi (3.20.0-0ubuntu1) ...
Setting up sabnzbdplus (2.2.1-0ubuntu1~jcfp1~16.04) ...
Setting up unrar (1:5.3.2-1) ...
update-alternatives: using /usr/bin/unrar-nonfree to provide /usr/bin/unrar (unrar) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for dbus (1.10.6-1ubuntu3.3) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
```
... let's check:
```
sander@nanopineo2:~$ python -c "import cryptography"
sander@nanopineo2:~$ 

```
Yes, that worked!

**Comment by sanderjo** [comment]
Maybe this is relevant:

```
sander@nanopineo2:~$ cat /etc/apt/apt.conf.d/71-no-recommends 
APT::Install-Recommends "0";
APT::Install-Suggests "0";
```

**Comment by sanderjo** [comment]
... or (after a faulty install):
```
sudo apt-get purge sabnzbdplus python-sabyenc
sudo apt-get -o APT::Install-Recommends=1 install sabnzbdplus python-sabyenc

```
