### ISSUE TITLE
Error when accessing config/special in 2.30Alpha1 on macOS

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1021]
http://localhost:8080/config/special/

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy/_cprequest.pyc", line 670, in respond
  File "cherrypy/lib/encoding.pyc", line 220, in __call__
  File "cherrypy/_cpdispatch.pyc", line 60, in __call__
  File "sabnzbd/interface.pyc", line 1406, in index
TypeError: 'NoneType' object is not callable

Powered by CherryPy 8.1.2

**Comment by Cpuroast** [comment]
Also, tried with a fresh ini file and the results were the same.

**Comment by Safihre** [comment]
Oops, yeah.. My fault, it's not just macOS it's all platforms.
