### ISSUE TITLE
2.3.0.alpha.1 -> visititing ../config/special -> crashes

### ISSUE THREAD

**Issue by OldskoolOrion** [sabnzbd/sabnzbd#1024]
Going to special settings page (/config/special), leaves you with an internal server error (500).

The traceback is as follows :

ERROR 2017-09-05 15:18 [05/Sep/2017:15:18:42] HTTP 
Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 220, in __call__
  File "cherrypy\_cpdispatch.pyo", line 60, in __call__
  File "sabnzbd\interface.pyo", line 1406, in index
TypeError: 'NoneType' object is not callable

**Comment by Safihre** [comment]
Fixed, will be put in next release. 
Might just make one now to also include some other bugfixes.

**Comment by OldskoolOrion** [comment]
aww.. was going to look at it myself the moment I got home (it's not a page long traceback.. probably a typo ? :P) .. but i'll find something else useful to do :-) extremely fast follow up :-)
