### ISSUE TITLE
Sabnzbd 2.3.0 Alpha 2 error on RSS filter page

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1026]
Error when accessing the filter list of an RSS feed.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy/_cprequest.pyc", line 670, in respond
  File "cherrypy/lib/encoding.pyc", line 220, in __call__
  File "cherrypy/_cpdispatch.pyc", line 60, in __call__
  File "sabnzbd/interface.pyc", line 1822, in index
  File "sabnzbd/interface.pyc", line 2686, in GetRssLog
  File "sabnzbd/rss.pyc", line 71, in show_result
  File "sabnzbd/decorators.pyc", line 30, in newFunction
  File "sabnzbd/rss.pyc", line 526, in show_result
TypeError: argument of type 'NoneType' is not iterable

It was working fine following the upgrade but since I had removed a few feeds, I decided to shutdown sab and wipe my rss_data file and let it build fresh, upon trying to access the filter listing, I now get this error.

**Comment by Cpuroast** [comment]
Ah, it looks like it was already reported and fixed in: 
https://github.com/sabnzbd/sabnzbd/commit/06dc5b181ea150a290b8ad2181797a5a0e607ce5

**Comment by Safihre** [comment]
Did you maybe also get other warning that it couldn't load the RSS data file? 
Got another report of this here: https://forums.sabnzbd.org/viewtopic.php?f=11&t=22952&sid=b81d72f0e9278ea49c8e4839f7bb1977
Wondered what is causing the failures to load (or save) the RSS data.

**Comment by Cpuroast** [comment]
Nope, in this case, I had shutdown sab and erased the rss data file, then started sab again, didn't get a warning that it couldn't load it, just the error I opened this issue with.

**Comment by Safihre** [comment]
Ok, that should be fixed indeed!
