### ISSUE TITLE
Traceback "RuntimeError: dictionary changed size during iteration"; SABnzbd version: 2.2.0RC3

### ISSUE THREAD

**Issue by pctuthill** [sabnzbd/sabnzbd#1085]
I've just seen the following two tracebacks in the "warnings" tab.

```
Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 220, in __call__
  File "cherrypy\_cpdispatch.pyo", line 60, in __call__
  File "sabnzbd\interface.pyo", line 780, in index
  File "sabnzbd\api.pyo", line 1299, in build_queue
  File "sabnzbd\api.pyo", line 1693, in build_queue_header
  File "sabnzbd\nzbqueue.pyo", line 819, in queue_info
  File "sabnzbd\nzbstuff.pyo", line 1588, in remaining
RuntimeError: dictionary changed size during iteration
```

and

```
Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 220, in __call__
  File "cherrypy\_cpdispatch.pyo", line 60, in __call__
  File "sabnzbd\interface.pyo", line 451, in tapi
  File "sabnzbd\api.pyo", line 115, in api_handler
  File "sabnzbd\api.pyo", line 174, in _api_queue
  File "sabnzbd\api.pyo", line 276, in _api_queue_default
  File "sabnzbd\api.pyo", line 1299, in build_queue
  File "sabnzbd\api.pyo", line 1693, in build_queue_header
  File "sabnzbd\nzbqueue.pyo", line 819, in queue_info
  File "sabnzbd\nzbstuff.pyo", line 1588, in remaining
RuntimeError: dictionary changed size during iteration
```

Version
`2.2.0RC3 [27f83f2]`

Python version
`2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] [cp1252]`

Potentially related to to pull request #1029.

**Comment by Safihre** [comment]
This has been long ago fixed, we are already at 2.3.1. Why are you using the latest version?
