### ISSUE TITLE
API for retry_all throwing 500 error on 1.1.0 [8abcf08]

### ISSUE THREAD

**Issue by brandonscript** [sabnzbd/sabnzbd#1094]
This call:

    {{url}}/sabnzbd/api?output=json&apikey={{apikey}}&mode=retry_all

Is returning a 500 error:

```
500 Internal Server Error

Traceback (most recent call last):
  File "cherrypy/_cprequest.pyc", line 670, in respond
  File "cherrypy/lib/encoding.pyc", line 220, in __call__
  File "cherrypy/_cpdispatch.pyc", line 60, in __call__
  File "sabnzbd/interface.pyc", line 535, in api
  File "sabnzbd/api.pyc", line 112, in api_handler
  File "sabnzbd/api.pyc", line 727, in _api_retry_all
  File "sabnzbd/api.pyc", line 1019, in report
  File "json/__init__.pyc", line 243, in dumps
  File "json/encoder.pyc", line 207, in encode
  File "json/encoder.pyc", line 270, in iterencode
  File "json/encoder.pyc", line 184, in default
TypeError: &lt;function retry_all_jobs at 0x298c4f0&gt; is not JSON serializable
```

According to the [docs](https://sabnzbd.org/wiki/advanced/api#retry_all), this should work?

I tried without JSON output, and it returns a function object:

    <function retry_all_jobs at 0x298c4f0>

Which seems to suggest that it's returning the function object and not actually executing it?

*whispers...*<sub>(also... https://forums.sabnzbd.org/viewtopic.php?t=21572)</sub>

**Comment by thezoggy** [comment]
What about Sab 2.3.1?

**Comment by Safihre** [comment]
This has long been fixed (also written in the linked [forum post](https://forums.sabnzbd.org/viewtopic.php?t=21572#p108526)), please upgrade to a more recent version of SABnzbd. Instructions for many platforms and repositories are linked from the downloads page: https://sabnzbd.org/downloads.

**Comment by brandonscript** [comment]
Yeah, definitely is! Not sure how I missed the 2.X release ¯\_(ツ)_/¯
