### ISSUE TITLE
sabnzbd not working with proxychains

### ISSUE THREAD

**Issue by thomas41587** [sabnzbd/sabnzbd#1114]
If sabnzb is beeing started with proxychains (to route all data trough a proxy) it takes about ten minutes until you get the following error:
```
2018-03-15 13:49:33,607::INFO::[sabnzbdplus:1498] Starting web-interface on 0.0.0.0:9999
2018-03-15 13:49:54,711::INFO::[_cplogging:55] [15/Mar/2018:13:49:54] ENGINE Bus STARTING
2018-03-15 13:49:54,729::INFO::[_cplogging:55] [15/Mar/2018:13:49:54] ENGINE Started monitor thread '_TimeoutMonitor'.
2018-03-15 13:49:54,836::INFO::[_cplogging:55] [15/Mar/2018:13:49:54] ENGINE Serving on ::1:9999
2018-03-15 14:00:18,839::ERROR::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x755d9f50>>
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 9999 not bound on '0.0.0.0'

2018-03-15 14:00:18,844::ERROR::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 184, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 9999 not bound on '0.0.0.0'

2018-03-15 14:00:18,848::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Bus STOPPING
2018-03-15 14:00:18,850::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9999)) already shut down
2018-03-15 14:00:18,858::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::1', 9999)) shut down
2018-03-15 14:00:18,870::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Stopped thread '_TimeoutMonitor'.
2018-03-15 14:00:18,871::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Bus STOPPED
2018-03-15 14:00:18,873::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Bus EXITING
2018-03-15 14:00:18,874::INFO::[_cplogging:55] [15/Mar/2018:14:00:18] ENGINE Bus EXITED
2018-03-15 14:00:18,875::ERROR::[sabnzbdplus:1513] Failed to start web-interface: 
Traceback (most recent call last):
  File "/usr/bin/sabnzbdplus", line 1505, in main
    cherrypy.engine.start()
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 184, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 9999 not bound on '0.0.0.0'
2018-03-15 14:00:18,887::ERROR::[sabnzbdplus:305] Fehler beim Starten der Weboberfläche. : Port 9999 not bound on '0.0.0.0'
2018-03-15 14:00:18,896::INFO::[__init__:371] SABnzbd shutting down...
2018-03-15 14:00:18,898::INFO::[__init__:917] Saving data for bookmarks.sab in /root/.sabnzbd/admin/bookmarks.sab
2018-03-15 14:00:18,900::INFO::[urlgrabber:72] URLGrabber shutting down
2018-03-15 14:00:18,908::INFO::[__init__:917] Saving data for watched_data.sab in /root/.sabnzbd/admin/watched_data.sab
2018-03-15 14:00:18,911::INFO::[dirscanner:270] Dirscanner shutting down
2018-03-15 14:00:19,414::INFO::[postproc:85] Saving postproc queue
2018-03-15 14:00:19,416::INFO::[__init__:917] Saving data for postproc1.sab in /root/.sabnzbd/admin/postproc1.sab
2018-03-15 14:00:19,418::INFO::[nzbqueue:214] Saving queue
2018-03-15 14:00:19,420::INFO::[__init__:917] Saving data for queue9.sab in /root/.sabnzbd/admin/queue9.sab
2018-03-15 14:00:19,422::INFO::[__init__:917] Saving data for rss_data.sab in /root/.sabnzbd/admin/rss_data.sab
2018-03-15 14:00:19,424::INFO::[__init__:917] Saving data for bookmarks.sab in /root/.sabnzbd/admin/bookmarks.sab
2018-03-15 14:00:19,428::INFO::[__init__:917] Saving data for watched_data.sab in /root/.sabnzbd/admin/watched_data.sab
2018-03-15 14:00:19,430::INFO::[postproc:85] Saving postproc queue
2018-03-15 14:00:19,439::INFO::[__init__:917] Saving data for postproc1.sab in /root/.sabnzbd/admin/postproc1.sab
2018-03-15 14:00:19,442::INFO::[__init__:438] All processes stopped
```

**Comment by Safihre** [comment]
Seems like it can't bind to the IP and port you specified. Are you sure you set it up correctly?

**Comment by thomas41587** [comment]
Yes I am sure it is set up correctly. sabnzb starts and works perfectly with the exact same settings using no proxychain.

**Comment by thezoggy** [comment]
https://forums.sabnzbd.org/viewtopic.php?t=5163

**Comment by thomas41587** [comment]
What do you want to tell me with this link which has no solution? I have tried various ports and ip addresses/hosts. The -b0 option does not help either

**Comment by thomas41587** [comment]
I think I found the problem: If sabnzbd is started via proxychains, you cannot see the local ip-adress and port in the list of netstat. You just find the IP-Adress of the proxy in combination with the socks port. So I guess it is neccessary to disable the check in sabnzbd? Is there any way to do that?

**Comment by Safihre** [comment]
This is not a check, it just tries to bind to the IP and port you specified but it just can't.
Maybe try different IP settings or something? I know nothing about proxies.

**Comment by thomas41587** [comment]
As I already mentioned I have tried all sorts of ports and ip adresses! localhost, 127.0.0.1, 0.0.0.0, 192.168.2.100 (which is the ip-adress of the device), ... and of course various ports like 80, 8080, 1234, 9999, ....
And the information, that it cannot bind to the specified port on the specified ip adress is just wrong. It can obviously bind as I am able to connect to the webinterface for about 10 minues.

**Comment by Safihre** [comment]
I am sorry but I think this is out of the scope of the software and a configuration issue.
