### ISSUE TITLE
Traceback error can anyone please help Sabnzbd

### ISSUE THREAD

**Issue by avobad** [sabnzbd/sabnzbd#1147]
```
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.9
  ACCEPT-ENCODING: gzip, deflate, br
  COOKIE: _pk_id.1.1fff=ca098e7bc77b10ca.1524861013.3.1526268040.1526268040.
2018-05-25 19:54:53,685::ERROR::[_cplogging:219] [25/May/2018:19:54:53] HTTP 
Traceback (most recent call last):
  File "cherrypy/_cprequest.pyc", line 670, in respond
  File "cherrypy/lib/encoding.pyc", line 220, in __call__
  File "cherrypy/_cpdispatch.pyc", line 60, in __call__
  File "sabnzbd/interface.pyc", line 465, in tapi
  File "sabnzbd/api.pyc", line 111, in api_handler
  File "sabnzbd/api.pyc", line 691, in _api_watched_now
  File "sabnzbd/dirscanner.pyc", line 449, in dirscan
  File "sabnzbd/dirscanner.pyc", line 428, in scan
  File "sabnzbd/dirscanner.pyc", line 400, in run_dir
  File "sabnzbd/decorators.pyc", line 48, in call_func
  File "sabnzbd/dirscanner.pyc", line 114, in ProcessArchiveFile
  File "sabnzbd/dirscanner.pyc", line 72, in is_archive
  File "zipfile.pyc", line 153, in is_zipfile
  File "zipfile.pyc", line 136, in _check_zipfile
  File "zipfile.pyc", line 231, in _EndRecData
  File "zipfile.pyc", line 177, in _EndRecData64
BadZipfile: zipfiles that span multiple disks are not supported
```

**Comment by thezoggy** [comment]
what version of sab?
it looks like this happened when you told sab to process a multi-part zip to load a nzb?

**Comment by Safihre** [comment]
Seems to be the way the zip-file was created:
https://mail.python.org/pipermail//docs/2012-November/011581.html

**Comment by Safihre** [comment]
Closing due to lack of response.
