### ISSUE TITLE
[BUG] v2.3.4 ChannelFailures: TypeError('not enough arguments for format string',)

### ISSUE THREAD

**Issue by patvdleer** [sabnzbd/sabnzbd#1151]
```
downloader@fractal:~$ sabnzbdplus --log-all --server 0.0.0.0:8080
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1147] --------------------------------
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1148] sabnzbdplus-2.3.4 (rev=2a113f7f588fe78c5dcc3453db31e0ec540efd60)
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1149] Full executable path = /usr/bin/sabnzbdplus
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1159] Platform = posix
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1160] Python-version = 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
2018-06-03 17:20:38,805::INFO::[sabnzbdplus:1161] Arguments = /usr/bin/sabnzbdplus --log-all --server 0.0.0.0:8080
2018-06-03 17:20:38,806::INFO::[sabnzbdplus:1166] Preferred encoding = UTF-8
2018-06-03 17:20:38,806::INFO::[sabnzbdplus:1176] SSL version = OpenSSL 1.0.2g  1 Mar 2016
2018-06-03 17:20:38,806::INFO::[sabnzbdplus:1224] Read INI file /home/downloader/.sabnzbd/sabnzbd.ini
2018-06-03 17:20:38,807::INFO::[postproc:100] Loading postproc queue
2018-06-03 17:20:38,807::INFO::[__init__:985] [N/A] /home/downloader/.sabnzbd/admin/Rating.sab missing
2018-06-03 17:20:38,807::INFO::[scheduler:197] Setting schedule for midnight BPS reset
2018-06-03 17:20:38,809::INFO::[config:853] Writing settings to INI file /home/downloader/.sabnzbd/sabnzbd.ini
2018-06-03 17:20:38,811::INFO::[__init__:349] All processes started
2018-06-03 17:20:38,812::INFO::[sabnzbdplus:286] Web dir is /usr/share/sabnzbdplus/interfaces/Glitter
2018-06-03 17:20:38,812::INFO::[sabnzbdplus:286] Web dir is /usr/share/sabnzbdplus/interfaces/Config
2018-06-03 17:20:38,813::INFO::[config:853] Writing settings to INI file /home/downloader/.sabnzbd/sabnzbd.ini
2018-06-03 17:20:38,816::INFO::[sabnzbdplus:1262] pygtk2 not found. No SysTray.
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:397] SABYenc module (v3.3.1)... found!
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:414] Cryptography module (v1.2.3)... found!
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:419] par2 binary... found (/usr/bin/par2)
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:429] UNRAR binary... found (/usr/bin/unrar)
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:437] UNRAR binary version 5.30
2018-06-03 17:20:38,822::INFO::[sabnzbdplus:442] unzip binary... found (/usr/bin/unzip)
2018-06-03 17:20:38,823::INFO::[sabnzbdplus:447] 7za binary... found (/usr/bin/7za)
2018-06-03 17:20:38,823::INFO::[sabnzbdplus:453] nice binary... found (/usr/bin/nice)
2018-06-03 17:20:38,823::INFO::[sabnzbdplus:457] ionice binary... found (/usr/bin/ionice)
2018-06-03 17:20:38,823::INFO::[sabnzbdplus:1382] Starting web-interface on 0.0.0.0:8080
2018-06-03 17:20:38,824::INFO::[_cplogging:219] [03/Jun/2018:17:20:38] ENGINE Bus STARTING
2018-06-03 17:20:39,014::INFO::[_cplogging:219] [03/Jun/2018:17:20:39] ENGINE Serving on http://0.0.0.0:8080
2018-06-03 17:20:44,040::ERROR::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 245, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 223, in publish
    level=40, traceback=True)
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 517, in log
    self.publish('log', msg, level)
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 225, in publish
    raise exc
ChannelFailures: TypeError('not enough arguments for format string',)

2018-06-03 17:20:44,040::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE Bus STOPPING
2018-06-03 17:20:44,044::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
2018-06-03 17:20:44,045::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.1.1', 8080)) already shut down
2018-06-03 17:20:44,045::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE Bus STOPPED
2018-06-03 17:20:44,046::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE Bus EXITING
2018-06-03 17:20:44,046::INFO::[_cplogging:219] [03/Jun/2018:17:20:44] ENGINE Bus EXITED
```

**Comment by patvdleer** [comment]
Apparently setting the host to `0.0.0.0` isn't allowed anymore

**Comment by Safihre** [comment]
Yes it is, I use it all the time and so do many others.
Seems to happen when ports are occupied or the host doesn't allow you to bind to the port.

**Comment by thezoggy** [comment]
Don't include the port with the IP?

**Comment by patvdleer** [comment]
@Safihre I checked and that wasn't it, checked via netstat and I was able to run it on 127.0.0.1

@thezoggy I tried this via /etc/default first which failed me too.

**Comment by thezoggy** [comment]
tried on windows, worked just fine... 

```C:\Program Files (x86)\sabnzbd_git>python SABnzbd.py -f C:\test\sabnzbd.ini --log-all --server 0.0.0.0:8080
2018-06-03 16:12:30,040::INFO::[SABnzbd:1159] --------------------------------
2018-06-03 16:12:30,040::INFO::[SABnzbd:1160] SABnzbd.py-2.4.0-develop (rev=unknown)
2018-06-03 16:12:30,040::INFO::[SABnzbd:1161] Full executable path = C:\Program Files (x86)\sabnzbd_git\SABnzbd.py
2018-06-03 16:12:30,056::INFO::[SABnzbd:1167] Platform = Windows-7-6.1.7601-SP1 (win64)
2018-06-03 16:12:30,056::INFO::[SABnzbd:1172] Python-version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
2018-06-03 16:12:30,056::INFO::[SABnzbd:1173] Arguments = SABnzbd.py -f C:\test\sabnzbd.ini --log-all --server 0.0.0.0:8080
2018-06-03 16:12:30,072::INFO::[SABnzbd:1178] Preferred encoding = cp1252
2018-06-03 16:12:30,072::INFO::[SABnzbd:1188] SSL version = OpenSSL 1.0.2k  26 Jan 2017
2018-06-03 16:12:30,586::DEBUG::[SABnzbd:1202] Available certificates: {'x509': 43, 'x509_ca': 40, 'crl': 0}
2018-06-03 16:12:30,586::DEBUG::[SABnzbd:1209] My local IPv4 address = 192.168.0.2
2018-06-03 16:12:30,618::DEBUG::[SABnzbd:1215] My public IPv4 address = 47.184.7.67
2018-06-03 16:12:30,618::DEBUG::[SABnzbd:1223] Could not determine my IPv6 address
2018-06-03 16:12:30,618::DEBUG::[SABnzbd:1229] CPU Pystone available performance = 228243
2018-06-03 16:12:30,634::DEBUG::[SABnzbd:1234] CPU model = Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
2018-06-03 16:12:30,634::INFO::[SABnzbd:1236] Read INI file C:\test\sabnzbd.ini
2018-06-03 16:12:30,650::DEBUG::[__init__:982] [sabnzbd.rss.__init__] Loading data for rss_data.sab from C:\test\admin\rss_data.sab
2018-06-03 16:12:30,664::DEBUG::[__init__:982] [sabnzbd.bpsmeter.read] Loading data for totals10.sab from C:\test\admin\totals10.sab
2018-06-03 16:12:30,664::DEBUG::[bpsmeter:180] Read quota q=0.0 l=0.0 reset=0
2018-06-03 16:12:30,664::DEBUG::[downloader:164] Initializing downloader/decoder
2018-06-03 16:12:30,680::INFO::[postproc:100] Loading postproc queue
2018-06-03 16:12:30,680::DEBUG::[__init__:982] [sabnzbd.postproc.load] Loading data for postproc2.sab from C:\test\admin\postproc2.sab
2018-06-03 16:12:30,696::DEBUG::[__init__:982] [sabnzbd.nzbqueue.read_queue] Loading data for queue10.sab from C:\test\admin\queue10.sab
2018-06-03 16:12:30,696::DEBUG::[__init__:982] [sabnzbd.dirscanner.__init__] Loading data for watched_data2.sab from C:\test\admin\watched_data2.sab
2018-06-03 16:12:30,711::DEBUG::[__init__:982] [sabnzbd.rating.__init__] Loading data for Rating.sab from C:\test\admin\Rating.sab
2018-06-03 16:12:30,711::INFO::[__init__:985] [sabnzbd.rating.__init__] C:\test\admin\Rating.sab missing
2018-06-03 16:12:30,727::DEBUG::[scheduler:180] Scheduling RSS interval task every 15 min (delay=8)
2018-06-03 16:12:30,727::DEBUG::[scheduler:192] Scheduling VersionCheck on day 4 at 13:13
2018-06-03 16:12:30,727::INFO::[scheduler:207] Setting schedule for midnight BPS reset
2018-06-03 16:12:30,727::DEBUG::[__init__:598] PAUSED_ALL inactive
2018-06-03 16:12:30,743::INFO::[__init__:349] All processes started
2018-06-03 16:12:30,743::INFO::[SABnzbd:285] Web dir is C:\Program Files (x86)\sabnzbd_git\interfaces\Glitter
2018-06-03 16:12:30,743::INFO::[SABnzbd:285] Web dir is C:\Program Files (x86)\sabnzbd_git\interfaces\Config
2018-06-03 16:12:30,759::INFO::[config:853] Writing settings to INI file C:\test\sabnzbd.ini
2018-06-03 16:12:30,773::DEBUG::[sabtray:185] SysTray uses codepage 1252
2018-06-03 16:12:30,773::INFO::[SABnzbd:409] SABYenc module (v3.3.2)... found!
2018-06-03 16:12:30,773::INFO::[SABnzbd:426] Cryptography module (v1.8.1)... found!
2018-06-03 16:12:30,789::INFO::[SABnzbd:431] par2 binary... found (C:\Program Files (x86)\sabnzbd_git\win\par2\par2.exe)
2018-06-03 16:12:30,789::INFO::[SABnzbd:436] MultiPar binary... found (C:\Program Files (x86)\sabnzbd_git\win\par2\multipar\par2j64.exe)
2018-06-03 16:12:30,805::INFO::[SABnzbd:441] UNRAR binary... found (C:\Program Files (x86)\sabnzbd_git\win\unrar\x64\UnRAR.exe)
2018-06-03 16:12:30,805::INFO::[SABnzbd:456] unzip binary... NOT found!
2018-06-03 16:12:30,821::INFO::[SABnzbd:459] 7za binary... found (C:\Program Files (x86)\sabnzbd_git\win\7zip\7za.exe)
2018-06-03 16:12:30,821::INFO::[SABnzbd:1394] Starting web-interface on 0.0.0.0:8080
2018-06-03 16:12:30,821::INFO::[_cplogging:219] [03/Jun/2018:16:12:30] ENGINE Bus STARTING
2018-06-03 16:12:31,071::INFO::[_cplogging:219] [03/Jun/2018:16:12:31] ENGINE Serving on https://0.0.0.0:8080
2018-06-03 16:12:31,071::INFO::[_cplogging:219] [03/Jun/2018:16:12:31] ENGINE Bus STARTED
2018-06-03 16:12:31,071::INFO::[SABnzbd:1432] Starting SABnzbd.py-2.4.0-develop
2018-06-03 16:12:31,071::DEBUG::[__init__:360] Starting postprocessor
2018-06-03 16:12:31,085::DEBUG::[__init__:363] Starting assembler
2018-06-03 16:12:31,085::INFO::[postproc:187] Completed Download Folder C:\test\downloads\complete is not on FAT
2018-06-03 16:12:31,085::DEBUG::[__init__:366] Starting downloader
2018-06-03 16:12:31,085::WARNING::[postproc:194] Module subprocessww missing. Expect problems with Unicoded file and directory names in downloads.
2018-06-03 16:12:31,101::DEBUG::[scheduler:219] Starting scheduler
2018-06-03 16:12:31,101::DEBUG::[__init__:371] Starting dirscanner
2018-06-03 16:12:31,118::DEBUG::[__init__:1174] Test IPv6: Disabling IPv6, because it looks like it's not available. Reason: <class 'socket.gaierror'>
2018-06-03 16:12:31,118::INFO::[dirscanner:330] Dirscanner starting up
2018-06-03 16:12:31,118::DEBUG::[__init__:376] Starting urlgrabber
2018-06-03 16:12:31,118::DEBUG::[downloader:410] External IPv6 test result: False
2018-06-03 16:12:31,132::INFO::[urlgrabber:82] URLGrabber starting up
2018-06-03 16:12:31,132::INFO::[panic:209] Launching browser with https://127.0.0.1:8080/sabnzbd
```

8080 i bet is already being taken or blocked...  try another port and see

**Comment by thezoggy** [comment]
yeah, I ran into this same 'issue' awhile back (due to an actual bug) where sab was trying to start up on a port that is already used: https://github.com/sabnzbd/sabnzbd/issues/862

so yeah thats what it is. now I will agree that the error doesnt really give you a clue to know this. we should deal with that better

**Comment by Safihre** [comment]
That seems to be a special case, we check if the port is occupied and give a nice error if it is. 
If it passes that check, it must be some strange way of blocking the port.

**Comment by thezoggy** [comment]
also to note, you prob should update your unrar
> 2018-06-03 17:20:38,822::INFO::[sabnzbdplus:437] UNRAR binary version 5.30

**Comment by thezoggy** [comment]
unrelated, you prob should update your unrar:
> 2018-06-03 17:20:38,822::INFO::[sabnzbdplus:437] UNRAR binary version 5.30

**Comment by nick30935n** [comment]
It is something in 2.3.9
I have installed several times in last few months and never had any problems now with 2.3.9 I get this issue.

**Comment by nick30935n** [comment]
Sorry here is log...
2019-05-25 19:51:25,622::INFO::[sabnzbdplus:397] SABYenc module (v3.3.5)... found!
2019-05-25 19:51:25,622::INFO::[sabnzbdplus:414] Cryptography module (v2.1.4)... found!
2019-05-25 19:51:25,622::INFO::[sabnzbdplus:419] par2 binary... found (/usr/bin/par2)
2019-05-25 19:51:25,622::INFO::[sabnzbdplus:429] UNRAR binary... found (/usr/bin/unrar)
2019-05-25 19:51:25,622::INFO::[sabnzbdplus:437] UNRAR binary version 5.50
2019-05-25 19:51:25,623::INFO::[sabnzbdplus:444] unzip binary... NOT found!
2019-05-25 19:51:25,623::INFO::[sabnzbdplus:447] 7za binary... found (/usr/bin/7za)
2019-05-25 19:51:25,623::INFO::[sabnzbdplus:453] nice binary... found (/usr/bin/nice)
2019-05-25 19:51:25,623::INFO::[sabnzbdplus:457] ionice binary... found (/usr/bin/ionice)
2019-05-25 19:51:25,624::INFO::[sabnzbdplus:1385] Starting web-interface on 127.0.0.1:8080
2019-05-25 19:51:25,625::INFO::[_cplogging:219] [25/May/2019:19:51:25] ENGINE Bus STARTING
2019-05-25 19:51:25,832::INFO::[_cplogging:219] [25/May/2019:19:51:25] ENGINE Serving on http://127.0.0.1:8080
2019-05-25 19:51:25,832::INFO::[_cplogging:219] [25/May/2019:19:51:25] ENGINE Bus STARTED
2019-05-25 19:51:25,832::INFO::[sabnzbdplus:1423] Starting sabnzbdplus-2.3.9
2019-05-25 19:51:25,836::INFO::[dirscanner:330] Dirscanner starting up
2019-05-25 19:51:25,837::INFO::[postproc:187] Completed Download Folder /home/fozzie/Downloads/complete is not on FAT
2019-05-25 19:51:25,839::INFO::[urlgrabber:82] URLGrabber starting up
2019-05-25 19:51:25,839::INFO::[panic:209] Launching browser with http://127.0.0.1:8080/sabnzbd
I assume the Panic:209 is significant.

**Comment by nick30935n** [comment]
Switching to beta branch seems to work OK.

**Comment by Safihre** [comment]
The code hasnt changed in years, most likely you should change your  `host =` setting in your Config file. Try setting it to `localhost`, `127.0.0.1` or `0.0.0.0`.
Also, your log doesn't show any errors.
