### ISSUE TITLE
2.3.7b1 -- The write operation timed out

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1206]
never seen these before until after upgrading to 2.3.7b1.
5 so far in 6 days.
```
 2018-12-28 3:01pm [28/Dec/2018:15:01:45] ENGINE socket.error 'The write operation timed out'
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1412, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 863, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2342, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2424, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 916, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1050, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1057, in send
  File "ssl.pyo", line 725, in send
SSLError: ('The write operation timed out',)
```

**Comment by thezoggy** [comment]
Logs:
```
2018-12-27 19:34:13,947::INFO::[postproc:94] Saving postproc queue
2018-12-27 19:34:13,947::DEBUG::[__init__:959] [sabnzbd\postproc.pyo.save] Saving data for postproc2.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\postproc2.sab
2018-12-28 00:40:10,842::WARNING::[_cplogging:219] [28/Dec/2018:00:40:10] ENGINE socket.error 'The write operation timed out'
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1412, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 863, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2342, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2424, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 916, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1050, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1057, in send
  File "ssl.pyo", line 725, in send
SSLError: ('The write operation timed out',)

2018-12-28 00:40:28,673::WARNING::[_cplogging:219] [28/Dec/2018:00:40:28] ENGINE socket.error 'The write operation timed out'
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1412, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 863, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2342, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2424, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 916, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1050, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1057, in send
  File "ssl.pyo", line 725, in send
SSLError: ('The write operation timed out',)

2018-12-28 00:55:23,368::INFO::[config:853] Writing settings to INI file C:\Users\<USERNAME>\AppData\Local\sabnzbd\sabnzbd.ini
2018-12-28 01:06:14,944::WARNING::[_cplogging:219] [28/Dec/2018:01:06:14] ENGINE socket.error 'The write operation timed out'
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1412, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 863, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2342, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2424, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 916, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1050, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1057, in send
  File "ssl.pyo", line 725, in send
SSLError: ('The write operation timed out',)

2018-12-28 01:06:25,099::WARNING::[_cplogging:219] [28/Dec/2018:01:06:25] ENGINE socket.error 'The write operation timed out'
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1412, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 863, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2342, in respond
  File "cherrypy\wsgiserver\__init__.pyo", line 2424, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 916, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1050, in write
  File "cherrypy\wsgiserver\__init__.pyo", line 1057, in send
  File "ssl.pyo", line 725, in send
SSLError: ('The write operation timed out',)

2018-12-28 03:29:05,683::INFO::[__init__:681] Adding Deadly...nzb
```

**Comment by thezoggy** [comment]
sadly no other log entries to help narrow it down or confirm it was just external api command that caused it (i have api_logging disabled due to the noise 3rd party apps caused)

**Comment by Safihre** [comment]
I don't think this is related to Sab version since it's such a low level error.
The build process didn't change, neither did the Python version. 
Will keep this open in case others experience it.
