### ISSUE TITLE
sab 2.3.7 -- sslv3 alert bad certificate

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1215]
lets say you have sab using ssl, but delete the key/cert to have it regen a new one.
or if you load up a browser and access sab via ssl where it wants to yell about self signed cert and wants you to add an exception.
for each time of those scenarios sab throws the error:

example:
```
2019-01-15 01:47:51,970::WARNING::[_cplogging:219] [15/Jan/2019:01:47:51] ENGINE socket.error 1
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 1402, in communicate
  File "cherrypy\wsgiserver\__init__.pyo", line 602, in parse_request
  File "cherrypy\wsgiserver\__init__.pyo", line 635, in read_request_line
  File "cherrypy\wsgiserver\__init__.pyo", line 304, in readline
  File "cherrypy\wsgiserver\__init__.pyo", line 1219, in readline
  File "cherrypy\wsgiserver\__init__.pyo", line 1070, in recv
  File "ssl.pyo", line 772, in recv
  File "ssl.pyo", line 659, in read
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1941)
```

**Comment by thezoggy** [comment]
tried to replicate in chrome.. all good there.

looks like its a thing with firefox only..
https://github.com/cdgriffith/pyctf#sslv3-alert-bad-certificate

**Comment by thezoggy** [comment]
oh well, after you add exception you don't get the message anymore. but still we probably should handle that traceback more gracefully

**Comment by Safihre** [comment]
I'm aware of it since we removed PyOpenSSL, but I remember it being hard to catch and only at an ugly place.
So I kind of just gave up on it.. "Known issue".

**Comment by thezoggy** [comment]
gotcha, no worries. i just went down a path last night trying to figure out why my ssl certs were no longer good and was regenerating stuff and ran into it
