### ISSUE TITLE
cat_to_opts() missing 1 required positional argument: 'cat'

### ISSUE THREAD

**Issue by OutOfGears** [sabnzbd/sabnzbd#1222]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: cat_to_opts() missing 1 required positional argument: 'cat'

**Comment by OutOfGears** [comment]
This is easly fixed by setting cat=None
