### ISSUE TITLE
nntplib.NNTPPermanentError: Authentication failed, check username/password &  ValueError: invalid literal for int() with base 10: 'Aut'

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1241]
#python3  

I get this error when I have a 2nd prio-0 server (newszilla.xs4all.nl, and also for ninja) for which I have not filled out credentials.

SAB stops, and restarts.

Reproducible on 
Ubuntu 18.04 on Intel, Python 3.6.7
Ubuntu 16.04.5 LTS on ARM, Python 3.5.2

The problem does **not** occur if I fill out some (fake) credentials; then I get a correct "Failed login for server news.newsgroup.ninja"

```
2019-02-25 13:39:28,919::INFO::[downloader:703] Connecting 2@newsreader.eweka.nl finished
2019-02-25 13:39:28,932::INFO::[newswrapper:105] 3@newszilla.xs4all.nl: Connected using TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384)
2019-02-25 13:39:28,937::INFO::[downloader:703] Connecting 3@newszilla.xs4all.nl finished
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/sander/git/py3-sab/sabnzbd/downloader.py", line 619, in run
    nw.finish_connect(nw.status_code)
  File "/home/sander/git/py3-sab/sabnzbd/newswrapper.py", line 353, in finish_connect
    raise NNTPPermanentError(nntp_to_msg(self.data))
nntplib.NNTPPermanentError: Authentication failed, check username/password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/sander/git/py3-sab/sabnzbd/downloader.py", line 628, in run
    ecode = int(msg[:3])
ValueError: invalid literal for int() with base 10: 'Aut'

2019-02-25 13:39:28,959::INFO::[newswrapper:105] 2@newszilla.xs4all.nl: Connected using TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384)
2019-02-25 13:39:28,962::INFO::[newswrapper:105] 5@newszilla.xs4all.nl: Connected using TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384)
2019-02-25 13:39:28,965::INFO::[newswrapper:105] 6@newszilla.xs4all.nl: Connected using TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384)
2019-02-25 13:39:28,966::INFO::[newswrapper:105] 4@newszilla.xs4all.nl: Connected using TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384)
```

![image](https://user-images.githubusercontent.com/1273502/53338241-8032aa80-3903-11e9-9cb6-21c2e6e8eef4.png)

Download speed goes to a very lowel level. SAB restarts itself now and then.

```
2019-02-25 18:52:04,699::INFO::[newswrapper:105] 5@newsreader.eweka.nl: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,700::INFO::[newswrapper:105] 6@newsreader.eweka.nl: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,703::INFO::[newswrapper:105] 7@newsreader.eweka.nl: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,708::INFO::[newswrapper:105] 8@newsreader.eweka.nl: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,850::INFO::[happyeyeballs:137] Quickest IP address for news.newsgroup.ninja (port 563, ssl 1, preferipv6 True) is 81.171.92.234
2019-02-25 18:52:04,853::INFO::[downloader:492] 2@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,856::INFO::[downloader:492] 3@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,864::INFO::[downloader:492] 4@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,867::INFO::[downloader:492] 5@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,870::INFO::[downloader:492] 6@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,871::INFO::[downloader:492] 7@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,872::INFO::[downloader:492] 8@news.newsgroup.ninja: Initiating connection
2019-02-25 18:52:04,923::INFO::[downloader:703] Connecting 8@newsreader.eweka.nl finished
2019-02-25 18:52:04,925::INFO::[newswrapper:105] 5@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,926::INFO::[downloader:703] Connecting 2@newsreader.eweka.nl finished
2019-02-25 18:52:04,926::INFO::[newswrapper:105] 6@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,926::INFO::[newswrapper:105] 4@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,926::INFO::[newswrapper:105] 3@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,926::INFO::[newswrapper:105] 2@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,927::INFO::[newswrapper:105] 1@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,927::INFO::[downloader:703] Connecting 6@newsreader.eweka.nl finished
2019-02-25 18:52:04,928::INFO::[downloader:703] Connecting 5@news.newsgroup.ninja finished
2019-02-25 18:52:04,929::INFO::[downloader:703] Connecting 6@news.newsgroup.ninja finished
2019-02-25 18:52:04,930::INFO::[downloader:703] Connecting 4@news.newsgroup.ninja finished
2019-02-25 18:52:04,931::INFO::[downloader:703] Connecting 3@news.newsgroup.ninja finished
2019-02-25 18:52:04,932::INFO::[downloader:703] Connecting 2@news.newsgroup.ninja finished
2019-02-25 18:52:04,933::INFO::[downloader:703] Connecting 1@news.newsgroup.ninja finished
2019-02-25 18:52:04,956::INFO::[newswrapper:105] 7@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,957::INFO::[newswrapper:105] 8@news.newsgroup.ninja: Connected using TLSv1.2 (AES128-SHA)
2019-02-25 18:52:04,960::INFO::[downloader:703] Connecting 8@news.newsgroup.ninja finished
2019-02-25 18:52:04,962::INFO::[downloader:703] Connecting 7@news.newsgroup.ninja finished
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/sander/git/py3-sab/sabnzbd/downloader.py", line 619, in run
    nw.finish_connect(nw.status_code)
  File "/home/sander/git/py3-sab/sabnzbd/newswrapper.py", line 353, in finish_connect
    raise NNTPPermanentError(nntp_to_msg(self.data))
nntplib.NNTPPermanentError: Authentication failed, check username/password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/sander/git/py3-sab/sabnzbd/downloader.py", line 628, in run
    ecode = int(msg[:3])
ValueError: invalid literal for int() with base 10: 'Aut'

2019-02-25 18:52:21,921::INFO::[__init__:985] Restarting because of crashed downloader
2019-02-25 18:52:21,922::INFO::[__init__:730] [N/A] Performing SABnzbd shutdown
2019-02-25 18:52:21,922::INFO::[__init__:365] SABnzbd shutting down...
2019-02-25 18:52:21,923::INFO::[directunpacker:463] Aborting all DirectUnpackers
2019-02-25 18:52:21,923::INFO::[urlgrabber:78] URLGrabber shutting down
2019-02-25 18:52:22,872::INFO::[dirscanner:321] Dirscanner shutting down

```

**Comment by sanderjo** [comment]
When I change the `raise ...` to a plain `pass`, I get a normal `Failed login for server news.newsgroup.ninja` and SAB keeps running nicely.

```
        elif self.user_ok and not self.pass_ok:
            if code != 281:
                # Assume that login failed (code 481 or other)
                #raise NNTPPermanentError(nntp_to_msg(self.data))
                pass
```

**Comment by Safihre** [comment]
Found the issue. In some cases we supply our own fake response, but it didn't include a NNTP-code so later on it would fail.

**Comment by Safihre** [comment]
Fixed and tests added! Please continue testing 😉
