### ISSUE TITLE
[py3] ValueError: ('Expected version spec in', "pypiwin32; sys_platform == 'win32'", 'at', "; sys_platform == 'win32'")

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1244]
... work-around: remove the  pypiwin32 from requirements.txt

Dislaimer: Ubuntu 16.04, which is EOL in a few months.

```
sander@haring:~/git/py3-sab$ sudo python3 -m pip install -r requirements.txt -U
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', "pypiwin32; sys_platform == 'win32'", 'at', "; sys_platform == 'win32'")

Storing debug log for failure in /home/sander/.pip/pip.log
sander@haring:~/git/py3-sab$
```

**Comment by Safihre** [comment]
That's due to the ancient version of `setuptools`, version 3.3 is from 2014. 
https://pypi.org/project/setuptools/3.3/#history

Update!

**Comment by sanderjo** [comment]
Ah:

```
sudo python3 -m pip uninstall setuptools
sudo python3 -m pip install setuptools
```
... and OK
