### ISSUE TITLE
[py3]: SAB passworded => traceback "TypeError: Unicode-objects must be encoded before hashing"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1246]
Happens on password-protected SAB webpage, after the login

Happens on Ubuntu 14.04 and Ubuntu 18.04

```
2019-02-26 16:48:32,512::DEBUG::[zconfig:96] Failed to start Bonjour service: (-65537, 'unknown')
2019-02-26 16:48:32,519::DEBUG::[downloader:416] SSL verification test: True
2019-02-26 16:49:08,832::ERROR::[_cplogging:222] [26/Feb/2019:16:49:08] HTTP
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/superman/git/py3-sab/sabnzbd/interface.py", line 105, in internal_wrap
    if not check_login() and not check_session_key:
  File "/home/superman/git/py3-sab/sabnzbd/interface.py", line 228, in check_login
    return check_login_cookie()
  File "/home/superman/git/py3-sab/sabnzbd/interface.py", line 215, in check_login_cookie
    return cherrypy.request.cookie['login_cookie'].value == hashlib.sha1(str(cherrypy.request.cookie['login_salt'].value) + cherrypy.request.remote.ip + COOKIE_SECRET).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
2019-02-26 16:49:08,837::INFO::[_cplogging:222] [26/Feb/2019:16:49:08] HTTP
Request Headers:
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6,de;q=0.5
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.46 Safari/537.36
  HOST: 127.0.0.1:11111
  ACCEPT-ENCODING: gzip, deflate, br
  COOKIE: login_cookie=7bfa44089cd12b012db56b8371cf91c58c57eccb; login_salt=896
  UPGRADE-INSECURE-REQUESTS: 1
  X-FORWARDED-HOST: www.aardappelzak.com
  CONNECTION: Keep-Alive
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
  X-FORWARDED-SERVER: www.aardappelzak.com
  Remote-Addr: 127.0.0.1
  X-FORWARDED-FOR: 11.22.52.90
  CACHE-CONTROL: max-age=0
```

**Comment by sanderjo** [comment]
Same same on Ubuntu 18.04 if SAB is passworded (no reverse proxy not relevant):

```
2019-02-26 18:24:29,854::ERROR::[_cplogging:216] [26/Feb/2019:18:24:29] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/py3-sab/sabnzbd/interface.py", line 682, in index
    set_login_cookie(remember_me=kwargs.get('remember_me', False))
  File "/home/sander/git/py3-sab/sabnzbd/interface.py", line 189, in set_login_cookie
    cherrypy.response.cookie['login_cookie'] = hashlib.sha1(str(salt) + cherrypy.request.remote.ip + COOKIE_SECRET).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
2019-02-26 18:24:29,871::INFO::[_cplogging:216] [26/Feb/2019:18:24:29] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: 127.0.0.1:8080
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  ORIGIN: http://127.0.0.1:8080
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  REFERER: http://127.0.0.1:8080/sabnzbd/login/
  ACCEPT-ENCODING: gzip, deflate, br
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6,de;q=0.5
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 31
```
