### ISSUE TITLE
[py3]: Show Logging => Traceback "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 344820: invalid continuation byte"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1248]
Another problem with Show Logging.

(Yes, after the fix:

```
$ git show HEAD
commit 50ad203aa8aa56ef18f5309cce5214abd4b67e00 (HEAD -> py3, origin/py3)
Author: Safihre <safihre@sabnzbd.org>
Date:   Tue Feb 26 22:21:15 2019 +0100

    Py3: Fix Show Logging
    
    Closes #1247

```

Traceback is:
```
2019-02-26 23:01:38,345::DEBUG::[misc:152] Cat->Attrib cat=movies pp=3 script=None prio=0
2019-02-26 23:01:39,966::ERROR::[_cplogging:216] [26/Feb/2019:23:01:39] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/py3-sab/sabnzbd/interface.py", line 120, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/home/sander/git/py3-sab/sabnzbd/interface.py", line 2278, in showlog
    log_data += open(sabnzbd.LOGFILE, "r").read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 344820: invalid continuation byte
2019-02-26 23:01:39,980::INFO::[_cplogging:216] [26/Feb/2019:23:01:39] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: 127.0.0.1:8080
  CONNECTION: keep-alive
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  REFERER: http://127.0.0.1:8080/sabnzbd/
  ACCEPT-ENCODING: gzip, deflate, br
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6,de;q=0.5
  COOKIE: login_cookie=a756d07b95a5f27501c609ae8a7440576adb569a; login_salt=550
2019-02-26 23:01:53,361::DEBUG::[__init__:913] [sabnzbd.rss.save] Saving data for rss_data.sab

```

**Comment by sanderjo** [comment]
Oh, wait: no problem after:

```
./SABnzbd.py -f blabla.ini
```

So ... something fishy in my real sabnzbd.ini ?

**Comment by Safihre** [comment]
In that case, sticking to bytes only.
Could you re-test?

**Comment by sanderjo** [comment]
re-test: works! 

FWIW:

My editor gedit says

> There was a problem opening the file “/home/sander/Downloads/sabnzbd (5).log”.
> The file you opened has some invalid characters. If you continue editing this file you could corrupt this document.
> You can also choose another character encoding and try again.

... so there is a non-ASCII-character in there, but ... so be it.
