### ISSUE TITLE
[py3] as a service: Traceback "ValueError: can't have unbuffered text I/O"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1255]
I get a traceback trying to run the py3 git version as a service.

Ubuntu 18.04.2
python3 3.6.7

Note: the git version works perfectly from CLI.

```
sander@haring1:~/git/sab-py3$ sudo service sabnzbdplus restart
Warning: The unit file, source configuration file or drop-ins of sabnzbdplus.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for sabnzbdplus.service failed because the control process exited with error code.
See "systemctl status sabnzbdplus.service" and "journalctl -xe" for details.

sander@haring1:~/git/sab-py3$ sudo systemctl daemon-reload

sander@haring1:~/git/sab-py3$ sudo service sabnzbdplus restart
Job for sabnzbdplus.service failed because the control process exited with error code.
See "systemctl status sabnzbdplus.service" and "journalctl -xe" for details.
sander@haring1:~/git/sab-py3$ sudo systemctl status sabnzbdplus.service
● sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
   Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
   Active: failed (Result: exit-code) since Fri 2019-03-08 12:01:39 CET; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4638 ExecStart=/etc/init.d/sabnzbdplus start (code=exited, status=1/FAILURE)

Mär 08 12:01:39 haring1 sabnzbdplus[4638]: Traceback (most recent call last):
Mär 08 12:01:39 haring1 sabnzbdplus[4638]:   File "/home/sander/git/sab-py3/SABnzbd.py", line 1694, in <module>
Mär 08 12:01:39 haring1 sabnzbdplus[4638]:     main()
Mär 08 12:01:39 haring1 sabnzbdplus[4638]:   File "/home/sander/git/sab-py3/SABnzbd.py", line 1083, in main
Mär 08 12:01:39 haring1 sabnzbdplus[4638]:     out_log = open(ol_path, 'a+', 0)
Mär 08 12:01:39 haring1 sabnzbdplus[4638]: ValueError: can't have unbuffered text I/O
Mär 08 12:01:39 haring1 sabnzbdplus[4638]:    ...fail!
Mär 08 12:01:39 haring1 systemd[1]: sabnzbdplus.service: Control process exited, code=exited status=1
Mär 08 12:01:39 haring1 systemd[1]: sabnzbdplus.service: Failed with result 'exit-code'.
Mär 08 12:01:39 haring1 systemd[1]: Failed to start LSB: SABnzbd+ binary newsgrabber.
sander@haring1:~/git/sab-py3$
```

Maybe related to https://github.com/chriskiehl/Gooey/issues/289#issuecomment-387912257

OK from CLI:
```
sander@haring1:~/git/sab-py3$ ./SABnzbd.py
2019-03-08 12:05:21,273::INFO::[SABnzbd:1111] --------------------------------
2019-03-08 12:05:21,273::INFO::[SABnzbd:1112] SABnzbd.py-3.0.0-develop (rev=unknown)
2019-03-08 12:05:21,274::INFO::[SABnzbd:1113] Full executable path = /home/sander/git/sab-py3/SABnzbd.py
2019-03-08 12:05:21,274::INFO::[SABnzbd:1123] Platform = posix
2019-03-08 12:05:21,274::INFO::[SABnzbd:1124] Python-version = 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
2019-03-08 12:05:21,274::INFO::[SABnzbd:1125] Arguments = ./SABnzbd.py
2019-03-08 12:05:21,274::INFO::[SABnzbd:1128] Preferred encoding = UTF-8
2019-03-08 12:05:21,275::INFO::[SABnzbd:1135] SSL version = OpenSSL 1.1.0g  2 Nov 2017
2019-03-08 12:05:21,275::INFO::[SABnzbd:1182] Read INI file /home/sander/.sabnzbd/sabnzbd.ini
2019-03-08 12:05:21,292::INFO::[postproc:100] Loading postproc queue
2019-03-08 12:05:21,294::INFO::[__init__:877] [N/A] /home/sander/.sabnzbd/admin/Rating.sab missing
2019-03-08 12:05:21,294::INFO::[scheduler:207] Setting schedule for midnight BPS reset
2019-03-08 12:05:21,297::INFO::[config:831] Writing settings to INI file /home/sander/.sabnzbd/sabnzbd.ini
2019-03-08 12:05:21,299::INFO::[__init__:330] All processes started
2019-03-08 12:05:21,300::INFO::[SABnzbd:253] Web dir is /home/sander/git/sab-py3/interfaces/Glitter
2019-03-08 12:05:21,332::INFO::[SABnzbd:253] Web dir is /home/sander/git/sab-py3/interfaces/Config
2019-03-08 12:05:21,362::INFO::[config:831] Writing settings to INI file /home/sander/.sabnzbd/sabnzbd.ini
2019-03-08 12:05:21,376::INFO::[SABnzbd:365] SABYenc module (v4.0.0)... found!
2019-03-08 12:05:21,376::INFO::[SABnzbd:377] Cryptography module (v2.6.1)... found!
2019-03-08 12:05:21,376::INFO::[SABnzbd:380] par2 binary... found (/usr/bin/par2)
2019-03-08 12:05:21,377::INFO::[SABnzbd:392] UNRAR binary... found (/usr/bin/unrar)
2019-03-08 12:05:21,377::INFO::[SABnzbd:400] UNRAR binary version 5.50
2019-03-08 12:05:21,378::INFO::[SABnzbd:407] unzip binary... found (/usr/bin/unzip)
2019-03-08 12:05:21,378::INFO::[SABnzbd:412] 7za binary... found (/usr/bin/7za)
2019-03-08 12:05:21,378::INFO::[SABnzbd:418] nice binary... found (/usr/bin/nice)
2019-03-08 12:05:21,379::INFO::[SABnzbd:422] ionice binary... found (/usr/bin/ionice)
2019-03-08 12:05:21,380::INFO::[SABnzbd:1336] Starting web-interface on 0.0.0.0:8080
2019-03-08 12:05:21,400::INFO::[_cplogging:216] [08/Mar/2019:12:05:21] ENGINE Bus STARTING
2019-03-08 12:05:21,526::INFO::[_cplogging:216] [08/Mar/2019:12:05:21] ENGINE Serving on http://0.0.0.0:8080
2019-03-08 12:05:21,527::INFO::[_cplogging:216] [08/Mar/2019:12:05:21] ENGINE Bus STARTED
2019-03-08 12:05:21,527::INFO::[SABnzbd:1385] Starting SABnzbd.py-3.0.0-develop
2019-03-08 12:05:21,531::INFO::[dirscanner:330] Dirscanner starting up
2019-03-08 12:05:21,532::INFO::[postproc:187] Completed Download Folder /home/sander/Downloads/complete is not on FAT
2019-03-08 12:05:21,532::INFO::[urlgrabber:83] URLGrabber starting up
2019-03-08 12:05:21,556::INFO::[zconfig:76] Bonjour/ZeroConfig does not support "localhost"
```

**Comment by sanderjo** [comment]
OK ... without any knowledge, I changed that line to 

`            out_log = open(ol_path, 'ab+', 0)`

(so, a 'b' into it), and now SAB works as a service ....

**Comment by Safihre** [comment]
Closing, duplicate #1237 😉
