### ISSUE TITLE
Synology: big (26MB) sabnzbd.error.log, with binary stuff

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1269]
Triggered by https://forums.sabnzbd.org/viewtopic.php?f=3&t=24095

On my synology, there is a big (26MB) sabnzbd.error.log:
```
root@DiskStation:/# ls -al /volume1/@appstore/sabnzbd/var/logs/sabnzbd.error.log
-rw-r--r-- 1 sc-sabnzbd sabnzbd 26243433 Mar 18 17:43 /volume1/@appstore/sabnzbd/var/logs/sabnzbd.error.log
```

Inspecting the sabnzbd.error.log, it's binary stuff.

Is this how it should be?

For now, I've renamed the file

```
root@DiskStation:/# mv /volume1/@appstore/sabnzbd/var/logs/sabnzbd.error.log /volume1/@appstore/sabnzbd/var/logs/sabnzbd.error.log.OLD
root@DiskStation:/# ls -al /volume1/@appstore/sabnzbd/var/logs/
total 27048
drwxr-xr-x 2 sc-sabnzbd sabnzbd     4096 Apr  8 14:41 .
drwxr-xr-x 5 sc-sabnzbd sabnzbd     4096 Mar 15 16:39 ..
-rw-r--r-- 1 sc-sabnzbd sabnzbd 26243433 Mar 18 17:43 sabnzbd.error.log.OLD
-rw-r--r-- 1 sc-sabnzbd sabnzbd  1435827 Apr  8 14:41 sabnzbd.log
root@DiskStation:/#
```

Update: everything is binary, except the last lines: a Traceback. Just one traceback in the complete log.

![image](https://user-images.githubusercontent.com/1273502/55724258-51801780-5a0b-11e9-9f1d-61901b19e0d0.png)

![image](https://user-images.githubusercontent.com/1273502/55724472-c3f0f780-5a0b-11e9-93d2-51c39e33f39c.png)

**Comment by pven** [comment]
So I have the same problem. If you need info, just let me know.

**Comment by pven** [comment]
Btw: my biggest sabnzbd.error-log is 1,5GB ...

**Comment by Safihre** [comment]
Crazy, seems to be unrelated to the platform (Synology/etc).
Can you (@sanderjo/@pven) remove this line from `SABnzbd.py`? This way we can identify if it's `stderr` _or_ `stdout`.
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1134

**Comment by pven** [comment]
Done, and started a download that will probably fail. So far, a empty sabnzbd.error.log is created.

**Comment by pven** [comment]
And something is in there:
```
Exception in thread Thread-169:
Traceback (most recent call last):
  File "/var/packages/python/target/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/directunpacker.py", line 171, in run
    char = self.active_instance.stdout.read(1)
ValueError: I/O operation on closed file
```

**Comment by sanderjo** [comment]
Done. 


```
root@DiskStation:/volume1/@appstore/sabnzbd/share/SABnzbd# cat SABnzbd.py |  grep -n " os.dup2(out_log.fileno()"
1133:            os.dup2(out_log.fileno(), sys.stderr.fileno())
1134:            # os.dup2(out_log.fileno(), sys.stdout.fileno())
root@DiskStation:/volume1/@appstore/sabnzbd/share/SABnzbd#
```

**Comment by sanderjo** [comment]
FWIW: my very wild guesses for the binary stuff:

- a rar file that ends up in STDOUT/STDERR
- a core dump that ends up in STDOUT/STDERR

**Comment by pven** [comment]
I saved some old binary error-logs. Can I somehow find out whats in there?

**Comment by pven** [comment]
Wen ignoring the text I saw 'par2j' in there, looks like a par2-file. Which sounds like what @sanderjo says: there is some kind of binary in there.

**Comment by sanderjo** [comment]
I searched for 'par2' in the bulky sabnzbd.error.log, and it's there 41.

```
$ cat sabnzbd.error.log | grep -i -a par2 | wc -l
41
```

Searching more, I see the name of a certain download (I've changed some letters), and it looks like the rar file names.

```
00abc7b0  00 00 00 00 54 68 65 2e  0a 42 61 6c 6c 61 64 2e  |....The..Billad.|
00abc7c0  6f 0a 66 2e 42 75 73 74  65 72 0a 2e 53 63 72 75  |o.f.Bister..Scri|
00abc7d0  67 67 73 0a 2e 32 30 31  38 2e 31 30 0a 38 30 70  |ggs..2018.10.80p|
00abc7e0  2e 4e 46 2e 57 0a 45 42  2d 44 4c 2e 44 44 0a 50  |.NF.W.EB-DL.DD.P|
00abc7f0  35 2e 31 2e 78 32 36 0a  34 2d 6d 6f 6e 6b 65 65  |5.1.x26.4-monkee|
00abc800  0a 2e 72 34 30 50 41 52  32 0a 00 50 4b 54 18 01  |..r40PAR2..PKT..|
```



```
$ cat sabnzbd.error.log | hd | grep -i par2
00aba8e0  36 4b 7a 0a 44 fe 1c f4  50 41 52 32 0a 00 50 4b  |6Kz.D...PAR2..PK|
00abaa20  0d 2a e4 50 41 52 32 0a  00 50 4b 54 c0 00 00 00  |.*.PAR2..PKT....|
00abaaf0  6d 6f 6e 6b 65 65 0a 2e  72 32 36 50 41 52 32 0a  |monkee..r26PAR2.|
00abac30  7a 0a 18 94 7d 80 50 41  52 32 0a 00 50 4b 54 c0  |z...}.PAR2..PKT.|
00abae40  22 92 38 2e 0a 89 04 57  73 50 41 52 32 0a 00 50  |".8....WsPAR2..P|
00abaf20  38 50 41 52 32 0a 00 50  4b 54 18 01 00 00 0a 00  |8PAR2..PKT......|
00abb050  92 3d 24 b8 af 36 dd 0a  94 13 00 64 50 41 52 32  |.=$..6.....dPAR2|
00abb130  2e 72 32 39 50 41 52 32  0a 00 50 4b 54 18 01 00  |.r29PAR2..PKT...|
00abb340  65 65 0a 2e 72 33 30 50  41 52 32 0a 00 50 4b 54  |ee..r30PAR2..PKT|
00abb480  91 b5 50 41 52 32 0a 00  50 4b 54 c0 00 00 00 0a  |..PAR2..PKT.....|
00abb550  6f 6e 6b 65 65 0a 2e 72  33 31 50 41 52 32 0a 00  |onkee..r31PAR2..|
00abb690  0a 6a 19 d9 b6 50 41 52  32 0a 00 50 4b 54 c0 00  |.j...PAR2..PKT..|
00abb8a0  26 ad 56 0a 34 50 41 2c  50 41 52 32 0a 00 50 4b  |&.V.4PA,PAR2..PK|
00abb980  50 41 52 32 0a 00 50 4b  54 18 01 00 00 0a 00 00  |PAR2..PKT.......|
00abbab0  b6 a3 34 4e 75 51 0a 69  98 50 92 50 41 52 32 0a  |..4NuQ.i.P.PAR2.|
00abbb90  72 33 34 50 41 52 32 0a  00 50 4b 54 18 01 00 00  |r34PAR2..PKT....|
00abbda0  65 0a 2e 72 33 35 50 41  52 32 0a 00 50 4b 54 18  |e..r35PAR2..PKT.|
00abbee0  73 50 41 52 32 0a 00 50  4b 54 c0 00 00 00 0a 00  |sPAR2..PKT......|
00abbfb0  6e 6b 65 65 0a 2e 72 33  36 50 41 52 32 0a 00 50  |nkee..r36PAR2..P|
00abc0f0  f5 92 4c 71 50 41 52 32  0a 00 50 4b 54 c0 00 00  |..LqPAR2..PKT...|
00abc1c0  2d 6d 6f 6e 6b 65 65 0a  2e 72 33 37 50 41 52 32  |-monkee..r37PAR2|
00abc300  69 3f 0a 44 cc ae 8f 50  41 52 32 0a 00 50 4b 54  |i?.D...PAR2..PKT|
00abc510  0b f6 1c 1f c4 0a f5 27  30 c5 50 41 52 32 0a 00  |.......'0.PAR2..|
00abc5f0  33 39 50 41 52 32 0a 00  50 4b 54 18 01 00 00 0a  |39PAR2..PKT.....|
00abc800  0a 2e 72 34 30 50 41 52  32 0a 00 50 4b 54 18 01  |..r40PAR2..PKT..|
00abc940  50 41 52 32 0a 00 50 4b  54 c0 00 00 00 0a 00 00  |PAR2..PKT.......|
00abca10  6b 65 65 0a 2e 72 34 31  50 41 52 32 0a 00 50 4b  |kee..r41PAR2..PK|
00abcb50  77 8c eb 50 41 52 32 0a  00 50 4b 54 c0 00 00 00  |w..PAR2..PKT....|
00abcc20  6d 6f 6e 6b 65 65 0a 2e  72 34 32 50 41 52 32 0a  |monkee..r42PAR2.|
00abcd60  a6 0a b0 88 2a 9d 50 41  52 32 0a 00 50 4b 54 c0  |....*.PAR2..PKT.|
00abcf70  c9 6d 13 0b 0a a4 d6 55  c1 50 41 52 32 0a 00 50  |.m.....U.PAR2..P|
00abd050  34 50 41 52 32 0a 00 50  4b 54 18 01 00 00 0a 00  |4PAR2..PKT......|
00abd180  18 c0 c4 47 15 85 4f 0a  31 36 0c 49 50 41 52 32  |...G..O.16.IPAR2|
00abd260  2e 72 34 35 50 41 52 32  0a 00 50 4b 54 44 40 9c  |.r45PAR2..PKTD@.|

```

**Comment by Safihre** [comment]
Yep, those are par2 files `par2 pkt`

**Comment by pven** [comment]
> Crazy, seems to be unrelated to the platform (Synology/etc).
> Can you (@sanderjo/@pven) remove this line from `SABnzbd.py`? This way we can identify if it's `stderr` _or_ `stdout`.
> https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1134

FYI: since I did this, no binary stuff has been added to sabnzbd.error.log

**Comment by thezoggy** [comment]
It's prob just the par2 packet code that we log to show what app generated the data..  I would comment that line out and confirm

**Comment by sanderjo** [comment]
I redownload the NZB again:

without `os.dup2(out_log.fileno(), sys.stdout.fileno())`: no sabnzbd.error.log (or: size 0 bytes)
with `os.dup2(out_log.fileno(), sys.stdout.fileno())` in place again: 22 MB sabnzbd.error.log

**Comment by Safihre** [comment]
You can maybe remove these lines and try again? But with `stdout` back on.
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/par2file.py#L167-L172

**Comment by sanderjo** [comment]
So SABnzbd.py is (still) back to original, I've removed those 5 lines, restarted SABnzbd and re-downloading the NZB ... 

Result in 48 minutes.

```
root@DiskStation:/volume1/@appstore/sabnzbd/share/SABnzbd# diff sabnzbd/par2file.py sabnzbd/par2file.py.ORG
166a167,171
>         elif data[offset:offset + 15] == PAR_CREATOR_ID:
>             # From here until the end is the creator-text
>             # Useful in case of bugs in the par2-creating software
>             par2creator = data[offset+16:].strip('\0')  # Remove any trailing \0
>             logging.debug('Par2-creator of %s is: %s', os.path.basename(f.name), par2creator)

```

**Comment by sanderjo** [comment]
Update: sabnzbd.error.log has grown again:

```
root@DiskStation:~# ls -al /volume1/@appstore/sabnzbd/var/logs/sabnzbd.error.log                                                                             -rw-r--r-- 1 sc-sabnzbd sabnzbd 45555712 Apr 14 09:58 /volume1/@appstore/sabnzbd                                                                             /var/logs/sabnzbd.error.log
root@DiskStation:~#
```

So uncommenting that `elif` did not solve it.

**Comment by thezoggy** [comment]
checking my windows sab install, never have had a sabnzbd.error.log file since installing sab 1.x.

checking friends ubuntu box, he has a 104 meg file with repeating errors like:
```
Exception in thread Thread-11776:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/sabnzbdplus/sabnzbd/directunpacker.py", line 241, in run
    self.create_unrar_instance()
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/directunpacker.py", line 348, in create_unrar_instance
    rarfile_path = os.path.join(self.nzo.downpath, self.rarfile_nzf.filename)
AttributeError: 'bool' object has no attribute 'filename'

Exception in thread Thread-12513:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/sabnzbdplus/sabnzbd/directunpacker.py", line 241, in run
    self.create_unrar_instance()
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/directunpacker.py", line 348, in create_unrar_instance
    rarfile_path = os.path.join(self.nzo.downpath, self.rarfile_nzf.filename)
AttributeError: 'bool' object has no attribute 'filename'
```

**Comment by thezoggy** [comment]
@sanderjo I wonder if its this 'print' that gets sent to stderr: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/par2file.py#L134
can you try omitting `parse_par2_file_packet` completely by just force it to do `return nothing` after the declare so it bypasses and we can confirm.

**Comment by sanderjo** [comment]
@thezoggy I commented out that specific, did a redownload, and ... no extra stuff sabnzbd.error.log (to be exact: still the logging of yesterday morning.

Looks good. To be sure, I will put that line back in, and redownload, and verify that I get the extra binary stuff in sabnzbd.error.log again ...


```
root@DiskStation:/volume1/@appstore/sabnzbd/var/logs# ls -al sabnzbd.error.log
-rw-r--r-- 1 sc-sabnzbd sabnzbd 45555712 Apr 14 09:58 sabnzbd.error.log
root@DiskStation:/volume1/@appstore/sabnzbd/var/logs#
```

**Comment by sanderjo** [comment]
Oh, wait: maybe the problem is in

par2creator = data[offset+16:].strip('\0')  # Remove any trailing \0

... it does not end the string. I think I have introduced that code ... and maybe I was thinking too much C style, assuming to stop the string at `\0` ...

So new code:

```
root@DiskStation:/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd# diff par2file.py.ORG par2file.py
171c171
<             logging.debug('Par2-creator of %s is: %s', os.path.basename(f.name), par2creator)
---
>             logging.debug('Par2-creator of DELETED SJ. Length of par2creator is %d', len(par2creator) )
root@DiskStation:/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd#
```

**Comment by Safihre** [comment]
@sanderjo So does it still happen after using that code?

**Comment by sanderjo** [comment]
I'm close to giving up after a Traceback, confusion about what is causing what, slowness of the Synology, and not able to reproduce it on my (fast) Linux machine.

**Comment by pven** [comment]
Can I test something on my not so fast Synology?

Last sabnzbd.error.log I have is from today, but it is empty. (I commented out line 1134, thats all I did)

**Comment by Safihre** [comment]
Oh shit, that `print header` is still in there?! I totally missed that and your comment about it, sorry @thezoggy!

Of course that's the problem...

**Comment by Safihre** [comment]
I added [some code](https://github.com/sabnzbd/sabnzbd/commit/b0332e141c9c588abd615a858525f8e5a02e9f78) that will remove the `sabnzbd.error.log` if it gets above the maximum size we also use for the normal log.
