### ISSUE TITLE
sabnzbd -- 2.3.9 [03c10dc] -  Decoder failure: Out of memory

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1295]
friends sab instance is spewing memory errors after updating to 2.3.9:
```
2019-05-31 09:14:53,191::WARNING::[decoder:139] Decoder failure: Out of memory
2019-05-31 09:14:53,191::INFO::[decoder:141] Decoder-Queue: 0, Cache: 0, 0, 0
2019-05-31 09:14:53,191::INFO::[decoder:142] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/decoder.py", line 124, in run
    data = self.decode(article, lines, raw_data)
  File "/usr/share/sabnzbdplus/sabnzbd/decoder.py", line 222, in decode
    decoded_data, output_filename, crc, crc_expected, crc_correct = sabyenc.decode_usenet_chunks(raw_data, article.bytes)
MemoryError
```

```$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32070        5406         440           2       26224       26203
Swap:         61033        1255       59778
```

**Comment by thezoggy** [comment]
told sab to restart in the gui,
```$ ps -aux | grep sab
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
keith     1590  3.4  0.2 2486328 73504 ?       Sl   09:23   0:01 /usr/bin/python2 /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
```

```
2019-05-31 09:23:09,844::INFO::[_cplogging:219] [31/May/2019:09:23:09] ENGINE Re-spawning /usr/bin/python2 /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
2019-05-31 09:23:10,665::INFO::[sabnzbdplus:1152] --------------------------------
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1153] sabnzbdplus-2.3.9 (rev=03c10dce91e13918bc2e6f8ca9c309196b90be11)
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1154] Full executable path = /usr/bin/sabnzbdplus
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1164] Platform = posix
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1165] Python-version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1166] Arguments = /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1171] Preferred encoding = UTF-8
2019-05-31 09:23:10,666::INFO::[sabnzbdplus:1181] SSL version = OpenSSL 1.1.0g  2 Nov 2017
2019-05-31 09:23:11,103::DEBUG::[sabnzbdplus:1222] CPU Pystone available performance = 155587
2019-05-31 09:23:11,120::DEBUG::[sabnzbdplus:1227] CPU model = Intel(R) Xeon(R) CPU E5-2630L v3 @ 1.80GHz
2019-05-31 09:23:11,120::INFO::[sabnzbdplus:1229] Read INI file /home/keith/.sabnzbd/sabnzbd.ini
...
2019-05-31 09:23:11,229::INFO::[sabnzbdplus:397] SABYenc module (v3.3.5)... found!
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:414] Cryptography module (v1.2.3)... found!
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:419] par2 binary... found (/usr/bin/par2)
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:429] UNRAR binary... found (/usr/bin/unrar)
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:437] UNRAR binary version 5.10
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:442] unzip binary... found (/usr/bin/unzip)
2019-05-31 09:23:11,230::INFO::[sabnzbdplus:447] 7za binary... found (/usr/bin/7za)
2019-05-31 09:23:11,231::INFO::[sabnzbdplus:453] nice binary... found (/usr/bin/nice)
2019-05-31 09:23:11,231::INFO::[sabnzbdplus:457] ionice binary... found (/usr/bin/ionice)
2019-05-31 09:23:11,232::INFO::[sabnzbdplus:1385] Starting web-interface on 0.0.0.0:8800
...
2019-05-31 09:23:12,446::INFO::[downloader:490] 1@news.cheapnews.eu: Initiating connection
2019-05-31 09:23:14,239::INFO::[downloader:704] Connecting 1@news.cheapnews.eu finished
2019-05-31 09:23:14,643::WARNING::[decoder:139] Decoder failure: Out of memory
2019-05-31 09:23:14,644::INFO::[decoder:141] Decoder-Queue: 0, Cache: 0, 0, 0
2019-05-31 09:23:14,644::INFO::[decoder:142] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/decoder.py", line 124, in run
    data = self.decode(article, lines, raw_data)
  File "/usr/share/sabnzbdplus/sabnzbd/decoder.py", line 222, in decode
    decoded_data, output_filename, crc, crc_expected, crc_correct = sabyenc.decode_usenet_chunks(raw_data, article.bytes)
MemoryError
2019-05-31 09:23:14,645::INFO::[downloader:279] Pausing
```

so on restart can see that with one item in the queue seeing the memory spike and the error still there:
```
$ ps -aux | grep sab
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
keith     1590  7.6  2.1 2954828 715252 ?      Sl   09:23   0:29 /usr/bin/python2 /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
```

**Comment by thezoggy** [comment]
might have found the issue, article cache limit was set to `0`. setting it to `512M` and restarting. yep that fixed it.

**Comment by Safihre** [comment]
MemoryError is really only thrown if the `malloc` call in C fails. Since that's such low level, I would be surprised if that was a false reading.

**Comment by thezoggy** [comment]
welp, setting it to 512M did not fix it. so something is still up.

**Comment by thezoggy** [comment]
so there was one nzb in the queue that just seemed 'stuck'. 
even downgraded on 2.3.2 the memory problem was happening. 
deleted that queue item and now the out of memory problem seems resolved....

**Comment by thezoggy** [comment]
re-upgraded back to 2.3.9. added orphaned nzb back to the queue. no problems. so no idea the true root cause. just that the 'stuck' nzb in the queue was tied to it.
