### ISSUE TITLE
Exception when nzb filename is short number

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1296]
https://forums.sabnzbd.org/viewtopic.php?f=11&t=24228&p=118912#p118912

```
2019-05-29 12:50:21,483::INFO::[postproc:328] Starting Post-Processing on 1000 => Repair:True, Unpack:True, Delete:True, Script:, Cat:*
2019-05-29 12:50:21,520::INFO::[nzbstuff:1548] [sabnzbd.postproc.process_job] Purging data for job 1000 (delete_all_data=False)
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\t\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\git\sabnzbd\sabnzbd\postproc.py", line 239, in run
    process_job(nzo)
  File "C:\git\sabnzbd\sabnzbd\postproc.py", line 570, in process_job
    history_db.add_history_db(nzo, clip_path(workdir_complete), nzo.downpath, postproc_time, script_log, script_line)
  File "C:\git\sabnzbd\sabnzbd\database.py", line 280, in add_history_db
    t = build_history_info(nzo, storage, path, postproc_time, script_output, script_line, series_info=True)
  File "C:\git\sabnzbd\sabnzbd\database.py", line 493, in build_history_info
    seriesname, season, episode, _ = sabnzbd.newsunpack.analyse_show(nzo.final_name)
  File "C:\git\sabnzbd\sabnzbd\newsunpack.py", line 2281, in analyse_show
    job.match(force=True)
  File "C:\git\sabnzbd\sabnzbd\sorting.py", line 207, in match
    self.match_obj, self.extras = check_regexs(self.original_job_name, series_match)
  File "C:\git\sabnzbd\sabnzbd\sorting.py", line 1139, in check_regexs
    match1 = expression.search(filename)
TypeError: expected string or bytes-like object
```

**Comment by sanderjo** [comment]
I tried with "1.nzb" on SAB-py2 and "2.nzb" on SAB-py3, and no problem at all. So ... am I doing wrong?

**Comment by puzzledsab** [comment]
I don't know what happened. I am unable to recreate the error, even with the same file. It's possible that it was orphaned and recovered.

**Comment by Safihre** [comment]
Closing it then :)
