### ISSUE TITLE
py3: wrongpassword in curly brackets => (double) traceback

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1301]
I got the password protected NZB (https://www.binsearch.info/?q=reftestnzb+password+is+test123+8ca204ccaf40&max=100&adv_age=1100&server=) and renamed it to `reftestnzb-8ca204ccaf40{{wrongPassword}}.nzb` and fed it to py3-sab, which gave the (double?) traceback below.

```
}/__ADMIN__/SABnzbd_nzf_giuyprcl
2019-06-18 20:37:52,947::INFO::[misc:697] Found a password that was set by the user:  wrongPassword
2019-06-18 20:37:52,947::INFO::[assembler:258] Trying password "wrongPassword" on job "reftestnzb-8ca204ccaf40{{wrongPassword}}"
2019-06-18 20:37:53,003::INFO::[assembler:304] Error during inspection of RAR-file /home/sander/Downloads/incomplete/reftestnzb-8ca204ccaf40{{wrongPassword}}/my_passworded_post.part01.rar
2019-06-18 20:37:53,003::DEBUG::[assembler:305] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/blabla-sab/sabnzbd/assembler.py", line 266, in check_encrypted_and_unwanted_files
    zf.testrar()
  File "/home/sander/git/blabla-sab/sabnzbd/utils/rarfile.py", line 874, in testrar
    check_returncode(p, output)
  File "/home/sander/git/blabla-sab/sabnzbd/utils/rarfile.py", line 2992, in check_returncode
    raise exc(msg)
sabnzbd.utils.rarfile.RarWrongPassword: None [11]: b'\nThe specified password is incorrect.\nCannot find volume /home/sander/Downloads/incomplete/reftestnzb-8ca204ccaf40{{wrongPassword}}/my_passworded_post.part02.rar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sander/git/blabla-sab/sabnzbd/assembler.py", line 275, in check_encrypted_and_unwanted_files
    if 'need to start extraction from a previous volume' in e:
TypeError: argument of type 'RarWrongPassword' is not iterable
2019-06-18 20:37:53,004::DEBUG::[directunpacker:130] DirectUnpack queued my_passworded_post.part01.rar for my_passworded_post
2019-06-18 20:37:53,005::DEBUG::[filesystem:691] Renaming "/home/sander/Downloads/complete/reftestnzb-8ca204ccaf40{{wrongPassword}}" to "/home/sander/Downloads/complete/_UNPACK_reftestnzb-8ca204ccaf40{{wrongPassword}}"
```

The `TypeError: argument of type 'RarWrongPassword' is not iterable`:

type of e is <class 'sabnzbd.utils.rarfile.RarWrongPassword'>

... not a string or so.

**Comment by Safihre** [comment]
Fixed
