### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by windancert** [sabnzbd/sabnzbd#1306]
I was adding a bunch of .nzb files by placing them in a watched directory and I saw this error appear:
```
 [07/Jul/2019:10:57:37] HTTP 
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 468, in tapi
    return api_handler(kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 110, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 530, in _api_history
    output=output)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 1795, in build_history
    items = get_active_history(queue, items)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 1868, in get_active_history
    history = build_history_info(nzo)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/database.py", line 478, in build_history_info
    stages = decode_factory(nzo.unpack_info)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/database.py", line 570, in decode_factory
    for key in text:
RuntimeError: dictionary changed size during iteration
```

It looks like the same problem as #318 but it is a much more recent version of SabNZBD: I'm running SabNZBD 2.3.5 on Synology with Python 2.7.14 (default, May 28 2018, 14:47:12) [GCC 4.6.4] [UTF-8]

**Comment by sanderjo** [comment]
Can you reproduce it? If so, how?

Because if you can reproduce it, it's worth trying the solution with `list(...)` like https://stackoverflow.com/a/11941855

**Comment by windancert** [comment]
Haven't been able to reproduce so far, I'll keep monitoring.

**Comment by Safihre** [comment]
Will close due to it being very rare!
