### ISSUE TITLE
py3: Password in the nzb filename breaks retry

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1315]
When the password is stored as {{password}} in the file name it is included in the directory name as well. If the download fails and I click retry I have to enter the password in the pop up box. However, this time it looks for a path without the password and fails with
```
  File "<redacted>\sabnzbd\interface.py", line 121, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "<redacted>\sabnzbd\interface.py", line 489, in retry_pp
    retry_job(kwargs.get('job'), kwargs.get('nzbfile'), kwargs.get('password'))
  File "<redacted>\sabnzbd\api.py", line 1425, in retry_job
    nzo_id = NzbQueue.do.repair_job(path, new_nzb, password)
  File "<redacted>\sabnzbd\nzbqueue.py", line 174, in repair_job
    nzo = NzbObject(name, pp=None, script=None, nzb='', cat=None, priority=None, nzbname=name, reuse=True)
  File "<redacted>\sabnzbd\nzbstuff.py", line 545, in __init__
    os.mkdir(adir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '<redacted>\\passworded\\__ADMIN__'
```
The actual directory is called passworded{{test123}}. When I rename it to passworded and recover it through orphaned jobs it works.

Test: Download https://gist.github.com/puzzledsab/5ed1fb14a6e0212dd5994dd7e3787d98 and call it passworded{{test123}}.nzb.

**Comment by sanderjo** [comment]
I tested with:

SAB-py3 on Linux:  `Error "'str' object has no attribute 'append'" while running rar_unpack on passworded{{test123}}`

SAB-py2 on Linux: No problem

```
2019-08-02 07:51:03,821::DEBUG::[filesystem:725] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/<USERNAME>/git/sab-py3/Downloads/incomplete/passworded{{test123}}/__ADMIN__/SABnzbd_nzf__ikbk74k
2019-08-02 07:51:03,822::INFO::[misc:697] Found a password that was set by the user:  test123
2019-08-02 07:51:03,822::INFO::[assembler:304] Error during inspection of RAR-file /home/<USERNAME>/git/sab-py3/Downloads/incomplete/passworded{{test123}}/my_passworded_post.part09.rar
2019-08-02 07:51:03,822::DEBUG::[assembler:305] Traceback: 
Traceback (most recent call last):
  File "/home/<USERNAME>/git/sab-py3/sabnzbd/assembler.py", line 243, in check_encrypted_and_unwanted_files
    passwords = get_all_passwords(nzo)
  File "/home/<USERNAME>/git/sab-py3/sabnzbd/misc.py", line 705, in get_all_passwords
    meta_passwords.append(pw)
AttributeError: 'str' object has no attribute 'append'
2019-08-02 07:51:03,966::DEBUG::[nzbstuff:1229] Download Quality: bad-articles=0
```

**Comment by Safihre** [comment]
Fixed
