### ISSUE TITLE
[py3] after running py2: "Loading /home/sander/.sabnzbd/admin/rss_data.sab failed"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1321]
Running py3 after running py2, SAB's GUI says

`Error: Loading /home/sander/.sabnzbd/admin/rss_data.sab failed`
But the RSS is OK

![image](https://user-images.githubusercontent.com/1273502/63209758-93ba1380-c0e5-11e9-81dd-6944c9f15e4e.png)

On the second run of py3, the error does not happen. So ... this could be relevant for users switchting from py2 to py3, who have RSS filled out. And it could scare them. 
As the RSS just works, mabye just an try - except - pass (and maybe only on the first run)? And or label as py3, or not?

With py3, the console says:
```
2019-08-17 11:49:00,425::ERROR::[__init__:922] Loading /home/sander/.sabnzbd/admin/rss_data.sab failed
2019-08-17 11:49:00,425::INFO::[__init__:923] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/__init__.py", line 915, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 1: invalid continuation byte

```
The strange thing is I don't see 0xe3 at position (=byte?) 1.

FWIW & less relevant: Switching back to py2, gives an explainable message:

```
2019-08-17 11:54:54,839::ERROR::[__init__:999] Loading /home/sander/.sabnzbd/admin/rss_data.sab failed with error <type 'exceptions.ValueError'>
2019-08-17 11:54:54,839::INFO::[__init__:1000] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/__init__.py", line 993, in load_admin
    data = cPickle.load(data_file)
ValueError: unsupported pickle protocol: 4
```

**Comment by sanderjo** [comment]
With some lines of code, no more Error (good) ... but I'm not sure the data from `rss_data.sab` in python2 style is inherited & used at all ...

```
2019-08-17 16:26:59,924::DEBUG::[__init__:910] [sabnzbd.load_admin] Loading data for rss_data.sab from /home/sander/.sabnzbd/admin/rss_data.sab
2019-08-17 16:26:59,925::DEBUG::[__init__:919] SJ: Maybe python2 heritage
2019-08-17 16:26:59,928::DEBUG::[__init__:921] SJ: ... that worked!
```
Code: see the a few lines around `data = pickle.load(data_file, encoding='latin1')`:

```
    try:
        with open(path, "rb") as data_file:
            if do_pickle:
                try:
                    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
                except:
                    # Maybe the pickle is in python2 style:
                    logging.debug("SJ: Maybe python2 heritage")
                    data = pickle.load(data_file, encoding='latin1')
                    logging.debug("SJ: ... that worked!")
                    
            else:
                data = data_file.read()

        if remove:
            filesystem.remove_file(path)
    except:
        logging.error(T("Loading %s failed"), path)
        logging.info("Traceback: ", exc_info=True)
        return None
```

**Comment by sanderjo** [comment]
Or a lazy method:

```
except UnicodeDecodeError:
    print("probably an older file")
    pass
```

**Comment by Safihre** [comment]
Agreed, let's use UnicodeDecodeError
