### ISSUE TITLE
pre-queue script error after py3

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1344]
So I've been running on the py3 branch, updated regularly and finally realized that my pre-queue script hadn't been running. 
I 2to3 -f all -w <file> it and fixed a couple minor things.
All working from the commandline as expected.
But.. When running it from SAB as the pre-queue option. I was getting an error.

```
2019-11-26 15:54:35,298::INFO::[newsunpack:2320] Running pre-queue script ['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1', '', 'tv', 'nzbToMedia.py', 1, '915894787', 'alt.binaries.font alt.binaries.etc alt.binaries.amazing alt.binaries.ath alt.binaries.bloaf alt.binaries.british.drama alt.binaries.chello alt.binaries.tatu alt.binaries.misc', '', '', '', '']
2019-11-26 15:54:35,299::DEBUG::[newsunpack:2325] Failed script /opt/Sick-Beard/autoProcessTV/preq-name.py, Traceback: 
Traceback (most recent call last):
  File "/opt/sabnzbd/sabnzbd/newsunpack.py", line 2323, in pre_queue
    creationflags=creationflags)
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
```
It seemed it didn't like the priority value being a int.
So I tested it and confirmed. Note that the only change is making the priority value a string.

```
Python 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import Popen
>>>  p = Popen(['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1', '', 'tv', 'nzbToMedia.py', 1, '915894787', 'alt.binaries.font alt.binaries.etc alt.binaries.amazing alt.binaries.ath alt.binaries.bloaf alt.binaries.british.drama alt.binaries.chello alt.binaries.tatu alt.binaries.misc', '', '', '', ''])
  File "<stdin>", line 1
    p = Popen(['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1', '', 'tv', 'nzbToMedia.py', 1, '915894787', 'alt.binaries.font alt.binaries.etc alt.binaries.amazing alt.binaries.ath alt.binaries.bloaf alt.binaries.british.drama alt.binaries.chello alt.binaries.tatu alt.binaries.misc', '', '', '', ''])
    ^
IndentationError: unexpected indent
>>> p = Popen(['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1', '', 'tv', 'nzbToMedia.py', 1, '915894787', 'alt.binaries.font alt.binaries.etc alt.binaries.amazing alt.binaries.ath alt.binaries.bloaf alt.binaries.british.drama alt.binaries.chello alt.binaries.tatu alt.binaries.misc', '', '', '', ''])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
>>> p = Popen(['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1', '', 'tv', 'nzbToMedia.py', '1', '915894787', 'alt.binaries.font alt.binaries.etc alt.binaries.amazing alt.binaries.ath alt.binaries.bloaf alt.binaries.british.drama alt.binaries.chello alt.binaries.tatu alt.binaries.misc', '', '', '', ''])
>>> 0


tv

-2

PREQ BLACKLIST rejected Gold.Rush.Maisie.1940.HDTV.x264-REGRET-Obfuscated.1.2.1

```

**Comment by mgaulton** [comment]
And noticing that py3 is behind develop, I switch to try that.

**Comment by sanderjo** [comment]
Ah, nice, I can reproduce with sab-py3 (the PPA version):

```
sander@brixit:~$ cat .sabnzbd/logs/sabnzbd.log  | grep -A100 -i example
2019-11-26 23:45:06,794::INFO::[newsunpack:2331] Running pre-queue script ['/home/sander/scripts-for-SAB/pre-queue-example.py', 'test_download_100MB', '', '', '', 2, '118739881', 'alt.binaries.test', '', '', '', '']
2019-11-26 23:45:06,797::DEBUG::[newsunpack:2336] Failed script /home/sander/scripts-for-SAB/pre-queue-example.py, Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/newsunpack.py", line 2334, in pre_queue
    creationflags=creationflags)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
2019-11-26 23:45:06,810::DEBUG::[misc:151] Cat->Attrib cat=* pp=3 script=None prio=2
```

**Comment by sanderjo** [comment]
there are a lot of occurences of `creationflags` ... danger zone?

```
sander@brixit:~$ cat /usr/share/sabnzbdplus/sabnzbd/newsunpack.py | grep creationflags
        stup, need_shell, command, creationflags = build_command(command)
                  startupinfo=stup, env=env, creationflags=creationflags)
        stup, need_shell, command, creationflags = build_command(command)
                  startupinfo=stup, env=env, creationflags=creationflags)
    stup, need_shell, command, creationflags = build_command(command, flatten_command=True)
              startupinfo=stup, creationflags=creationflags)
    stup, need_shell, command, creationflags = build_command(command)
                         startupinfo=stup, creationflags=creationflags)
    stup, need_shell, command, creationflags = build_command(command)
                         startupinfo=stup, creationflags=creationflags)
    stup, need_shell, command, creationflags = build_command(command)
                             startupinfo=stup, creationflags=creationflags)
    stup, need_shell, command, creationflags = build_command(command)
              startupinfo=stup, creationflags=creationflags)
        creationflags = 0
        creationflags = WIN_SCHED_PRIOS[cfg.win_process_prio()]
    return stup, need_shell, command, creationflags
            stup, need_shell, command, creationflags = build_command(command)
            print("SJ: creationflags", creationflags)
                      creationflags=creationflags)
        stup, need_shell, command, creationflags = build_command(command)
                  startupinfo=stup, creationflags=creationflags)
        stup, need_shell, command, creationflags = build_command(command)
                  startupinfo=stup, creationflags=creationflags)
```

**Comment by mgaulton** [comment]
Seems switching to the develop from the py3 (sorry, didn't realize I hadn't switched it) corrected the issue.
2019-11-27 12:49:56,291::INFO::[newsunpack:2327] Running pre-queue script ['/opt/Sick-Beard/autoProcessTV/preq-name.py', 'Undisputed.II.Last.Man.Standing.2006.720p.BluRay.x264-DAMiANA-RakuvArrow.4.2', '', 'movies', 'nzbToMedia.py', '', '5401727192', 'alt.binaries.multimedia', '', '', '', '']
2019-11-27 12:49:56,369::DEBUG::[interface:447] API-call from 192.168.2.5 [CouchPotato linux - git-75e576ee - v2] {'output': 'json', 'apikey': '8e6cfb1ed84064bf1fc79060d2d2b0b2', 'limit': '15', 'mode': 'history'}
2019-11-27 12:49:57,477::DEBUG::[bpsmeter:241] bps: 351568.6829053296
2019-11-27 12:49:58,792::INFO::[newsunpack:2337] Pre-queue script returns 0 and output=
2


movies

1

Too Big Movies Undisputed.II.Last.Man.Standing.2006.720p.BluRay.x264-DAMiANA-RakuvArrow.4.2

**Comment by sanderjo** [comment]
Are you sure? With the git py3 version, I still get this:
```
2019-11-27 20:01:05,034::INFO::[newsunpack:2320] Running pre-queue script ['/home/sander/pp-scripts-for-sabnzbd/pre-queue-example-python3.py', 'test_download_100MB', '', '', '', 2, '118739881', 'alt.binaries.test', '', '', '', '']
2019-11-27 20:01:05,035::DEBUG::[newsunpack:2325] Failed script /home/sander/pp-scripts-for-sabnzbd/pre-queue-example-python3.py, Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabbie-27nov2019/sabnzbd/newsunpack.py", line 2323, in pre_queue
    creationflags=creationflags)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
2019-11-27 20:01:05,042::DEBUG::[misc:151] Cat->Attrib cat=* pp=3 script=None prio=2
```

And PS, @mgaulton can you please do some formatting of your post? Very hard to read now.

**Comment by sanderjo** [comment]
in `def build_command(`, I changed the last line to 

```
    return stup, need_shell, command, str(creationflags) #SJ
```
and the Traceback is gone.

Pinging @Safihre for his feedback (probably on Friday)

**Comment by mgaulton** [comment]
Sorry about the formatting. I was multitasking.
I just parsed the logs so far today and saw what seemed a successful
result, now using the develop, instead of the py3. I
'''
3.0.0-develop [unknown]
Uptime: 21h
Config File: /opt/.sabnzbd/sabnzbd.ini
Parameters: /opt/sabnzbd/SABnzbd.py -d -f /opt/.sabnzbd/sabnzbd.ini
--repair-all
Python Version: 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC] [UTF-8]
OpenSSL: OpenSSL 1.1.1d 10 Sep 2019
Multicore Par2
'''

**Comment by sanderjo** [comment]
In `def pre_queue(nzo, pp, cat)` I changed it like this:
```
       command = [script_path, nzo.final_name_pw_clean, pp, cat, nzo.script, str(nzo.priority), str(nzo.bytes), ' '.join(nzo.groups)] # SJ10000
```
So nzo.priority is now a string. Result:
* no more traceback
* downloaded filename is now ... "2" instead of "test_download_100MB"

I'm calling it a day for now.


![image](https://user-images.githubusercontent.com/1273502/69758196-20518480-115f-11ea-85cf-836b7a5b6cd6.png)

**Comment by sanderjo** [comment]
and I learned a plain `print` or `print()` in python3 does **not** print an empty line. So the pre-queue example script in python3 must be:

```
#!/usr/bin/env python3
import sys

try:
    (scriptname, nzbname, postprocflags, category, script, prio, downloadsize, grouplist, showname, season, episodenumber, episodename) = sys.argv
    downloadsize = int(downloadsize)
except:
    sys.exit(1)    # exit with 1 causes SABnzbd to ignore the output of this script

prio = -100    # Default
if downloadsize > 50111222:
    prio = 2

print("1")    # Accept
print("")     # make sure to print an empty line; needed on python3
print("")
print("")
print("")
print(prio)
print("")
# 0 means OK
sys.exit(0)

```

**Comment by mgaulton** [comment]
OK, that's good to know. I used print() and I thought it worked. I'll go
back and verify.

**Comment by Safihre** [comment]
@sanderjo The `creationflags` are only filled on Windows, see the `newsunpack.build_command` function. They are needed on Windows.

As far as I know nothing has really changed about this code, if we send `int` before we send `int` now. I tried to reproduce, but with the current `develop` code it's working for me, it's sending `str`.

**Comment by Safihre** [comment]
Ah wait, I see now on Windows we call `list2cmd` which translates everything to string. Will have to check on Linux what happens there.

**Comment by Safihre** [comment]
Fixed, thanks for reporting :) 
In Py2 version this used the `unicoder()` function inside the sub-function `fix()`, so also on other platforms it was fixed.

**Comment by mgaulton** [comment]
Awesome, thanks!
