### ISSUE TITLE
py3: WARNING and ERROR "ENGINE socket.error 'cannot read from timed out object'" 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1354]
I have a SAB-py3 running on VPS, directly connected to Internet.
Now and then, the GUI shows this warning and error combination:

![image](https://user-images.githubusercontent.com/1273502/71310255-4b538f00-2412-11ea-9fc1-aa45bbb20324.png)

![image](https://user-images.githubusercontent.com/1273502/71310269-67573080-2412-11ea-8637-de8c8ba49a82.png)

From the logging:

```
2019-12-21 10:58:21,847::INFO::[_cplogging:216] [21/Dec/2019:10:58:21] HTTP 
Request Headers:
  Remote-Addr: 82.118.242.108
  HOST: 192.168.0.14:80
  CONNECTION: keep-alive
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  USER-AGENT: python-requests/2.20.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 227
```
and
```
2019-11-28 11:27:50,088::INFO::[_cplogging:216] [28/Nov/2019:11:27:50] HTTP 
Request Headers:
  Remote-Addr: 197.51.38.52
  HOST: 192.168.0.14:80
  CONNECTION: keep-alive
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  USER-AGENT: python-requests/2.20.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 227

```
Weird: all kinds of public IPv4 addresses (not mine) as Remote-Addr, and HOST with RFC1918 address (which is in use nor available on this VPS; only public IP addressess).

So:
1. annoying that SAB gives these errors and warnings. Possible to avoid / catch that?
2. what are these requests? Robots? 

This did not happen for my sab-py2, but that was behind a apache proxy (which might catch these requests).
 
```
2019-12-21 10:45:05,394::INFO::[rss:572] Finished scheduled RSS read-outs

2019-12-21 10:58:21,722::ERROR::[_cplogging:216] [21/Dec/2019:10:58:21] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 680, in _do_respond
    self.body.process()
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 982, in process
    super(RequestBody, self).process()
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 559, in process
    proc(self)
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 145, in process_urlencoded
    qs = entity.fp.read()
  File "/home/sander/.local/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 817, in read
    data = self.fp.read(chunksize)
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 379, in read
    data = self.rfile.read(size)
  File "/usr/lib/python3.6/_pyio.py", line 1001, in read
    return self._read_unlocked(size)
  File "/usr/lib/python3.6/_pyio.py", line 1041, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
2019-12-21 10:58:21,847::INFO::[_cplogging:216] [21/Dec/2019:10:58:21] HTTP 
Request Headers:
  Remote-Addr: 82.118.242.108
  HOST: 192.168.0.14:80
  CONNECTION: keep-alive
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  USER-AGENT: python-requests/2.20.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 227
2019-12-21 10:58:21,855::WARNING::[_cplogging:216] [21/Dec/2019:10:58:21] ENGINE socket.error 'cannot read from timed out object'
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/wsgi.py", line 147, in respond
    self.write(chunk)
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/wsgi.py", line 226, in write
    self.req.ensure_headers_sent()
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 1103, in ensure_headers_sent
    self.send_headers()
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 1169, in send_headers
    self.rfile.read(remaining)
  File "/home/sander/.local/lib/python3.6/site-packages/cheroot/server.py", line 379, in read
    data = self.rfile.read(size)
  File "/usr/lib/python3.6/_pyio.py", line 1001, in read
    return self._read_unlocked(size)
  File "/usr/lib/python3.6/_pyio.py", line 1041, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "/usr/lib/python3.6/socket.py", line 583, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object

2019-12-21 11:45:05,399::INFO::[rss:558] Starting scheduled RSS read-out for "nzbs.in testje"

```

**Comment by jcfp** [comment]
As for the second part: the host header in a http request should never contain a private network ip address when the connection is made over the public internet  - so these are probably lame attempts at gaining access to a resource in a (non-existent in your case) private network. The remote addresses belong to data centers in egypt and bulgaria, unlikely to be legit traffic.

**Comment by sanderjo** [comment]
> so these are probably lame attempts at gaining access to a resource in a (non-existent in your case) private network. The remote addresses belong to data centers in egypt and bulgaria, unlikely to be legit traffic.

Yeah, probably.

To get rid of the Errors and Warnings, I've put SABnzbd on another, less well-known port to see if that helps.
