### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by DrakeJones** [sabnzbd/sabnzbd#1371]
I see that this has been an issue for other people > Dictionary changed size during iteration #1306> but the issue was closed as being very rare, but it has happened toa couple of times to me in past few days.  Could be a Python issue. [https://bugs.python.org/issue35615]( https://bugs.python.org/issue35615)

Log:

A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)

[22:08:11] [INFO]::MAIN: Loading config from [C:\Scripts\nzbToMedia\autoProcessMedia.cfg]
[22:08:11] [INFO]::MAIN: Python v3.7 will reach end of life in 1211 days.
[22:08:11] [INFO]::MAIN: Checking database structure... 
[22:08:11] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[22:08:11] [DEBUG]::MAIN: InitialSchema upgrade not required
[22:08:11] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: git version 2.21.0.windows.1
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
[22:08:11] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: refs/heads/master
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
[22:08:11] [INFO]::MAIN: Checking if git needs an update
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Scripts\nzbToMedia
[22:08:12] [DEBUG]::MAIN: git output:
[22:08:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
[22:08:12] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\Scripts\nzbToMedia
[22:08:12] [DEBUG]::MAIN: git output: fatal: no such branch: '''
[22:08:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''
[22:08:12] [DEBUG]::MAIN: git didn't return newest commit hash
[22:08:12] [INFO]::MAIN: No update needed
[22:08:12] [INFO]::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Windows 7)
[22:08:12] [INFO]::MAIN: #########################################################
[22:08:12] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[22:08:12] [INFO]::MAIN: #########################################################
[22:08:12] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\Scripts\\nzbToMedia\\nzbToCouchPotato.py', 'D:\\ADMIN\\comp\\movie\\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)', 'A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb', 'A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)', '', 'movie', 'alt.binaries.nzb', '-1', '']
[22:08:12] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[22:08:12] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[22:08:14] [DEBUG]::MAIN: Adding NZB download info for directory D:\ADMIN\comp\movie\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200) to database
[22:08:14] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[22:08:14] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\ADMIN\comp\movie\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)
[22:08:14] [INFO]::MAIN: Calling CouchPotato:movie to post-process:A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb
[22:08:14] [INFO]::MAIN: Attemping imdbID lookup for A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb
[22:08:14] [INFO]::MAIN: Searching folder and file names for imdbID ...
[22:08:14] [INFO]::MAIN: Found imdbID [tt6644200]
[22:08:14] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/
[22:08:15] [DEBUG]::SERVER: Server responded at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/
[22:08:15] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/media.get with PARAMS: {'id': 'tt6644200'}
Changing to directory: C:\Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/plugins/__pycache__/\nRemoving core/plugins/downloaders/__pycache__/\nRemoving core/plugins/downloaders/nzb/__pycache__/\nRemoving core/plugins/downloaders/torrent/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/__pycache__/\nRemoving libs/common/guessit/rules/common/__pycache__/\nRemoving libs/common/guessit/rules/markers/__pycache__/\nRemoving libs/common/guessit/rules/properties/__pycache__/\nRemoving libs/common/idna/__pycache__/\nRemoving libs/common/mutagen/__pycache__/\nRemoving libs/common/mutagen/asf/__pycache__/\nRemoving libs/common/mutagen/id3/__pycache__/\nRemoving libs/common/mutagen/mp4/__pycache__/\nRemoving libs/common/pkg_resources/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/packaging/__pycache__/\nRemoving libs/common/pkg_resources/extern/__pycache__/\nRemoving libs/common/pysrt/__pycache__/\nRemoving libs/common/qbittorrent/__pycache__/\nRemoving libs/common/rebulk/__pycache__/\nRemoving libs/common/rencode/__pycache__/\nRemoving libs/common/requests/__pycache__/\nRemoving libs/common/stevedore/__pycache__/\nRemoving libs/common/subliminal/__pycache__/\nRemoving libs/common/subliminal/providers/__pycache__/\nRemoving libs/common/transmissionrpc/__pycache__/\nRemoving libs/common/unidecode/__pycache__/\nRemoving libs/common/urllib3/__pycache__/\nRemoving libs/common/urllib3/contrib/__pycache__/\nRemoving libs/common/urllib3/packages/__pycache__/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/__pycache__/\nRemoving libs/common/urllib3/util/__pycache__/\nRemoving libs/common/yaml/__pycache__/\nRemoving libs/custom/synchronousdeluge/__pycache__/\nRemoving libs/custom/utorrent/__pycache__/\nRemoving libs/win/__pycache__/\nRemoving libs/win/jaraco/structures/__pycache__/\nRemoving libs/win/jaraco/windows/__pycache__/\nRemoving libs/win/jaraco/windows/api/__pycache__/\nRemoving libs/win/jaraco/windows/filesystem/__pycache__/\n'
b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/plugins/__pycache__/\nRemoving core/plugins/downloaders/__pycache__/\nRemoving core/plugins/downloaders/nzb/__pycache__/\nRemoving core/plugins/downloaders/torrent/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/__pycache__/\nRemoving libs/common/guessit/rules/common/__pycache__/\nRemoving libs/common/guessit/rules/markers/__pycache__/\nRemoving libs/common/guessit/rules/properties/__pycache__/\nRemoving libs/common/idna/__pycache__/\nRemoving libs/common/mutagen/__pycache__/\nRemoving libs/common/mutagen/asf/__pycache__/\nRemoving libs/common/mutagen/id3/__pycache__/\nRemoving libs/common/mutagen/mp4/__pycache__/\nRemoving libs/common/pkg_resources/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/packaging/__pycache__/\nRemoving libs/common/pkg_resources/extern/__pycache__/\nRemoving libs/common/pysrt/__pycache__/\nRemoving libs/common/qbittorrent/__pycache__/\nRemoving libs/common/rebulk/__pycache__/\nRemoving libs/common/rencode/__pycache__/\nRemoving libs/common/requests/__pycache__/\nRemoving libs/common/stevedore/__pycache__/\nRemoving libs/common/subliminal/__pycache__/\nRemoving libs/common/subliminal/providers/__pycache__/\nRemoving libs/common/transmissionrpc/__pycache__/\nRemoving libs/common/unidecode/__pycache__/\nRemoving libs/common/urllib3/__pycache__/\nRemoving libs/common/urllib3/contrib/__pycache__/\nRemoving libs/common/urllib3/packages/__pycache__/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/__pycache__/\nRemoving libs/common/urllib3/util/__pycache__/\nRemoving libs/common/yaml/__pycache__/\nRemoving libs/custom/synchronousdeluge/__pycache__/\nRemoving libs/custom/utorrent/__pycache__/\nRemoving libs/win/__pycache__/\nRemoving libs/win/jaraco/structures/__pycache__/\nRemoving libs/win/jaraco/windows/__pycache__/\nRemoving libs/win/jaraco/windows/api/__pycache__/\nRemoving libs/win/jaraco/windows/filesystem/__pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  C:\SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "C:\Scripts\nzbToMedia\nzbToCouchPotato.py", line 272, in <module>
result = nzbToMedia.main(sys.argv, section)
File "C:\Scripts\nzbToMedia\nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "C:\Scripts\nzbToMedia\nzbToMedia.py", line 803, in process
result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "C:\Scripts\nzbToMedia\core\auto_process\movies.py", line 80, in process
release = get_release(base_url, imdbid, download_id)
File "C:\Scripts\nzbToMedia\core\auto_process\movies.py", line 514, in get_release
for x2 in results.values():
RuntimeError: dictionary changed size during iteration

**Comment by jcfp** [comment]
> File "C:\Scripts\nzbToMedia\core\auto_process\movies.py", line 514, in get_release
> for x2 in results.values():
> RuntimeError: dictionary changed size during iteration

The traceback is in a third-party [nzbtomedia](https://github.com/clinton-hall/nzbToMedia) script, not in sabnzbd.

**Comment by DrakeJones** [comment]
Thanks.
