### ISSUE TITLE
TypeError: robots_txt() got an unexpected keyword argument

### ISSUE THREAD

**Issue by inferno-adam** [sabnzbd/sabnzbd#1379]
**SABnzbd Version:** 2.3.9 [03c10dc]
**Server OS:** Ubuntu 18.04
**Environment:** Docker container ([linuxserver/sabnzbd](https://hub.docker.com/r/linuxserver/sabnzbd))
**Client OS:** MacOS Catalina 10.15.3
**Browser:** Google Chrome 80.0.3987.149

Google search lead me to this [Reddit post](https://www.reddit.com/r/usenet/comments/cadnzi/sabnzbd_error_i_cant_work_out/) that says it was going to be fixed, but I've got the issue still.

**Log entry:**

```
2020-03-21 21:30:53,034::INFO::[_cplogging:219] [21/Mar/2020:21:30:53] HTTP
Request Headers:
  HOST: 0.0.0.0:8080
  CONNECTION: keep-alive
  Remote-Addr: 172.17.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
  ACCEPT-LANGUAGE: en-US,en;q=0.9
  ACCEPT-ENCODING: gzip, deflate
2020-03-21 21:30:53,034::ERROR::[_cplogging:219] [21/Mar/2020:21:30:53] HTTP
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 127, in internal_wrap
    return wrap_func(*args, **kwargs)
TypeError: robots_txt() got an unexpected keyword argument '1584851453028'
```

[sabnzbd.ini.zip](https://github.com/sabnzbd/sabnzbd/files/4364660/sabnzbd.ini.zip)
[sabnzbd.log.zip](https://github.com/sabnzbd/sabnzbd/files/4364661/sabnzbd.log.zip)

**Comment by inferno-adam** [comment]
This turned out to be an issue with the [Link Redirect Trace](https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh) Chrome extension.
