### ISSUE TITLE
py 2 working, py 3 no downloading/stalls

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1389]
Opensuse Tumbleweed
Sab info 
Version: | 3.0.0-develop [unknown]
(latest checkout of develop currently)
/opt/.sabnzbd/sabnzbd.ini
/opt/sabnzbd/SABnzbd.py -d -f /opt/.sabnzbd/sabnzbd.ini
3.8.2 (default, Mar 05 2020, 18:58:42) [GCC] [UTF-8]
OpenSSL 1.1.1f 31 Mar 2020
 

I've been struggling with something for a while where when running python2.x, SAB runs full out all day, every day.
I switch to the develop branch or py3 branch, run it with python3.x and nothing happens.  Doesn't seem to be downloading anything. I do see RSS checks and some other housekeeping but actual download, nothing.
I've left it as long as 3 days to see if it just got stuck on something.
I've also rebuilt the queue multiple times.
I keep the config separate, so i've even nuked the program folder and recloned it, no change.
Any suggestions would be helpful.

The only meaningful log entry in errors, I believe is related to a empty nzb message I get in the console.
`
AttributeError: 'list' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/sabnzbd/sabnzbd/decoder.py", line 149, in run
    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):
AttributeError: 'list' object has no attribute 'startswith'

`

**Comment by sanderjo** [comment]
That traceback is from this part of the code:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/decoder.py#L145-L151

```
                except (BadYenc, ValueError):
                    # Handles precheck and badly formed articles
                    killed = False
                    found = False
                    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):
                        # STAT was used, so we only get a status code
                        found = True
```

So:
* SAB got an exception earlier on. That is bad. While running SAB-py3, what does `sabnzbd.log` say about `SABYenc module`
* do you have pre-check aka "check before download"  on? See config/switches/#pre_check  in the SAB-gui
* you run `/opt/sabnzbd/SABnzbd.py`. Is that where you unpacked the git version, to into `/opt/sabnzbd/`? I'm checking that your source code is not mixing up sab-py3 and sab-py3.

**Comment by mgaulton** [comment]
restarting to get fresh logs, greping '-i sabyenc' didn't show anything.
I have check before download on, I can try turning it off.
/opt/sabnzbd is where the clone of github is, yes
running git clone straight from github

**Comment by mgaulton** [comment]
So i pulled the preceding from the error.log

`
Exception in thread Thread-6:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/sabnzbd/sabnzbd/decoder.py", line 109, in run
Traceback (most recent call last):
    raise BadYenc
sabnzbd.decoder.BadYenc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/opt/sabnzbd/sabnzbd/decoder.py", line 109, in run
    raise BadYenc
    self.run()
  File "/opt/sabnzbd/sabnzbd/decoder.py", line 149, in run
sabnzbd.decoder.BadYenc
    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):
AttributeError: 'list' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/sabnzbd/sabnzbd/decoder.py", line 149, in run
    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):
AttributeError: 'list' object has no attribute 'startswith'

`

**Comment by mgaulton** [comment]
2020-04-09 11:12:29,305::INFO::[SABnzbd:378] SABYenc module (v4.0.1)... found!

**Comment by sanderjo** [comment]
> I have check before download on, I can try turning it off.

yes, please do so, and report the result.

**Comment by sanderjo** [comment]
Oh, wait: I activated pre-check / Check Before Download, click on Test Download 1000MB, and ... boom:

```
2020-04-09 17:45:12,292::INFO::[downloader:700] Connecting 7@newsreader.eweka.nl finished
2020-04-09 17:45:12,293::INFO::[downloader:700] Connecting 2@newsreader.eweka.nl finished
2020-04-09 17:45:12,312::DEBUG::[downloader:705] Article <OrCqUeLxQaHgCvYuZoPiEbCw-1584818078523@nyuu> is present
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 109, in run
    raise BadYenc
2020-04-09 17:45:12,322::DEBUG::[downloader:705] Article <ScTuVkJrRrMlXlUxInIcNvEk-1584818206205@nyuu> is present
sabnzbd.decoder.BadYenc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 109, in run
    self.run()
2020-04-09 17:45:12,326::DEBUG::[downloader:705] Article <ChJqZaSpDkIjHpQcPrGwBuMp-1584818101579@nyuu> is present
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 149, in run
    raise BadYenc
sabnzbd.decoder.BadYenc
    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):

During handling of the above exception, another exception occurred:

AttributeError: 'list' object has no attribute 'startswith'
Traceback (most recent call last):
2020-04-09 17:45:12,331::DEBUG::[downloader:705] Article <FbRyFtIhHtKzWjZnIoFgWiPr-1584818232884@nyuu> is present
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 149, in run
2020-04-09 17:45:12,335::DEBUG::[downloader:705] Article <QgNlBlCdCzZiKwInRkEjLiMo-1584818285356@nyuu> is present
    if nzo.precheck and raw_data and raw_data.startswith(b'223 '):
AttributeError: 'list' object has no attribute 'startswith'
2020-04-09 17:45:12,339::DEBUG::[downloader:705] Article <SfTtUjWrHbKfTvUuAfXgDhJw-1584818259095@nyuu> is present
```


![image](https://user-images.githubusercontent.com/1273502/78913914-010e2080-7a8a-11ea-9596-821af4cf92dc.png)

**Comment by sanderjo** [comment]
```
raw_data is [b'223 0 <OuIgBdRbTmOrXuAyFcSjDgTh-1584818153948@nyuu>\r\n']
```
So ... I think we need the first element.

BRB.

**Comment by mgaulton** [comment]
@sanderjo Should I also disable pre-check or is that still ok to use?

**Comment by sanderjo** [comment]
> @sanderjo Should I also disable pre-check or is that still ok to use?

Depends:
- if you're able to add `[0]` like I did, pre-check is working again, so no need to disable
- if you don't want to edit, turn pre-check off for now, and you can download again.

BTW: pre-check is not recommended anymore by @Safihre

**Comment by mgaulton** [comment]
Adding the [0] fixed it! Thanks.
Ok, i'll disable it. its always been in my config.
Appreciate the help!

**Comment by sanderjo** [comment]
> Appreciate the help!

And we appreciate your testing of SAB-py3. Keep on testing! Or better: stay to SAB-py3 all the time. just like I and others did somewhere in 2019.

**Comment by Safihre** [comment]
Thanks for debugging and fixing!
