### ISSUE TITLE
ubuntu 20.04 error with ssl

### ISSUE THREAD

**Issue by ITJamie** [sabnzbd/sabnzbd#1410]
ubuntu 20.04 
Python Version: 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0] [UTF-8]
OpenSSL: 1.1.1f 31 Mar 2020
Apt package: sabnzbdplus/focal,now 3.0.0~0git20200408+dfsg-1 all [installed]

Error in webui ( when attempting to download from https usenet server )
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by ITJamie** [comment]
im seeing some reference to a similar error that was fixed in https://github.com/sabnzbd/sabnzbd/commit/5e80c2aab9f922d33c938cd4c6b3cf723f84e2f2

**Comment by Safihre** [comment]
Unfortunately it's a bug in Python with OpenSSL 1.1.1 that for soms reason they just aren't fixing: https://bugs.python.org/issue31122

**Comment by Safihre** [comment]
Yeah it's fixed in a newer version of Cherrypy, maybe that isn't include in that version of the apt package.

**Comment by thezoggy** [comment]
@ITJamie what verysion of cherrypy do you have installed?

**Comment by Safihre** [comment]
Closing due to inactivity.
