### ISSUE TITLE
3.0.0Alpha1 - "Object of type function is not JSON serializable" before hibernation

### ISSUE THREAD

**Issue by anthonws** [sabnzbd/sabnzbd#1417]
Windows 10 1909.
3.0.0Alpha1 (MSI 64-bit)
Happens every night, before hibernation.

Traceback (most recent call last):
  File "lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
  File "lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
  File "lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
  File "lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 461, in api
  File "sabnzbd\api.py", line 99, in api_handler
  File "sabnzbd\api.py", line 150, in _api_qstatus
  File "sabnzbd\api.py", line 981, in report
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type function is not JSON serializable

**Comment by sanderjo** [comment]
I know nothing about this, and Googleing `TypeError: Object of type function is not JSON serializable` does not reveal anything useful, so let's try to approach this from the other side, and reproduce the error message with a few lines of pure python3 code:

```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json

  >>> json.dumps('{ "name":"John", "age":30, "city":"New York"}')
'"{ \\"name\\":\\"John\\", \\"age\\":30, \\"city\\":\\"New York\\"}"'
>>> 
 
>>> def myfunc():
...     print("hello")
...
>>> json.dumps(myfunc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable
>>>
```

Bingo. So ... back to SAB: is SAB trying to do a JSON operation on a functional call ... ?

**Comment by thezoggy** [comment]
can you share what you have in your config > scheduling ?
and/or do you use the sab api to fire off a request at that time?

**Comment by Safihre** [comment]
The `qstatus` call is not used by sabnzbd, it's used by an external application. I think only CouchPotato uses it still. I wanted to remove this obsolete function, but that broke CouchPotato.

**Comment by thezoggy** [comment]
Do you use sabconnect ?

**Comment by anthonws** [comment]
@thezoggy I don't have any configuration under scheduling. And I'm not using CouchPotato.
Radarr, Lidarr and Sonarr.
This error started immediately after updating to 3.0.0Alpha1.

Thanks for your help! Let me know what else I can assist you with.

**Comment by thezoggy** [comment]
can you post logs then?

**Comment by anthonws** [comment]
@thezoggy if there's no activity whatsoever in SAB, this is the only log I get:

`2020-05-01 22:05:19,545::INFO::[nzbqueue:204] Saving queue
2020-05-01 22:05:19,561::INFO::[postproc:123] Saving postproc queue
2020-05-01 22:05:19,561::INFO::[notifier:377] Failed to send Windows notification
2020-05-02 02:00:03,256::ERROR::[_cplogging:213] [02/May/2020:02:00:03] HTTP 
Traceback (most recent call last):
  File "lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
  File "lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
  File "lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
  File "lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 461, in api
  File "sabnzbd\api.py", line 99, in api_handler
  File "sabnzbd\api.py", line 150, in _api_qstatus
  File "sabnzbd\api.py", line 981, in report
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type function is not JSON serializable
2020-05-02 02:00:03,256::INFO::[_cplogging:213] [02/May/2020:02:00:03] HTTP 
Request Headers:
  Remote-Addr: 192.168.25.8
  USER-AGENT: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.18362.752
  HOST: 192.168.25.8:8080
  CONNECTION: Keep-Alive
`

**Comment by anthonws** [comment]
@thezoggy the PowerShell bit gave me a clue!
It's my hibernation script, that checks is SAB is downloading something or not.
![image](https://user-images.githubusercontent.com/181357/80858855-21c63200-8c54-11ea-8b58-aac04c8caf88.png)

**Comment by sanderjo** [comment]
Ah, nice: I can reproduce: With

`curl http://localhost:8080/sabnzbd/api -F apikey=6b952e934deb260e09f89af6ac125597 -F mode=qstatus -F output=json
`
results in server side

```
2020-05-02 10:14:45,800::DEBUG::[interface:447] API-call from ::ffff:127.0.0.1 [curl/7.68.0] {'apikey': '6b952e934deb260e09f89af6ac125597', 'mode': 'qstatus', 'output': 'json'}
2020-05-02 10:14:45,801::ERROR::[_cplogging:213] [02/May/2020:10:14:45] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/interface.py", line 461, in api
    return api_handler(kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 99, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 150, in _api_qstatus
    return report(output, data=info)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 981, in report
    response = json.dumps(info).encode('utf-8')
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
2020-05-02 10:14:45,802::INFO::[_cplogging:213] [02/May/2020:10:14:45] HTTP 
Request Headers:
  Remote-Addr: ::ffff:127.0.0.1
  HOST: localhost:8080
  USER-AGENT: curl/7.68.0
  ACCEPT: */*
  Content-Type: multipart/form-data; boundary=------------------------2e66f1031701a256
  Content-Length: 372
```


and client side


```
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/interface.py", line 461, in api
    return api_handler(kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 99, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 150, in _api_qstatus
    return report(output, data=info)
  File "/home/sander/git/sab-1mei2020/sabnzbd/api.py", line 981, in report
    response = json.dumps(info).encode('utf-8')
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.5.0</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by sanderjo** [comment]
@anthonws can you switch to queue instead of qstatus ? After all: "qstatus	Simple Queue output To be **deprecated**"

**Comment by thezoggy** [comment]
@anthonws change your logs to debug level and restart sab and there should be a lot more

**Comment by anthonws** [comment]
@sanderjo For sure! I was not aware of qstatus deprecation. Thanks!
@thezoggy I'll enable debug logging for the tests.

**Comment by anthonws** [comment]
Sorted! Thank you so much for your help and apologies for the false positive!

**Comment by sanderjo** [comment]
@anthonws maybe you can put the words "API qstatus" into the subject? (And not "hibernation").

**Comment by sanderjo** [comment]
@Safihre FWIW I did some debugging:

an API call with queue (all working) gives:

```
2020-05-02 10:46:54,779::DEBUG::[interface:447] API-call from ::ffff:127.0.0.1 [curl/7.68.0] {'apikey': '6b952e934deb260e09f89af6ac125597', 'mode': 'queue', 'output': 'json'}
SJ310:
output json
error None
keyword queue
data {'version': '3.0.0-develop', 'paused': False, 'pause_int': '0', 'paused_all': False, 'diskspace1': '11.47', 'diskspace2': '15.81', 'diskspace1_norm': '11.5 G', 'diskspace2_norm': '15.8 G', 'diskspacetotal1': '116.38', 'diskspacetotal2': '119.05', 'loadavg': '0.12 | 0.30 | 0.58 | V=1898M R=82M', 'speedlimit': '100', 'speedlimit_abs': '', 'have_warnings': '1', 'finishaction': None, 'quota': '0 ', 'have_quota': False, 'left_quota': '0 ', 'cache_art': '0', 'cache_size': '0 B', 'cache_max': '1001704652', 'kbpersec': '0.00', 'speed': '0 ', 'mbleft': '0.00', 'mb': '0.00', 'sizeleft': '0 B', 'size': '0 B', 'noofslots_total': 0, 'status': 'Idle', 'timeleft': '0:00:00', 'eta': 'unknown', 'refresh_rate': '1', 'scripts': [], 'categories': ['*', 'movies', 'tv', 'audio', 'software'], 'rating_enable': False, 'noofslots': 0, 'start': 0, 'limit': 0, 'finish': 0, 'slots': []}
compat False
```

but an API call with qstatus gives

```
2020-05-02 10:44:19,642::DEBUG::[interface:447] API-call from ::ffff:127.0.0.1 [curl/7.68.0] {'apikey': '6b952e934deb260e09f89af6ac125597', 'mode': 'qstatus', 'output': 'json'}
SJ310:
output json
error None
keyword value
data {'T': <function Ttemplate at 0x7f438589bb80>, 'Tspec': <function Tspec at 0x7f438589baf0>, 'uptime': '0m', 'color_scheme': 'Default', 'helpuri': 'https://sabnzbd.org/wiki/', 'restart_req': False, 'pid': 150360, 'active_lang': 'en', 'my_lcldata': '/home/sander/.sabnzbd', 'my_home': '/home/sander', 'webdir': '/home/sander/git/sab-2mei2020/interfaces/Glitter/templates', 'url_base': '/sabnzbd', 'nt': False, 'darwin': False, 'power_options': True, 'pp_pause_event': False, 'session': '6b952e934deb260e09f89af6ac125597', 'new_release': None, 'new_rel_url': None, 'version': '3.0.0-develop', 'paused': False, 'pause_int': '0', 'paused_all': False, 'diskspace1': '11.47', 'diskspace2': '15.81', 'diskspace1_norm': '11.5 G', 'diskspace2_norm': '15.8 G', 'diskspacetotal1': '116.38', 'diskspacetotal2': '119.05', 'loadavg': '0.48 | 0.47 | 0.67 | V=1898M R=81M', 'speedlimit': '100', 'speedlimit_abs': '', 'have_warnings': '0', 'finishaction': None, 'quota': '0 ', 'have_quota': False, 'left_quota': '0 ', 'cache_art': '0', 'cache_size': '0 B', 'cache_max': '1001704652', 'kbpersec': '0.00', 'speed': '0 ', 'mbleft': '0.00', 'mb': '0.00', 'sizeleft': '0 B', 'size': '0 B', 'noofslots_total': 0, 'status': 'Idle', 'timeleft': '0:00:00', 'eta': 'unknown', 'refresh_rate': '1', 'scripts': [], 'categories': ['Default', 'movies', 'tv', 'audio', 'software'], 'rating_enable': False, 'noofslots': 0, 'start': 0, 'limit': 0, 'finish': 0, 'slots': []}
compat False
```
That `data {'T': <function Ttemplate at 0x7f438589bb80>, 'Tspec': <function Tspec at 0x7f438589baf0>, 'uptime': '0m', ...` looks suspicious to me, and probably cause of the traceback?

**Comment by Safihre** [comment]
Pushed a fix :)

**Comment by anthonws** [comment]
> 
> 
> @anthonws maybe you can put the words "API qstatus" into the subject? (And not "hibernation").

Changed!

**Comment by sanderjo** [comment]
> Pushed a fix :)

Cool. I can confirm it works.

**Comment by sanderjo** [comment]
What a great cooperation, guys! :100:

**Comment by sanderjo** [comment]
> The `qstatus` call is not used by sabnzbd, it's used by an external application. I think only CouchPotato uses it still. I wanted to remove this obsolete function, but that broke CouchPotato.

I did a brute-force check on CouchPotatoServer, and it seems it does NOT use qstatus:

```
~/git/CouchPotatoServer$ grep -irn mode couchpotato/core/downloaders/sabnzbd.py
46:            'mode': 'addurl',
59:            req_params['mode'] = 'addfile'
64:            if nzb_filename and req_params.get('mode') is 'addfile':
95:                'mode': 'version',
103:                'mode': 'queue',
126:                'mode': 'queue',
135:                'mode': 'history',
185:                'mode': 'queue',
191:                'mode': 'history',
207:                'mode': 'history',
232:            return d.get(request_params['mode']) or d
```
and
`grep -i qstatus couchpotato/core/downloaders/sabnzbd.py` does not yield anything.

So safe to remove qstatus? Or give a warning in SABnzbd if it's used ... ? Version 3.0 can be a moment to do that for a deprecated function, right?
