### ISSUE TITLE
"Error renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10""

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1427]
I often have these error messages with the test-download (with SAB-py3, don't know it's relevant):

`Error renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"`

Afterwards, the download stuff is in both directories:

```
$ ll /media/sander/6665-6464/complete/*test_download_100MB.10/
/media/sander/6665-6464/complete/test_download_100MB.10/:
total 102784
drwxr-xr-x   3 sander sander    131072 mei  5 15:01 ./
drwxr-xr-x 102 sander sander    131072 mei  5 15:03 ../
-rwxr-xr-x   1 sander sander 104857600 mrt 21 19:58 my_test_100MB.bin*
drwxr-xr-x   2 sander sander    131072 mei  5 15:01 _UNPACK_test_download_100MB.10/

/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/:
total 102656
drwxr-xr-x   2 sander sander    131072 mei  5 15:03 ./
drwxr-xr-x 102 sander sander    131072 mei  5 15:03 ../
-rwxr-xr-x   1 sander sander 104857600 mrt 21 19:58 my_test_100MB.bin*
```

Traceback:
```
2020-05-05 15:03:08,815::INFO::[postproc:419] Unpacked files ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 15:03:08,816::INFO::[postproc:424] Finished unpack_magic on test_download_100MB
2020-05-05 15:03:08,817::DEBUG::[filesystem:450] Applying permissions 0o775 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 15:03:08,817::DEBUG::[filesystem:450] Applying permissions 0o664 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 15:03:08,819::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
2020-05-05 15:03:08,820::ERROR::[postproc:480] Error renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
2020-05-05 15:03:08,820::INFO::[postproc:485] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabbie-5mei-tweeeeee/sabnzbd/postproc.py", line 478, in process_job
    newfiles = rename_and_collapse_folder(tmp_workdir_complete, workdir_complete, newfiles)
  File "/home/sander/git/sabbie-5mei-tweeeeee/sabnzbd/postproc.py", line 1129, in rename_and_collapse_folder
    renamer(oldpath, newpath)
  File "/home/sander/git/sabbie-5mei-tweeeeee/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/home/sander/git/sabbie-5mei-tweeeeee/sabnzbd/filesystem.py", line 721, in renamer
    shutil.move(old, new)
  File "/usr/lib/python3.8/shutil.py", line 786, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/media/sander/6665-6464/complete/test_download_100MB.10/_UNPACK_test_download_100MB.10' already exists
2020-05-05 15:03:08,834::INFO::[nzbstuff:1537] [sabnzbd.postproc.process_job] Purging data for job test_download_100MB (delete_all_data=True)
2020-05-05 15:03:08,834::DEBUG::[filesystem:759] Removing dir recursively /home/sander/Downloads/incomplete/test_download_100MB.1
```

```
$ ll /media/sander/6665-6464/complete/ | grep test_download_100MB
drwxr-xr-x   3 sander sander 131072 mei  9  2020 test_download_100MB.1/
drwxr-xr-x   3 sander sander 131072 mei  5 15:01 test_download_100MB.10/
drwxr-xr-x   3 sander sander 131072 mei 22  2020 test_download_100MB.2/
drwxr-xr-x   3 sander sander 131072 mei 28  2020 test_download_100MB.3/
drwxr-xr-x   3 sander sander 131072 jun  1  2020 test_download_100MB.4/
drwxr-xr-x   3 sander sander 131072 jun  5  2020 test_download_100MB.5/
drwxr-xr-x   3 sander sander 131072 jun  5  2020 test_download_100MB.6/
drwxr-xr-x   3 sander sander 131072 mei  5 14:34 test_download_100MB.7/
drwxr-xr-x   3 sander sander 131072 mei  5 14:44 test_download_100MB.8/
drwxr-xr-x   3 sander sander 131072 mei  5 14:48 test_download_100MB.9/
drwxr-xr-x   2 sander sander 131072 mei  9  2020 _UNPACK_test_download_100MB/
drwxr-xr-x   2 sander sander 131072 jun  1  2020 _UNPACK_test_download_100MB.1/
drwxr-xr-x   2 sander sander 131072 mei  5 15:03 _UNPACK_test_download_100MB.10/
drwxr-xr-x   2 sander sander 131072 jun  1  2020 _UNPACK_test_download_100MB.2/
drwxr-xr-x   2 sander sander 131072 jun  1  2020 _UNPACK_test_download_100MB.3/
drwxr-xr-x   2 sander sander 131072 jun  1  2020 _UNPACK_test_download_100MB.4/
drwxr-xr-x   2 sander sander 131072 jun  5  2020 _UNPACK_test_download_100MB.5/
drwxr-xr-x   2 sander sander 131072 jun  5  2020 _UNPACK_test_download_100MB.6/
drwxr-xr-x   2 sander sander 131072 mei  5 14:35 _UNPACK_test_download_100MB.7/
drwxr-xr-x   2 sander sander 131072 mei  5 14:44 _UNPACK_test_download_100MB.8/
drwxr-xr-x   2 sander sander 131072 mei  5 14:50 _UNPACK_test_download_100MB.9/
```

**Comment by Safihre** [comment]
Can you see where the folder `test_download_100MB.10` was created?

**Comment by sanderjo** [comment]
See below.
Is that first line OK? `Renaming "/media/sander/6665-6464/complete/test_download_100MB" to "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10"`
```
$ cat .sabnzbd/logs/sabnzbd.log* | grep "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10"

2020-05-05 14:53:56,769::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/test_download_100MB" to "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10"
2020-05-05 14:53:56,771::DEBUG::[directunpacker:377] Running unrar for DirectUnpack ['/usr/bin/unrar', 'x', '-vp', '-idp', '-o+', '-p-', '/home/sander/Downloads/incomplete/test_download_100MB.1/sometestfile-100MB.part1.rar', '/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/']
Extracting  /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 14:54:01,518::DEBUG::[newsunpack:539] rar_unpack(): Newfiles: ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 14:54:01,616::INFO::[postproc:419] Unpacked files ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 14:54:01,620::DEBUG::[filesystem:450] Applying permissions 0o775 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 14:54:01,621::DEBUG::[filesystem:450] Applying permissions 0o664 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 14:54:01,623::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
2020-05-05 14:54:01,625::DEBUG::[filesystem:733] [sabnzbd.postproc.rename_and_collapse_folder] Removing dir /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 15:01:34,084::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/test_download_100MB" to "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10"
2020-05-05 15:01:34,089::DEBUG::[directunpacker:377] Running unrar for DirectUnpack ['/usr/bin/unrar', 'x', '-vp', '-idp', '-o+', '-p-', '/home/sander/Downloads/incomplete/test_download_100MB.1/sometestfile-100MB.part1.rar', '/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/']
Extracting  /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 15:01:40,474::DEBUG::[newsunpack:539] rar_unpack(): Newfiles: ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 15:01:40,552::INFO::[postproc:419] Unpacked files ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 15:01:40,556::DEBUG::[filesystem:450] Applying permissions 0o775 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 15:01:40,557::DEBUG::[filesystem:450] Applying permissions 0o664 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 15:01:40,558::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
2020-05-05 15:01:40,561::DEBUG::[filesystem:733] [sabnzbd.postproc.rename_and_collapse_folder] Removing dir /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 15:03:03,971::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/test_download_100MB" to "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10"
2020-05-05 15:03:03,972::DEBUG::[directunpacker:377] Running unrar for DirectUnpack ['/usr/bin/unrar', 'x', '-vp', '-idp', '-o+', '-p-', '/home/sander/Downloads/incomplete/test_download_100MB.1/sometestfile-100MB.part1.rar', '/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/']
Extracting  /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 15:03:08,781::DEBUG::[newsunpack:539] rar_unpack(): Newfiles: ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 15:03:08,815::INFO::[postproc:419] Unpacked files ['/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin']
2020-05-05 15:03:08,817::DEBUG::[filesystem:450] Applying permissions 0o775 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10
2020-05-05 15:03:08,817::DEBUG::[filesystem:450] Applying permissions 0o664 (octal) to /media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10/my_test_100MB.bin
2020-05-05 15:03:08,819::DEBUG::[filesystem:692] Renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
2020-05-05 15:03:08,820::ERROR::[postproc:480] Error renaming "/media/sander/6665-6464/complete/_UNPACK_test_download_100MB.10" to "/media/sander/6665-6464/complete/test_download_100MB.10"
```

**Comment by sanderjo** [comment]
I will close this, until I get these errors again.
