### ISSUE TITLE
FYI: Traceback "Exception ignored in: <function IOBase.__del__ at 0x7f4afb62f730>" 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1429]
Not an issue in SAB, but a FYI:

The message below sometimes appears in my SABnzbd (which is exposed to Internet on port 8080). I'm quite sure it's caused by port scanners that do a half open, or somehting like that.

I guess it's a problem in cheroot (part of cherrypy), and not SABnzbd.
If so, I'll close this tomorrow.

```
Exception ignored in: <function IOBase.__del__ at 0x7f4afb62f730>
Traceback (most recent call last):
  File "/usr/lib/python3.8/_pyio.py", line 419, in __del__
    self.close()
  File "/usr/lib/python3.8/_pyio.py", line 1318, in close
    self.flush()
  File "/usr/lib/python3.8/_pyio.py", line 1279, in flush
    self._flush_unlocked()
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
```

**Comment by Safihre** [comment]
Yeah, I've seen them too. On Windows when running with HTTPS there's a whole bunch of errors displayed originating from cherrypy, bad closing of sockets etc.. I used to report these bugs to cherrypy but kind of gave up.

**Comment by sanderjo** [comment]
Do you a link to such a issue, so that we can put in here, and close this ticket under "upstream"

**Comment by sanderjo** [comment]
@Safihre I don't see your bug report on https://github.com/cherrypy/cherrypy/issues?q=safihre

Closing anyway: upstream

**Comment by sanderjo** [comment]
FYI / updating:

Easy to reproduce: start SAB with ` python3.8 -X dev -X tracemalloc=5 SABnzbd.py` with  HTTPS on, and do **plain HTTP connect** from a web browser.

```
$ curl -v http://127.0.0.1:8080/
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

SABnzbd side:

```
Exception ignored in: <function IOBase.__del__ at 0x7f920e856d70>
Traceback (most recent call last):
  File "/usr/lib/python3.8/_pyio.py", line 419, in __del__
    self.close()
  File "/usr/lib/python3.8/_pyio.py", line 1318, in close
    self.flush()
  File "/usr/lib/python3.8/_pyio.py", line 1279, in flush
    self._flush_unlocked()
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
```

So something in cheroot https://github.com/cherrypy/cheroot
