### ISSUE TITLE
cherrypy Tracebacks by testssl.sh, but not with plain cherrypy server

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1437]
@Safihre not your favourite subject, but here we go: cherrypy:

Users sometimes get Traceback in their screen from cherrypy, for example:

![image](https://user-images.githubusercontent.com/1273502/81482577-54fe5780-9238-11ea-822a-46c52fc71b93.png)

See https://forums.sabnzbd.org/viewtopic.php?p=120794#p120794 for more.

It's easy to trigger with `./testssl.sh 127.0.0.1:8080`. 

So I thought: Yet Another Cherrypy Problem, so ignore.

BUT: with my own cherrypy instance, a `./testssl.sh 127.0.0.1:4444` does not give a traceback nor error in cherrypy:

```
$ python3 my_cherrypy.py 
[09/May/2020:20:59:23] ENGINE Listening for SIGTERM.
[09/May/2020:20:59:23] ENGINE Listening for SIGHUP.
[09/May/2020:20:59:23] ENGINE Listening for SIGUSR1.
[09/May/2020:20:59:23] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[09/May/2020:20:59:23] ENGINE Started monitor thread 'Autoreloader'.
[09/May/2020:20:59:23] ENGINE Serving on https://0.0.0.0:4444
[09/May/2020:20:59:23] ENGINE Bus STARTED

127.0.0.1 - - [09/May/2020:20:59:36] "GET / HTTP/1.1" 200 35 "" "TLS tester from https://testssl.sh/dev/"
127.0.0.1 - - [09/May/2020:21:00:00] "GET / HTTP/1.1" 200 35 "" "TLS tester from https://testssl.sh/dev/"
127.0.0.1 - - [09/May/2020:21:00:37] "GET / HTTP/1.1" 200 35 "https://google.com/" "TLS tester from https://testssl.sh/dev/"

```

So, why does SABnzbd's cherrypy give tracebacks, but no a simple cherrypy server script?
Or, more important: if a simple cherrypy server script can be good,  can we get SAB's cherrypy good?
Or ... do not route the cherrypy Tracebacks to the GUI ... 

```
import cherrypy
 
class RootServer:
    @cherrypy.expose
    def index(self, **keywords):
        return "Yeah, the cherrypy webserver works!"
 
if __name__ == '__main__':
    server_config={
        'server.socket_host': '0.0.0.0',
        'server.socket_port':4444,
 
        'server.ssl_module':'pyopenssl',
        'server.ssl_certificate':'/home/sander/.sabnzbd/admin/server.cert',
        'server.ssl_private_key':'/home/sander/.sabnzbd/admin/server.key',
        # this is optional
        #'server.ssl_certificate_chain':'/home/ubuntu/gd_bundle.crt'
   }
 
cherrypy.config.update(server_config)
cherrypy.quickstart(RootServer())
 ````

**Comment by Safihre** [comment]
`'server.ssl_module':'pyopenssl',`
That's why. Try using `builtin`, that's what SABnzbd does.

**Comment by sanderjo** [comment]
Ah, yes, with `builtin` cherrypy starts spewings errors. Does that mean it's a cherrypy problem after all>

And in SAB we must use `builtin`?

```
$ python3 my_cherrypy.py 
[09/May/2020:21:31:45] ENGINE Listening for SIGTERM.
[09/May/2020:21:31:45] ENGINE Listening for SIGHUP.
[09/May/2020:21:31:45] ENGINE Listening for SIGUSR1.
[09/May/2020:21:31:45] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[09/May/2020:21:31:45] ENGINE Started monitor thread 'Autoreloader'.
[09/May/2020:21:31:45] ENGINE Serving on https://0.0.0.0:4444
[09/May/2020:21:31:45] ENGINE Bus STARTED
127.0.0.1 - - [09/May/2020:21:32:05] "GET / HTTP/1.1" 200 35 "" "TLS tester from https://testssl.sh/dev/"
[09/May/2020:21:32:11] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/server.py", line 1776, in serve
    self.tick()
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/server.py", line 1999, in tick
    conn = self.connections.get_conn(self.socket)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/connections.py", line 180, in get_conn
    return self._from_server_socket(server_socket)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/connections.py", line 199, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", line 243, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1108)

[09/May/2020:21:32:11] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/server.py", line 1776, in serve
    self.tick()
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/server.py", line 1999, in tick
    conn = self.connections.get_conn(self.socket)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/connections.py", line 180, in get_conn
    return self._from_server_socket(server_socket)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/connections.py", line 199, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", line 243, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)
```

**Comment by Safihre** [comment]
Yeah, it's annoying to package `pyopenssl` for the releases.
Also, often these errors could be highly diagnostic to know why you can't connect to your server. So cherrypy throwing them isn't necessarily bad. Something is going wrong, so it reports it.

**Comment by sanderjo** [comment]
OK, clear.
