### ISSUE TITLE
v3 Queue gets stuck in delayed (permanently)

### ISSUE THREAD

**Issue by biship** [sabnzbd/sabnzbd#1449]
Running latest build from source:
https://github.com/sabnzbd/sabnzbd/commit/d2c3a51aac23fec14c0102921ab7fc1915e023a6

I've tried both with fail_fast enabled and not enabled.

These articles are definitely missing from the nntp servers.

1st item in queue is Orange "16% 312MB Missing articles"
2nd item is Green 14%.

It was stuck like this for 8+ hours.
No space issues on drives.

Debug log:
https://drive.google.com/file/d/14XS2xnlrQWhLri6f0JFRbQoBjqLJEY2V/view?usp=sharing

EDIT:
Disabled: Only Get Articles for Top of Queue
Disabled: Check before download
Enabled: Abort jobs that cannot be completed

**Comment by biship** [comment]
I use a .bat file to run SABnzbd.py and noticed this in the log. Seems related.
`Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\site-packages\cheroot\ssl\builtin.py", line 68, in <lambda>
    target=lambda: context.wrap_socket(
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\nick\AppData\Local\Programs\sabnzbddev\sabnzbd\decoder.py", line 211, in run
    sabnzbd.nzbqueue.NzbQueue.do.register_article(article, found)
  File "C:\Users\nick\AppData\Local\Programs\sabnzbddev\sabnzbd\nzbqueue.py", line 690, in register_article
    articles_left, file_done, post_done = nzo.remove_article(article, found)
ValueError: not enough values to unpack (expected 3, got 2)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\nick\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\nick\AppData\Local\Programs\sabnzbddev\sabnzbd\decoder.py", line 211, in run
    sabnzbd.nzbqueue.NzbQueue.do.register_article(article, found)
  File "C:\Users\nick\AppData\Local\Programs\sabnzbddev\sabnzbd\nzbqueue.py", line 690, in register_article
    articles_left, file_done, post_done = nzo.remove_article(article, found)
ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by jcfp** [comment]
@Safihre looks like this is related to abc9cc6cc46b2f8459c412506db0fa6f5389e2ac?

**Comment by Safihre** [comment]
That specific one is fixed in https://github.com/sabnzbd/sabnzbd/pull/1448/commits/8b461ebea87f91a4c47881b5aee50fa50918c683

**Comment by Safihre** [comment]
Pushed that fix now to `develop`, it was only on `feature/smarter-cache` which I thought I would merge sooner. But still working on it.

**Comment by biship** [comment]
I have upgraded to https://github.com/sabnzbd/sabnzbd/commit/3a74fcdc401d95ec2588356238b29affe6697d87 on develop
I've since deleted the stuck downloads, but will let you know if future ones get stuck.

**Comment by Safihre** [comment]
You can re-open if it happens again!

**Comment by amritk** [comment]
Hey I've noticed this as well, here's my setup

Ubuntu server 20.04
Ryzen 3600
16GB ram
Sabnzbd version: 3.0.0-develop
Python Version: 3.8.2

I have attached the logs:
https://pastebin.com/jGshyuwX
