### ISSUE TITLE
tracebacks in current git version

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1458]
I get tracebacks in the current git version (even with the plain Test Download 100MB).

I'll back go in history to see which git version is safe.

If only SAB could print the version / commit I'm using ... ;-)

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 255, in run
    ArticleCache.do.save_article(article, data)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 112, in save_article
    self.__article_table[article] = data
TypeError: unhashable type: 'Article'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 255, in run
    ArticleCache.do.save_article(article, data)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 112, in save_article
    self.__article_table[article] = data
TypeError: unhashable type: 'Article'
2020-05-22 23:04:31,921::INFO::[downloader:684] Connecting 1@europe.newsgroupdirect.com finished
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 255, in run
    ArticleCache.do.save_article(article, data)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 112, in save_article
    self.__article_table[article] = data
TypeError: unhashable type: 'Article'
```

**Comment by sanderjo** [comment]
Going from 15 commits in the past to current state, it goes wrong at

`* (HEAD detached at 4f79dd70)
`

![image](https://user-images.githubusercontent.com/1273502/82710873-3e1e2300-9c84-11ea-957e-948a80772068.png)

```
2020-05-22 23:28:50,902::INFO::[__init__:913] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/__init__.py", line 903, in save_data
    pickle.dump(data, data_file, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/sander/git/sabnzbd/sabnzbd/nzbstuff.py", line 380, in __getstate__
    dict_[item] = getattr(self, item)
AttributeError: article_count
```

**Comment by sanderjo** [comment]
and back on the most recent commit `(HEAD detached at e7ca5344)`, it really goes wrong





```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 255, in run
    ArticleCache.do.save_article(article, data)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 112, in save_article
    self.__article_table[article] = data
TypeError: unhashable type: 'Article'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/decoder.py", line 255, in run
    ArticleCache.do.save_article(article, data)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 112, in save_article
    self.__article_table[article] = data
TypeError: unhashable type: 'Article'
```

![image](https://user-images.githubusercontent.com/1273502/82711061-aec53f80-9c84-11ea-86ef-a071de0574e3.png)

**Comment by Safihre** [comment]
It is not `4f79dd70`, that one only crashes on your system because the structure of the files changed and it is trying to convert. 
The problem was e7ca534.
