### ISSUE TITLE
3.0.0 b1 - AttributeError: 'dict' object has no attribute 'set'

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1465]
Noticed that nzb360 v13.7 causing traceback now in v3.0.0b1 when getting queue (was not doing it on 3.0.0 alpha2:
```
2020-05-27 00:33:04,163::DEBUG::[apikey=<APIKEY>] API-call from 192.168.0.96 [okhttp/4.0.1] {'mode': 'history', 'start': '0', 'output': 'json', 'limit': '20', 'apikey':<APIKEY>'}
2020-05-27 00:33:04,173::DEBUG::[apikey=<APIKEY>] API-call from 192.168.0.96 [okhttp/4.0.1] {'mode': 'queue', 'start': '0', 'output': 'json', 'apikey':<APIKEY>'}
2020-05-27 00:33:05,773::DEBUG::[apikey=<APIKEY>] API-call from 192.168.0.96 [??] {'mode': 'queue', 'output': ['json', 'json'], 'apikey':<APIKEY>', 'start': '0'}
2020-05-27 00:33:05,773::ERROR::[_cplogging:213] [27/May/2020:00:33:05] HTTP 
Traceback (most recent call last):
  File "lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
  File "lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
  File "lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
  File "lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 403, in api
  File "sabnzbd\api.py", line 105, in api_handler
AttributeError: 'dict' object has no attribute 'set'
```
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/api.py#L105

**Comment by thezoggy** [comment]
`'output': ['json', 'json']` does stand out as a bug on nzb360's end.. but wonder if it is always done this and just now exposed after recent api change

**Comment by Safihre** [comment]
Oops, that was a basic mistake of me.. Should have tested beter.
Indeed nzb360 is sending bad input, but the point of that code is to correct it.
Fixed it.
