### ISSUE TITLE
ChromeOS Linux subsystem (Debian 9 stretch): "Unable to guess signature from an empty list" [notifier, NotifyOSD]

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1483]
On my ChromeOS Linux subsystem (Debian9 stretch), I get the error below each time I start SABnzbd.py:
```
2020-05-31 23:13:47,442::INFO::[notifier:180] Send to NotifyOSD: SABnzbd / SABnzbd 3.0.0-develop started
2020-05-31 23:13:47,451::ERROR::[connection:646] Unable to set arguments ('icon-summary-body', 0, '/home/pietdevries/git/sabnzbd/interfaces/Config/templates/staticcfg/images/logo-arrow.svg', 'SABnzbd', 'SABnzbd 3.0.0-develop started', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
2020-05-31 23:13:47,454::INFO::[notifier:186] NotifyOSD not working
```
So that happens here https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/notifier.py#L180-L188

Can we avoid that ERROR? Is it a another module hard-writing via logging.error()?

> Unable to set arguments ('icon-summary-body', 0, '/home/pietdevries/git/sabnzbd/interfaces/Config/templates/staticcfg/images/logo-arrow.svg', 'SABnzbd', 'SABnzbd 3.0.0-develop started', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list

https://www.google.com/search?q=Unable+to+guess+signature+from+an+empty+list gives a lot hits with Dbus, most of them quite old.

**Comment by sanderjo** [comment]
It seems I can reproduce with this python3 code:

```
#!/usr/bin/python3
import notify2
notify2.init("icon-summary-body")
note = notify2.Notification("blabla", "this is the text")
note.show()
```
yielding:
```
$ ./my_test_notify2.py 
ERROR:dbus.connection:Unable to set arguments ('icon-summary-body', 0, '', 'blabla', 'this is the text', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "./my_test_notify2.py", line 6, in <module>
    note.show()
  File "/home/sanderjonkers/.local/lib/python3.5/site-packages/notify2.py", line 229, in show
    self.timeout,  # expire_timeout
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
```

A try-except still spits out stuff to stdout / stderr:

```
try:
        note.show()
except:
        print("sorry ... an error")
        pass
```

```
$ ./my_test_notify2.py 2>&1 
ERROR:dbus.connection:Unable to set arguments ('icon-summary-body', 0, '', 'blabla', 'this is the text', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
sorry ... an error
```

**Comment by sanderjo** [comment]
With this ugly hack, the error message is gone ... 

```
#!/usr/bin/python3

import notify2
notify2.init("icon-summary-body")
note = notify2.Notification("blabla", "this is the text")
try:
        logger.disabled = True
        note.show()
        logger.disabled = False
except:
        print("sorry ... an error")
        pass

```

**Comment by sanderjo** [comment]
Disabling "Enable NotifyOSD" makes the ERROR go away, too, of course.

**Comment by sanderjo** [comment]
@jcfp @Safihre any feedback? Is this an upstream problem (with a workaround: turn off NotifyOSD), and shall I close this as so?

**Comment by jcfp** [comment]
Looks like a dbus issue to me. I assume you do have some kind of notification daemon running?

**Comment by sanderjo** [comment]
Yes: within the Linux subsystem on ChromeOS I see this:
```
sanderjo@penguin:~$ ps -ef | grep -i dbus
message+    43     1  0 May31 ?        00:00:03 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
sanderj+   157    93  0 May31 ?        00:00:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation
sanderj+   733 21169  0 09:48 pts/0    00:00:00 grep -i dbus
```

**Comment by sanderjo** [comment]
FWIW: the ERROR logging is coming from the dbus python module (not notify2), so quite deep-down.

```
$ cat /usr/lib/python3/dist-packages/dbus/connection.py | grep -B4 -A4 "Unable to set arguments"
        try:
            message.append(signature=signature, *args)
        except Exception as e:
            logging.basicConfig()
            _logger.error('Unable to set arguments %r according to '
                          'signature %r: %s: %s',
                          args, signature, e.__class__, e)
            raise

--
        try:
            message.append(signature=signature, *args)
        except Exception as e:
            logging.basicConfig()
            _logger.error('Unable to set arguments %r according to '
                          'signature %r: %s: %s',
                          args, signature, e.__class__, e)
            raise
```

**Comment by sanderjo** [comment]
I'm closing this: niche case (SABnzbd on ChromeOS' Linux subsystem ... ), very probably upstream, and workaround available: turn off NotifyOSD

We can always re-open if needed.
