### ISSUE TITLE
HTTPServer.tick error

### ISSUE THREAD

**Issue by Fish2** [sabnzbd/sabnzbd#1519]
Just started testing out and on start up im getting this error on 3.0.0b4

```
2020-06-20 23:48:11,832::ERROR::[_cplogging:219] [20/Jun/2020:23:48:11] ENGINE Error in HTTPServer.tick

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start

    self.tick()

  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick

    s, ssl_env = self.ssl_adapter.wrap(s)

  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap

    server_side=True)

  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket

    _context=self, _session=session)

  File "/usr/lib/python3.6/ssl.py", line 817, in __init__

    self.do_handshake()

  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake

    self._sslobj.do_handshake()

  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake

    self._sslobj.do_handshake()

OSError: [Errno 0] Error
```

**Comment by thezoggy** [comment]
Invalid cert?

**Comment by Safihre** [comment]
It's something with the certificate or the ciphers. Unfortunately the error handling of Python for this is quite bad, often throwing the Error 0..
You can try to generate new certificates. Do you use a proxy or anything?

**Comment by sanderjo** [comment]
Weird: I have the same (Ubuntu 20.04). But also with a pure cherrypy server, so not a SAB specific thing.

Disclaimer: I've been messing with my cherrypy install, cleaned it AFAIK, but there is a chance there.

```
2020-06-21 07:59:00,868::INFO::[SABnzbd:1278] HTTPS keys are OK
2020-06-21 07:59:00,870::INFO::[SABnzbd:1405] Starting web-interface on :::8080
2020-06-21 07:59:00,871::INFO::[_cplogging:219] [21/Jun/2020:07:59:00] ENGINE Bus STARTING
2020-06-21 07:59:00,873::INFO::[_cplogging:219] [21/Jun/2020:07:59:00] ENGINE Started monitor thread '_TimeoutMonitor'.
2020-06-21 07:59:01,030::INFO::[_cplogging:219] [21/Jun/2020:07:59:01] ENGINE Serving on https://:::8080
2020-06-21 07:59:01,031::INFO::[_cplogging:219] [21/Jun/2020:07:59:01] ENGINE Bus STARTED
2020-06-21 07:59:01,031::INFO::[SABnzbd:1442] Starting SABnzbd.py-3.0.0-develop
2020-06-21 07:59:01,031::DEBUG::[__init__:355] Starting postprocessor
2020-06-21 07:59:01,032::DEBUG::[__init__:358] Starting assembler
2020-06-21 07:59:01,037::ERROR::[_cplogging:219] [21/Jun/2020:07:59:01] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

```
I get the same error when I start a pure cherrypy server 
```
sander@witte2004:~/my_cherrypy$ python3 my_cherrypy.py 
[21/Jun/2020:08:00:16] ENGINE Listening for SIGTERM.
[21/Jun/2020:08:00:16] ENGINE Listening for SIGHUP.
[21/Jun/2020:08:00:16] ENGINE Listening for SIGUSR1.
[21/Jun/2020:08:00:16] ENGINE Bus STARTING
[21/Jun/2020:08:00:16] ENGINE Started monitor thread 'Autoreloader'.
[21/Jun/2020:08:00:16] ENGINE Started monitor thread '_TimeoutMonitor'.
[21/Jun/2020:08:00:17] ENGINE Serving on https://0.0.0.0:4444
[21/Jun/2020:08:00:17] ENGINE Bus STARTED
[21/Jun/2020:08:00:17] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by Safihre** [comment]
It's this one again, bug in Python core: https://bugs.python.org/issue31122

**Comment by thezoggy** [comment]
recap of that bug, peer closed connection during TLS negotiation, cosmetic. just ugly OSError get bubbled up.. there is a patch submitted to python core to make it SSL error so it can be more surgically caught and handled.
