### ISSUE TITLE
SAB3 from PPA on Ubuntu 18.04 on ARM: "Missing module: jaraco.collections" ... due to pip's version of cherrypy

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1546]
**Summary**:

the pip version of cherrypy results in a problem for SAB on Ubuntu: 
`ModuleNotFoundError: No module named 'jaraco.collections'`
 https://github.com/cherrypy/cherrypy/issues/1862

**Long**:

On Ubuntu 18.04 on ARM (quite a clean system), I was running successfully SABnzbd.py from git source.

I decided to install sab from PPA, and got problems with "Missing module: jaraco.collections". A lot of tries did not solve that. See below.

And then SABnzbd.py from git source did not run either anymore.

As a wild move, I de-installed sabnzbdplus from PPA ... and SABnbzd.py from git source was working again.

Weird. Is this interfering of Ubuntu and pip library stuff? If so, if I deinstall all pip libraries, could the PPA work again?

Maybe @jcfp has ideas?

**EDIT**:
in the SAB git source directory, I ran
```
python3 -m pip uninstall -r requirements.txt  -y
```
to uninstall the pip libraries ... and after that sabnzbdplus and SABnzbd were able to run!
Still:

```
$ python3 -c "import jaraco.collections"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jaraco.collections'
```
but apparantly that is no problem for sabnzbdplus/SABnzbd the libraries they use now. Hyothesis: in a pip library (jaraco? correction: cherrypy) there is wrong pointer to jaraco.collections?

```
Collecting jaraco.collections (from cherrypy->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/fe/06/a89652069f0a13a33701714c0c8e0cc8656bf6d21b7c6b85fde86cf06ff6/jaraco.collections-3.0.0-py2.py3-none-any.wh
```
digging:
```
CherryPy-18.6.0.dist-info/METADATA:46:Requires-Dist: jaraco.collections
cherrypy/lib/httputil.py:20:import jaraco.collections
cherrypy/lib/httputil.py:390:class CaseInsensitiveDict(jaraco.collections.KeyTransformingDict):
```
So cherrypy wants jaraco.collections?

Reported it as a cherrypy bug: https://github.com/cherrypy/cherrypy/issues/1862

**OLD**

```
Recommended packages:
  javascript-common python3-routes python3-simplejson libavahi-compat-libdnssd1 p7zip-full python3-notify2
The following NEW packages will be installed:
  libjs-bootstrap libjs-jquery-ui libjs-moment python3-cheetah python3-cherrypy3 python3-feedparser python3-jaraco.functools python3-more-itertools python3-portend python3-sabyenc
  python3-tempora sabnzbdplus

...

Setting up libjs-moment (2.20.1+ds-1) ...
Setting up python3-sabyenc (4.0.1-0ubuntu1~jcfp2~18.04) ...
Setting up python3-cherrypy3 (8.9.1-2) ...
Setting up python3-more-itertools (3.2.0-2) ...
Setting up python3-feedparser (5.2.1-1) ...
Setting up python3-jaraco.functools (3.0.0-0ubuntu1~jcfp1~18.04) ...
Setting up libjs-jquery-ui (1.12.1+dfsg-5) ...
Setting up python3-tempora (2.1.1-0ubuntu1~jcfp1~18.04) ...
Setting up python3-portend (2.6-0ubuntu1~jcfp1~18.04) ...
Setting up python3-cheetah (3.2.4-0ubuntu1~jcfp1~18.04) ...
Setting up libjs-bootstrap (3.3.7+dfsg-2) ...
Setting up sabnzbdplus (3.0.0~rc1-0ubuntu1~jcfp1~18.04) ...
Job for sabnzbdplus.service failed because the control process exited with error code.
See "systemctl status sabnzbdplus.service" and "journalctl -xe" for details.
invoke-rc.d: initscript sabnzbdplus, action "restart" failed.
* sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
   Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
   Active: failed (Result: exit-code) since Tue 2020-06-30 21:12:53 CEST; 41ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3596 ExecStart=/etc/init.d/sabnzbdplus start (code=exited, status=1/FAILURE)

Jun 30 21:12:47 nanopineo2 systemd[1]: Starting LSB: SABnzbd+ binary newsgrabber...
Jun 30 21:12:47 nanopineo2 sabnzbdplus[3596]:  * Starting SABnzbd+ binary newsgrabber
Jun 30 21:12:53 nanopineo2 sabnzbdplus[3596]: Not all required Python modules are available, please check requirements.txt
Jun 30 21:12:53 nanopineo2 sabnzbdplus[3596]: Missing module: jaraco.collections
Jun 30 21:12:53 nanopineo2 sabnzbdplus[3596]: You can read more at: https://sabnzbd.org/python3
Jun 30 21:12:53 nanopineo2 sabnzbdplus[3596]: If you still experience problems, remove all .pyc files in this folder and subfolders
Jun 30 21:12:53 nanopineo2 sabnzbdplus[3596]:    ...fail!
Jun 30 21:12:53 nanopineo2 systemd[1]: sabnzbdplus.service: Control process exited, code=exited status=1
Jun 30 21:12:53 nanopineo2 systemd[1]: sabnzbdplus.service: Failed with result 'exit-code'.
Jun 30 21:12:53 nanopineo2 systemd[1]: Failed to start LSB: SABnzbd+ binary newsgrabber.
dpkg: error processing package sabnzbdplus (--configure):
 installed sabnzbdplus package post-installation script subprocess returned error exit status 1
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.41) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 sabnzbdplus
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

and

```
sander@nanopineo2:~$ sabnzbdplus
Not all required Python modules are available, please check requirements.txt
Missing module: jaraco.collections
You can read more at: https://sabnzbd.org/python3
If you still experience problems, remove all .pyc files in this folder and subfolders
```
and

```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jaraco

>>> import jaraco.functools

>>> import jaraco.collections
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jaraco.collections'
```
nothing available:

```
sander@nanopineo2:~$ apt search jaraco
Sorting... Done
Full Text Search... Done
python-jaraco.itertools/bionic,bionic 2.0.1-1 all
  Tools for working with iterables (Python 2)

python3-jaraco.functools/bionic,bionic,now 3.0.0-0ubuntu1~jcfp1~18.04 all [installed,automatic]
  additional functools in the spirit of stdlib's functools

python3-jaraco.itertools/bionic,bionic 2.0.1-1 all
  Tools for working with iterables (Python 3)
```

pip installs it, but no solution:

```
sander@nanopineo2:~$ python3 -m pip install jaraco.collections
Collecting jaraco.collections
  Using cached https://files.pythonhosted.org/packages/fe/06/a89652069f0a13a33701714c0c8e0cc8656bf6d21b7c6b85fde86cf06ff6/jaraco.collections-3.0.0-py2.py3-none-any.whl
Collecting six>=1.7.0 (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting jaraco.text (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/50/cd/6eda44738065e844bed8fae60a229b6c46f42d0ba8d48205e9fb57e254cd/jaraco.text-3.2.0-py2.py3-none-any.whl
Collecting jaraco.classes (from jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/68/ce/8f43aa0d0f18120e687ae0192fe3168630040841a3e87bed93c5fe024dbe/jaraco.classes-3.1.0-py2.py3-none-any.whl
Collecting jaraco.functools (from jaraco.text->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/4f/2b/bbab94f3e461adaf3c7a3a25da0c67c91d8cf7a4ddae7096028601ff940f/jaraco.functools-3.0.1-py3-none-any.whl
Collecting importlib-resources; python_version < "3.7" (from jaraco.text->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/ce/06/94cb4028cbcb834c3a6a0c239ab37e76e293c75bed51a9cee2cb8337b47e/importlib_resources-2.0.1-py2.py3-none-any.whl
Collecting more-itertools (from jaraco.classes->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/ef/9b/6c35ec5483710492e21252465160ee508170159f7e0e2d6cd769022f52f6/more_itertools-8.4.0-py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from importlib-resources; python_version < "3.7"->jaraco.text->jaraco.collections)
  Downloading https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
Collecting zipp>=0.4; python_version < "3.8" (from importlib-resources; python_version < "3.7"->jaraco.text->jaraco.collections)
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Installing collected packages: six, more-itertools, jaraco.functools, zipp, importlib-metadata, importlib-resources, jaraco.text, jaraco.classes, jaraco.collections
Successfully installed importlib-metadata-1.7.0 importlib-resources-2.0.1 jaraco.classes-3.1.0 jaraco.collections-3.0.0 jaraco.functools-3.0.1 jaraco.text-3.2.0 more-itertools-8.4.0 six-1.15.0 zipp-3.1.0

sander@nanopineo2:~$ python3 -c "import jaraco.collections"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jaraco.collections'
sander@nanopineo2:~$
```

Final: remove sabndplus (from PPA):

$ sudo apt-get remove sabnzbdplus
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libjs-bootstrap libjs-jquery libjs-jquery-ui libjs-moment python3-cheetah python3-cherrypy3 python3-feedparser python3-jaraco.functools python3-more-itertools python3-portend
  python3-sabyenc python3-tempora sabnzbdplus
0 upgraded, 0 newly installed, 13 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 11.8 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 54053 files and directories currently installed.)
Removing sabnzbdplus (3.0.0~rc1-0ubuntu1~jcfp1~18.04) ...
Removing libjs-bootstrap (3.3.7+dfsg-2) ...
Removing libjs-jquery-ui (1.12.1+dfsg-5) ...
Removing libjs-jquery (3.2.1-1) ...
Removing libjs-moment (2.20.1+ds-1) ...
Removing python3-cheetah (3.2.4-0ubuntu1~jcfp1~18.04) ...
Removing python3-cherrypy3 (8.9.1-2) ...
Removing python3-feedparser (5.2.1-1) ...
Removing python3-portend (2.6-0ubuntu1~jcfp1~18.04) ...
Removing python3-tempora (2.1.1-0ubuntu1~jcfp1~18.04) ...
Removing python3-jaraco.functools (3.0.0-0ubuntu1~jcfp1~18.04) ...
Removing python3-more-itertools (3.2.0-2) ...
Removing python3-sabyenc (4.0.1-0ubuntu1~jcfp2~18.04) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...

**Comment by Safihre** [comment]
Closing as upstream.
