### ISSUE TITLE
EngineError in HTTPServer.tick

### ISSUE THREAD

**Issue by hugeyeti** [sabnzbd/sabnzbd#1548]
When acquiring a new NZB the following is noticed:

3/Jul/2020:15:42:50] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

let me know what verbose logs you are looking for and I will post.

**Comment by thezoggy** [comment]
What version of cherrypy is installed?

**Comment by hugeyeti** [comment]
> What version of cherrypy is installed?

yeti@paw:~$ python3 -c "import cherrypy; print (cherrypy.__version__)" 
8.9.1

**Comment by thezoggy** [comment]
@hugeyeti  I assume you are using self signed cert?
https://github.com/sabnzbd/sabnzbd/issues/1519

**Comment by thezoggy** [comment]
I would check your cert to make sure its not invalid.
Now about why this isnt gracefully handled, its a long outstanding core python handling issue which at one point cherrypy I thought was addressing on their side.. but cant recall now if its just in newer code we arent using or what. 

your cherrypy v8.9.1 is from Jan 16, 2017, latest is 18.6.0 which I do believe has some breaking changes @Safihre will have to confirm.

**Comment by hugeyeti** [comment]
> I would check your cert to make sure its not invalid.
> Now about why this isnt gracefully handled, its a long outstanding core python handling issue which at one point cherrypy I thought was addressing on their side.. but cant recall now if its just in newer code we arent using or what.
> 
> your cherrypy v8.9.1 is from Jan 16, 2017, latest is 18.6.0 which I do believe has some breaking changes @Safihre will have to confirm.

yeti@paw:~/Downloads$ python3 -c "import cherrypy; print (cherrypy.__version__)" 
18.6.1.dev2+g9c07c677

self signed cert ok (validated) -->

ERROR 3 minutes ago [04/Jul/2020:01:09:25] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

From what I see, looks like a python cosmetic issue you mentioned in [#1519 ](https://github.com/sabnzbd/sabnzbd/issues/1519)

**Comment by Safihre** [comment]
Yeah, it's still the annoying bug in Python that they don't wanna fix. Will probably just switch to using PyOpenSSL for SABnzbd 3.0.1.

**Comment by ysangkok** [comment]
@Safihre So since the fix was reverted, is the best way to avoid this just upgrading Python? I am using Pyenv.
