### ISSUE TITLE
assembler - BadRarFile("cannot load le32")

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1563]
version: 3.0.0RC2 from ppa on ubuntu 18.04.4 LTS

looks like it processed just fine however there was a traceback during download:
```
2020-08-01 12:40:36,035::DEBUG::[filesystem:767] [sabnzbd.load_data] Deleting file /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/__ADMIN__/SABnzbd_article_ibh0reqw
2020-08-01 12:40:36,037::DEBUG::[filesystem:486] Applying permissions 0o644 (octal) to /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/yay.part21.rar
2020-08-01 12:40:36,037::INFO::[assembler:114] Decoding finished /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/yay.part21.rar
2020-08-01 12:40:36,037::DEBUG::[nzbstuff:453] Removing article database for SABnzbd_nzf_l8y1d_kn
2020-08-01 12:40:36,037::DEBUG::[filesystem:767] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/__ADMIN__/SABnzbd_nzf_l8y1d_kn
2020-08-01 12:40:36,038::INFO::[assembler:368] Error during inspection of RAR-file /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/yay.part21.rar

2020-08-01 12:40:36,038::DEBUG::[assembler:369] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/assembler.py", line 298, in check_encrypted_and_unwanted_files
    zf = rarfile.RarFile(filepath, single_file_check=True)
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 711, in __init__
    self._parse()
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 922, in _parse
    self._file_parser.parse()
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 1036, in parse
    self._parse_real()
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 1060, in _parse_real
    h = self._parse_header(fd)
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 1142, in _parse_header
    return self._parse_block_header(fd)
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 1692, in _parse_block_header
    header_crc, pos = load_le32(start_bytes, 0)
  File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 2668, in load_le32
    raise BadRarFile("cannot load le32")
sabnzbd.utils.rarfile.BadRarFile: cannot load le32

2020-08-01 12:40:36,266::DEBUG::[assembler:89] Decoding part of /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/yay.part29.rar
2020-08-01 12:40:36,268::DEBUG::[filesystem:767] [sabnzbd.load_data] Deleting file /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/__ADMIN__/SABnzbd_article_1yldxm5v
2020-08-01 12:40:36,273::DEBUG::[filesystem:767] [sabnzbd.load_data] Deleting file /home/<USERNAME>/tmp/downloads/incomplete/nzb/Coma.2019.BluRay.720p.DTS.x264-MTeam/__ADMIN__/SABnzbd_article_gtgvvefv

```

**Comment by Safihre** [comment]
It's at INFO level on purpose, this can hebben when `rarfile` doesn't understand the fileformat.

**Comment by thezoggy** [comment]
Perhaps we should handle the exception more gracefully since Tracebacks generally are a sign that something went afoul
