### ISSUE TITLE
3.0.x folder renaming failures due to anti virus scanner locking files on Windows 10

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1569]
Since the alpha versions of SABnzbd 3.0.0, the renaming of folders on Windows 10 fails every now and then. It used to happen before with version 2.x also but much less frequent. The reason of the renaming issue is that the anti virus scanner temporarily locks a file in the folder. I use Avast free antivirus and I was advised to use Sophos by another user since this would not cause the issue. This was indeed correct but since I had a few occasions of Sophos not detecting malware I switched back to Avast. 

But besides this, the proper working of SABnzbd should not be depending on the type of virus scanner that a user has. Therefore I would like to suggest to solve this issue with one of two solutions:

1) Build in a fixed delay before renaming the folder of 5 seconds or so
2) Retry the renaming of the folder after a short delay

Solution 1 should solve most instances of the renaming issue already. In case this issue is not seen on Linux, then maybe the delay can be made OS dependent? If a standard delay is seen as unwanted, then it can be made configurable or option 2 could then be the solution. I would have loved to provide a pull request for this but I am not very proficient in Python.

**Comment by thezoggy** [comment]
Just add exclusion for your sab complete/incomplete folder and/or sab itself?

**Comment by thezoggy** [comment]
We should not punish all users for <insert app> behavior. We already have warnings on our wiki about antivirus interference.

**Comment by Safihre** [comment]
We already do many retries on Windows: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L754-L773
But: there was a change in Python to `WinError`/`OSError` so the specific code [here](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L764-L768) might not work anymore. I couldn't verify it works.
Maybe its good if you could post the tracebacks?

**Comment by ErikBrown2** [comment]
The following is from an older debug log. I will try to recreate the issue again and post the log 


2020-05-21 15:11:31,363::DEBUG::[filesystem:733] [sabnzbd\postproc.py.cleanup_list] Removing dir \\?\E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles
2020-05-21 15:11:31,364::DEBUG::[filesystem:692] Renaming "\\?\E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "\\?\E:\SABnzbd\Magazines\MyDownloadedFiles"
2020-05-21 15:11:31,364::DEBUG::[filesystem:706] Error renaming "\\?\E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "\\?\E:\SABnzbd\Magazines\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\E:\\SABnzbd\\Magazines\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\E:\\SABnzbd\\Magazines\\MyDownloadedFiles'>
2020-05-21 15:11:31,364::ERROR::[postproc:480] Error renaming "E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "E:\SABnzbd\Magazines\MyDownloadedFiles"
2020-05-21 15:11:31,365::INFO::[postproc:485] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 478, in process_job
  File "sabnzbd\postproc.py", line 1129, in rename_and_collapse_folder
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\filesystem.py", line 699, in renamer
PermissionError: [WinError 5] Access is denied: '\\\\?\\E:\\SABnzbd\\Magazines\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\E:\\SABnzbd\\Magazines\\MyDownloadedFiles'
2020-05-21 15:11:31,365::INFO::[postproc:1108] Skipping sample-removal, false-positive

**Comment by ErikBrown2** [comment]
Here is an up to date log entry from 3.0.1RC1

2020-08-08 22:36:52,365::INFO::[postproc:433] Finished unpack_magic on MyDownloadedFiles
2020-08-08 22:36:52,693::DEBUG::[filesystem:749] Renaming "\\?\E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "\\?\E:\SABnzbd\Magazines\MyDownloadedFiles"
2020-08-08 22:36:52,693::DEBUG::[filesystem:763] Error renaming "\\?\E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "\\?\E:\SABnzbd\Magazines\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\E:\\SABnzbd\\Magazines\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\E:\\SABnzbd\\Magazines\\MyDownloadedFiles'>
2020-08-08 22:36:52,705::ERROR::[postproc:492] Error renaming "E:\SABnzbd\Magazines\_UNPACK_MyDownloadedFiles" to "E:\SABnzbd\Magazines\MyDownloadedFiles"
2020-08-08 22:36:52,705::INFO::[postproc:495] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 490, in process_job
  File "sabnzbd\postproc.py", line 1143, in rename_and_collapse_folder
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\filesystem.py", line 756, in renamer
PermissionError: [WinError 5] Access is denied: '\\\\?\\E:\\SABnzbd\\Magazines\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\E:\\SABnzbd\\Magazines\\MyDownloadedFiles'
2020-08-08 22:36:52,706::INFO::[postproc:1122] Skipping sample-removal, false-positive

**Comment by thezoggy** [comment]
What is E: ? Internal HDD with NTFS?  External USB with exFat?

**Comment by ErikBrown2** [comment]
e: is an internal ntfs harddisk. All my categories are on other internal harddisks than c: so I do not have a final destination folder on c:. I will create a test category for that and let you know the result.

**Comment by ErikBrown2** [comment]
It also happens with the final destination folder on the c: drive

2020-08-09 13:27:11,466::INFO::[postproc:433] Finished unpack_magic on MyDownloadedFiles
2020-08-09 13:27:11,499::DEBUG::[filesystem:749] Renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles"
2020-08-09 13:27:11,499::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\C:\\CatOnCFolder\\MyDownloadedFiles'>
2020-08-09 13:27:11,500::ERROR::[postproc:492] Error renaming "C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "C:\CatOnCFolder\MyDownloadedFiles"
2020-08-09 13:27:11,500::INFO::[postproc:495] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 490, in process_job
  File "sabnzbd\postproc.py", line 1143, in rename_and_collapse_folder
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\filesystem.py", line 756, in renamer
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\C:\\CatOnCFolder\\MyDownloadedFiles'
2020-08-09 13:27:11,500::INFO::[postproc:1122] Skipping sample-removal, false-positive

**Comment by Safihre** [comment]
Could you try [this](https://github.com/sabnzbd/sabbuild/releases/tag/test-build) test-build with the change to include "Access Denied" in the retries?
The downside of this change is that in case it's a permissions error, it will now take up to 20 seconds (due to 10 retries) before it throws the error.

**Comment by ErikBrown2** [comment]
Still renaming issues with this test build

2020-08-09 20:38:27,578::INFO::[postproc:433] Finished unpack_magic on MyDownloadedFiles
2020-08-09 20:38:27,922::DEBUG::[filesystem:749] Renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles"
2020-08-09 20:38:27,922::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\C:\\CatOnCFolder\\MyDownloadedFiles'>
2020-08-09 20:38:27,923::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:29,938::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\C:\\CatOnCFolder\\MyDownloadedFiles'>
2020-08-09 20:38:29,938::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:31,950::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles' -> '\\\\?\\C:\\CatOnCFolder\\MyDownloadedFiles'>
2020-08-09 20:38:31,951::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:32,139::DEBUG::[bpsmeter:262] bps: 1165344.6079349034
2020-08-09 20:38:33,474::DEBUG::[assembler:89] Decoding part of \\?\C:\SABnzbd\incomplete\MyDownloadedFilesa\soijajsfsdjrewjtreltjetletlejtej.part01.rar
2020-08-09 20:38:33,966::DEBUG::[filesystem:759] Could not rename, trying move for \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:34,664::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles\\PW-1956-06.pdf'>
2020-08-09 20:38:34,664::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:36,671::DEBUG::[filesystem:759] Could not rename, trying move for \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:37,144::DEBUG::[bpsmeter:262] bps: 1181738.9681658738
2020-08-09 20:38:37,567::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <[WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_MyDownloadedFiles\\PW-1998-10.pdf'>
2020-08-09 20:38:37,567::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:39,569::DEBUG::[filesystem:759] Could not rename, trying move for \\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles to \\?\C:\CatOnCFolder\MyDownloadedFiles
2020-08-09 20:38:39,569::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "\\?\C:\CatOnCFolder\MyDownloadedFiles" <Destination path '\\?\C:\CatOnCFolder\MyDownloadedFiles\_UNPACK_MyDownloadedFiles' already exists>
2020-08-09 20:38:39,570::ERROR::[postproc:492] Error renaming "C:\CatOnCFolder\_UNPACK_MyDownloadedFiles" to "C:\CatOnCFolder\MyDownloadedFiles"
2020-08-09 20:38:39,570::INFO::[postproc:495] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 490, in process_job
  File "sabnzbd\postproc.py", line 1143, in rename_and_collapse_folder
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\filesystem.py", line 760, in renamer
  File "shutil.py", line 786, in move
shutil.Error: Destination path '\\?\C:\CatOnCFolder\MyDownloadedFiles\_UNPACK_MyDownloadedFiles' already exists
2020-08-09 20:38:39,939::INFO::[nzbstuff:1794] [sabnzbd\postproc.py.process_job] Purging data for job MyDownloadedFiles (delete_all_data=True)
2020-08-09 20:38:39,939::DEBUG::[filesystem:817] Removing dir recursively \\?\C:\SABnzbd\incomplete\MyDownloadedFiles
2020-08-09 20:38:39,943::DEBUG::[sorting:269] Found TV Show (MyDownloadedFiles)
2020-08-09 20:38:40,362::INFO::[database:290] Added job MyDownloadedFiles to history

**Comment by Safihre** [comment]
In this case, we can't do much then.. We already wait 20 seconds. You'll have to add exclusions to your virus scanner!

**Comment by ErikBrown2** [comment]
It is a bit surprising that the files are locked so long. Maybe you can increase the retries or the delay a bit? The nzb that I use for the test contains 79 pdf files and it is an extreme case since it causes the retry error to occur 9 out of 10 times.

**Comment by ErikBrown2** [comment]
It is actually a great improvement. Before the renaming failed 9 out of 10 downloads wit this nzb. Now if failed only 3 out of 10 downloads. And this is really an extreme nzb for the renaming issue. So I think that you can consider it solved with this fix.

The below is a sample where the fix solved the issue

2020-08-09 21:08:47,292::INFO::[postproc:433] Finished unpack_magic on Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:47,722::DEBUG::[filesystem:749] Renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d"
2020-08-09 21:08:47,723::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d' -> '\\\\?\\C:\\CatOnCFolder\\Amateur Radio Magazines etc. 10-5-2010-111d'>
2020-08-09 21:08:47,723::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:49,739::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d' -> '\\\\?\\C:\\CatOnCFolder\\Amateur Radio Magazines etc. 10-5-2010-111d'>
2020-08-09 21:08:49,740::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:51,749::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d' -> '\\\\?\\C:\\CatOnCFolder\\Amateur Radio Magazines etc. 10-5-2010-111d'>
2020-08-09 21:08:51,750::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:52,034::DEBUG::[bpsmeter:262] bps: 1192433.855310073
2020-08-09 21:08:53,518::DEBUG::[assembler:89] Decoding part of \\?\C:\SABnzbd\incomplete\Amateur Radio Magazines etc. 10-5-2010-111e\soijajsfsdjrewjtreltjetletlejtej.part01.rar
2020-08-09 21:08:53,752::DEBUG::[filesystem:759] Could not rename, trying move for \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:54,584::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d" <[WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d\\PW-1956-01.pdf'>
2020-08-09 21:08:54,585::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:56,593::DEBUG::[filesystem:759] Could not rename, trying move for \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:56,595::DEBUG::[filesystem:791] [sabnzbd\postproc.py.rename_and_collapse_folder] Removing dir \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:57,035::DEBUG::[bpsmeter:262] bps: 1188450.009905298
2020-08-09 21:08:57,059::INFO::[nzbstuff:1794] [sabnzbd\postproc.py.process_job] Purging data for job Amateur Radio Magazines etc. 10-5-2010-111d (delete_all_data=True)
2020-08-09 21:08:57,059::DEBUG::[filesystem:817] Removing dir recursively \\?\C:\SABnzbd\incomplete\Amateur Radio Magazines etc. 10-5-2010-111d
2020-08-09 21:08:57,439::INFO::[database:290] Added job Amateur Radio Magazines etc. 10-5-2010-111d to history

**Comment by Safihre** [comment]
I would have to agree with @thezoggy that we would then be working around a problem that's not within the scope of SABnzbd.
I don't see why you couldn't exclude your Incomplete folder from your virusscanner?

**Comment by ErikBrown2** [comment]
I do have the incomplete folder excluded in the virus scanner. But not the final destination folder. It is the final destination folder that is being renamed and where the file is locked. But as I wrote in my previous comment, the issue is very much reduced. I test with a nzb that almost guarantees to create the renaming issue. But in practice, it is seen approximately one time in 25 downloads. So this fix that you implemented will have solved the issue for as good as all normal downloads.

**Comment by Safihre** [comment]
Oke then I leave the code 👍

**Comment by ErikBrown2** [comment]
Here another sample of a renaming issue where the fix solved it. This is for almost all downloads of this test nzb the case:

2020-08-09 21:31:28,310::INFO::[postproc:433] Finished unpack_magic on Amateur Radio Magazines etc. 10-5-2010-111g
2020-08-09 21:31:28,340::DEBUG::[filesystem:749] Renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111g" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111g"
2020-08-09 21:31:28,341::DEBUG::[filesystem:763] Error renaming "\\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111g" to "\\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111g" <[WinError 5] Access is denied: '\\\\?\\C:\\CatOnCFolder\\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111g' -> '\\\\?\\C:\\CatOnCFolder\\Amateur Radio Magazines etc. 10-5-2010-111g'>
2020-08-09 21:31:28,341::DEBUG::[filesystem:771] File busy, retrying rename \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111g to \\?\C:\CatOnCFolder\Amateur Radio Magazines etc. 10-5-2010-111g
2020-08-09 21:31:29,955::DEBUG::[bpsmeter:262] bps: 1162804.4827805595
2020-08-09 21:31:30,350::DEBUG::[filesystem:791] [sabnzbd\postproc.py.rename_and_collapse_folder] Removing dir \\?\C:\CatOnCFolder\_UNPACK_Amateur Radio Magazines etc. 10-5-2010-111g
2020-08-09 21:31:30,529::INFO::[nzbstuff:1794] [sabnzbd\postproc.py.process_job] Purging data for job Amateur Radio Magazines etc. 10-5-2010-111g (delete_all_data=True)
2020-08-09 21:31:30,530::DEBUG::[filesystem:817] Removing dir recursively \\?\C:\SABnzbd\incomplete\Amateur Radio Magazines etc. 10-5-2010-111g
2020-08-09 21:31:30,706::INFO::[database:290] Added job Amateur Radio Magazines etc. 10-5-2010-111g to history
2020-08-09 21:31:30,707::INFO::[postproc:132] Saving postproc queue
2020-08-09 21:31:30,707::DEBUG::[__init__:1000] [sabnzbd\postproc.py.save] Saving data for postproc2.sab
2020-08-09 21:31:30,708::DEBUG::[__init__:932] [sabnzbd\__init__.py.save_admin] Saving data for postproc2.sab in \\?\C:\SABnzbd\Admin
2020-08-09 21:31:30,709::INFO::[downloader:310] Post-processing finished, resuming download

**Comment by thezoggy** [comment]
Can you test with Avast disabled and try again so we can confirm if Avast is the source of the issues

**Comment by ErikBrown2** [comment]
Another user had suggested to me to switch to Sophos as virus scanner and that did indeed solve the issue. So it was caused by Avast. But I switched back to Avast when I noticed on a few occasions that Sophos did not detect malware.

**Comment by ErikBrown2** [comment]
> Oke then I leave the code 👍

Thank you very much for the effort. I am convinced that many more users will be helped by this.
