### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1572]
Just started seeing this error today with fresh installations from the `master` branch when testing on my QNAP. It happens within a few seconds of accessing the UI. :confused: 
```
2020-08-13 12:02:40,706::INFO::[SABnzbd:1136] --------------------------------
2020-08-13 12:02:40,710::INFO::[SABnzbd:1137] SABnzbd.py-3.0.0 (rev=cc465c75543dfa26e3065c7dbf98354d53ad1112)
2020-08-13 12:02:40,712::INFO::[SABnzbd:1138] Full executable path = /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py
2020-08-13 12:02:40,717::INFO::[SABnzbd:1148] Platform = posix
2020-08-13 12:02:40,719::INFO::[SABnzbd:1149] Python-version = 3.8.3 (default, Jun 12 2020, 20:24:48) 
[GCC 8.4.0]
2020-08-13 12:02:40,721::INFO::[SABnzbd:1150] Arguments = "SABnzbd.py" "--daemon" "--browser" "0" "--config-file" "/share/MD0_DATA/.qpkg/SABnzbd/config/config.ini" "--pidfile" "/var/run/SABnzbd.pid"
2020-08-13 12:02:40,723::INFO::[SABnzbd:1154] Not inside a docker container
2020-08-13 12:02:40,724::INFO::[SABnzbd:1157] Preferred encoding = UTF-8
2020-08-13 12:02:40,726::INFO::[SABnzbd:1169] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-08-13 12:02:40,729::INFO::[SABnzbd:1217] Using INI file /share/MD0_DATA/.qpkg/SABnzbd/config/config.ini
2020-08-13 12:02:40,756::INFO::[postproc:138] Loading postproc queue
2020-08-13 12:02:40,765::INFO::[__init__:955] [N/A] /share/MD0_DATA/.qpkg/SABnzbd/config/admin/Rating.sab missing
2020-08-13 12:02:40,770::INFO::[scheduler:216] Setting schedule for midnight BPS reset
2020-08-13 12:02:40,773::INFO::[__init__:350] All processes started
2020-08-13 12:02:40,776::INFO::[SABnzbd:292] Template location for Glitter is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Glitter
2020-08-13 12:02:40,778::INFO::[SABnzbd:292] Template location for Config is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Config
2020-08-13 12:02:40,886::INFO::[SABnzbd:393] SABYenc module (v4.0.2)... found!
2020-08-13 12:02:40,889::INFO::[SABnzbd:412] Cryptography module (v2.9.2)... found!
2020-08-13 12:02:40,890::INFO::[SABnzbd:417] par2 binary... found (/usr/bin/par2)
2020-08-13 12:02:40,892::INFO::[SABnzbd:424] UNRAR binary... found (/opt/bin/unrar)
2020-08-13 12:02:40,894::INFO::[SABnzbd:432] UNRAR binary version 5.90
2020-08-13 12:02:40,897::INFO::[SABnzbd:440] 7za binary... found (/opt/bin/7za)
2020-08-13 12:02:40,898::INFO::[SABnzbd:451] nice binary... found (/opt/bin/nice)
2020-08-13 12:02:40,900::INFO::[SABnzbd:455] ionice binary... found (/opt/bin/ionice)
2020-08-13 12:02:40,914::INFO::[SABnzbd:1403] Starting web-interface on 0.0.0.0:8900
2020-08-13 12:02:40,916::INFO::[_cplogging:213] [13/Aug/2020:12:02:40] ENGINE Bus STARTING
2020-08-13 12:02:41,057::INFO::[_cplogging:213] [13/Aug/2020:12:02:41] ENGINE Serving on http://0.0.0.0:8900
2020-08-13 12:02:41,062::INFO::[_cplogging:213] [13/Aug/2020:12:02:41] ENGINE Bus STARTED
2020-08-13 12:02:41,067::INFO::[SABnzbd:1440] Starting SABnzbd.py-3.0.0
2020-08-13 12:02:41,071::INFO::[postproc:228] Completed Download Folder /share/Download/complete is not on FAT
2020-08-13 12:02:41,099::INFO::[dirscanner:117] Dirscanner starting up
2020-08-13 12:02:41,103::INFO::[urlgrabber:96] URLGrabber starting up
2020-08-13 12:02:41,413::INFO::[zconfig:71] No Bonjour/ZeroConfig support installed
2020-08-13 12:04:08,114::ERROR::[_cplogging:213] [13/Aug/2020:12:04:08] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 1795, in serve
    self.tick()
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 2030, in tick
    self.connections.expire()
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "/opt/lib/python3.8/_collections_abc.py", line 743, in __iter__
RuntimeError: dictionary changed size during iteration
```

Sometimes, new ones keep being added to the log.

**Comment by Safihre** [comment]
This is an issue with `cheroot`. I can report it there.
If needed, would you be able to run a script on your NAS manually? Through SSH for example?

**Comment by Safihre** [comment]
If so, could you run with the right `python`:
```
python -c "import cherrypy; print(cherrypy.__version__)"
python -c "import cheroot; print(cheroot.__version__)"
```

**Comment by OneCDOnly** [comment]
> This is an issue with `cheroot`. I can report it there.

Thank you. :+1: 

> If needed, would you be able to run a script on your NAS manually? Through SSH for example?

Yes, I don't think that will be a problem. :wink: 
```
[~] # python -V
Python 3.8.3
[~] # python -c "import cherrypy; print(cherrypy.__version__)"
18.6.0
[~] # python -c "import cheroot; print(cheroot.__version__)"
8.4.4
```

**Comment by Safihre** [comment]
@OneCDOnly I just updated `cheroot` on my own system and now also getting these errors. Seems they introduced this problem recently, as I was using `cheroot==8.4.2` before.

**Comment by Safihre** [comment]
cherrypy/cheroot/issues/312

**Comment by webknjaz** [comment]
@Safihre @OneCDOnly https://github.com/cherrypy/cheroot/pull/313#issuecomment-673588241

**Comment by tixetsal** [comment]
I am also affected by this issue on Arch Linux.

**Comment by Safihre** [comment]
Are you using a package? iio7 Please tell the maintainer to update with the latest `requirements.txt`, where we down-grade the `cheroot` version.

**Comment by f0ff886f** [comment]
For users on Archlinux, you should download the 8.4.2 `python-cheroot` package: https://archive.archlinux.org/packages/p/python-cheroot/python-cheroot-8.4.2-1-any.pkg.tar.zst

Then add it to your IgnorePkg list in pacman.conf until things are better in the upstream cheroot package.

**Comment by tixetsal** [comment]
> For users on Archlinux, you should download the 8.4.2 `python-cheroot` package: https://archive.archlinux.org/packages/p/python-cheroot/python-cheroot-8.4.2-1-any.pkg.tar.zst
> 
> Then add it to your IgnorePkg list in pacman.conf until things are better in the upstream cheroot package.

This can be accomplished by:

yay -Rdd python-cheroot

wget https://archive.archlinux.org/packages/p/python-cheroot/python-cheroot-8.4.2-1-any.pkg.tar.zst

sudo pacman -U python-cheroot-8.4.2-1-any.pkg.tar.zst

Then edit /etc/pacman.conf and uncomment the beginning of the "IgnorePkg" line and make it read:

IgnorePkg = python-cheroot

The next time you call yay/pacman for an update, it should notify you that you've pinned the package and it's ignoring the update. If you're hitting this page, you probably know how to do this, but just in case...

**Comment by webknjaz** [comment]
Cheroot v8.4.5 is out. Try upgrading, it will fix the problem.

**Comment by f0ff886f** [comment]
Nice, tried it out and it works. Thank you!

**Comment by Safihre** [comment]
Sticking to 8.4.2 for now due to new problems: cherrypy/cheroot/issues/317.
