### ISSUE TITLE
Windows: Traceback pywintypes.error: (-2147467259, 'Shell_NotifyIcon', 'Niet nader omschreven fout')""

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1573]
FWIW: On Win10, with SAB3.0.0., I get the Tracebacks in sabnzbd.log like below

```
2020-08-14 08:09:52,235::INFO::[notifier:375] Failed to send Windows notification
2020-08-14 08:09:52,236::DEBUG::[notifier:376] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\notifier.py", line 373, in send_windows
  File "sabnzbd\utils\systrayiconthread.py", line 101, in sendnotification
pywintypes.error: (-2147467259, 'Shell_NotifyIcon', 'Niet nader omschreven fout')
```

No traceback in the GUI, so not a big problem, but a FWIW

context:

```
2020-08-14 08:09:52,227::INFO::[postproc:428] Unpacked files ['\\\\?\\C:\\Users\\blabbab\\AppData\\Local\\sabnzbd\\Downloads\\complete\\_UNPACK_test_download_100MB\\100MB.bin']
2020-08-14 08:09:52,227::INFO::[postproc:433] Finished unpack_magic on test_download_100MB
2020-08-14 08:09:52,227::DEBUG::[filesystem:733] Renaming "\\?\C:\Users\blabbab\AppData\Local\sabnzbd\Downloads\complete\_UNPACK_test_download_100MB" to "\\?\C:\Users\blabbab\AppData\Local\sabnzbd\Downloads\complete\test_download_100MB"
2020-08-14 08:09:52,231::DEBUG::[filesystem:774] [sabnzbd\postproc.py.rename_and_collapse_folder] Removing dir \\?\C:\Users\blabbab\AppData\Local\sabnzbd\Downloads\complete\_UNPACK_test_download_100MB
2020-08-14 08:09:52,232::INFO::[nzbstuff:1795] [sabnzbd\postproc.py.process_job] Purging data for job test_download_100MB (delete_all_data=True)
2020-08-14 08:09:52,232::DEBUG::[filesystem:800] Removing dir recursively \\?\C:\Users\blabbab\AppData\Local\sabnzbd\Downloads\incomplete\test_
2020-08-14 08:09:52,235::INFO::[notifier:375] Failed to send Windows notification
2020-08-14 08:09:52,236::DEBUG::[notifier:376] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\notifier.py", line 373, in send_windows
  File "sabnzbd\utils\systrayiconthread.py", line 101, in sendnotification
pywintypes.error: (-2147467259, 'Shell_NotifyIcon', 'Niet nader omschreven fout')
2020-08-14 08:09:52,244::INFO::[database:290] Added job test_download_100MB to history
```

**Comment by Safihre** [comment]
Have you tried restarting SABnzbd and the PC? Is the tray icon showing and can you right click it?

**Comment by sanderjo** [comment]
Ah, yes, Windows, so reboot. Made me think of an old business idea "Reboot Consultancy. Baat 't niet, dan schaadt 't niet". ;-)

But no, after a Windows reboot, still Tracebacks. And no, there is nog logo at all.



```
2020-08-14 09:55:59,877::INFO::[notifier:375] Failed to send Windows notification
2020-08-14 09:55:59,877::DEBUG::[notifier:376] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 246, in run
  File "queue.py", line 178, in get
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 251, in run
  File "queue.py", line 178, in get
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sabnzbd\notifier.py", line 373, in send_windows
  File "sabnzbd\utils\systrayiconthread.py", line 101, in sendnotification
pywintypes.error: (-2147467259, 'Shell_NotifyIcon', 'Niet nader omschreven fout')
```

**Comment by sanderjo** [comment]
When I google `pywintypes.error: (-2147467259, 'Shell_NotifyIcon'` I get a lot of hits, so not SAB specific.

**Comment by Safihre** [comment]
Closing as upstream/can't fix.
