### ISSUE TITLE
ENGINE Error in HTTPServer.tick in v3

### ISSUE THREAD

**Issue by ne0ark** [sabnzbd/sabnzbd#1576]
Hello,

Is there any fix for this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by Safihre** [comment]
Unfortunately not, it's a bug in Python-core that they are not fixing:
#1548  #1548 https://bugs.python.org/issue31122

**Comment by Safihre** [comment]
Oh wow, they actually just merged the patch! I complained a bit 😅

**Comment by sanderjo** [comment]
"Months are just passing while the PR is just a few lines of code" ... hahaha, sometimes Dutch Directness is effective ... :+1:

**Comment by thezoggy** [comment]
yep, sadly looks like its only going to be in 3.8+ code base :(
so may just have to recommend anyone annoyed by this error that is on 3.6-7 to upgrade (when available)

**Comment by Safihre** [comment]
When investigating #1577 I remembered that new versions of `cherrypy` actually have a workaround for this. So we need to update your version of `cherrypy`. How do you run SABnzbd?
