### ISSUE TITLE
Constant Error since a few days ago

### ISSUE THREAD

**Issue by AcidRain999** [sabnzbd/sabnzbd#1586]
2020-08-19 15:24:44,922::ERROR::[_cplogging:213] [19/Aug/2020:15:24:44] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 1795, in serve
    self.tick()
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 2030, in tick
    self.connections.expire()
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "/usr/lib/python3.8/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration

i keep receiving this error every few seconds, i have restarted sabnzbd twice and checked permissions.
it started only a couple days ago at most

it is running on arch-linux current
version sabnzbd is 3.0.1 [9a4be70]

**Comment by AcidRain999** [comment]
i seem to have fixed it by restarting the server. i am not sure what caused it in the first place but it seems to have disappeared for the time being. sorry for making the post

**Comment by Safihre** [comment]
It's this error:
https://github.com/sabnzbd/sabnzbd/issues/1572

The creator of the package should check our `requirements.txt` in which we define a lower version of `cheroot`, because the newer versions have problems.
