### ISSUE TITLE
"SQL Command Failed, see log"

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#1601]
I'm getting this error ("SQL Command Failed, see log") when adding new NZB files. I'm running develop from source, latest version, OpenSUSE Linux Leap 15.2. Logs say that error first appeared yesterday.

Log excerpt when adding test files:

```
2020-09-08 11:34:18,014::INFO::[__init__:560] Fetching https://sabnzbd.org/tests/test_download_100MB.nzb
2020-09-08 11:34:18,029::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:18,031::INFO::[urlgrabber:138] Grabbing URL https://sabnzbd.org/tests/test_download_100MB.nzb
2020-09-08 11:34:18,255::INFO::[__init__:682] Attempting to add test_download_100MB.nzb [/home/abc/.sabnzbd/admin/future/test_download_100MB.nzb]
2020-09-08 11:34:18,255::INFO::[nzbstuff:714] Replacing dots with spaces in test_download_100MB
2020-09-08 11:34:18,256::ERROR::[database:152] SQL Command Failed, see log
2020-09-08 11:34:18,256::INFO::[database:153] SQL: SELECT COUNT(*) FROM History WHERE ( LOWER(name) = LOWER(?) OR md5sum = ? ) AND md5sum = ? AND STATUS != ?
2020-09-08 11:34:18,256::INFO::[database:154] Arguments: ('test_download_100MB', None, 'Failed')
2020-09-08 11:34:18,256::INFO::[database:155] Traceback: 
Traceback (most recent call last):
  File "/home/abc/.sabnzbd/sabnzbd/database.py", line 123, in execute
    self.c.execute(command, args)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 4, and there are 3 supplied.
2020-09-08 11:34:18,300::INFO::[filesystem:577] Creating directories: /data3/sabnzbd/incomplete/test_download_100MB
2020-09-08 11:34:18,302::INFO::[nzbparser:133] File sometestfile-100MB.part1.rar added to queue
2020-09-08 11:34:18,302::INFO::[nzbparser:133] File sometestfile-100MB.part2.rar added to queue
2020-09-08 11:34:18,303::INFO::[nzbparser:133] File sometestfile-100MB.part3.rar added to queue
2020-09-08 11:34:18,303::INFO::[nzbparser:133] File sometestfile-100MB.part4.rar added to queue
2020-09-08 11:34:18,303::INFO::[nzbparser:133] File sometestfile-100MB.part5.rar added to queue
2020-09-08 11:34:18,304::INFO::[nzbparser:133] File sometestfile-100MB.part6.rar added to queue
2020-09-08 11:34:18,304::INFO::[nzbparser:133] File sometestfile-100MB.par2 added to queue
2020-09-08 11:34:18,304::INFO::[nzbparser:133] File sometestfile-100MB.vol000+02.par2 added to queue
2020-09-08 11:34:18,304::INFO::[nzbparser:133] File sometestfile-100MB.vol002+04.par2 added to queue
2020-09-08 11:34:18,305::INFO::[nzbparser:133] File sometestfile-100MB.part7.rar added to queue
2020-09-08 11:34:18,305::INFO::[nzbparser:133] File sometestfile-100MB.vol006+08.par2 added to queue
2020-09-08 11:34:18,305::INFO::[nzbparser:133] File sometestfile-100MB.vol014+16.par2 added to queue
2020-09-08 11:34:18,306::INFO::[nzbparser:133] File sometestfile-100MB.vol030+32.par2 added to queue
2020-09-08 11:34:18,306::INFO::[nzbparser:133] File sometestfile-100MB.vol062+64.par2 added to queue
2020-09-08 11:34:18,306::INFO::[nzbparser:133] File sometestfile-100MB.vol126+74.par2 added to queue
2020-09-08 11:34:18,307::INFO::[__init__:630] Backing up /home/abc/.sabnzbd/nzbbackup/test_download_100MB.nzb.gz
2020-09-08 11:34:18,344::INFO::[__init__:630] Backing up /data3/sabnzbd/incomplete/test_download_100MB/__ADMIN__/test_download_100MB.nzb.gz
2020-09-08 11:34:18,345::WARNING::[nzbstuff:868] Pausing duplicate NZB "test_download_100MB.nzb"
2020-09-08 11:34:18,345::INFO::[nzbqueue:383] [N/A] Removing job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_100MB.nzb
2020-09-08 11:34:18,345::INFO::[nzbstuff:1783] [N/A] Purging data for job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_100MB.nzb (delete_all_data=False)
2020-09-08 11:34:18,345::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:18,346::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:19,438::INFO::[misc:986] [N/A] Running external command: ['/usr/bin/nice', '-n19', '/usr/bin/ionice', '-c3', '/home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py', 'warning', 'SABnzbd: Warning', 'Pausing duplicate NZB "test_download_100MB.nzb"', 'dbus://']
2020-09-08 11:34:19,439::INFO::[misc:986] [N/A] Running external command: ['/usr/bin/nice', '-n19', '/usr/bin/ionice', '-c3', '/home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py', 'error', 'SABnzbd: Error', 'SQL Command Failed, see log', 'dbus://']
2020-09-08 11:34:20,305::INFO::[notifier:376] Successfully executed notification script /home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py
2020-09-08 11:34:20,323::INFO::[notifier:376] Successfully executed notification script /home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py
2020-09-08 11:34:27,648::INFO::[__init__:560] Fetching https://sabnzbd.org/tests/test_download_1000MB.nzb
2020-09-08 11:34:27,723::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:27,724::INFO::[urlgrabber:138] Grabbing URL https://sabnzbd.org/tests/test_download_1000MB.nzb
2020-09-08 11:34:27,977::INFO::[__init__:682] Attempting to add test_download_1000MB.nzb [/home/abc/.sabnzbd/admin/future/test_download_1000MB.nzb]
2020-09-08 11:34:27,978::INFO::[nzbstuff:714] Replacing dots with spaces in test_download_1000MB
2020-09-08 11:34:27,978::ERROR::[database:152] SQL Command Failed, see log
2020-09-08 11:34:27,978::INFO::[database:153] SQL: SELECT COUNT(*) FROM History WHERE ( LOWER(name) = LOWER(?) OR md5sum = ? ) AND md5sum = ? AND STATUS != ?
2020-09-08 11:34:27,978::INFO::[database:154] Arguments: ('test_download_1000MB', None, 'Failed')
2020-09-08 11:34:27,978::INFO::[database:155] Traceback: 
Traceback (most recent call last):
  File "/home/abc/.sabnzbd/sabnzbd/database.py", line 123, in execute
    self.c.execute(command, args)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 4, and there are 3 supplied.
2020-09-08 11:34:27,988::INFO::[filesystem:577] Creating directories: /data3/sabnzbd/incomplete/test_download_1000MB
2020-09-08 11:34:27,994::INFO::[nzbparser:133] File sometestfile-1000MB.part01.rar added to queue
2020-09-08 11:34:27,995::INFO::[nzbparser:133] File sometestfile-1000MB.part02.rar added to queue
2020-09-08 11:34:27,996::INFO::[nzbparser:133] File sometestfile-1000MB.part03.rar added to queue
2020-09-08 11:34:27,996::INFO::[nzbparser:133] File sometestfile-1000MB.part04.rar added to queue
2020-09-08 11:34:27,997::INFO::[nzbparser:133] File sometestfile-1000MB.part05.rar added to queue
2020-09-08 11:34:27,998::INFO::[nzbparser:133] File sometestfile-1000MB.part06.rar added to queue
2020-09-08 11:34:27,999::INFO::[nzbparser:133] File sometestfile-1000MB.part07.rar added to queue
2020-09-08 11:34:27,999::INFO::[nzbparser:133] File sometestfile-1000MB.part08.rar added to queue
2020-09-08 11:34:28,000::INFO::[nzbparser:133] File sometestfile-1000MB.part09.rar added to queue
2020-09-08 11:34:28,001::INFO::[nzbparser:133] File sometestfile-1000MB.part10.rar added to queue
2020-09-08 11:34:28,001::INFO::[nzbparser:133] File sometestfile-1000MB.par2 added to queue
2020-09-08 11:34:28,002::INFO::[nzbparser:133] File sometestfile-1000MB.part11.rar added to queue
2020-09-08 11:34:28,002::INFO::[nzbparser:133] File sometestfile-1000MB.vol000+02.par2 added to queue
2020-09-08 11:34:28,003::INFO::[nzbparser:133] File sometestfile-1000MB.vol002+04.par2 added to queue
2020-09-08 11:34:28,004::INFO::[nzbparser:133] File sometestfile-1000MB.vol006+08.par2 added to queue
2020-09-08 11:34:28,005::INFO::[nzbparser:133] File sometestfile-1000MB.vol014+16.par2 added to queue
2020-09-08 11:34:28,006::INFO::[nzbparser:133] File sometestfile-1000MB.vol030+32.par2 added to queue
2020-09-08 11:34:28,007::INFO::[nzbparser:133] File sometestfile-1000MB.vol062+64.par2 added to queue
2020-09-08 11:34:28,007::INFO::[nzbparser:133] File sometestfile-1000MB.vol126+74.par2 added to queue
2020-09-08 11:34:28,008::INFO::[__init__:630] Backing up /home/abc/.sabnzbd/nzbbackup/test_download_1000MB.nzb.gz
2020-09-08 11:34:28,036::INFO::[__init__:630] Backing up /data3/sabnzbd/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz
2020-09-08 11:34:28,044::WARNING::[nzbstuff:868] Pausing duplicate NZB "test_download_1000MB.nzb"
2020-09-08 11:34:28,045::INFO::[nzbqueue:383] [N/A] Removing job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_1000MB.nzb
2020-09-08 11:34:28,045::INFO::[nzbstuff:1783] [N/A] Purging data for job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_1000MB.nzb (delete_all_data=False)
2020-09-08 11:34:28,045::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:28,046::INFO::[nzbqueue:225] Saving queue
2020-09-08 11:34:28,470::INFO::[misc:986] [N/A] Running external command: ['/usr/bin/nice', '-n19', '/usr/bin/ionice', '-c3', '/home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py', 'warning', 'SABnzbd: Warning', 'Pausing duplicate NZB "test_download_1000MB.nzb"', 'dbus://']
2020-09-08 11:34:28,507::INFO::[misc:986] [N/A] Running external command: ['/usr/bin/nice', '-n19', '/usr/bin/ionice', '-c3', '/home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py', 'error', 'SABnzbd: Error', 'SQL Command Failed, see log', 'dbus://']
2020-09-08 11:34:29,413::INFO::[notifier:376] Successfully executed notification script /home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py
2020-09-08 11:34:29,422::INFO::[notifier:376] Successfully executed notification script `/home/abc/.sabnzbd/scripts/nzbToMedia/sabnzbd-notify.py```

**Comment by Safihre** [comment]
Oops, should have made a unittest. 
Thanks for reporting 💯
