### ISSUE TITLE
sab 3.0.2 -- EOFError: Ran out of input

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1605]
saw user report this, hadnt seen this one before:
```
2020-09-07 05:58:26,497::INFO::[SABnzbd:1132] SABnzbd.py-3.0.2 (rev=<HASH>31d1a56f2777775)
2020-09-07 05:58:26,499::INFO::[SABnzbd:1133] Full executable path = /usr/lib/sabnzbd/SABnzbd.py
2020-09-07 05:58:26,500::INFO::[SABnzbd:1143] Platform = posix
2020-09-07 05:58:26,501::INFO::[SABnzbd:1144] Python-version = 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
2020-09-07 05:58:26,502::INFO::[SABnzbd:1145] Arguments = "/usr/lib/sabnzbd/SABnzbd.py" "--config-file" "/config" "--server" "0.0.0.0:8080" "--https" "8090"
2020-09-07 05:58:26,503::INFO::[SABnzbd:1147] Running inside a docker container
2020-09-07 05:58:26,505::INFO::[SABnzbd:1152] Preferred encoding = UTF-8
2020-09-07 05:58:26,523::INFO::[SABnzbd:1164] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-09-07 05:58:26,525::INFO::[SABnzbd:1219] Using INI file /config/sabnzbd.ini
2020-09-07 05:58:26,527::ERROR::[filesystem:491] Cannot change permissions of /data/Incomplete
2020-09-07 05:58:26,528::INFO::[filesystem:492] Traceback: 
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/sabnzbd/filesystem.py", line 487, in set_chmod
    os.chmod(path, permissions)
PermissionError: [Errno 1] Operation not permitted: '/data/Incomplete'
2020-09-07 05:58:26,544::INFO::[postproc:138] Loading postproc queue
2020-09-07 05:58:26,548::ERROR::[__init__:975] Loading /config/admin/queue10.sab failed
2020-09-07 05:58:26,552::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
EOFError: Ran out of input
```

**Comment by Safihre** [comment]
It seems this can happen if the file is empty or broken.. Not sure what we can do.
