### ISSUE TITLE
repeatedly "ZeroDivisionError: division by zero" from "availability_ratio = 100 * "

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1608]
ZeroDivisionError errors, on git version, like this:

```
2020-09-11 22:54:10,752::DEBUG::[downloader:749] Thread 1@newszilla6.xs4all.nl: Article part1of14.Wa7g8WEQYPlHIIAbzpA0@camelsystem-powerpost.local missing (error=430)
2020-09-11 22:54:10,752::INFO::[nzbstuff:248] <Article: article=part1of14.Wa7g8WEQYPlHIIAbzpA0@camelsystem-powerpost.local, bytes=397314, art_id=None> => missing from all servers, discarding
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sander/git/sjo-sab/sabnzbd/downloader.py", line 775, in run
    self.decode(article, nw.data)
  File "/home/sander/git/sjo-sab/sabnzbd/downloader.py", line 415, in decode
    sabnzbd.nzbqueue.NzbQueue.do.register_article(article, success=False)
  File "/home/sander/git/sjo-sab/sabnzbd/nzbqueue.py", line 745, in register_article
    articles_left, file_done, post_done = nzo.remove_article(article, success)
  File "/home/sander/git/sjo-sab/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/home/sander/git/sjo-sab/sabnzbd/nzbstuff.py", line 1170, in remove_article
    job_can_succeed, _ = self.check_availability_ratio()
  File "/home/sander/git/sjo-sab/sabnzbd/nzbstuff.py", line 1453, in check_availability_ratio
    availability_ratio = 100 * (self.bytes - self.bytes_missing) / (self.bytes - self.bytes_par2)
ZeroDivisionError: division by zero
```

**Comment by sanderjo** [comment]
cause: par2-only nzb, of which the articles are missing on the server(s).

Indeed solved with @Safihre 's patch. :100:
