### ISSUE TITLE
feedparser 6.0.0 breaks SABnzbd startup

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1609]
Just a heads-up guys. Looks like `feedparser` 6.0.0 was [released today](https://pypi.org/project/feedparser/#history) and is breaking my test installs of `SABnzbd` and `Mylar3`. 😞 

I'll add some startup details shortly.

**Comment by OneCDOnly** [comment]
```
[/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd] # /opt/bin/python3 SABnzbd.py --browser 0 
2020-09-13 15:10:36,647::INFO::[SABnzbd:1131] --------------------------------
2020-09-13 15:10:36,648::INFO::[SABnzbd:1132] SABnzbd.py-3.0.2 (rev=51cc7659493b8f98b5da7537831d1a56f2777775)
2020-09-13 15:10:36,649::INFO::[SABnzbd:1133] Full executable path = /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py
2020-09-13 15:10:36,651::INFO::[SABnzbd:1143] Platform = posix
2020-09-13 15:10:36,652::INFO::[SABnzbd:1144] Python-version = 3.8.3 (default, Jun 12 2020, 20:24:48) 
[GCC 8.4.0]
2020-09-13 15:10:36,653::INFO::[SABnzbd:1145] Arguments = "SABnzbd.py" "--browser" "0"
2020-09-13 15:10:36,654::INFO::[SABnzbd:1149] Not inside a docker container
2020-09-13 15:10:36,656::INFO::[SABnzbd:1152] Preferred encoding = UTF-8
2020-09-13 15:10:36,657::INFO::[SABnzbd:1164] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-09-13 15:10:36,663::INFO::[SABnzbd:1173] Certifi version: 2020.04.05.1
2020-09-13 15:10:36,664::INFO::[SABnzbd:1174] Loaded additional certificates from: /opt/lib/python3.8/site-packages/certifi/cacert.pem
2020-09-13 15:10:36,665::INFO::[SABnzbd:1219] Using INI file /root/.sabnzbd/sabnzbd.ini
2020-09-13 15:10:36,667::INFO::[filesystem:305] download_dir directory: /root/Downloads/incomplete does not exist, try to create it
2020-09-13 15:10:36,668::INFO::[filesystem:558] Creating directories: /root/Downloads/incomplete
2020-09-13 15:10:36,696::INFO::[config:857] Writing settings to INI file /root/.sabnzbd/sabnzbd.ini
2020-09-13 15:10:36,721::INFO::[__init__:955] [N/A] /root/.sabnzbd/admin/rss_data.sab missing
Traceback (most recent call last):
  File "SABnzbd.py", line 1721, in <module>
    main()
  File "SABnzbd.py", line 1224, in main
    sabnzbd.initialize(pause, clean_up, evalSched=True, repair=repair)
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 323, in initialize
    rss.init()
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/rss.py", line 48, in init
    __RSS = RSSQueue()
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/rss.py", line 209, in __init__
    patch_feedparser()
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/rss.py", line 648, in patch_feedparser
    feedparser._FeedParserMixin.namespaces["http://www.newznab.com/DTD/2010/feeds/attributes/"] = "newznab"
AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```

**Comment by Safihre** [comment]
Feedparser 6.0.0 is supported from SABnzbd 3.1.x (current develop branch), unfortunately it's now too late to change the requirements file for 3.0.2 to specify it doesn't.

**Comment by OneCDOnly** [comment]
No worries. Thanks @Safihre 

Should we close this issue then?

**Comment by Safihre** [comment]
Updated the `requirements.txt` of `master` and `3.0.x` branches.
