### ISSUE TITLE
RAR5 archive with subfolder including several nzb's can't read password in {{ }}

### ISSUE THREAD

**Issue by PeterCodar** [sabnzbd/sabnzbd#1619]
The attached RAR5 archive contains 12 nzbs in a subfolder.
SABnzbd (on Synology NAS) can't read the password in curly brackets.
(The password is available for the RAR-archive itself, for the subfolder and every NZB)

```
 [23/Sep/2020:10:03:00] HTTP 
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 446, in api
    return api_handler(kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 142, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 368, in _api_addfile
    nzbname=kwargs.get("nzbname"),
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/__init__.py", line 714, in add_nzbfile
    nzo_id=nzo_id,
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/nzbparser.py", line 203, in process_nzb_archive_file
    data = correct_unknown_encoding(zf.read(name))
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 815, in read
    with self.open(fname, "r", psw) as f:
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 796, in open
    raise PasswordRequired("File %s requires password" % inf.filename)
sabnzbd.utils.rarfile.PasswordRequired: File THE REAL MCKENZIES - DISKOGRAFIE 1995 - 2020 {{MONSTAkilla86_2020}}/1995 - The Real Mckenzies {{MONSTAkilla86_2020}}.nzb requires password
```

The attachment is renamed with .REMOVE.ZIP because github doesn't allow RAR uploads.
Please delete .REMOVE.ZIP to get the original RAR archive.
[THE REAL MCKENZIES - DISKOGRAFIE 1995 - 2020 {{MONSTAkilla86_2020}}.rar.REMOVE.ZIP](https://github.com/sabnzbd/sabnzbd/files/5266563/THE.REAL.MCKENZIES.-.DISKOGRAFIE.1995.-.2020.MONSTAkilla86_2020.rar.REMOVE.ZIP)

**Comment by Safihre** [comment]
It took me a bit to understand exactly what you mean, but the RAR that contains the NZB's is actually encrypted.
This is not something we support: we only support supplying passwords to unpack the stuff that we download, not the archive used to add the NZB's. 
We could add this, but I see limited use cases: users can just unpack the file first and then add the NZB's directly.

**Comment by PeterCodar** [comment]
> We could add this, but I see limited use cases: users can just unpack the file first and then add the NZB's directly.

I see your point. 

Maybe a more obvious hint would already help? Something like 
**Archive is password protected, please unpack it manually**?
instead of the very long error message?
