### ISSUE TITLE
traceback "socket.gaierror: [Errno 11001] getaddrinfo failed"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1621]
I got the traceback below with SAB 3.1.0RC1 on Windows. I don't know the cause (network not yet up, other temp problem?), but I find the Error in the GUI annoying and not necessary.

![image](https://user-images.githubusercontent.com/1273502/94111473-69886880-fe44-11ea-8d4f-039ef0d61418.png)

```
2020-09-24 08:10:39,481::INFO::[rss:558] Starting scheduled RSS read-out for "mini-1940-vrijdag"
2020-09-24 08:10:39,481::DEBUG::[rss:286] Running feedparser on https://www.appelboor.com/dump/rss-mini-1940
2020-09-24 08:10:39,779::ERROR::[kronos:315] ERROR DURING SCHEDULER EXECUTION <urlopen error [Errno 11001] getaddrinfo failed>
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "http\client.py", line 1417, in connect
  File "http\client.py", line 921, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sabnzbd\utils\kronos.py", line 300, in __call__
  File "sabnzbd\utils\kronos.py", line 311, in execute
  File "sabnzbd\rss.py", line 88, in run_method
  File "sabnzbd\rss.py", line 560, in run
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\rss.py", line 287, in run_feed
  File "feedparser\api.py", line 214, in parse
  File "feedparser\api.py", line 114, in _open_resource
  File "feedparser\http.py", line 158, in get
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1393, in https_open
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
2020-09-24 08:10:40,365::INFO::[notifier:122] Sending notification: Error - ERROR DURING SCHEDULER EXECUTION <urlopen error [Errno 11001] getaddrinfo failed> (type=error, job_cat=None)
```

**Comment by sanderjo** [comment]
Ah, I can reproduce: turn off network, in RSS click on Read Feed, wait half a minute or so ... and bingo:

![image](https://user-images.githubusercontent.com/1273502/94116535-78264e00-fe4b-11ea-9d78-1de0d89f4352.png)


I think this should just be a warning. Not a big fat red error in the GUI.

**Comment by Safihre** [comment]
Scheduler handling is a bit ugly, to say it mildly. But it works..
Only recently with my typing efforts I really looked at the scheduler code, and just like `rating.py`, it discouraged me too much to try and improve it.. Would probably just have to refactor the whole thing.

**Comment by Safihre** [comment]
I see, it is feedparser that changed. Sigh.
It used to just handle bad fetches, now it seems it just throws them at us.

**Comment by Safihre** [comment]
Upstream: kurtmckee/feedparser/issues/239

**Comment by sanderjo** [comment]
> I see, it is feedparser that changed.

I'm still on feedparser 5.2.1:

```
>>> feedparser.__version__
'5.2.1'
```

**Comment by Safihre** [comment]
From your Traceback, that's impossible. Because version 5 feedparser was all in 1 file `feedparser.py`. While in your Traceback there is `api.py` and `http.py` which are part of version 6.

**Comment by sanderjo** [comment]
Oh, wait, sorry: that was on Windows, so with the SAB-exe 3.1.0 RC1 ... is that built with feedparser version 6 ?
