### ISSUE TITLE
sabnzbd latest develop version 3.2.0 still won't start

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#1625]
Re #1624: After updating to https://github.com/sabnzbd/sabnzbd/commit/3ae2cbcd2c2e3547e345f5418fdd7b57c527464e, sabnzbd still won't start.

From file sabnzbd.log after having updated to the currently latest commit and trying to start sabnzbd:

```
2020-09-27 11:26:24,516::INFO::[SABnzbd:1142] --------------------------------
2020-09-27 11:26:24,518::INFO::[SABnzbd:1143] SABnzbd.py-3.2.0-develop (rev=unknown)
2020-09-27 11:26:24,521::INFO::[SABnzbd:1144] Full executable path = /home/abc/.sabnzbd/SABnzbd.py
2020-09-27 11:26:24,531::INFO::[SABnzbd:1154] Platform = posix
2020-09-27 11:26:24,532::INFO::[SABnzbd:1155] Python-version = 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC]
2020-09-27 11:26:24,533::INFO::[SABnzbd:1156] Arguments = "/home/abc/.sabnzbd/SABnzbd.py" "-d" "-f" "/home/abc/.sabnzbd/sabnzbd.ini"
2020-09-27 11:26:24,534::INFO::[SABnzbd:1160] Not inside a docker container
2020-09-27 11:26:24,534::INFO::[SABnzbd:1163] Preferred encoding = UTF-8
2020-09-27 11:26:24,534::INFO::[SABnzbd:1175] SSL version = OpenSSL 1.1.0i-fips  14 Aug 2018
2020-09-27 11:26:24,547::INFO::[SABnzbd:1184] Certifi version: 2018.01.18
2020-09-27 11:26:24,550::INFO::[SABnzbd:1185] Loaded additional certificates from: /etc/ssl/ca-bundle.pem
2020-09-27 11:26:24,550::INFO::[SABnzbd:1230] Using INI file /home/abc/.sabnzbd/sabnzbd.ini
2020-09-27 11:26:24,569::INFO::[postproc:135] Loading postproc queue
```

From file sabnzbd.error.log after having updated to the currently latest commit and trying to start sabnzbd:

```
Traceback (most recent call last):
  File "/home/abc/.sabnzbd/SABnzbd.py", line 1733, in <module>
    main()
  File "/home/abc/.sabnzbd/SABnzbd.py", line 1235, in main
    sabnzbd.initialize(pause, clean_up, evaluate_schedules=True, repair=repair)
  File "/home/abc/.sabnzbd/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/home/abc/.sabnzbd/sabnzbd/__init__.py", line 342, in initialize
    scheduler.init()
  File "/home/abc/.sabnzbd/sabnzbd/scheduler.py", line 125, in init
    action = sabnzbd.rss.run_method
AttributeError: module 'sabnzbd.rss' has no attribute 'run_method'
```

**Comment by Safihre** [comment]
Sorry about that, should work now!

**Comment by anonvoy** [comment]
It does. Thanks.
