### ISSUE TITLE
RSS GUI stuff "UnboundLocalError: local variable 'msg' referenced before assignment"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1634]
In the SAB GUI, when clicking around in the RSS, I now and then get the error below. Once it has happened, any click in the RSS settings results in it.

3.1.0RC3 [6aef50d]

![image](https://user-images.githubusercontent.com/1273502/95653975-f4cc5400-0afc-11eb-8317-d689e73fac78.png)

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 136, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1780, in index
    msg = sabnzbd.rss.run_feed(
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 65, in run_feed
    return __RSS.run_feed(feed, download, ignoreFirst, force=force, readout=readout)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 550, in run_feed
    return msg
UnboundLocalError: local variable 'msg' referenced before assignment
Powered by CherryPy 8.9.1
```

**Comment by sanderjo** [comment]
from sabnzbd.log / stdout, right after my clock on any RSS feed name:

```
2020-10-10 13:46:07,106::DEBUG::[interface:1774] RSS READOUT = False
2020-10-10 13:46:07,106::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [95/95] "42298498389c49d1ba0b9e63ded323c4.vol063+059.par2" yEnc
2020-10-10 13:46:07,107::DEBUG::[rss:403] Size 233935303
2020-10-10 13:46:07,107::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,108::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [94/95] "42298498389c49d1ba0b9e63ded323c4.vol031+032.par2" yEnc
2020-10-10 13:46:07,108::DEBUG::[rss:403] Size 126992480
2020-10-10 13:46:07,108::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,109::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [93/95] "42298498389c49d1ba0b9e63ded323c4.vol015+016.par2" yEnc
2020-10-10 13:46:07,109::DEBUG::[rss:403] Size 63567245
2020-10-10 13:46:07,110::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,110::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [92/95] "42298498389c49d1ba0b9e63ded323c4.vol007+008.par2" yEnc
2020-10-10 13:46:07,110::DEBUG::[rss:403] Size 31832565
2020-10-10 13:46:07,111::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,111::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [90/95] "42298498389c49d1ba0b9e63ded323c4.vol001+002.par2" yEnc
2020-10-10 13:46:07,112::DEBUG::[rss:403] Size 7970060
2020-10-10 13:46:07,112::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,112::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [91/95] "42298498389c49d1ba0b9e63ded323c4.vol003+004.par2" yEnc
2020-10-10 13:46:07,113::DEBUG::[rss:403] Size 15940265
2020-10-10 13:46:07,113::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,114::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [88/95] "42298498389c49d1ba0b9e63ded323c4.par2" yEnc
2020-10-10 13:46:07,114::DEBUG::[rss:403] Size 48749
2020-10-10 13:46:07,114::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,115::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [89/95] "42298498389c49d1ba0b9e63ded323c4.vol000+001.par2" yEnc
2020-10-10 13:46:07,115::DEBUG::[rss:403] Size 4009627
2020-10-10 13:46:07,116::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,116::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [87/95] "42298498389c49d1ba0b9e63ded323c4.7z.087" yEnc
2020-10-10 13:46:07,116::DEBUG::[rss:403] Size 43049551
2020-10-10 13:46:07,116::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,117::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [86/95] "42298498389c49d1ba0b9e63ded323c4.7z.086" yEnc
2020-10-10 13:46:07,117::DEBUG::[rss:403] Size 55483096
2020-10-10 13:46:07,117::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,117::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [85/95] "42298498389c49d1ba0b9e63ded323c4.7z.085" yEnc
2020-10-10 13:46:07,117::DEBUG::[rss:403] Size 55448892
2020-10-10 13:46:07,117::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,117::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [84/95] "42298498389c49d1ba0b9e63ded323c4.7z.084" yEnc
2020-10-10 13:46:07,118::DEBUG::[rss:403] Size 55448791
2020-10-10 13:46:07,118::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,118::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [83/95] "42298498389c49d1ba0b9e63ded323c4.7z.083" yEnc
2020-10-10 13:46:07,118::DEBUG::[rss:403] Size 55448864
2020-10-10 13:46:07,118::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,118::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [82/95] "42298498389c49d1ba0b9e63ded323c4.7z.082" yEnc
2020-10-10 13:46:07,118::DEBUG::[rss:403] Size 55448432
2020-10-10 13:46:07,119::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,119::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [81/95] "42298498389c49d1ba0b9e63ded323c4.7z.081" yEnc
2020-10-10 13:46:07,119::DEBUG::[rss:403] Size 55448941
2020-10-10 13:46:07,119::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,119::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [80/95] "42298498389c49d1ba0b9e63ded323c4.7z.080" yEnc
2020-10-10 13:46:07,119::DEBUG::[rss:403] Size 55447602
2020-10-10 13:46:07,119::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,119::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [79/95] "42298498389c49d1ba0b9e63ded323c4.7z.079" yEnc
2020-10-10 13:46:07,120::DEBUG::[rss:403] Size 55447537
2020-10-10 13:46:07,120::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,120::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [78/95] "42298498389c49d1ba0b9e63ded323c4.7z.078" yEnc
2020-10-10 13:46:07,120::DEBUG::[rss:403] Size 55448883
2020-10-10 13:46:07,120::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,120::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [77/95] "42298498389c49d1ba0b9e63ded323c4.7z.077" yEnc
2020-10-10 13:46:07,120::DEBUG::[rss:403] Size 55448524
2020-10-10 13:46:07,120::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,121::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [76/95] "42298498389c49d1ba0b9e63ded323c4.7z.076" yEnc
2020-10-10 13:46:07,121::DEBUG::[rss:403] Size 55448799
2020-10-10 13:46:07,121::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,121::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [75/95] "42298498389c49d1ba0b9e63ded323c4.7z.075" yEnc
2020-10-10 13:46:07,121::DEBUG::[rss:403] Size 55448620
2020-10-10 13:46:07,121::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,121::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [74/95] "42298498389c49d1ba0b9e63ded323c4.7z.074" yEnc
2020-10-10 13:46:07,121::DEBUG::[rss:403] Size 55447748
2020-10-10 13:46:07,122::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,122::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [73/95] "42298498389c49d1ba0b9e63ded323c4.7z.073" yEnc
2020-10-10 13:46:07,122::DEBUG::[rss:403] Size 55446679
2020-10-10 13:46:07,122::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,122::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [72/95] "42298498389c49d1ba0b9e63ded323c4.7z.072" yEnc
2020-10-10 13:46:07,122::DEBUG::[rss:403] Size 55448120
2020-10-10 13:46:07,122::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,122::DEBUG::[rss:392] Trying title 42298498389c49d1ba0b9e63ded323c4 [71/95] "42298498389c49d1ba0b9e63ded323c4.7z.071" yEnc
2020-10-10 13:46:07,123::DEBUG::[rss:403] Size 55448640
2020-10-10 13:46:07,123::DEBUG::[rss:446] Filter matched on rule 0
2020-10-10 13:46:07,123::ERROR::[_cplogging:219] [10/Oct/2020:13:46:07] HTTP
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 136, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1780, in index
    msg = sabnzbd.rss.run_feed(
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 65, in run_feed
    return __RSS.run_feed(feed, download, ignoreFirst, force=force, readout=readout)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 550, in run_feed
    return msg
UnboundLocalError: local variable 'msg' referenced before assignment
2020-10-10 13:46:07,124::INFO::[_cplogging:219] [10/Oct/2020:13:46:07] HTTP
Request Headers:
  Remote-Addr: 192.168.1.92
  HOST: 192.168.1.4:8080
  CONNECTION: keep-alive
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  REFERER: http://192.168.1.4:8080/config/rss/
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6
2020-10-10 13:46:10,030::INFO::[notifier:122] Sending notification: Error - [10/Oct/2020:13:46:07] HTTP  (type=error, job_cat=None)
```
