### ISSUE TITLE
Traceback "sabnzbd.utils.rarfile.BadRarFile: cannot load le32"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1681]
After the tracebacks of https://github.com/sabnzbd/sabnzbd/issues/1680 , I got some of these:
```
2020-11-17 19:57:49,627::INFO::[assembler:360] Error during inspection of RAR-file /home/sander/Downloads/incomplete/Der.Lok/d47ccde0406d409691da.part42.rar
2020-11-17 19:57:49,627::DEBUG::[assembler:361] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sjo-sab/sabnzbd/assembler.py", line 290, in check_encrypted_and_unwanted_files
    zf = rarfile.RarFile(filepath, single_file_check=True)
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 708, in __init__
    self._parse()
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 917, in _parse
    self._file_parser.parse()
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 1028, in parse
    self._parse_real()
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 1052, in _parse_real
    h = self._parse_header(fd)
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 1134, in _parse_header
    return self._parse_block_header(fd)
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 1675, in _parse_block_header
    header_crc, pos = load_le32(start_bytes, 0)
  File "/home/sander/git/sjo-sab/sabnzbd/utils/rarfile.py", line 2644, in load_le32
    raise BadRarFile("cannot load le32")
sabnzbd.utils.rarfile.BadRarFile: cannot load le32
```
Not the same as https://github.com/sabnzbd/sabyenc/issues/14 AFAIK

So ... leave it like this? Or make it a Warning/Debug?

**Comment by Safihre** [comment]
This is also for diagnostic purposes, because Rarfile can throw many errors and it's worth seeing them for developers. Soon we will replace our own version with the official one (because he included our patches), so this will still be of Debug value.
