### ISSUE TITLE
RSS Index out of range

### ISSUE THREAD

**Issue by 4np** [sabnzbd/sabnzbd#1725]
Just ran into this index out of range exception:

`3.1.1-46` on `Synology`.

```
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 136, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 1815, in index
    return template.respond()
  File "_volume1__appstore_sabnzbd_share_SABnzbd_interfaces_Config_templates_config_rss_tmpl.py", line 1213, in respond
IndexError: list index out of range
```

I have seen these before although I'm not sure when these happen. I do see some nzb failures so I suspect these might have triggered it.

**Comment by Safihre** [comment]
This is the whole traceback?
I can imagine this happens when the RSS feed is read while it is being updated. Is that possible to see in the logs if a readout was happening at the same time?

**Comment by 4np** [comment]
Yeah this is the whole trace I saw in the UI. Looks like the RSS was indeed being updated.

```log
2020-12-26 11:33:27,100::INFO::[nzbqueue:231] Saving queue
2020-12-26 11:33:27,147::INFO::[notifier:122] Sending notification: NZB added to queue - foo.nzb (type=download, job_cat=tv)
2020-12-26 11:33:27,928::INFO::[assembler:114] Decoding finished /volume1/downloads/incomplete/bar.rar
2020-12-26 11:33:36,994::INFO::[config:857] Writing settings to INI file /volume1/@appstore/sabnzbd/var/config.ini
2020-12-26 11:33:36,807::ERROR::[_cplogging:216] [26/Dec/2020:11:33:36] HTTP
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 136, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 1815, in index
    return template.respond()
  File "_volume1__appstore_sabnzbd_share_SABnzbd_interfaces_Config_templates_config_rss_tmpl.py", line 1213, in respond
IndexError: list index out of range
2020-12-26 11:33:37,139::INFO::[_cplogging:216] [26/Dec/2020:11:33:37] HTTP
Request Headers:
  Remote-Addr: 1.2.3.4
  HOST: some.host.com
  X-REAL-IP: 2.3.4.5
  X-FORWARDED-FOR: 2.3.4.5
  X-FORWARDED-PROTO: https
  CONNECTION: close
  ACCEPT: */*
  ACCEPT-ENCODING: gzip, deflate, br
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
  ACCEPT-LANGUAGE: en-us
  REFERER: https://some.host.com/config/rss/?feed=somefeed
  X-REQUESTED-WITH: XMLHttpRequest
2020-12-26 11:33:38,376::INFO::[notifier:122] Sending notification: Error - [26/Dec/2020:11:33:36] HTTP  (type=error, job_cat=None)
```

**Comment by Safihre** [comment]
Alright, so no downloading was active.
Can you reproduce it? I clicked a lot through the RSS interface but I cannot reproduce it so far.

**Comment by 4np** [comment]
Not really 🤷🏻‍♂️ I have seen it before but perhaps when I was updating RSS feeds while it was busy updating feeds in the background?
