### ISSUE TITLE
Exception when calling article.nzf.nzo.update_download_stats because article.nzf was deleted

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1728]
This has happened at least a couple of times today. It was a coincidence that I noticed because it wasn't logged, but I have a long scroll back. It caused a crash and restart. Both times it was right after a download was finished. I assume it had time to delete it while the bandwidth limiter was sleeping. Not sure what a good way to fix it would be. Maybe do the update before the loop, or put the bandwidth loop after the `for selected in read:` loop?

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\t\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\git\sabnzbd\sabnzbd\downloader.py", line 639, in run
    article.nzf.nzo.update_download_stats(sabnzbd.BPSMeter.bps, server.id, bytes_received)
AttributeError: 'NoneType' object has no attribute 'nzf'

This is the line:
https://github.com/sabnzbd/sabnzbd/blob/5df4a76367fba92756c2c3dba50c3c5126f5dfb0/sabnzbd/downloader.py#L639

**Comment by puzzledsab** [comment]
Having thought about it I think the best solution is to move the update above the delay loop or get the nzo reference before the loop.
