### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by ThisLimn0** [sabnzbd/sabnzbd#1729]
On  Version 3.1.1 [99b5a00]

whenever i try to repair some broken downloads manually three out of four times this is being written in the error log between the queue and history.

What details can i provide you with to help resolve this?

 [31/Dec/2020:04:14:15] HTTP 
Traceback (most recent call last):
  File "cherrypy\_cprequest.py", line 638, in respond
  File "cherrypy\_cprequest.py", line 697, in _do_respond
  File "cherrypy\lib\encoding.py", line 219, in __call__
  File "cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 447, in api
  File "sabnzbd\api.py", line 139, in api_handler
  File "sabnzbd\api.py", line 720, in _api_retry_all
  File "sabnzbd\api.py", line 1505, in retry_all_jobs
  File "sabnzbd\api.py", line 1490, in retry_job
  File "sabnzbd\nzbqueue.py", line 196, in repair_job
IndexError: list index out of range

**Comment by Safihre** [comment]
You could have provided a little more information than just dumping a stack trace here 🙃

**Comment by ThisLimn0** [comment]
Lol sorry dude, was drunk when i submitted that. Edited now.

**Comment by jcfp** [comment]
Looks similar to #1649 fixed in https://github.com/sabnzbd/sabnzbd/commit/09e844a63fef3426659b80336979ba58a8c8dfa6 ?

**Comment by puzzledsab** [comment]
I think it has been fixed. Line 196 in master is `nzo_id = nzo_ids[0]`, which is no longer called without a check.

**Comment by Safihre** [comment]
Indeed fixed in next release!
