### ISSUE TITLE
3.2.0b1 - pause test_download

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1741]
noticed when running the speed test, you can not pause it (but acts like you should, and can pause it if you use the global pause):
![sab](http://zoggy.net/firefox_2021-01-03_18-14-02.png)

guessing this is byproduct of 'forced' priority being used?

**Comment by Safihre** [comment]
Indeed the same behavior as force priority.

**Comment by Cpuroast** [comment]
As far as I know, force priority bypasses local and global pause by design.

**Comment by thezoggy** [comment]
side note, when deleting speed test job I see it do traceback:
```
2021-01-03 18:14:09,698::INFO::[filesystem:831] Cannot remove folder \\?\C:\Users\zoggy\downloads\complete\_UNPACK_test_download_10GB
Traceback (most recent call last):
  File "sabnzbd\filesystem.py", line 829, in remove_all
  File "shutil.py", line 740, in rmtree
  File "shutil.py", line 618, in _rmtree_unsafe
  File "shutil.py", line 616, in _rmtree_unsafe
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\C:\\Users\\zoggy\\downloads\\complete\\_UNPACK_test_download_10GB\\sometestfile-10GB.bin'
2021-01-03 18:14:09,698::DEBUG::[articlecache:149] Purging 76 articles from the cache/disk
```
