### ISSUE TITLE
ENGINE Error in HTTPServer.tick on MacOS

### ISSUE THREAD

**Issue by r33mi** [sabnzbd/sabnzbd#1743]
Frequently getting this error:
```
[06/Jan/2021:17:59:16] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "cheroot/server.py", line 1788, in serve
  File "cheroot/server.py", line 2023, in tick
  File "cheroot/connections.py", line 185, in get_conn
  File "cheroot/connections.py", line 204, in _from_server_socket
  File "cheroot/ssl/builtin.py", line 277, in wrap
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1019, in _create
OSError: [Errno 22] Invalid argument
```
Can't find the problem

**Comment by Safihre** [comment]
Interesting, never seen this one and neither has Google 🤔
Any way to reproduce?

**Comment by r33mi** [comment]
Can’t reproduce myself but comes up every few days...

**Comment by r33mi** [comment]
Also getting this one:

06/Jan/2021:20:36:31] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "cheroot/server.py", line 1788, in serve
  File "cheroot/server.py", line 2023, in tick
  File "cheroot/connections.py", line 185, in get_conn
  File "cheroot/connections.py", line 204, in _from_server_socket
  File "cheroot/ssl/builtin.py", line 277, in wrap
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1124)

**Comment by sanderjo** [comment]
`ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1124)`

That is a well-known one. Checking: you have HTTPS enabled on SABnzbd, and your SABnzbd is reachable from Internet ... correct?

If so: the error is caused by port scanners with incorrect / low-version SSL. The framework cherrypy reports it with a traceback, which IMHO is quite unuseful.

**Comment by r33mi** [comment]
> `ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1124)`
> 
> That is a well-known one. Checking: you have HTTPS enabled on SABnzbd, and your SABnzbd is reachable from Internet ... correct?
> 
> If so: the error is caused by port scanners with incorrect / low-version SSL. The framework cherrypy reports it with a traceback, which IMHO is quite unuseful.

Yes that's correct, then I leave that one for what it is. The other one is weird though: 

> 06/Jan/2021:20:36:31] ENGINE Error in HTTPServer.tick
> Traceback (most recent call last):
> File "cheroot/server.py", line 1788, in serve
> File "cheroot/server.py", line 2023, in tick
> File "cheroot/connections.py", line 185, in get_conn
> File "cheroot/connections.py", line 204, in _from_server_socket
> File "cheroot/ssl/builtin.py", line 277, in wrap
> File "ssl.py", line 500, in wrap_socket
> File "ssl.py", line 1040, in _create
> File "ssl.py", line 1309, in do_handshake
> ssl.SSLError: [SSL: VERSION_TOO_LOW] version too low (_ssl.c:1124)

**Comment by sanderjo** [comment]
One more check: SABnzbd is reachable via port 8080 or another well-known port. Correct?

If so, if you can put it on a less-used port (like 43210 or 24680), the scanners will probably not find you anymore, and thus no more tracebacks ...

**Comment by r33mi** [comment]
Changed the port, I'll keep an eye on it for a week or so and see if it's gone. Thanks!

**Comment by r33mi** [comment]
No more errors since changing the port!
