### ISSUE TITLE
3.2 b1 won't start on macOS

### ISSUE THREAD

**Issue by ItchyData** [sabnzbd/sabnzbd#1747]
The app doesn't seem to want to launch on Big Sur. Log is below. I can't seem to go back to 3.1.1 either.

I wasn't having any trouble with 3.1.1 until I tried the beta. 

```
2021-01-09 19:30:30,682::INFO::[SABnzbd:1142] --------------------------------
2021-01-09 19:30:30,683::INFO::[SABnzbd:1143] SABnzbd-3.2.0Beta1
2021-01-09 19:30:30,683::INFO::[SABnzbd:1153] Commit: c2a89731c91c1041adefdc5cbdcb3fce27d3109b
2021-01-09 19:30:30,683::INFO::[SABnzbd:1154] Full executable path = /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
2021-01-09 19:30:30,683::INFO::[SABnzbd:1164] Platform = posix
2021-01-09 19:30:30,683::INFO::[SABnzbd:1165] Python-version = 3.9.1 (default, Dec  8 2020, 21:56:20) 
[Clang 11.0.0 (clang-1100.0.33.17)]
2021-01-09 19:30:30,683::INFO::[SABnzbd:1166] Arguments = "/Applications/SABnzbd.app/Contents/MacOS/SABnzbd"
2021-01-09 19:30:30,683::INFO::[SABnzbd:1170] Not inside a docker container
2021-01-09 19:30:30,683::INFO::[SABnzbd:1173] Preferred encoding = UTF-8
2021-01-09 19:30:30,684::INFO::[SABnzbd:1185] SSL version = OpenSSL 1.1.1i  8 Dec 2020
2021-01-09 19:30:30,684::INFO::[SABnzbd:1194] Certifi version: 2020.12.05
2021-01-09 19:30:30,684::INFO::[SABnzbd:1195] Loaded additional certificates from: /Applications/SABnzbd.app/Contents/MacOS/certifi/cacert.pem
2021-01-09 19:30:30,684::INFO::[SABnzbd:1237] Using INI file /Users/greg/Library/Application Support/SABnzbd/sabnzbd.ini
2021-01-09 19:30:30,802::INFO::[postproc:139] Loading postproc queue
2021-01-09 19:30:30,837::INFO::[scheduler:188] Scheduling RSS interval task every 60 min (delay=23)
2021-01-09 19:30:30,837::INFO::[scheduler:199] Scheduling VersionCheck on day 7 at 19:54
2021-01-09 19:30:30,837::INFO::[scheduler:213] Setting schedule for midnight BPS reset
2021-01-09 19:30:30,838::INFO::[__init__:333] All processes started
2021-01-09 19:30:30,838::INFO::[SABnzbd:303] Template location for Glitter is /Applications/SABnzbd.app/Contents/MacOS/interfaces/Glitter
2021-01-09 19:30:30,838::INFO::[SABnzbd:303] Template location for Config is /Applications/SABnzbd.app/Contents/MacOS/interfaces/Config
2021-01-09 19:30:30,839::INFO::[SABnzbd:397] SABYenc module (v4.0.2)... found!
2021-01-09 19:30:30,839::INFO::[SABnzbd:416] Cryptography module (v3.3.1)... found!
2021-01-09 19:30:30,839::INFO::[SABnzbd:421] par2 binary... found (/Applications/SABnzbd.app/Contents/MacOS/osx/par2/par2-sl64)
2021-01-09 19:30:30,839::INFO::[SABnzbd:428] UNRAR binary... found (/Applications/SABnzbd.app/Contents/MacOS/osx/unrar/unrar)
2021-01-09 19:30:30,839::INFO::[SABnzbd:446] 7za binary... found (/Applications/SABnzbd.app/Contents/MacOS/osx/7zip/7za)
2021-01-09 19:30:30,839::INFO::[SABnzbd:457] nice binary... found (/usr/bin/nice)
2021-01-09 19:30:30,839::INFO::[SABnzbd:463] ionice binary... NOT found!
2021-01-09 19:30:30,840::INFO::[SABnzbd:1424] Starting web-interface on 0.0.0.0:8080
2021-01-09 19:30:30,840::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Bus STARTING
2021-01-09 19:30:30,943::INFO::[notifier:122] Sending notification: Error - [09/Jan/2021:19:30:30] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x10d07df70>>
Traceback (most recent call last):
  File "cherrypy/process/wspbus.py", line 230, in publish
  File "cherrypy/_cpserver.py", line 180, in start
  File "cherrypy/process/servers.py", line 184, in start
  File "cherrypy/process/servers.py", line 260, in wait
  File "portend.py", line 160, in occupied
  File "portend.py", line 71, in assert_free
  File "portend.py", line 82, in _connect
  File "contextlib.py", line 303, in __exit__
  File "socket.py", line 501, in close
  File "socket.py", line 495, in _real_close
OSError: [Errno 41] Protocol wrong type for socket
 (type=error, job_cat=None)
2021-01-09 19:30:30,943::ERROR::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x10d07df70>>
Traceback (most recent call last):
  File "cherrypy/process/wspbus.py", line 230, in publish
  File "cherrypy/_cpserver.py", line 180, in start
  File "cherrypy/process/servers.py", line 184, in start
  File "cherrypy/process/servers.py", line 260, in wait
  File "portend.py", line 160, in occupied
  File "portend.py", line 71, in assert_free
  File "portend.py", line 82, in _connect
  File "contextlib.py", line 303, in __exit__
  File "socket.py", line 501, in close
  File "socket.py", line 495, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

2021-01-09 19:30:30,944::INFO::[notifier:122] Sending notification: Error - [09/Jan/2021:19:30:30] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "cherrypy/process/wspbus.py", line 268, in start
  File "cherrypy/process/wspbus.py", line 248, in publish
cherrypy.process.wspbus.ChannelFailures: OSError(41, 'Protocol wrong type for socket')
 (type=error, job_cat=None)
2021-01-09 19:30:30,944::ERROR::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "cherrypy/process/wspbus.py", line 268, in start
  File "cherrypy/process/wspbus.py", line 248, in publish
cherrypy.process.wspbus.ChannelFailures: OSError(41, 'Protocol wrong type for socket')

2021-01-09 19:30:30,945::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Bus STOPPING
2021-01-09 19:30:30,945::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) already shut down
2021-01-09 19:30:30,945::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Bus STOPPED
2021-01-09 19:30:30,945::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Bus EXITING
2021-01-09 19:30:30,945::INFO::[_cplogging:213] [09/Jan/2021:19:30:30] ENGINE Bus EXITED
```

**Comment by Safihre** [comment]
Seems maybe something else is already on that port. This doesn't seem version specific.
Try a restart and make sure to just start the application once. Otherwise maybe change the port in sabnzbd.ini.

**Comment by Safihre** [comment]
Seems like a Python/macOS bug: https://bugs.python.org/issue33450

**Comment by ItchyData** [comment]
Did some more testing, and it's occurring because Adguard Desktop is enabled. Turrning Adguard off, starting SAB, then enabling Adguard again resolves the issue.
