### ISSUE TITLE
3.3.0 Beta2: clicking on "Read All Feeds Now" results in 500 Internal Server Error & Traceback

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1865]
3.3.0 Beta2: clicking on "Read All Feeds Now" results in 500 Internal Server Error on page http://127.0.0.1:8080/sabnzbd/config/rss/?feed=None

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.


Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/sjo-sab/sabnzbd/interface.py", line 172, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/home/sander/git/sjo-sab/sabnzbd/interface.py", line 1856, in index
    return template.respond()
  File "_home_sander_git_sjo_sab_interfaces_Config_templates_config_rss_tmpl.py", line 387, in respond
KeyError: 'None'
Powered by CherryPy 18.6.0
```

![image](https://user-images.githubusercontent.com/1273502/116011074-52e90080-a623-11eb-86a6-9e58dfefd474.png)

```
2021-04-26 00:05:56,403::DEBUG::[interface:1815] RSS READOUT = False
2021-04-26 00:05:56,416::INFO::[notifier:122] Sending notification: Error - [26/Apr/2021:00:05:56] HTTP  (type=error, job_cat=None)
2021-04-26 00:05:56,404::ERROR::[_cplogging:213] [26/Apr/2021:00:05:56] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/sjo-sab/sabnzbd/interface.py", line 172, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/home/sander/git/sjo-sab/sabnzbd/interface.py", line 1856, in index
    return template.respond()
  File "_home_sander_git_sjo_sab_interfaces_Config_templates_config_rss_tmpl.py", line 387, in respond
KeyError: 'None'
2021-04-26 00:05:56,417::INFO::[_cplogging:213] [26/Apr/2021:00:05:56] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: 127.0.0.1:8080
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  SEC-FETCH-SITE: same-origin
  SEC-FETCH-MODE: navigate
  SEC-FETCH-USER: ?1
  SEC-FETCH-DEST: document
  SEC-CH-UA: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
  SEC-CH-UA-MOBILE: ?0
  REFERER: http://127.0.0.1:8080/sabnzbd/config/rss/
  ACCEPT-ENCODING: gzip, deflate, br
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6
  COOKIE: plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0
```

**Comment by sanderjo** [comment]
To show it's not a fluke, I tried on Windows:

![image](https://user-images.githubusercontent.com/1273502/116045025-e77a4f80-a671-11eb-96c2-ca74ffe7dbd4.png)


```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy\_cprequest.py", line 638, in respond
  File "cherrypy\_cprequest.py", line 697, in _do_respond
  File "cherrypy\lib\encoding.py", line 219, in __call__
  File "cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 172, in internal_wrap
  File "sabnzbd\interface.py", line 1856, in index
  File "_Program_Files_SABnzbd_interfaces_Config_templates_config_rss_tmpl.py", line 387, in respond
KeyError: 'None'
Powered by CherryPy unknown

```
