### ISSUE TITLE
Traceback: "TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1882]
3.3.0Beta3

With downloads from nzb.su, with all episodes from a certain series (but not on other series / other indexer), I get the Traceback below.

```
2021-05-02 13:17:21,755::INFO::[filesystem:297] Checking if any resulting filenames need to be sanitized
2021-05-02 13:17:21,755::INFO::[notifier:122] Sending notification: Error - Post Processing Failed for blabla.zero-nine.s06e13.hdtv.x264-lucidtv.mkv-xpost (see logfile) (type=error, job_cat=None)
2021-05-02 13:17:21,755::ERROR::[postproc:613] Post Processing Failed for blabla.zero-nine.s06e13.hdtv.x264-lucidtv.mkv-xpost (see logfile)
2021-05-02 13:17:21,755::INFO::[postproc:614] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 438, in process_job
    newfiles = sanitize_files(filelist=newfiles)
  File "/usr/share/sabnzbdplus/sabnzbd/filesystem.py", line 299, in sanitize_files
    filelist = listdir_full(folder)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/filesystem.py", line 716, in listdir_full
    for root, dirs, files in os.walk(input_dir):
  File "/usr/lib/python3.8/os.py", line 339, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Hey ... `newfiles = sanitize_files(filelist=newfiles)` ... isn't that the part that we changed in Beta3?

**Comment by Safihre** [comment]
Solved in cdd7e6931a32b8458c084d237d5d723d10812d97
