### ISSUE TITLE
malformed IP address as input to "-s" leads to ... nothing

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1883]
... SAB does not start, and does not give a warning.

```
sander@brixit:~/git/sabnzbd$ ./SABnzbd.py   --server 0...0 -b0 -l2

sander@brixit:~/git/sabnzbd$ ./SABnzbd.py   --server 0...0
sander@brixit:~/git/sabnzbd$

sander@brixit:~/git/sabnzbd$ ./SABnzbd.py   --server 1...1
sander@brixit:~/git/sabnzbd$
```

Suggestion, in https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L526 do a check if input is an IP addres

```
>>> import ipaddress
>>> ipaddress.ip_address('0...0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: '0...0' does not appear to be an IPv4 or IPv6 address
>>>
```
I think the logic should be:

```
if not an_ipaddress() and not resolable_host_name():
    bail_out_with_error_message()
```

**Comment by sanderjo** [comment]
Related:

```
./SABnzbd.py -l2 -s jdjdjdjdjdjdj

Fatal error:
  Unable to bind to port 8080 on jdjdjdjdjdjdj. Some other software uses the port or SABnzbd is already running.
```

Some checking afterg
```
        elif opt in ("-s", "--server"):
            (cherryhost, cherryport) = split_host(arg)
```
and before https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1023-L1025

would be useful.

**Comment by Safihre** [comment]
Feel free to submit a pr!
