### ISSUE TITLE
Disabling ipv6 stack via kernel option, breaks binding of port.

### ISSUE THREAD

**Issue by gothrek22** [sabnzbd/sabnzbd#1886]
Not sure if this is a docker issue or sabnzbd (probably the latter as other apps work without a problem).

But, setting `ipv6.disable=1` as a kernel option on linux, causes 

`Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.`

error in docker container (I'm using ghcr.io/linuxserver/sabnzbd:latest, freshly pulled). Can replicate the issue each time I switch that flag.

IPv6 is useless in private networks and only adds to dns resolving performance, I've tried disabling it via sabnzbd options, but no luck there.

The moment I've reenabled the ipv6 driver, sabnzbd starts without an issue. 

PS. I'd recommend adding an ISSUE_TEMPLATE, as it might make it easier for you guys to triage issues.

**Comment by sanderjo** [comment]
Maybe localhost still resolves to something with ::1 ?
What if you start SAB with 127.0.0.1 (which is hard IPV4-only), so in --server 127.0.01:8080, or in the ini settings?

**Comment by gothrek22** [comment]
Nope, it's set to 0.0.0.0, I've checked to make sure I'm not using any weird name resolving.

**Comment by sanderjo** [comment]
Show how you reproduce, because I can't:

IPv4 only docker:

```
# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.3  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:03  txqueuelen 0  (Ethernet)
        RX packets 46205  bytes 75063749 (75.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3775  bytes 293912 (293.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 38  bytes 2012 (2.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38  bytes 2012 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```


... and SAB just runs:


```
root@496bfacbc622:/# cd SABnzbd-3.2.1
root@496bfacbc622:/SABnzbd-3.2.1# ./SABnzbd.py -b0 --server 0.0.0.0
2021-05-03 14:46:54,597::INFO::[SABnzbd:1161] --------------------------------
2021-05-03 14:46:54,597::INFO::[SABnzbd:1162] SABnzbd.py-3.2.1
2021-05-03 14:46:54,597::INFO::[SABnzbd:1172] Commit: 0542c25003d0cafb1be21a3ff4c8a66f66c9d339
2021-05-03 14:46:54,598::INFO::[SABnzbd:1173] Full executable path = /SABnzbd-3.2.1/SABnzbd.py
2021-05-03 14:46:54,598::INFO::[SABnzbd:1183] Platform = posix
2021-05-03 14:46:54,598::INFO::[SABnzbd:1184] Python-version = 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]
2021-05-03 14:46:54,598::INFO::[SABnzbd:1185] Arguments = "./SABnzbd.py" "-b0" "--server" "0.0.0.0"
2021-05-03 14:46:54,598::INFO::[SABnzbd:1187] Running inside a docker container
2021-05-03 14:46:54,598::INFO::[SABnzbd:1192] Preferred encoding = UTF-8
2021-05-03 14:46:54,598::INFO::[SABnzbd:1204] SSL version = OpenSSL 1.1.1f  31 Mar 2020
2021-05-03 14:46:54,599::INFO::[SABnzbd:1256] Using INI file /root/.sabnzbd/sabnzbd.ini
2021-05-03 14:46:54,600::INFO::[postproc:139] Loading postproc queue
2021-05-03 14:46:54,601::INFO::[__init__:921] [N/A] /root/.sabnzbd/admin/Rating.sab missing
2021-05-03 14:46:54,602::INFO::[scheduler:190] Scheduling RSS interval task every 60 min (delay=55)
2021-05-03 14:46:54,602::INFO::[scheduler:201] Scheduling VersionCheck on day 5 at 0:28
2021-05-03 14:46:54,602::INFO::[scheduler:215] Setting schedule for midnight BPS reset
2021-05-03 14:46:54,602::INFO::[scheduler:218] Setting schedule for server expiration check
2021-05-03 14:46:54,602::INFO::[scheduler:223] Setting scheduler for server quota check
2021-05-03 14:46:54,608::INFO::[config:905] Writing settings to INI file /root/.sabnzbd/sabnzbd.ini
2021-05-03 14:46:54,610::INFO::[__init__:331] All processes started
2021-05-03 14:46:54,611::INFO::[SABnzbd:319] Template location for Glitter is /SABnzbd-3.2.1/interfaces/Glitter
2021-05-03 14:46:54,611::INFO::[SABnzbd:319] Template location for Config is /SABnzbd-3.2.1/interfaces/Config
2021-05-03 14:46:54,612::INFO::[misc:1050] [N/A] Running external command: ['/usr/bin/unrar']
2021-05-03 14:46:54,623::INFO::[misc:1050] [N/A] Running external command: ['/usr/bin/par2', '-h']
2021-05-03 14:46:54,635::INFO::[SABnzbd:413] SABYenc module (v4.0.1)... found!
2021-05-03 14:46:54,635::INFO::[SABnzbd:432] Cryptography module (v2.8)... found!
2021-05-03 14:46:54,635::INFO::[SABnzbd:437] par2 binary... found (/usr/bin/par2)
2021-05-03 14:46:54,635::INFO::[SABnzbd:444] UNRAR binary... found (/usr/bin/unrar)
2021-05-03 14:46:54,635::INFO::[SABnzbd:454] UNRAR binary version 5.61
2021-05-03 14:46:54,636::INFO::[SABnzbd:462] 7za binary... found (/usr/bin/7za)
2021-05-03 14:46:54,636::INFO::[SABnzbd:473] nice binary... found (/usr/bin/nice)
2021-05-03 14:46:54,636::INFO::[SABnzbd:477] ionice binary... found (/usr/bin/ionice)
2021-05-03 14:46:54,638::INFO::[SABnzbd:1443] Starting web-interface on 0.0.0.0:8080
2021-05-03 14:46:54,638::INFO::[_cplogging:219] [03/May/2021:14:46:54] ENGINE Bus STARTING
2021-05-03 14:46:54,645::INFO::[_cplogging:219] [03/May/2021:14:46:54] ENGINE Started monitor thread '_TimeoutMonitor'.
2021-05-03 14:46:54,764::INFO::[_cplogging:219] [03/May/2021:14:46:54] ENGINE Serving on http://0.0.0.0:8080
2021-05-03 14:46:54,764::INFO::[_cplogging:219] [03/May/2021:14:46:54] ENGINE Bus STARTED
2021-05-03 14:46:54,764::INFO::[SABnzbd:1480] Starting SABnzbd.py-3.2.1
2021-05-03 14:46:54,765::INFO::[postproc:237] Completed Download Folder /root/Downloads/complete is not on FAT
2021-05-03 14:46:54,793::INFO::[dirscanner:117] Dirscanner starting up
2021-05-03 14:46:54,801::INFO::[notifier:122] Sending notification: SABnzbd - SABnzbd 3.2.1 started (type=startup, job_cat=None)
2021-05-03 14:46:54,873::INFO::[ssdp:108] Serving SSDP on 172.17.0.3 as SABnzbd

```

**Comment by gothrek22** [comment]
Sure thing, just a fair warning, this requires changing things in grub and might be a bit different on different OSes.

1. Edit /etc/default/grub and add `ipv6.disable=1` to `GRUB_CMDLINE_LINUX`
2. Run `grub2-mkconfig -o /boot/grub2/grub.cfg` to regenerate grub.
3. Reboot (you should no longer have support for ipv6 stack in the kernel.
4. Try to start Sabnzbd (not sure if docker is a variable here, I have ipv6 on docker disabled too).
5. You should get the bind error.

What's interesting is that you can use 127.0.0.1 and it binds without an issue 🤔 

Reverting that change is as simple as redoing the first two steps and removing that argument from grub config.

btw. Thank you for your help.

**Comment by sanderjo** [comment]
Oh ... I'm not going to touch my GRUB settings.

**Comment by gothrek22** [comment]
Yeah, that's why I added the warning. But unfortunately this is the only way to completely disable ipv6. All the other ways are a bit wonky, as in, they can cause issues as the driver is still there.

I'm gonna look at the code later this week, to verify my guess, so please leave the ticket open for now.

**Comment by sanderjo** [comment]
> Nope, it's set to 0.0.0.0, I've checked to make sure I'm not using any weird name resolving, both in config and as a flag provided by the linuxserver.
> 
> Here's the run command:
> `python3 /app/sabnzbd/SABnzbd.py --config-file /config --server 0.0.0.0:8080`

... and then SAB says "Unable to bind to port 8080 on localhost. " ... So 0.0.0.0 gets changes into localhost? Weird. And that is refused? Double weird. I still doubt it has to do with IPv6 ... more like port 8080 is already in use, or any binding is not allowed.


FWIW: 
On the IPv4-only docker guest: binding to IPv6 only like

`./SABnzbd.py -b0 --server ip6-localhost`

leads to

```
2021-05-03 17:11:41,646::INFO::[SABnzbd:1443] Starting web-interface on ip6-localhost:8080
2021-05-03 17:11:41,649::INFO::[_cplogging:219] [03/May/2021:17:11:41] ENGINE Bus STARTING
2021-05-03 17:11:41,653::INFO::[_cplogging:219] [03/May/2021:17:11:41] ENGINE Started monitor thread '_TimeoutMonitor'.
2021-05-03 17:11:41,668::INFO::[notifier:122] Sending notification: Error - [03/May/2021:17:11:41] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 217, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2008, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('::1', 8080, 0, 0): [Errno 99] Cannot assign requested address)
 (type=error, job_cat=None)
2021-05-03 17:11:41,668::ERROR::[_cplogging:219] [03/May/2021:17:11:41] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 217, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2008, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('::1', 8080, 0, 0): [Errno 99] Cannot assign requested address)
```


... so that is a real error.

**Comment by sanderjo** [comment]
> What's interesting is that you can use 127.0.0.1 and it binds without an issue 🤔

That's interesting indeed.

**Comment by gothrek22** [comment]
Yeah and nothing else is running in that container, I've tried using different ports as a naive way of troubleshooting, but it seems to not trigger that issue. 

Doubly weird I've reenabled ipv6 driver via removing that stuff from grub and it started right away. 

My guess is that the web server that is used in sabnzbd uses a method that binds to an ipv6 OR ipv4 socket but that fails miserably due to bad handling of missing ipv6 support. But that's just a guess.

**Comment by sanderjo** [comment]
> Yeah and nothing else is running in that container, I've tried using different ports as a naive way of troubleshooting, but it seems to not trigger that issue.

Can you post different tries and the results? So

0.0.0.0:8080
0.0.0.0:8888
127.0.0.1:8080
127.0.0.1:8888
localhsot:8080
localhost:8888
<LAN-IP-address>:8080
<LAN-IP-address>:8888
ip6-localhost:8080
ip6-localhost:8888

... maybe we can't a pattern

**Comment by gothrek22** [comment]
Sure, thing I'll do so tomorrow.

Thanks again!

**Comment by thezoggy** [comment]
what error did you get? curious if it mimics
https://www.reddit.com/r/SABnzbd/comments/i5dybo/startup_error_getsockaddrarg_bad_family_with_300/

**Comment by gothrek22** [comment]
@thezoggy nope, not that one. The one on reddit is way further in the stack. Mine is thrown right away when trying to bind the port. But it might be covered by a different subset of IOError or something. I'll try to do the debugging steps as @sanderjo asked and do some of my own to track it down.

**Comment by djpbessems** [comment]
@gothrek22  Have you ever managed to find a solution while still keeping ipv6 disabled in the kernel?

**Comment by thezoggy** [comment]
if you have a current issue do open a new GHI with relevant info as many things have changed since this issue started

**Comment by djpbessems** [comment]
Actually, the error message along with the described context is still the same; so it would actually fragment the available information if I created a new issue.

Since this issue comes up at the top at a Google-search, I'll post my solution here; I changed my kubernetes-manifest as follows:
```
    [...]
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd
        command: ["/bin/sh"]
        args:
        - -c
        - "sed -e '/-server/c\  --config-file /config --server \":8080\"' -i /etc/services.d/sabnzbd/run;/init"
    [...]
```

**Comment by LckyLuciano** [comment]
For docker if you're using the linuxserver.io containers, I got this working by adding an environment variable  `- HAS_IPV6=false` in my docker-compose file.

The issue is marked as resolved over here:  https://github.com/linuxserver/docker-sabnzbd/issues/144

**Comment by npawelek** [comment]
The default sabnzbd.ini has an option `ipv6_servers = 1`. Change that to `0` and you should be good to go.
