### ISSUE TITLE
(possible) error situation when saving out RSS time update

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#1890]
I received repeatedly this error when saving out a new time interval for RSS checking. However the entered value DID save it seems when re-opening the webpage. I cannot say where the problem is, but am reporting it as using a beta version.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 638, in respond
  File "cherrypy/_cprequest.py", line 697, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "sabnzbd/interface.py", line 174, in internal_wrap
  File "sabnzbd/interface.py", line 1848, in index
  File "_Applications_SABnzbd_app_Contents_MacOS_interfaces_Config_templates_config_rss_tmpl.py", line 387, in respond
KeyError: 'None'

MacOS 10.5.7 3.3.0Beta3 [43817ae]
Python Version: | 3.9.4 (v3.9.4:1f2e3088f3, Apr 4 2021, 12:32:44) [Clang 6.0 (clang-600.0.57)] [UTF-8]
-- | --
OpenSSL 1.1.1k 25 Mar 2021

**Comment by sanderjo** [comment]
Ah, yes, I can reproduce wiht 3.3.0 Beta3:

![image](https://user-images.githubusercontent.com/1273502/117252375-282e5180-ae46-11eb-9813-a2583fa65c20.png)


```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 174, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1848, in index
    return template.respond()
  File "_usr_share_sabnzbdplus_interfaces_Config_templates_config_rss_tmpl.py", line 387, in respond
KeyError: 'None'
Powered by CherryPy 8.9.1
```

**Comment by Safihre** [comment]
Thank you for reporting, bug fixed!
