### ISSUE TITLE
Setting logging to -1 (off) disables useful warnings in the interface

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1892]
At least it does so for the unwanted extensions warning, but I suspect it's not limited to that. Upon encountering an unwanted extensions the job was correctly paused and tagged "unwanted", but the usual warning in the interface (Glitter dark) didn't appear and I was left to guess what extension triggered the pause.

I expected this and other warnings to work regardless of the disabled logging.

**Comment by sanderjo** [comment]
Does it do anything at all? 

When I start SAB like this

`~/git/sabnzbd$ ./SABnzbd.py -l-1`

https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb_bin_and_exe_855f226eccae.nzb (with a bin and an exe) is just downloaded and saved. Proof:

```
$ ll /media/sander/6665-6464/reftestnzb_bin_and_exe_855f226eccae/
total 11520
drwxr-xr-x  2 sander sander   131072 mei 12 20:50 ./
drwxr-xr-x 78 sander sander   131072 mei 12 20:50 ../
-rwxr-xr-x  1 sander sander 10485760 mei 12 20:46 blabla.bin*
-rwxr-xr-x  1 sander sander  1048576 mei 12 20:46 fake.exe*
```
Brrrr.

Same machine, start with

`./SABnzbd.py -l2`

gives correct "In "reftestnzb_bin_and_exe_855f226eccae" unwanted extension in RAR file. Unwanted file is fake.exe" and SAB is Paused.

**Comment by sanderjo** [comment]
Logging 


```
2021-05-12 21:19:27,031::DEBUG::[assembler:387] File contains: blabla.bin
2021-05-12 21:19:27,185::INFO::[nzbqueue:779] [sabnzbd.nzbqueue.register_article] Ending job reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,185::DEBUG::[assembler:110] Decoding part of /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar
2021-05-12 21:19:27,200::DEBUG::[filesystem:562] Applying permissions 0o644 (octal) to /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar
2021-05-12 21:19:27,201::INFO::[assembler:135] Decoding finished /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar
2021-05-12 21:19:27,201::DEBUG::[nzbstuff:464] Removing article database for SABnzbd_nzf_b9eh7yfm
2021-05-12 21:19:27,201::DEBUG::[filesystem:891] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/__ADMIN__/SABnzbd_nzf_b9eh7yfm
2021-05-12 21:19:27,202::DEBUG::[assembler:387] File contains: blabla.bin
2021-05-12 21:19:27,202::DEBUG::[assembler:387] File contains: fake.exe
2021-05-12 21:19:27,202::DEBUG::[assembler:389] Unwanted file fake.exe
2021-05-12 21:19:27,202::INFO::[notifier:122] Sending notification: Warning - In "reftestnzb_bin_and_exe_855f226eccae" unwanted extension in RAR file. Unwanted file is fake.exe  (type=warning, job_cat=None)
2021-05-12 21:19:27,202::WARNING::[assembler:164] In "reftestnzb_bin_and_exe_855f226eccae" unwanted extension in RAR file. Unwanted file is fake.exe 
2021-05-12 21:19:27,203::DEBUG::[assembler:169] Unwanted extension is in rar file /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar
2021-05-12 21:19:27,203::DEBUG::[assembler:171] Unwanted extension ... pausing
2021-05-12 21:19:27,203::DEBUG::[nzbstuff:1930] Saving attributes {'cat': '*', 'pp': 3, 'script': 'None', 'priority': 0, 'final_name': 'reftestnzb_bin_and_exe_855f226eccae', 'password': '', 'url': 'https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb_bin_and_exe_855f226eccae.nzb'} for reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,203::DEBUG::[__init__:895] [sabnzbd.nzbstuff.save_to_disk] Saving data for SABnzbd_nzo_rqzdckat in /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/__ADMIN__
2021-05-12 21:19:27,204::INFO::[nzbqueue:390] [sabnzbd.assembler.run] Removing job reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,204::INFO::[nzbqueue:233] Saving queue
2021-05-12 21:19:27,204::DEBUG::[__init__:963] [sabnzbd.nzbqueue.save] Saving data for queue10.sab
2021-05-12 21:19:27,205::DEBUG::[__init__:895] [sabnzbd.save_admin] Saving data for queue10.sab in /home/sander/.sabnzbd/admin
2021-05-12 21:19:27,205::INFO::[postproc:134] Saving postproc queue
2021-05-12 21:19:27,205::DEBUG::[__init__:963] [sabnzbd.postproc.save] Saving data for postproc2.sab
2021-05-12 21:19:27,205::INFO::[downloader:392] Waiting for post-processing to finish
2021-05-12 21:19:27,205::DEBUG::[nzbstuff:1930] Saving attributes {'cat': '*', 'pp': 3, 'script': 'None', 'priority': 0, 'final_name': 'reftestnzb_bin_and_exe_855f226eccae', 'password': '', 'url': 'https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb_bin_and_exe_855f226eccae.nzb'} for reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,206::DEBUG::[__init__:895] [sabnzbd.save_admin] Saving data for postproc2.sab in /home/sander/.sabnzbd/admin
2021-05-12 21:19:27,210::INFO::[postproc:372] Starting Post-Processing on reftestnzb_bin_and_exe_855f226eccae => Repair:True, Unpack:True, Delete:True, Script:None, Cat:*
2021-05-12 21:19:27,210::INFO::[notifier:122] Sending notification: Post-processing - reftestnzb_bin_and_exe_855f226eccae (type=pp, job_cat=*)
2021-05-12 21:19:27,210::INFO::[postproc:736] Starting verification and repair of reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,211::INFO::[__init__:924] [sabnzbd.postproc.parring] /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/__ADMIN__/__verified__ missing
2021-05-12 21:19:27,211::INFO::[postproc:756] Running verification and repair on set mypars
2021-05-12 21:19:27,211::DEBUG::[newsunpack:2065] Quick-check of file specialspecial.part2.rar OK
2021-05-12 21:19:27,211::DEBUG::[newsunpack:2065] Quick-check of file specialspecial.part1.rar OK
2021-05-12 21:19:27,211::INFO::[newsunpack:1111] Quick-check for mypars is OK, skipping repair
2021-05-12 21:19:27,211::DEBUG::[filesystem:891] [sabnzbd.newsunpack.par2_repair] Deleting file /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/mypars.par2
2021-05-12 21:19:27,212::DEBUG::[filesystem:891] [sabnzbd.newsunpack.par2_repair] Deleting file /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/mypars.vol000+001.par2
2021-05-12 21:19:27,212::DEBUG::[newsunpack:2033] build_filelists(): joinables: []
2021-05-12 21:19:27,212::DEBUG::[newsunpack:2034] build_filelists(): zips: []
2021-05-12 21:19:27,212::DEBUG::[newsunpack:2035] build_filelists(): rars: ['/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part1.rar', '/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar']
2021-05-12 21:19:27,212::DEBUG::[newsunpack:2036] build_filelists(): 7zips: []
2021-05-12 21:19:27,212::DEBUG::[newsunpack:2037] build_filelists(): ts: []
2021-05-12 21:19:27,213::DEBUG::[__init__:895] [sabnzbd.postproc.parring] Saving data for __verified__ in /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/__ADMIN__
2021-05-12 21:19:27,213::INFO::[postproc:811] Verification and repair finished for reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,213::INFO::[filesystem:297] Checking if any resulting filenames need to be sanitized
2021-05-12 21:19:27,214::INFO::[filesystem:648] Creating directories: /media/sander/6665-6464/reftestnzb_bin_and_exe_855f226eccae.4
2021-05-12 21:19:27,214::DEBUG::[filesystem:562] Applying permissions 0o744 (octal) to /media/sander/6665-6464/reftestnzb_bin_and_exe_855f226eccae.4
2021-05-12 21:19:27,215::DEBUG::[filesystem:855] Renaming "/media/sander/6665-6464/reftestnzb_bin_and_exe_855f226eccae.4" to "/media/sander/6665-6464/_UNPACK_reftestnzb_bin_and_exe_855f226eccae.4"
2021-05-12 21:19:27,215::INFO::[postproc:431] Running unpack_magic on reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,215::DEBUG::[newsunpack:2033] build_filelists(): joinables: []
2021-05-12 21:19:27,215::DEBUG::[newsunpack:2034] build_filelists(): zips: []
2021-05-12 21:19:27,215::DEBUG::[newsunpack:2035] build_filelists(): rars: ['/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part1.rar', '/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar']
2021-05-12 21:19:27,215::DEBUG::[newsunpack:2036] build_filelists(): 7zips: []
2021-05-12 21:19:27,216::DEBUG::[newsunpack:2037] build_filelists(): ts: []
2021-05-12 21:19:27,216::INFO::[newsunpack:261] Unrar starting on /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae
2021-05-12 21:19:27,216::DEBUG::[newsunpack:486] Rar_sets: {'specialspecial': ['/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part1.rar', '/home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part2.rar']}
2021-05-12 21:19:27,216::INFO::[newsunpack:528] Extracting rarfile /home/sander/Downloads/incomplete/reftestnzb_bin_and_exe_855f226eccae/specialspecial.part1.rar (belonging to specialspecial) to /media/sander/6665-6464/_UNPACK_reftestnzb_bin_and_exe_855f226eccae.4
2021-05-12 21:19:27,216::INFO::[notifier:122] Sending notification: Warning - Failed to read the password file /home/sander/binary-10k.bin (type=warning, job_cat=None)
2021-05-12 21:19:27,216::WARNING::[misc:772] Failed to read the password file /home/sander/binary-10k.bin
2021-05-12 21:19:27,217::INFO::[misc:773] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/misc.py", line 757, in get_all_passwords
    lines = pwf.read().split("\n")
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
2021-05-12 21:19:27,217::DEBUG::[newsunpack:622] rar_extract(): Extractionpath: /media/sander/6665-6464/_UNPACK_reftestnzb_bin_and_exe_855f226eccae.4
```

**Comment by jcfp** [comment]
> Does it do anything at all? Looks not pausing at all with `-l-1`:

For me it did pause (as configured) and tag the job correctly, but no warning message displayed. That was with the unwanted extension feature in whitelist mode encountering an unlisted extension - just in case that matters.

**Comment by sanderjo** [comment]
I have blacklist mode, with com, exe, ppt

With logging `-l-1`, the unwanted extension is not blocked, and no warning (duh).
With logging 0 or higher, it still works

**Comment by Safihre** [comment]
I mean.. of course the warnings are disabled. Seems to me this is "by design" and how it's supposed to work?

**Comment by JackDandy** [comment]
I read this `the unwanted extension is not blocked` - as meaning the business and the logging logic are mistakenly tied.

**Comment by Safihre** [comment]
In the code there's no reference to them, but if so, it should be a separate issue. Not part of this one.
