### ISSUE TITLE
snap sabnzbd failure to start

### ISSUE THREAD

**Issue by jjasghar** [sabnzbd/sabnzbd#1893]
I'm attempting to use the snap of sabnzbd, and it seems it's looking for `/etc/fedora-release` and can't find it:

```
2021-05-13T16:59:53Z sabnzbd.sabnzbd[4832]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/fedora-release'
2021-05-13T16:59:54Z systemd[1]: snap.sabnzbd.sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
2021-05-13T16:59:54Z systemd[1]: snap.sabnzbd.sabnzbd.service: Failed with result 'exit-code'.
2021-05-13T16:59:54Z systemd[1]: snap.sabnzbd.sabnzbd.service: Scheduled restart job, restart counter is at 100.
2021-05-13T16:59:54Z systemd[1]: Stopped Service for snap application sabnzbd.sabnzbd.
2021-05-13T16:59:54Z systemd[1]: Started Service for snap application sabnzbd.sabnzbd.
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: 2021-05-13 12:59:56,652::INFO::[SABnzbd:1160] --------------------------------
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: 2021-05-13 12:59:56,653::INFO::[SABnzbd:1161] SABnzbd.py-3.3.0-develop
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: 2021-05-13 12:59:56,653::INFO::[misc:1065] [N/A] Running external command: ['git', 'rev-parse', '--short', 'HEAD']
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: 2021-05-13 12:59:56,658::INFO::[SABnzbd:1171] Commit = unknown
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: 2021-05-13 12:59:56,659::INFO::[SABnzbd:1172] Full executable path = /snap/sabnzbd/3063/opt/sabnzbd/SABnzbd.py
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: Traceback (most recent call last):
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:   File "/snap/sabnzbd/3063/opt/sabnzbd/SABnzbd.py", line 1746, in <module>
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:     main()
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:   File "/snap/sabnzbd/3063/opt/sabnzbd/SABnzbd.py", line 1173, in main
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:     logging.info("Platform = %s - %s", os.name, platform.platform())
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:   File "/snap/sabnzbd/3063/usr/lib/python3.6/platform.py", line 1409, in platform
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:     distname, distversion, distid = dist('')
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:   File "/snap/sabnzbd/3063/usr/lib/python3.6/platform.py", line 437, in dist
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:     full_distribution_name=0)
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:   File "/snap/sabnzbd/3063/usr/lib/python3.6/platform.py", line 404, in _linux_distribution
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]:     encoding='utf-8', errors='surrogateescape') as f:
2021-05-13T16:59:56Z sabnzbd.sabnzbd[4863]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/fedora-release'
```

Any advice would be greatly appreciated.

**Comment by sanderjo** [comment]
Out of curiosity (I'm not a snap user): on which OS are you? Ubuntu, Fedora, or ... ?

**Comment by Safihre** [comment]
Will push new snap-package soon.

**Comment by Safihre** [comment]
Pushed new fixed package.

**Comment by jjasghar** [comment]
> Out of curiosity (I'm not a snap user): on which OS are you? Ubuntu, Fedora, or ... ?

I was running snap on a fedora ?33? installation.

@Safihre thanks! trying it now.
