### ISSUE TITLE
Recent commit breaks unpacking for some / many files

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#1932]
I noticed that I recently had a bunch of nzbs that were not unpacked by sabnzbd. Not all of them, but several. Then today, I had a bunch of older nzbs (ca. three years old), and none of them were unpacked. All I get in these cases is a bunch of RAR files (.rar, .r00, r.01 and so on) in the disk folder where the unpacked file should be. Un-raring those locally works without any problems, they are not passworded RAR files.

I get a bunch of error messages when sabnzbd does not unpack the files. They are like this (from a log file):

```
2021-07-25 15:49:25,463::ERROR::[_cplogging:216] [25/Jul/2021:15:49:25] HTTP 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib64/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib64/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 169, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 452, in api
    return api_handler(kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/api.py", line 100, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/api.py", line 582, in _api_history
    start=start, limit=limit, search=search, failed_only=failed_only, categories=categories, nzo_ids=nzo_ids
  File "/home/abc/.sabnzbd/sabnzbd/api.py", line 1784, in build_history
    items = get_active_history(postproc_queue, items)
  File "/home/abc/.sabnzbd/sabnzbd/api.py", line 1853, in get_active_history
    ) = build_history_info(nzo)
  File "/home/abc/.sabnzbd/sabnzbd/database.py", line 507, in build_history_info
    nzo.correct_password,
AttributeError: 'NzbObject' object has no attribute 'correct_password'
```

I went back several commits and found out that commit https://github.com/sabnzbd/sabnzbd/commit/1052f37d02724417fd36cfff3af07a075becaae6 (create a record for the successful password) apparently is the culprit. When I went back to commit https://github.com/sabnzbd/sabnzbd/commit/92b023599bad0d0b68d72e7cf46ab18178190d7e (Correct the build process to include guessit ), the problems went away completely, all files were unpacked as expected.

I'm on OpenSUSE Linux Leap 15.2, python version is 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC] [UTF-8], OpenSSL 1.1.1d 10 Sep 2019.

**Comment by Safihre** [comment]
Thanks for reporting, I pushed a commit that should fix it.
