### ISSUE TITLE
 Fatal error in Assembler: ValueError: list.remove(x): x not in list (repeatedly, SAB restarts)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1933]
with git version develop [9d61645] , I get this:

```
 Fatal error in Assembler
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/assembler.py", line 111, in run
    self.assemble(nzf, file_done)
  File "/home/sander/git/sabnzbd/sabnzbd/assembler.py", line 228, in assemble
    data = sabnzbd.ArticleCache.load_article(article)
  File "/home/sander/git/sabnzbd/sabnzbd/articlecache.py", line 133, in load_article
    nzo.remove_saved_article(article)
  File "/home/sander/git/sabnzbd/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/home/sander/git/sabnzbd/sabnzbd/nzbstuff.py", line 1227, in remove_saved_article
    self.saved_articles.remove(article)
ValueError: list.remove(x): x not in list
```

SAB seems to stop/restart, and the error appears again.

Two downloads are busy. I'll try to find if I can reproduce with one of them.

**Comment by Cpuroast** [comment]
I confirm, I've seen this also with 3.4.0Beta1 [92b0235]

**Comment by Safihre** [comment]
Are you getting this with downloads that fail (missing articles) or ones that are present?
Are there any other errors/warnings in the logs?

**Comment by sanderjo** [comment]
Ouch:
* I can't find the relevant logging anymore ... which is very weird.
* I can't reproduce
That means I have to wait for it to reoccur.

**Comment by puzzledsab** [comment]
It's unfortunate that some tracebacks aren't logged. Is it possible to always do that? I've noticed a couple of times that is has restarted at some point (because ctrl-c doesn't work), but the point where it happened is no longer in the scroll buffer. In the log files I can only see that it has restarted.

**Comment by sanderjo** [comment]
> It's unfortunate that some tracebacks aren't logged.

Oh ... I didn't know that. If so, that could be the reason I can't find the error in the log files? It only showed in my GUI, and I copy-pasted that here onto github?

**Comment by Safihre** [comment]
If it's in the interface, it's also in the logs. Some errors are not caught, when they fatally crash a thread and there's no try/except. In the case of the Assembler there is try/except.

**Comment by sopi20** [comment]
same thing happend to me today on develop:

```
2021-08-08 12:20:27,192::ERROR::[assembler:126] Fatal error in Assembler
Traceback (most recent call last):
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/assembler.py", line 111, in run
    self.assemble(nzf, file_done)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/assembler.py", line 228, in assemble
    data = sabnzbd.ArticleCache.load_article(article)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/articlecache.py", line 133, in load_article
    nzo.remove_saved_article(article)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/nzbstuff.py", line 1227, in remove_saved_article
    self.saved_articles.remove(article)
ValueError: list.remove(x): x not in list
2021-08-08 12:20:54,180::WARNING::[__init__:1012] Restarting because of crashed assembler
2021-08-08 12:20:55,596::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE Bus STOPPING
2021-08-08 12:20:55,609::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
2021-08-08 12:20:55,624::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
2021-08-08 12:20:55,625::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE Bus STOPPED
2021-08-08 12:20:55,625::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE Bus EXITING
2021-08-08 12:20:55,625::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE Bus EXITED
2021-08-08 12:20:55,626::INFO::[_cplogging:216] [08/Aug/2021:12:20:55] ENGINE Re-spawning python3 -OO SABnzbd.py -b 0 -l 0 -d -f /usr/local/sabnzbd/data/sabnzbd.ini --pidfile /usr/local/sabnzbd/data/sabnzbd.pid
2021-08-08 12:20:57,647::INFO::[_cplogging:216] [08/Aug/2021:12:20:57] ENGINE Bus STARTING
2021-08-08 12:20:57,763::INFO::[_cplogging:216] [08/Aug/2021:12:20:57] ENGINE Serving on http://0.0.0.0:8080
2021-08-08 12:20:57,909::INFO::[_cplogging:216] [08/Aug/2021:12:20:57] ENGINE Serving on https://0.0.0.0:9090
2021-08-08 12:20:57,910::INFO::[_cplogging:216] [08/Aug/2021:12:20:57] ENGINE Bus STARTED
2021-08-08 12:21:01,399::ERROR::[assembler:126] Fatal error in Assembler
...
```

nothing else in logs :/

**Comment by sanderjo** [comment]
> same thing happend to me today on develop:

Can you reproduce (with that same NZB)?

**Comment by sopi20** [comment]
tried it now (deleted the downloaded nzb from ui, reverted back to develop as I have previously reverted to 3.3.x branch), and tried downloading it again) and it works like a charm 😳 
I even tried to play with it in a few re-runs and it happened when I shutdown sabnzbd mid downloading and started it again, but it didn't end up in a loop without any log entries this time, but after one restart due to fatal error in assembler it was ok.... pretty weird....

```
2021-08-08 19:46:04,197::WARNING::[__init__:213] Signal 15 caught, saving and exiting...
2021-08-08 19:46:04,226::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE Bus STOPPING
2021-08-08 19:46:04,260::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
2021-08-08 19:46:04,274::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
2021-08-08 19:46:04,274::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE Bus STOPPED
2021-08-08 19:46:04,275::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE Bus EXITING
2021-08-08 19:46:04,275::INFO::[_cplogging:216] [08/Aug/2021:19:46:04] ENGINE Bus EXITED
2021-08-08 19:46:32,476::INFO::[_cplogging:216] [08/Aug/2021:19:46:32] ENGINE Bus STARTING
2021-08-08 19:46:32,592::INFO::[_cplogging:216] [08/Aug/2021:19:46:32] ENGINE Serving on http://0.0.0.0:8080
2021-08-08 19:46:32,741::INFO::[_cplogging:216] [08/Aug/2021:19:46:32] ENGINE Serving on https://0.0.0.0:9090
2021-08-08 19:46:32,742::INFO::[_cplogging:216] [08/Aug/2021:19:46:32] ENGINE Bus STARTED
2021-08-08 19:49:26,997::INFO::[_cplogging:216] [08/Aug/2021:19:49:26] ENGINE Bus STARTING
2021-08-08 19:49:27,144::INFO::[_cplogging:216] [08/Aug/2021:19:49:27] ENGINE Serving on https://0.0.0.0:9090
2021-08-08 19:49:27,254::INFO::[_cplogging:216] [08/Aug/2021:19:49:27] ENGINE Serving on http://0.0.0.0:8080
2021-08-08 19:49:27,255::INFO::[_cplogging:216] [08/Aug/2021:19:49:27] ENGINE Bus STARTED
2021-08-08 19:49:31,964::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part02.rar, bytes=103212559, nzf_id=SABnzbd_nzf_3wzjptz6>
2021-08-08 19:49:31,965::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part03.rar, bytes=103214095, nzf_id=SABnzbd_nzf_e4j0_tla>
2021-08-08 19:49:31,966::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part04.rar, bytes=103212664, nzf_id=SABnzbd_nzf_5dyud44w>
2021-08-08 19:49:31,967::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part05.rar, bytes=103213538, nzf_id=SABnzbd_nzf_wbdfvsmi>
2021-08-08 19:49:31,968::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part06.rar, bytes=103216365, nzf_id=SABnzbd_nzf_1ms1r1u8>
2021-08-08 19:49:31,968::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part07.rar, bytes=103214924, nzf_id=SABnzbd_nzf_501c726t>
2021-08-08 19:49:31,969::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part08.rar, bytes=103215347, nzf_id=SABnzbd_nzf_hchv6g67>
2021-08-08 19:49:31,969::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part09.rar, bytes=103214319, nzf_id=SABnzbd_nzf_updsrmdh>
2021-08-08 19:49:31,970::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part10.rar, bytes=103214139, nzf_id=SABnzbd_nzf_01zdo447>
2021-08-08 19:49:31,971::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part11.rar, bytes=103212173, nzf_id=SABnzbd_nzf_o7or8tdm>
2021-08-08 19:49:31,971::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part12.rar, bytes=103216405, nzf_id=SABnzbd_nzf_mjdysjlv>
2021-08-08 19:49:31,973::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part13.rar, bytes=103214766, nzf_id=SABnzbd_nzf_saeazg87>
2021-08-08 19:49:31,974::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part14.rar, bytes=103211625, nzf_id=SABnzbd_nzf_n7v0gt62>
2021-08-08 19:49:31,974::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part15.rar, bytes=103213153, nzf_id=SABnzbd_nzf_zb0v10ny>
2021-08-08 19:49:31,975::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part16.rar, bytes=103213175, nzf_id=SABnzbd_nzf_59rkc21u>
2021-08-08 19:49:31,975::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part17.rar, bytes=103212946, nzf_id=SABnzbd_nzf_vvmgaf66>
2021-08-08 19:49:31,976::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part18.rar, bytes=103214272, nzf_id=SABnzbd_nzf_5hf66old>
2021-08-08 19:49:31,977::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part19.rar, bytes=103212998, nzf_id=SABnzbd_nzf_7bvsp45k>
2021-08-08 19:49:31,977::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part20.rar, bytes=103213823, nzf_id=SABnzbd_nzf_8xkzlo37>
2021-08-08 19:49:31,978::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part21.rar, bytes=103213354, nzf_id=SABnzbd_nzf_9gm2iu1i>
2021-08-08 19:49:31,978::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part22.rar, bytes=103213856, nzf_id=SABnzbd_nzf_9ah5g76f>
2021-08-08 19:49:31,979::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part23.rar, bytes=103213765, nzf_id=SABnzbd_nzf_0l71kgcr>
2021-08-08 19:49:31,979::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part24.rar, bytes=103211120, nzf_id=SABnzbd_nzf_oyuvl83o>
2021-08-08 19:49:31,980::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part25.rar, bytes=103213355, nzf_id=SABnzbd_nzf_c7hpmz63>
2021-08-08 19:49:31,981::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part26.rar, bytes=103213496, nzf_id=SABnzbd_nzf_4kmig7tg>
2021-08-08 19:49:31,981::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part27.rar, bytes=103210574, nzf_id=SABnzbd_nzf_k7835v4x>
2021-08-08 19:49:31,982::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part28.rar, bytes=103211322, nzf_id=SABnzbd_nzf_ve7eiryf>
2021-08-08 19:49:31,982::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part29.rar, bytes=103215185, nzf_id=SABnzbd_nzf_c59t801r>
2021-08-08 19:49:31,983::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part30.rar, bytes=103214610, nzf_id=SABnzbd_nzf_38r2vdxo>
2021-08-08 19:49:31,983::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part31.rar, bytes=103216282, nzf_id=SABnzbd_nzf_5yb1j8w2>
2021-08-08 19:49:31,984::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part32.rar, bytes=103214332, nzf_id=SABnzbd_nzf_cnts2vnt>
2021-08-08 19:49:31,984::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part33.rar, bytes=103213871, nzf_id=SABnzbd_nzf_s3dyki8m>
2021-08-08 19:49:31,985::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part34.rar, bytes=103215385, nzf_id=SABnzbd_nzf_rahzgq9_>
2021-08-08 19:49:31,985::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part35.rar, bytes=103215765, nzf_id=SABnzbd_nzf_zth173eh>
2021-08-08 19:49:31,986::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part36.rar, bytes=103215405, nzf_id=SABnzbd_nzf_e4lrn8ye>
2021-08-08 19:49:31,986::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part37.rar, bytes=103214183, nzf_id=SABnzbd_nzf_5l1koonc>
2021-08-08 19:49:31,987::ERROR::[nzbstuff:1617] Error importing <NzbFile: filename=TVSHOW.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part38.rar, bytes=103213190, nzf_id=SABnzbd_nzf_4_aj9e5l>
2021-08-08 19:49:32,039::ERROR::[assembler:126] Fatal error in Assembler
Traceback (most recent call last):
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/assembler.py", line 111, in run
    self.assemble(nzf, file_done)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/assembler.py", line 228, in assemble
    data = sabnzbd.ArticleCache.load_article(article)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/articlecache.py", line 133, in load_article
    nzo.remove_saved_article(article)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/local/sabnzbd/releases/20210808/sabnzbd/nzbstuff.py", line 1227, in remove_saved_article
    self.saved_articles.remove(article)
ValueError: list.remove(x): x not in list
2021-08-08 19:49:57,600::WARNING::[__init__:1012] Restarting because of crashed assembler
2021-08-08 19:49:59,144::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE Bus STOPPING
2021-08-08 19:49:59,158::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
2021-08-08 19:49:59,175::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
2021-08-08 19:49:59,176::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE Bus STOPPED
2021-08-08 19:49:59,176::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE Bus EXITING
2021-08-08 19:49:59,176::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE Bus EXITED
2021-08-08 19:49:59,177::INFO::[_cplogging:216] [08/Aug/2021:19:49:59] ENGINE Re-spawning python3 -OO SABnzbd.py -b 0 -l 0 -d -f /usr/local/sabnzbd/data/sabnzbd.ini --pidfile /usr/local/sabnzbd/data/sabnzbd.pid
2021-08-08 19:50:01,690::INFO::[_cplogging:216] [08/Aug/2021:19:50:01] ENGINE Bus STARTING
2021-08-08 19:50:01,844::INFO::[_cplogging:216] [08/Aug/2021:19:50:01] ENGINE Serving on https://0.0.0.0:9090
2021-08-08 19:50:01,954::INFO::[_cplogging:216] [08/Aug/2021:19:50:01] ENGINE Serving on http://0.0.0.0:8080
2021-08-08 19:50:01,956::INFO::[_cplogging:216] [08/Aug/2021:19:50:01] ENGINE Bus STARTED
```

**Comment by puzzledsab** [comment]
Now I got it in a fork that is based on https://github.com/sabnzbd/sabnzbd/commit/d17368a9d236009e31efe88331e45d8893308028.

**Comment by puzzledsab** [comment]
@Safihre : Did you figure out why it can try to remove the same twice? Why didn't this seem to happen until recently?

**Comment by Safihre** [comment]
> @Safihre : Did you figure out why it can try to remove the same twice? Why didn't this seem to happen until recently?

I have no clue... 😢
