### ISSUE TITLE
Crashed downloader stops all downloads, even after restart?

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#1953]
Running v3.4.0 on OSX 10.15.7. 

Yesterday SAB was happily downloading, it then seemed to "freeze" (in the background, I wasn't watching) with lots of jobs "remaining". Manual "start" or "force" via the icons/GUI made no difference. Nor did rebuilding the queue etc.

I even used the GUI to restart SAB without any success. This morning (by the computer) I did "force quit" via "Activity Monitor" and restart. The same issue happens.

Plenty of disk space as shown in the top of the web page. It (web page) did seem to stop responding some of the time too, whether due to a crash or not I can't say.

I am unable to power restart the computer presently due to a big background file transfer.

Looking at the logs it makes reference to a crashed downloader, but it does not seem to make a difference on restart. This is why I am raising the report in case it is responsible for the problems, even with a restart.

The log has a bit of information prior to the suspected crash /start of incident, to show things were working and in case it gives any clues.

```
2021-09-22 13:11:05,954::ERROR::[nzbstuff:1620] Error importing <NzbFile: filename=pfa-huth.s23e34.web.r04, bytes=51608959, nzf_id=SABnzbd_nzf_dx7qi3f9>
2021-09-22 13:11:05,955::ERROR::[nzbstuff:1620] Error importing <NzbFile: filename=pfa-huth.s23e34.web.r05, bytes=51610153, nzf_id=SABnzbd_nzf_xa1lr0o6>
2021-09-22 16:17:47,787::WARNING::[nzbstuff:908] Pausing duplicate NZB "SAS.Australia.S02E06.Mindset.720p.HDTV.x264-ORENJI.nzb"
2021-09-22 16:17:52,117::WARNING::[nzbstuff:908] Pausing duplicate NZB "SAS.Australia.S02E06.Mindset.HDTV.x264-FQM.nzb"
2021-09-22 16:48:03,255::WARNING::[__init__:1006] Restarting because of crashed downloader
2021-09-22 16:48:04,120::INFO::[_cplogging:213] [22/Sep/2021:16:48:04] ENGINE Bus STOPPING
2021-09-22 16:48:04,143::INFO::[_cplogging:213] [22/Sep/2021:16:48:04] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.90', 8085)) shut down
2021-09-22 16:48:04,143::INFO::[_cplogging:213] [22/Sep/2021:16:48:04] ENGINE Bus STOPPED
2021-09-22 16:48:04,143::INFO::[_cplogging:213] [22/Sep/2021:16:48:04] ENGINE Bus EXITING
2021-09-22 16:48:04,144::INFO::[_cplogging:213] [22/Sep/2021:16:48:04] ENGINE Bus EXITED
2021-09-22 16:51:32,846::INFO::[_cplogging:213] [22/Sep/2021:16:51:32] ENGINE Bus STARTING
2021-09-22 16:51:32,964::INFO::[_cplogging:213] [22/Sep/2021:16:51:32] ENGINE Serving on http://192.168.0.90:8085
2021-09-22 16:51:32,965::INFO::[_cplogging:213] [22/Sep/2021:16:51:32] ENGINE Bus STARTED
2021-09-22 16:52:03,360::WARNING::[__init__:1006] Restarting because of crashed downloader
2021-09-22 16:52:04,670::INFO::[_cplogging:213] [22/Sep/2021:16:52:04] ENGINE Bus STOPPING
2021-09-22 16:52:04,685::INFO::[_cplogging:213] [22/Sep/2021:16:52:04] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.90', 8085)) shut down
2021-09-22 16:52:04,686::INFO::[_cplogging:213] [22/Sep/2021:16:52:04] ENGINE Bus STOPPED
2021-09-22 16:52:04,686::INFO::[_cplogging:213] [22/Sep/2021:16:52:04] ENGINE Bus EXITING
2021-09-22 16:52:04,686::INFO::[_cplogging:213] [22/Sep/2021:16:52:04] ENGINE Bus EXITED
2021-09-22 16:52:28,064::INFO::[_cplogging:213] [22/Sep/2021:16:52:28] ENGINE Bus STARTING
2021-09-22 16:52:28,176::INFO::[_cplogging:213] [22/Sep/2021:16:52:28] ENGINE Serving on http://192.168.0.90:8085
2021-09-22 16:52:28,178::INFO::[_cplogging:213] [22/Sep/2021:16:52:28] ENGINE Bus STARTED
2021-09-22 16:52:58,237::WARNING::[__init__:1006] Restarting because of crashed downloader
2021-09-22 16:52:59,293::INFO::[_cplogging:213] [22/Sep/2021:16:52:59] ENGINE Bus STOPPING
2021-09-22 16:52:59,307::INFO::[_cplogging:213] [22/Sep/2021:16:52:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.90', 8085)) shut down
2021-09-22 16:52:59,307::INFO::[_cplogging:213] [22/Sep/2021:16:52:59] ENGINE Bus STOPPED
2021-09-22 16:52:59,307::INFO::[_cplogging:213] [22/Sep/2021:16:52:59] ENGINE Bus EXITING
```
This continues with similar errors and retries, e.g.

```
2021-09-22 17:03:21,267::WARNING::[__init__:1006] Restarting because of crashed downloader
2021-09-22 17:03:22,348::INFO::[_cplogging:213] [22/Sep/2021:17:03:22] ENGINE Bus STOPPING
2021-09-22 17:03:22,365::INFO::[_cplogging:213] [22/Sep/2021:17:03:22] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.90', 8085)) shut down

```

Thanks!

**Comment by Safihre** [comment]
Can you enable DEBUG logging in the Status and Interface settings window?
Then we might see what is going on.

**Comment by DarrenPIngram** [comment]
Sorry for that oversight.
Changed to debug level now, used "restart" for the application, selected all to "force" and within a few seconds I got the "lost connection to SAB.." message (it is hosted on the same computer I am writing this on). It came back after a few seconds and zero traffic throughput.
Due to its size I've sent the log to the safihre@sab email address I had on file - I hope that is ok.

Thanks

**Comment by Safihre** [comment]
Unfortunately it is not logged why it crashes.. Just to be sure, could you download 3.4.1? I just pushed an update.
Then run SABnzbd from the Terminal, like so:
```
/Applications/SABnzbd.app/Contents/MacOS/SABnzbd --console
```
Somewhere before the restarting bit it should show a traceback, that's what we are looking for!

**Comment by DarrenPIngram** [comment]
Thank you. After some thinking about it it seemed to start downloading the
blocked items. I've emailed you the log so you can see as it mentions
things about leaks and missing data. I chose email as it may have sensitive
information in.

Hope this helps, whether a bug or just a local issue that got unblocked.


‌

**Comment by sanderjo** [comment]
@DarrenPIngram did you get a Traceback?

**Comment by DarrenPIngram** [comment]
TBH I didn't understand fully the output it was giving, so the first email
gave you everything. I've sent you since a second mail with a copy of the
entire session due it crashing.

Hopefully it shows the  launch command and all output.


‌

**Comment by Safihre** [comment]
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "sabnzbd/downloader.py", line 624, in run
  File "sabnzbd/downloader.py", line 509, in decode
  File "sabnzbd/nzbqueue.py", line 756, in register_article
  File "sabnzbd/decorators.py", line 36, in call_func
  File "sabnzbd/nzbstuff.py", line 1111, in promote_par2
ValueError: list.remove(x): x not in list
```

**Comment by DarrenPIngram** [comment]
Thanks for the update and some extract. Does this mean a problem at my end or of my making, a problem with the code, or something else. What should I do, if anything. SAB has not reloaded following the last crash and I've left matters lie pending hearing from you in case you needed extra information.

**Comment by Safihre** [comment]
@DarrenPIngram This is a bug in the code, but not an easy one. Or at least, I don't see the solution just yet 🙃 
Nothing you can do for now.
Just one last question: did it start with 3.4.0 or did you experience this previously?

**Comment by DarrenPIngram** [comment]
Thanks. I think it started with 3.4.0. I have recollections of the odd
crashing in the past for no specific reason, but nothing like the "jammed"
queue I've reported now.
Am I safe going back to the previous version or does 3.4.0 and upwards
happen to rewrite any indices or formats?
Sorry to be the bearer of bad news and extra programming work in the future.

‌

**Comment by sanderjo** [comment]
> What should I do

I wonder: if you go back to to SABnzbd 3.2.1, is the problem gone? My idea/guess is that the "Restarting because of crashed downloader" was introduced recently

**Comment by DarrenPIngram** [comment]
Thanks. I "downgraded". Initially it did not do anything different. In the
end I deleted the first few stuck items, it crashed twice but (so far) it
is downloading something. Let's see what happens next.

If you would like me to retry the latest version after this download queue
has cleared I'm happy to do it.

‌

**Comment by thezoggy** [comment]
Can you share a nzb of a problem file.. also do you see it happens with a specific category and does that category have a pre/post script?

**Comment by DarrenPIngram** [comment]
Sadly not, as I've deleted them from SAB. I can certainly do it if I get a
problem in the future (can I re-export the NZB file from SAB?).
I didn't recognise it with a specific category. I don't use script
processing at all (other than the default deobsfucate).



‌

**Comment by albino1** [comment]
In the Settings on the Folders tab at the bottom is a thing called `.nzb Backup Folder`.  They should be in there unless you never set it up or deleted them for some reason.

**Comment by DarrenPIngram** [comment]
Hi. Never set it up, as did not have the need to keep them (forgot the
option was there). I'll enable it in case it catches a problematical one.
Shall I go back to the latest version or do you prefer I see if it happens
again in the older version first?


‌

**Comment by albino1** [comment]
If you want peace of mind then stay in the older version.  If you want to help fix a potential bug then I would upgrade again and see if you can make it break.  Worst case scenario you can just downgrade again :)

**Comment by DarrenPIngram** [comment]
Sure, happy to live the life with the "bleeding edge". I will revert if I
manage to break things again.
Thank you for your prompt consideration.
‌

**Comment by Safihre** [comment]
@DarrenPIngram Thanks for helping us out.
You can download a patched version here: https://github.com/sabnzbd/sabnzbd/actions/runs/1268818316
Could you let us know if you experience any more problems with this version?

**Comment by DarrenPIngram** [comment]
Got the patched version now. Will update if the problem should reemerge.

‌
