### ISSUE TITLE
python3.10: AttributeError: module 'collections' has no attribute 'MutableMapping' ... by import guessit?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1971]
With python 3.10, I get:

```
sander@stream13:~/git/sabnzbd$ python3.10 SABnzbd.py 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/SABnzbd.py", line 49, in <module>
    import guessit
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/episodes.py", line 16, in <module>
    from .title import TitleFromPosition
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/usr/lib/python3/dist-packages/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/usr/lib/python3/dist-packages/babelfish/converters/__init__.py", line 11, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
sander@stream13:~/git/sabnzbd$

```
So ... guessit causes that? Looks like it:

```
$ python3.10
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import guessit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/episodes.py", line 16, in <module>
    from .title import TitleFromPosition
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/home/sander/.local/lib/python3.10/site-packages/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/usr/lib/python3/dist-packages/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/usr/lib/python3/dist-packages/babelfish/converters/__init__.py", line 11, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
>>> 
```

Problem in guessit?
Or in collections?

**Comment by sanderjo** [comment]
```
$ python3.10
Python 3.10.0 (default, Oct  4 2021, 22:09:55) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> collections.MutableMapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'collections' has no attribute 'MutableMapping'
>>> 

```

Let's check with python 3.8:

```
$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> collections.MutableMapping
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
<class 'collections.abc.MutableMapping'>
>>> 
```

Ah ...  "in 3.10 it will stop working"

**Comment by sanderjo** [comment]
Solved by updating ... babelfish

`python3.10 -m pip install babelfish -U`

SABnzbd is running with python 3.10 now.

**Comment by Safihre** [comment]
We run the unit tests using 3.10 for a few weeks now so I was pretty sure it works 😊
