### ISSUE TITLE
3.4.1 - sab crash due to radarr v4 .net6 sending tlsv1 requests

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1976]
testing out radarr v4 build that uses .net6 I noticed it stopped being able to communicate with sab (works just fine on v3 .net5).
they are looking into why the cert validation stuff isnt working right (if you add sab self signed cert into root store it will make it work) but still sab tosses up tlsv1 alerts and after a series of them sab stops working:

```
2021-11-17 13:15:22,314::INFO::[SABnzbd:1181] SABnzbd.exe-3.4.2
2021-11-17 13:15:22,314::INFO::[SABnzbd:1191] Commit = cc831e16d87d12fe4d7bbcc71b9ff579eb1335ff
2021-11-17 13:15:22,314::INFO::[SABnzbd:1193] Full executable path = C:\Program Files\SABnzbd\SABnzbd.exe
2021-11-17 13:15:22,314::INFO::[SABnzbd:1194] Arguments = "C:\Program Files\SABnzbd\SABnzbd.exe"
2021-11-17 13:15:22,314::INFO::[SABnzbd:1195] Python-version = 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
2021-11-17 13:15:22,314::INFO::[SABnzbd:1196] Dockerized = False
2021-11-17 13:15:22,314::INFO::[SABnzbd:1197] CPU architecture = AMD64
2021-11-17 13:15:22,351::INFO::[SABnzbd:1200] Platform = nt - Windows-10-10.0.19043-SP0
2021-11-17 13:15:22,351::INFO::[SABnzbd:1206] Preferred encoding = cp1252
2021-11-17 13:15:22,351::INFO::[SABnzbd:1218] SSL version = OpenSSL 1.1.1l  24 Aug 2021
2021-11-17 13:15:22,351::INFO::[SABnzbd:1227] Certifi version = 2021.10.08
2021-11-17 13:15:22,351::INFO::[SABnzbd:1228] Loaded additional certificates from C:\Program Files\SABnzbd\certifi\cacert.pem
2021-11-17 13:15:22,367::DEBUG::[SABnzbd:1237] Available certificates = {'x509': 151, 'crl': 0, 'x509_ca': 149}
2021-11-17 13:15:22,367::DEBUG::[SABnzbd:1240] Local IPv4 address = 192.168.0.2
2021-11-17 13:15:22,583::DEBUG::[SABnzbd:1241] Public IPv4 address = <removed>
2021-11-17 13:15:22,583::DEBUG::[SABnzbd:1242] IPv6 address = None
2021-11-17 13:15:22,924::DEBUG::[SABnzbd:1245] CPU Pystone available performance = 272680
2021-11-17 13:15:22,924::DEBUG::[SABnzbd:1246] CPU model = Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
2021-11-17 13:15:27,702::INFO::[interface:644] Successful login from 192.168.0.2 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0]
2021-11-17 13:16:57,878::INFO::[notifier:122] Sending notification: Warning - [17/Nov/2021:13:16:57] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)
 (type=warning, job_cat=None)
2021-11-17 13:16:57,878::WARNING::[_cplogging:213] [17/Nov/2021:13:16:57] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:16:57,893::WARNING::[_cplogging:213] [17/Nov/2021:13:16:57] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:43,538::INFO::[notifier:122] Sending notification: Warning - [17/Nov/2021:13:23:43] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)
 (type=warning, job_cat=None)
2021-11-17 13:23:43,538::WARNING::[_cplogging:213] [17/Nov/2021:13:23:43] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:43,560::WARNING::[_cplogging:213] [17/Nov/2021:13:23:43] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:45,358::WARNING::[_cplogging:213] [17/Nov/2021:13:23:45] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:45,364::WARNING::[_cplogging:213] [17/Nov/2021:13:23:45] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:46,846::WARNING::[_cplogging:213] [17/Nov/2021:13:23:46] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:23:46,868::WARNING::[_cplogging:213] [17/Nov/2021:13:23:46] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 13:24:45,285::WARNING::[_cplogging:213] [17/Nov/2021:13:24:45] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 14:22:53,182::INFO::[notifier:122] Sending notification: Warning - [17/Nov/2021:14:22:53] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)
 (type=warning, job_cat=None)
2021-11-17 14:22:53,182::WARNING::[_cplogging:213] [17/Nov/2021:14:22:53] ENGINE socket.error 1
Traceback (most recent call last):
  File "cheroot\server.py", line 1277, in communicate
  File "cheroot\server.py", line 706, in parse_request
  File "cheroot\server.py", line 747, in read_request_line
  File "cheroot\server.py", line 304, in readline
  File "_pyio.py", line 559, in readline
  File "_pyio.py", line 538, in nreadahead
  File "_pyio.py", line 1134, in peek
  File "_pyio.py", line 1141, in _peek_unlocked
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2633)

2021-11-17 14:32:35,090::INFO::[panic:239] Launching browser with https://192.168.0.2:8080/sabnzbd
```

sab process is still running, just gui wont load anymore. have to kill process and restart sab.

i can repeat this now on demand, in radarr v4 .net6 build.. go to downloader>sab>test and it fails. if you attempt to test like 5 times it will then cause sab gui to stop working, the api will still work.

thought maybe it was just the windows notification puking, tried turning that off and testing. same issue happens

to grab radarr v4 .net6 build (you can downgrade back to the v4 .net5 by just switching back to develop branch and updating - do make a backup before hand if your got an existing version):
https://artprodcus3.artifacts.visualstudio.com/Ae81bf62d-a2b3-4a5c-8bc1-60cc428c0287/961c82cf-1428-4ab0-9257-63be1671eac8/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL1JhZGFyci9wcm9qZWN0SWQvOTYxYzgyY2YtMTQyOC00YWIwLTkyNTctNjNiZTE2NzFlYWM4L2J1aWxkSWQvNDA1My9hcnRpZmFjdE5hbWUvV2luZG93c0luc3RhbGxlcg2/content?format=file&subPath=%2FRadarr.merge.4.0.0.5502.windows-core-x64-installer.exe

**Comment by sanderjo** [comment]
> i can repeat this now on demand, in radarr v4 .net6 build.. go to downloader>sab>test and it fails. if you attempt to test like 5 times it will then cause sab gui to stop working, the api will still work.

Same as https://github.com/Radarr/Radarr/issues/5512#issue-758859986 ?

**Comment by thezoggy** [comment]
alright, worked with radarr devs and got the .net6 build fixed. using newer http client and now its working again.
https://github.com/Radarr/Radarr/pull/6715

(if you have that build installed, change to the `net6` branch and update to latest to pull in update)

i still will leave that old build linked so one can test (will be gone in a few weeks though).
looks like you can basically take down any sab instance by just sending a bunch of tls v1 requests in a row

**Comment by thezoggy** [comment]
> This is an upstream problem: cherrypy just runs out of threads.

Seems like latest version of cheroot should have solved that? https://github.com/cherrypy/cheroot/blob/master/CHANGES.rst

**Comment by Safihre** [comment]
We're using that for a while though..
