### ISSUE TITLE
DSM 7 SABNZB errors: "ValueError: semaphore or lock released too many times"

### ISSUE THREAD

**Issue by Notoff** [sabnzbd/sabnzbd#2008]
Hi all,

Same issue than [https://github.com/sabnzbd/sabnzbd/issues/1988](https://github.com/sabnzbd/sabnzbd/issues/1988).

Setup
Package Name: SABNZBD
Package Version: 3.4.2-50

NAS Model: DS214Play
NAS Architecture: INTEL Atom CE5335 1.6GHz, 2 cores, 1GB RAM
DSM version: 7.0.1-42218

SABNZBD starts (I did a fresh install), I have access to the GUI, I can successfully connect to my NG server using the "Test Server" button but I cannot start any download (they appear in the GUI but remain idle at 0% ad 0B/s) and I get the "ValueError: semaphore or lock released too many times" message + stack trace.

I tried the suggestion of @sanderjo [https://github.com/sabnzbd/sabnzbd/issues/1988#issuecomment-984753943](https://github.com/sabnzbd/sabnzbd/issues/1988#issuecomment-984753943) but with no luck.

Here’s the full error message : 
```
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/env/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 169, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/interface.py", line 452, in api
    return api_handler(kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 100, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 474, in _api_status
    return _api_status_table.get(name, (_api_fullstatus, 2))[0](value, kwargs)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 465, in _api_fullstatus
    status = build_status(
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/api.py", line 1340, in build_status
    info["publicipv4"] = publicipv4()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/getipaddress.py", line 87, in publicipv4
    result = addresslookup4(sabnzbd.cfg.selftest_host())
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/getipaddress.py", line 45, in func_wrapper
    return async_result.get(max_timeout)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 736, in __exit__
    self.terminate()
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 654, in terminate
    self._terminate()
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/pool.py", line 687, in _terminate_pool
    change_notifier.put(None)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/var/packages/python38/target/lib/python3.8/multiprocessing/synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
ValueError: semaphore or lock released too many times
```

I can make any test from here.

Many thanks in advance guys :)

**Comment by Notoff** [comment]
Hi @Safihre,
I just saw you close the issue, but I don’t understand why.
Did I miss something ?
Many thanks :)
Notoff

**Comment by Notoff** [comment]
Oh, just saw that you committed some code...
OK so now, the error will be « caught » and the public_ipv4 will be returned.
I guess that will allow the downloads to actually occur instead of remaining stuck at 0%.
I can’t wait to have this fix released :)
Thanks!

**Comment by Safihre** [comment]
Well, it will not return the address but just not crash.
It seems this is so super exotic bug that I can't find the cause of it.. So better to not crash for now.. Hopefully indeed downloading will start normally.
Although this crash shouldn't block downloading, only maybe break updates of the interface.
