### ISSUE TITLE
ChromeOS -> Linux: "[sabnzbd.misc.run_command] The command in build_command is undefined." 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2035]
On ChromeOS -> Linux, starting SABnzbd leads to

![image](https://user-images.githubusercontent.com/1273502/150632028-5628f385-7ff0-4d77-9eeb-3f0040d2e7fa.png)

`[sabnzbd.misc.run_command] The command in build_command is undefined.`

logging:

```
2022-01-22 09:58:40,815::INFO::[SABnzbd:1271] python3-gi not found, no SysTray.
2022-01-22 09:58:40,833::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/unrar']
2022-01-22 09:58:40,834::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-01-22 09:58:40,871::INFO::[notifier:123] Sending notification: Error - [sabnzbd.misc.run_command] The command in build_command is undefined. (type=error, job_cat=None)
2022-01-22 09:58:40,870::ERROR::[misc:1113] [sabnzbd.misc.run_command] The command in build_command is undefined.
2022-01-22 09:58:40,874::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/par2', '-h']
2022-01-22 09:58:40,876::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-01-22 09:58:40,901::INFO::[SABnzbd:423] SABYenc module (v4.0.2)... found!
2022-01-22 09:58:40,903::INFO::[SABnzbd:442] Cryptography module (v36.0.1)... found!
2022-01-22 09:58:40,904::INFO::[SABnzbd:447] par2 binary... found (/usr/bin/par2)
2022-01-22 09:58:40,905::INFO::[SABnzbd:454] UNRAR binary... found (/usr/bin/unrar)
2022-01-22 09:58:40,906::INFO::[SABnzbd:462] UNRAR binary version 5.61
2022-01-22 09:58:40,907::INFO::[SABnzbd:474] 7za binary... NOT found!
```

The `python3-gi not found, no SysTray.` is untrue, due to the broad except: `import gi` is working OK, but the https://github.com/sabnzbd/sabnzbd/blob/78da7ddb5565b74e62980fcfc5940e31be928e25/SABnzbd.py#L1265 causes the exception.

Questions:
* is the no-systray stuff leading to the "[sabnzbd.misc.run_command] The command in build_command is undefined." , or uncorrelated?
* why is the "[sabnzbd.misc.run_command] The command in build_command is undefined." sent to screen, as a big deal error?
* if there is a systray problem / no systray, shouldn't https://github.com/sabnzbd/sabnzbd/blob/78da7ddb5565b74e62980fcfc5940e31be928e25/SABnzbd.py#L1257-L1271 turn it off?
* FWIW: https://github.com/sabnzbd/sabnzbd/blob/78da7ddb5565b74e62980fcfc5940e31be928e25/SABnzbd.py#L1261 does checking on DISPLAY ... which is set on ChromeOS -> Linux, but not a GUI-less Linux server. 

Proof `import gi` is **not** the problem:

```
>>> import gi # OK
>>> gi.require_version("Gtk", "3.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
>>> 
```

**Comment by sanderjo** [comment]
After installing 7z and 7za (via p7zip-full) (thanks @Safihre ), the GUI error message is gone

"is the no-systray stuff leading to the "[sabnzbd.misc.run_command] The command in build_command is undefined." , or uncorrelated?"

Conclusion: uncorrelated



Nice logging:

```
2022-01-22 12:08:18,073::INFO::[SABnzbd:1271] python3-gi not found, no SysTray.
2022-01-22 12:08:18,079::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/unrar']
2022-01-22 12:08:18,080::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-01-22 12:08:18,115::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/7za']
2022-01-22 12:08:18,117::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-01-22 12:08:18,144::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/par2', '-h']
2022-01-22 12:08:18,145::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-01-22 12:08:18,164::INFO::[SABnzbd:423] SABYenc module (v4.0.2)... found!
2022-01-22 12:08:18,167::INFO::[SABnzbd:442] Cryptography module (v36.0.1)... found!
2022-01-22 12:08:18,168::INFO::[SABnzbd:447] par2 binary... found (/usr/bin/par2)
2022-01-22 12:08:18,169::INFO::[SABnzbd:454] UNRAR binary... found (/usr/bin/unrar)
2022-01-22 12:08:18,172::INFO::[SABnzbd:462] UNRAR binary version 5.61
2022-01-22 12:08:18,174::INFO::[SABnzbd:470] 7za binary... found (/usr/bin/7za)
2022-01-22 12:08:18,174::INFO::[SABnzbd:472] 7za binary version 16.02
```
