### ISSUE TITLE
Exit(-1) Cannot run script

### ISSUE THREAD

**Issue by ButtaJones** [sabnzbd/sabnzbd#2041]
When I run SAB as admin in Windows 10 everything works fine. When I run SAB regularly I get this error. I tried changing file and folder permissions, nothing.

From web queue:
```
Exit(-1) Cannot run script C:\Program Files\SABnzbd\scripts\nzbToSickBeard.py
```

From debug log:
```
2022-01-25 15:05:48,416::DEBUG::[newsunpack:218] Failed script C:\Program Files\SABnzbd\scripts\nzbToSickBeard.py, Traceback: 
Traceback (most recent call last):
  File "sabnzbd\newsunpack.py", line 199, in external_processing
  File "sabnzbd\misc.py", line 1100, in build_and_run_command
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
OSError: [WinError 740] The requested operation requires elevation
```
Is there a fix without running as administrator?

Running Python 3.9.7
Windows 10 Pro 20H2

**Comment by sanderjo** [comment]
Traceback in nzbToSickBeard.py, which is provided by https://github.com/clinton-hall/nzbToMedia/blob/master/nzbToSickBeard.py , not by SABnzbd. So better to report over there?

**Comment by Safihre** [comment]
@ButtaJones You placed the script inside "C:\Program Files", this is a protected directory.
You should put your scripts somewhere else, not in the SABnzbd installation directory. For example somewhere in your Documents.
Whenever there is an update of SABnzbd it will remove your scirpts...
