### ISSUE TITLE
AttributeError: 'ExceptionTrap' object has no attribute 'passes'

### ISSUE THREAD

**Issue by Paul-Eccleston-i2** [sabnzbd/sabnzbd#2045]
Seeing the below traceback on startup of release 3.5.0 running on docker container 'Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] on linux':-

```
2022-01-28 16:08:43,095 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/SABnzbd.py", line 46, in <module>

2022-01-28 16:08:43,095 DEBG 'watchdog-script' stderr output:
    import cherrypy
  File "/usr/lib/python3.10/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/lib/python3.10/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/lib/python3.10/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/lib/python3.10/site-packages/jaraco/collections.py", line 10, in <module>

2022-01-28 16:08:43,095 DEBG 'watchdog-script' stderr output:
    import jaraco.text
  File "/usr/lib/python3.10/site-packages/jaraco/text/__init__.py", line 136, in <module>
    @_unicode_trap.passes
AttributeError: 'ExceptionTrap' object has no attribute 'passes'
```

**Comment by Safihre** [comment]
What Docker image is this?
This is outside of Sabnzbd code so not sure why it would crash..

**Comment by thezoggy** [comment]
its due to arc users  needing to install python-jarco

**Comment by Safihre** [comment]
Is this using the recommend SABnzbd Docker image from Linuxserver.io?
That one should auto rebuild every release so not have this problem..

**Comment by fryfrog** [comment]
The solution is to retain the older `python-jaraco` until `python-jaraco.context` is updated. :(

**Comment by Safihre** [comment]
Closing as unrelated problem.
