### ISSUE TITLE
3.5.1rc1 - fails to start on windows/macos due to missing files

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2056]
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pkg_resources\__init__.py", line 74, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "jaraco\text\__init__.py", line 227, in <module>
  File "pathlib.py", line 1132, in read_text
  File "pathlib.py", line 1117, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\SABnzbd\\pkg_resources\\extern\\jaraco\\text\\Lorem ipsum.txt'
``` 

I see the file is included in the zip but just not at the path it tries to load.

~ see below for fix

**Comment by thezoggy** [comment]
we need to update our builder to actually try and run the build to make sure it can start. even if its just basic start up and shutdown with no error code.  otherwise we will continuously get bit by dependency or build changes that break the end result

**Comment by Cpuroast** [comment]
Identical issue on macOS
```
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pkg_resources/__init__.py", line 74, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "jaraco/text/__init__.py", line 227, in <module>
  File "pathlib.py", line 1132, in read_text
  File "pathlib.py", line 1117, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SABnzbd-3.5.1RC1/SABnzbd.app/Contents/MacOS/pkg_resources/extern/jaraco/text/Lorem ipsum.txt'

**Comment by Cpuroast** [comment]
I think it boils down to the fact that "pkg_resources/extern" was inserted as a path somewhere.

"jaraco/text/Lorem ipsum.txt" does in fact still exist in "SABnzbd.app/Contents/MacOS/jaraco" on macOS

And "C:\Program Files\SABnzbd\jaraco" on Windows.

**Comment by thezoggy** [comment]
looks like its actually due to setuptools update breaking pyinstaller
https://github.com/pyinstaller/pyinstaller/issues/6564

**Comment by Cpuroast** [comment]
Can confimr @thezoggy's patch which pins setuptools to 60.6.0, allows the macOS build to launch.
Guess it's time to pin all the requirements in builder/requirements.txt also.

**Comment by Safihre** [comment]
Yes indeed we should try to run the binary... Maybe I have some time to implement that the next few weeks since it's not very trivial to do.
