### ISSUE TITLE
Unhandled KeyError on directunpacker

### ISSUE THREAD

**Issue by Drapersniper** [sabnzbd/sabnzbd#2060]
```
sabnzbd  | Exception in thread Thread-2009:
sabnzbd  | Traceback (most recent call last):
sabnzbd  |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
sabnzbd  |     self.run()
sabnzbd  |   File "/app/sabnzbd/directunpacker.py", line 313, in run
sabnzbd  |     perc = (self.cur_volume / self.total_volumes[self.cur_setname]) * 100
sabnzbd  | KeyError: 'little.house.on.the.prairie.1974.s02e16.1080p.bluray.x264-bravery'
sabnzbd  | Exception in thread Thread-2107:
sabnzbd  | Traceback (most recent call last):
sabnzbd  |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
sabnzbd  |     self.run()
sabnzbd  |   File "/app/sabnzbd/directunpacker.py", line 313, in run
sabnzbd  |     perc = (self.cur_volume / self.total_volumes[self.cur_setname]) * 100
sabnzbd  | KeyError: 'little.house.on.the.prairie.1974.s02e20.1080p.bluray.x264-bravery'
sabnzbd  | Exception in thread Thread-2118:
sabnzbd  | Traceback (most recent call last):
sabnzbd  |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
sabnzbd  |     self.run()
sabnzbd  |   File "/app/sabnzbd/directunpacker.py", line 313, in run
sabnzbd  |     perc = (self.cur_volume / self.total_volumes[self.cur_setname]) * 100
sabnzbd  | KeyError: 'mad.men.s05e09.1080p.bluray.x264-hd4u'
sabnzbd  | Exception in thread Thread-2186:
sabnzbd  | Traceback (most recent call last):
sabnzbd  |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
sabnzbd  |     self.run()
sabnzbd  |   File "/app/sabnzbd/directunpacker.py", line 313, in run
sabnzbd  |     perc = (self.cur_volume / self.total_volumes[self.cur_setname]) * 100
sabnzbd  | KeyError: 'little.house.on.the.prairie.1974.s02e17.1080p.bluray.x264-bravery'
sabnzbd  | Exception in thread Thread-2198:
sabnzbd  | Traceback (most recent call last):
sabnzbd  |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
sabnzbd  |     self.run()
sabnzbd  |   File "/app/sabnzbd/directunpacker.py", line 313, in run
sabnzbd  |     perc = (self.cur_volume / self.total_volumes[self.cur_setname]) * 100
sabnzbd  | KeyError: 'little.house.on.the.prairie.1974.s01e19.1080p.bluray.x264-bravery'
```

Sabnzbd: 3.5.1RC1 [76c5895]
Docker image: image: cr.hotio.dev/hotio/sabnzbd:testing

**Comment by Safihre** [comment]
For this I will need the full logs.
Please enable +Debug logging in the Status and Interface settings window and then after it happens again, send me the logs at safihre@sabnzbd.org
You can also share the NZB with me, maybe that already helps.

**Comment by Safihre** [comment]
Found the problem, thanks! 💯
