### ISSUE TITLE
3.5.1rc1 - windows - WinError 5] Access is denied

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2067]
sab binary, 3.5.1rc1  running on win10, with main drive being ssd

got error during unpacking release, it retried and finished just fine. first time ive seen this and just wanted to note:
```
2022-02-09 11:56:09,864::DEBUG::[filesystem:901] [sabnzbd\postproc.py.cleanup_list] Deleting file \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE\disenchantment.s04e04.1080p.web.h264-paleale-sample_s.jpg
2022-02-09 11:56:09,980::DEBUG::[filesystem:865] Renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE"
2022-02-09 11:56:09,980::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <[WinError 5] Access is denied: '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE' -> '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\Disenchantment.S04E04.1080p.WEB.h264-PALEALE'>
2022-02-09 11:56:09,995::DEBUG::[filesystem:887] File busy, retrying rename \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:10,011::DEBUG::[assembler:108] Decoding part of \\?\C:\Users\<USERNAME>\downloads\incomplete\Disenchantment.S04E05.1080p.WEB.h264-PALEALE\disenchantment.s04e05.1080p.web.h264-paleale.r01

2022-02-09 11:56:10,828::INFO::[directunpacker:318] DirectUnpacked volume 3 for disenchantment.s04e05.1080p.web.h264-paleale
2022-02-09 11:56:11,646::DEBUG::[bpsmeter:345] Speed: 82.3 MB/s
2022-02-09 11:56:11,769::DEBUG::[nzbstuff:389] Finishing import on disenchantment.s04e05.1080p.web.h264-paleale.r03
2022-02-09 11:56:11,769::DEBUG::[filesystem:1140] [sabnzbd\nzbstuff.py.finish_import] Loading data for SABnzbd_nzf_zhfc7f16 from \\?\C:\Users\<USERNAME>\downloads\incomplete\Disenchantment.S04E05.1080p.WEB.h264-PALEALE\__ADMIN__\SABnzbd_nzf_zhfc7f16
2022-02-09 11:56:12,016::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <[WinError 5] Access is denied: '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE' -> '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\Disenchantment.S04E04.1080p.WEB.h264-PALEALE'>
2022-02-09 11:56:12,016::DEBUG::[filesystem:887] File busy, retrying rename \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:12,749::DEBUG::[downloader:539] Delaying - Decoder queue: 1 - Assembler queue: 5
2022-02-09 11:56:14,021::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <[WinError 5] Access is denied: '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE' -> '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\Disenchantment.S04E04.1080p.WEB.h264-PALEALE'>
2022-02-09 11:56:14,021::DEBUG::[filesystem:887] File busy, retrying rename \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:16,026::DEBUG::[filesystem:875] Could not rename, trying move for \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:17,531::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <[WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE\\disenchantment.s04e04.1080p.web.h264-paleale.mkv'>
2022-02-09 11:56:17,531::DEBUG::[filesystem:887] File busy, retrying rename \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:19,536::DEBUG::[filesystem:875] Could not rename, trying move for \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:19,821::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <[WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\TV\\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE\\disenchantment.s04e04.1080p.web.h264-paleale.mkv'>
2022-02-09 11:56:19,821::DEBUG::[filesystem:887] File busy, retrying rename \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:21,842::DEBUG::[filesystem:875] Could not rename, trying move for \\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE to \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE
2022-02-09 11:56:21,842::DEBUG::[filesystem:879] Error renaming "\\?\C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" <Destination path '\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE' already exists>
2022-02-09 11:56:21,842::INFO::[notifier:123] Sending notification: Error - Error renaming "C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE" (type=error, job_cat=None)
2022-02-09 11:56:21,842::DEBUG::[assembler:108] Decoding part of \\?\C:\Users\<USERNAME>\downloads\incomplete\Disenchantment.S04E05.1080p.WEB.h264-PALEALE\disenchantment.s04e05.1080p.web.h264-paleale.r02
2022-02-09 11:56:21,842::ERROR::[postproc:490] Error renaming "C:\Users\<USERNAME>\downloads\complete\TV\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE" to "C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE"
2022-02-09 11:56:21,842::INFO::[postproc:495] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 488, in process_job
  File "sabnzbd\postproc.py", line 1189, in rename_and_collapse_folder
  File "sabnzbd\decorators.py", line 36, in call_func
  File "sabnzbd\filesystem.py", line 876, in renamer
  File "shutil.py", line 803, in move
shutil.Error: Destination path '\\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE\_UNPACK_Disenchantment.S04E04.1080p.WEB.h264-PALEALE' already exists
2022-02-09 11:56:21,842::INFO::[postproc:1162] Removing unwanted sample file \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE\disenchantment.s04e04.1080p.web.h264-paleale-sample.mkv
2022-02-09 11:56:21,842::DEBUG::[filesystem:901] [sabnzbd\filesystem.py.load_data] Deleting file \\?\C:\Users\<USERNAME>\downloads\incomplete\Disenchantment.S04E05.1080p.WEB.h264-PALEALE\__ADMIN__\SABnzbd_article_xyb6_ma7
2022-02-09 11:56:21,842::DEBUG::[filesystem:901] [sabnzbd\postproc.py.remove_samples] Deleting file \\?\C:\Users\<USERNAME>\downloads\complete\TV\Disenchantment.S04E04.1080p.WEB.h264-PALEALE\disenchantment.s04e04.1080p.web.h264-paleale-sample.mkv
2022-02-09 11:56:21,842::DEBUG::[deobfuscate_filenames:88] No par2 files found to process, running renamer
2022-02-09 11:56:21,842::INFO::[nzbstuff:1817] [sabnzbd\postproc.py.process_job] Purging data for job Disenchantment.S04E04.1080p.WEB.h264-PALEALE (delete_all_data=True)
2022-02-09 11:56:21,842::INFO::[directunpacker:453] Aborting DirectUnpack for disenchantment.s04e04.1080p.web.h264-paleale
```

**Comment by Safihre** [comment]
The `File busy, retrying rename ` is a specific one, where the system tells us:
```
# Error 32 - Used by another process
# Error 5 - Access is denied (virus scanners)
```
So.. we already try to handle it as best as we can..

**Comment by thezoggy** [comment]
i understand we retry, but shouldnt we catch and prevent the Traceback during the move since we are retrying?
