### ISSUE TITLE
Snap 3785 is broken

### ISSUE THREAD

**Issue by c-kr** [sabnzbd/sabnzbd#2089]
It looks like 2856f3af8c8f772e0505f588a82321f87a88c68d broke the snap package build yesterday, because access to /dev/shm is not allowed in snap context and it seems that there is no easy way to provide it:

```
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]: Traceback (most recent call last):
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/snap/sabnzbd/3785/opt/sabnzbd/SABnzbd.py", line 60, in <module>
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     import sabnzbd
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/snap/sabnzbd/3785/opt/sabnzbd/sabnzbd/__init__.py", line 83, in <module>
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     import sabnzbd.misc as misc
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/snap/sabnzbd/3785/opt/sabnzbd/sabnzbd/misc.py", line 42, in <module>
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     import sabnzbd.getipaddress
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/snap/sabnzbd/3785/opt/sabnzbd/sabnzbd/getipaddress.py", line 37, in <module>
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     THREAD_POOL = multiprocessing.pool.ThreadPool()
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     Pool.__init__(self, processes, initializer, initargs)
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     self._change_notifier = self._ctx.SimpleQueue()
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     return SimpleQueue(ctx=self.get_context())
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     self._rlock = ctx.Lock()
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     return Lock(ctx=self.get_context())
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]:     sl = self._semlock = _multiprocessing.SemLock(
2022-02-21T17:01:18+01:00 sabnzbd.sabnzbd[27690]: PermissionError: [Errno 13] Permission denied
```

**Comment by thezoggy** [comment]
https://stackoverflow.com/a/2009505

What os + arch are you running the snap on?

**Comment by Safihre** [comment]
So what do we dl? I hate snaps, all this **** every time.

**Comment by thezoggy** [comment]
The easy fix is just not use snap and have people use apt. Gets around their design choice. The other method is to adhere to their shared memory restrictions.  Looking around to see what others did (beside just stop doing snap)

**Comment by thezoggy** [comment]
ok lots of googling, so pretty much most of the python apps that do snaps dont use Python multiprocessing, so dont have this issue. then the ones that do all complained about the same thing and looks like the the current method to handle this is to use snapcraft-preload library. 
https://github.com/sergiusens/snapcraft-preload

but how to use that for our purposes i'm not certain...

**Comment by c-kr** [comment]
Thanks @thezoggy 

With a lot of trial and error i was able to use the snapcraft-preload library to rewrite the /dev/shm path dynamically. 

We need to set `SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1` because otherwise we get an fs-encoding error:

```
2022-02-22T10:58:25+01:00 sabnzbd.sabnzbd[57603]: Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
2022-02-22T10:58:25+01:00 sabnzbd.sabnzbd[57603]: Python runtime state: core initialized
2022-02-22T10:58:25+01:00 sabnzbd.sabnzbd[57603]: ModuleNotFoundError: No module named 'encodings'
2022-02-22T10:58:25+01:00 sabnzbd.sabnzbd[57603]: Current thread 0x00007f693cb40740 (most recent call first):
2022-02-22T10:58:25+01:00 sabnzbd.sabnzbd[57603]: <no Python frame>
```

I tested this only on amd64.

**Comment by Safihre** [comment]
@c-kr Updated the `latest/stable` snaps, the release build worked.

**Comment by c-kr** [comment]
Thanks

**Comment by jobe08** [comment]
Thanks for pushing a fixed update. The problem I have right now is that the stable/latest is listed as 3.6-develop and the application itself identifies as "develop" in the version api. This causes issues with sonarr - sonar then assumes its version 1.1.0 and expects values for the download dir in an old location (which going by the code was moved with 2.0 or so to fullstatus)
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L338-L346
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L219-L230
could you please push a fixed stable version (with a version number and not "develop" to the stable channel so that sonarr works again with sabnzbd ?
