### ISSUE TITLE
0.8.x unable to use ssl connections

### ISSUE THREAD

**Issue by lrusak** [sabnzbd/sabnzbd#209]
From the log.
```
2015-05-06 14:35:19,937::INFO::[downloader:399] 1@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:19,938::INFO::[downloader:399] 2@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:19,938::INFO::[downloader:399] 3@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:19,939::INFO::[downloader:399] 4@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:19,940::INFO::[downloader:399] 5@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:19,941::INFO::[downloader:399] 6@ssl-eu.astraweb.com: Initiating connection
2015-05-06 14:35:20,943::ERROR::[downloader:588] Connecting 5@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
2015-05-06 14:35:20,945::ERROR::[downloader:588] Connecting 6@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
2015-05-06 14:35:20,945::ERROR::[downloader:588] Connecting 1@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
2015-05-06 14:35:20,946::ERROR::[downloader:588] Connecting 2@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
2015-05-06 14:35:20,947::ERROR::[downloader:588] Connecting 3@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
2015-05-06 14:35:20,948::ERROR::[downloader:588] Connecting 4@ssl-eu.astraweb.com failed, message=200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
```

Other info
```
2015-05-06 14:33:24,467::INFO::[SABnzbd:1271] Arguments = /usr/local/usenet/sabnzbd/sabnzbd/SABnzbd.py -s 0.0.0.0 -f /usr/local/usenet/sabnzbd/data/config.ini --pid /usr/local/usenet/sabnzbd/data/ -d -b 0 --no_ipv6
```
```
2.7.8 (default, May 6 2015, 14:14:12) [GCC 4.2.1 20070831 patched [FreeBSD]]
```

It was working fine on the 0.7.x branch. Not sure if my python is missing something.

**Comment by shypike** [comment]
Which OS are you using?

**Comment by lrusak** [comment]
FreeBSD 9.3-RELEASE-p13

**Comment by lrusak** [comment]
seems to be just an ssl issue in general
```
[08/May/2015:19:12:18] ENGINE KeyError(0,) Traceback (most recent call last): File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 1312, in communicate req.parse_request() File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 589, in parse_request success = self.read_request_line() File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 620, in read_request_line request_line = self.rfile.readline() File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 283, in readline data = self.rfile.readline(256) File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 1134, in readline data = self.recv(self._rbufsize) File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/ssl_pyopenssl.py", line 103, in recv data = self._safe_call(True, r, *args, **kwargs) File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/ssl_pyopenssl.py", line 61, in _safe_call return call(*args, **kwargs) File "/usr/local/usenet/sabnzbd/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 1002, in recv data = self._sock.recv(size) File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv self._raise_ssl_error(self._ssl, result) File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error raise SysCallError(errno, errorcode[errno]) KeyError: 0
```

**Comment by sanderjo** [comment]
Strange: the message ```200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).``` looks normal and good.

I don't know if it is relevant, but you could try this with python (python 2, not python 3) on your FreeBSD:

```
import socket
import time

def send(command):
	totalcommand = command + "\r\n"
	print "Command sent is", totalcommand
	sslSocket.write(totalcommand)
	time.sleep(0.1)
	return sslSocket.read(5000)
	
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('ssl-eu.astraweb.com', 563))
sslSocket = socket.ssl(s)
print "Welcome is:", sslSocket.read(5000)	# Read the welcome message

print send("HELP")
print send("LIST")
print send("QUIT")

s.close()
```

On my Linux wiith python 2.7.9 it gives a normal sequence:
```
$ python blabla.py 
Welcome is: 200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).

Command sent is HELP

100 Legal commands
  article [MessageID|Number]
  body [MessageID|Number]
  date 
  head [MessageID|Number]
  help 
  mode reader|stream
  slave 
  quit 
  group newsgroup
  last 
  next 
  list [active|active.times|newsgroups|extensions|distributions|distrib.pats|moderators|overview.fmt|subscriptions]
  listgroup newsgroup
  newgroups yymmdd hhmmss ["GMT"] [<distributions>]
  post 
  stat [MessageID|Number]
  xgtitle [group_pattern]
  xhdr header [range|MessageID]
  xover [range]
  xzver [range]
  xzhdr header [range|MessageID]
  xpat header range|MessageID pat
  authinfo user Name|pass Password
.

Command sent is LIST

480 Authentication required for command

Command sent is QUIT

205 Transferred 743 bytes in 0 articles, 0 groups.  Disconnecting.


```
Note: the script uses socket and ssl because that is how SABnzbd does it. Probable reason: python2's nntplib has no NNTP_SSL.

**Comment by lrusak** [comment]
I updated to ```Python 2.7.9```

That script seems to work fine for me
```
Welcome is: 200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).

Command sent is HELP

100 Legal commands
  article [MessageID|Number]
  body [MessageID|Number]
  date 
  head [MessageID|Number]
  help 
  mode reader|stream
  slave 
  quit 
  group newsgroup
  last 
  next 
  list [active|active.times|newsgroups|extensions|distributions|distrib.pats|moderators|overview.fmt|subscriptions]
  listgroup newsgroup
  newgroups yymmdd hhmmss ["GMT"] [<distributions>]
  post 
  stat [MessageID|Number]
  xgtitle [group_pattern]
  xhdr header [range|MessageID]
  xover [range]
  xzver [range]
  xzhdr header [range|MessageID]
  xpat header range|MessageID pat
  authinfo user Name|pass Password
.

Command sent is LIST

480 Authentication required for command

Command sent is QUIT

205 Transferred 743 bytes in 0 articles, 0 groups.  Disconnecting.
```

I'll have to try a fresh git clone, and start fresh with a new config. Will report back.

**Comment by sanderjo** [comment]
You weren't running Python 2.7.9 before? Strange ... the whole SSL thing started with Python 2.7.9.

**Comment by sanderjo** [comment]
PS: what does SABnzbd say when you click on Test Server for ssl-eu.astraweb.com ?

**Comment by kindred** [comment]
I am having the exact same issue since upgrading SAB. I tried the script you posted above, and it works ok, but sab just tells me I have an "Invalid server address".

PS: I am also running Python 2.7.9.
PPS: I have tried all 3 astraweb servers.

**Comment by shypike** [comment]
As an experiment, ping astraweb's Usenet servers and use the shown numerical IP address as host name in SABnzbd.

**Comment by kindred** [comment]
Astraweb have 8 IPs for ssl.astraweb.com, I tried a few of them and they all return the exact same error "Invalid server address"/

**Comment by shypike** [comment]
In that case you'll need to be patient until I have time to look at FreeBSD. That will take a while, because I'm not familiar with it at all.

**Comment by kindred** [comment]
I'm running on Debian 8 (Jessie).

**Comment by shypike** [comment]
Same answer. So far tested only on Ubuntu, where it works. Discounting other causes, of course.

**Comment by kindred** [comment]
Yeah, not a problem. Let me know if I can help in any way. I'm not familiar with the codebase or python, so I'm not sure where to really start looking at the code. I might take a look later tonight, see if I can add some debugging.

**Comment by sanderjo** [comment]
"Invalid server address"? There is only one place where that code is generated: in servertests.py. So, checking: does that error only occur when you click on Test Server?

The message "Invalid server address" is generated by:

```
    except TypeError, e:
        return False, xml_name(T('Invalid server address.'))
```
A TypeError happens in case like this:
```
>>> 'abc'+1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot concatenate 'str' and 'int' objects

```

One option to analyze where your problem occurs exactly:

* Find the file sabnzbd/utils/servertests.py
* Open the file with root rights
* Find the two lines I mentioned above
* Put a "#" at the beginning of the two lines
* Save and close
* Run sabnzbd from the command line. Click on Test Server. SABnzbd should now crash. Paste the crash output here.

**Comment by kindred** [comment]
If only I had greped the code, I would have seen that.

I commented out the catch block, and now receive the following: "buf must be a byte string"

**Comment by kindred** [comment]
Here's the stack trace (I had to comment out the default exception catch code.

```
2015-05-25 00:22:39,109::INFO::[_cplogging:201] [25/May/2015:00:22:39] HTTP
Request Headers:
  COOKIE: plushHistPerPage=9999999; wanted_view2=details; manage_view2=details; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; plushQueuePerPage=9999999; plushMultiOps=0; _ga=GA1.1.695969404.1421223594; PHPSESSID=6ccqfcrs6cuuamk6rs7ag95pg6; plushContainerWidth=100%25; plushNoTopMenu=0
  ORIGIN: http://127.0.0.1:8080
  Remote-Addr: 127.0.0.1
  Content-Length: 283
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36
  CONNECTION: keep-alive
  REFERER: http://127.0.0.1:8080/config/server/
  X-REQUESTED-WITH: XMLHttpRequest
  DNT: 1
  HOST: 127.0.0.1:8080
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-US,en;q=0.8
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate
2015-05-25 00:22:39,206::ERROR::[_cplogging:201] [25/May/2015:00:22:39] HTTP Traceback (most recent call last):
  File "/home/media/sabnzbd/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/media/sabnzbd/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/media/sabnzbd/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/media/sabnzbd/sabnzbd/interface.py", line 415, in tapi
    return api_handler(kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 99, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 725, in _api_config
    return _api_config_table.get(name, (_api_config_undefined, 2))[0](output, kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 785, in _api_config_test_server
    result, msg = test_nntp_server_dict(kwargs)
  File "/home/media/sabnzbd/sabnzbd/utils/servertests.py", line 53, in test_nntp_server_dict
    password=password, ssl=ssl, ssl_type=ssl_type)
  File "/home/media/sabnzbd/sabnzbd/utils/servertests.py", line 87, in test_nntp_server
    nw.finish_connect(nw.lines[0][:3])
  File "/home/media/sabnzbd/sabnzbd/newswrapper.py", line 298, in finish_connect
    self.nntp.sock.sendall(command)
  File "<string>", line 4, in sendall
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

**Comment by sanderjo** [comment]
line 298 and around in newswrapper.py:

```
294:        if code in ('400', '502'):
295-            raise NNTPPermanentError(self.lines[0])
296-        elif not self.user_sent:
297-            command = 'authinfo user %s\r\n' % (self.server.username)
298-            self.nntp.sock.sendall(command)
299-            self.user_sent = True
300-        elif not self.user_ok:
```
Those lines are unchanged since SABnzbd 0.7.20

When I google "TypeError: buf must be a byte string", the first three hits are about ... unicode. And SAB 0.8.x introduces unicode. So, a long shot:

Change:
```
        elif not self.user_sent:
            command = 'authinfo user %s\r\n' % (self.server.username)
            self.nntp.sock.sendall(command)
```

to:
````
        elif not self.user_sent:
            command = 'authinfo user %s\r\n' % (self.server.username)
            command = command.encode('ascii', 'ignore')
            self.nntp.sock.sendall(command)
```
and try again

**Comment by kindred** [comment]
Updated the code:
```
        elif not self.user_sent:
            command = 'authinfo user %s\r\n' % (self.server.username)
            command = command.encode('ascii', 'ignore')
            self.nntp.sock.sendall(command)
            self.user_sent = True
```

I get the exact same error...

```
2015-05-25 01:19:48,738::ERROR::[_cplogging:201] [25/May/2015:01:19:48] HTTP Traceback (most recent call last):
  File "/home/media/sabnzbd/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/media/sabnzbd/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/media/sabnzbd/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/media/sabnzbd/sabnzbd/interface.py", line 415, in tapi
    return api_handler(kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 99, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 725, in _api_config
    return _api_config_table.get(name, (_api_config_undefined, 2))[0](output, kwargs)
  File "/home/media/sabnzbd/sabnzbd/api.py", line 785, in _api_config_test_server
    result, msg = test_nntp_server_dict(kwargs)
  File "/home/media/sabnzbd/sabnzbd/utils/servertests.py", line 53, in test_nntp_server_dict
    password=password, ssl=ssl, ssl_type=ssl_type)
  File "/home/media/sabnzbd/sabnzbd/utils/servertests.py", line 87, in test_nntp_server
    nw.finish_connect(nw.lines[0][:3])
  File "/home/media/sabnzbd/sabnzbd/newswrapper.py", line 314, in finish_connect
    self.nntp.sock.sendall(command)
  File "<string>", line 4, in sendall
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

**Comment by sanderjo** [comment]
Yes, same error, but ... in a different line in newswrapper.py: line 314, instead of 298. So problem in line 298 solved? That would be good.

So change it in line 314 too.

The correct change would be to change it in self.nntp.sock.sendall() itself, but I have to find out how.

**Comment by kindred** [comment]
Oh I see. I'm tired, and didn't notice.

I changed the other line, and I now get a successful connection :)

**Comment by sanderjo** [comment]
Good that it works for you. I hope Shypike can shine his light on this.

I tried sslreader.eweka.nl on my Ubuntu 15.04 with SAB 0.8.x, and that just works. So there is a difference between Ubuntu and Debian?
I have Debian on my cubox, so I'll checkk that.

**Comment by kindred** [comment]
Debian and Ubuntu tend to have different versioned libs, etc. So if something works on Ubuntu, it still may not work on Debian.

Either way, you are a champ, thanks for that :)

**Comment by sanderjo** [comment]
I tested on my Debian (Debian GNU/Linux testing (stretch)) with sslreader.eweka.nl and SABnzbd 0.8.x, and I get the same error "Invalid server address.".

![sabnzbd 0 8 x ssl problem on debian](https://cloud.githubusercontent.com/assets/1273502/7787311/801be202-0205-11e5-9421-02b46707c942.png)

**Comment by sanderjo** [comment]
On debian, the code in /usr/lib/python2.7/dist-packages/OpenSSL/SSL.py is

```
955-    def sendall(self, buf, flags=0):
956-        """
957-        Send "all" data on the connection. This calls send() repeatedly until
958-        all data is sent. If an error occurs, it's impossible to tell how much
959-        data has been sent.
960-
961-        :param buf: The string to send
962-        :param flags: (optional) Included for compatibility with the socket
963-                      API, the value is ignored
964-        :return: The number of bytes written
965-        """
966-        if isinstance(buf, _memoryview):
967-            buf = buf.tobytes()
968-        if not isinstance(buf, bytes):
969:            raise TypeError("buf must be a byte string")
```

So the isinstance(buf, bytes) is causing the exception. Let's see:

```
>>> isinstance('hello there', bytes)
True
>>> isinstance(u'hello there', bytes)
False
```
So a unicode string is not an instance of 'bytes'. The above confirms what we found and hacked around in newswrapper.py


FWIW: /usr/lib/python2.7/dist-packages/OpenSSL/SSL.py does not exist at all on my Ubuntu, but I don't know what that means.

**Comment by sanderjo** [comment]
To be complete: trying to download with Debian / pyopenssl 0.14 / SAB 0.8.x / SSL, SAB says:

```
ERROR:
Connecting 1@sslreader.eweka.nl failed, message=200 Welcome to Eweka (fx09.am4)
```

So that's the same message @lrusak reported on his FreeBSD. I guess his/her FreeBSD also uses pyopenssl 0.14.

**Comment by sanderjo** [comment]
In newswrapper.py, I replaced each
```
self.nntp.sock.sendall(command)
```
with
```
self.nntp.sock.sendall(command.encode('ascii', 'ignore'))
```
(see sed command below) and now the combination Debian / pyopenssl 0.14 / SAB 0.8.x / SSL works again.

```
sander@cubox:~$ cd git/sabnzbd/sabnzbd/

sander@cubox:~/git/sabnzbd/sabnzbd$ ll newswrapper.py*
-rw-r--r-- 1 sander sander 15301 May 24 10:46 newswrapper.py
-rw-r--r-- 1 sander sander 12243 May 24 10:55 newswrapper.pyo

sander@cubox:~/git/sabnzbd/sabnzbd$ sed -i.bak "s/self.nntp.sock.sendall(command)/self.nntp.sock.sendall(command.encode('ascii', 'ignore'))/" newswrapper.py 

sander@cubox:~/git/sabnzbd/sabnzbd$ ll newswrapper.py*
-rw-r--r-- 1 sander sander 15405 May 24 13:15 newswrapper.py
-rw-r--r-- 1 sander sander 15301 May 24 10:46 newswrapper.py.bak
-rw-r--r-- 1 sander sander 12243 May 24 10:55 newswrapper.pyo

sander@cubox:~/git/sabnzbd/sabnzbd$ grep sendall newswrapper.py
            self.nntp.sock.sendall(command.encode('ascii', 'ignore'))
            self.nntp.sock.sendall(command.encode('ascii', 'ignore'))
        self.nntp.sock.sendall(command.encode('ascii', 'ignore'))
        self.nntp.sock.sendall(command.encode('ascii', 'ignore'))
                    self.nntp.sock.sendall('QUIT\r\n')
                    self.nntp.sock.sendall('QUIT\r\n')
              'connect_ex', 'sendall', 'do_handshake', 'settimeout'):

sander@cubox:~/git/sabnzbd/sabnzbd$ 
```

**Comment by lrusak** [comment]
@sanderjo Thank you! I can confirm that your solution works.

Yes I am using pyopenssl 0.14
```
root@enterprise /usr/local/usenet/sabnzbd$ pkg info | grep py27-openssl                                                                                                                                           
py27-openssl-0.14              Python interface to the OpenSSL library
```
and Python 2.7.9
```
root@enterprise /usr/local/usenet/sabnzbd$ pkg info | grep python27                                                                                                                                               
python27-2.7.9_1               Interpreted object-oriented programming language
```

**Comment by John-Gee** [comment]
I can confirm your sed line works on my machine as well (Arch Linux with python 2.7.9 and pyopenssl 0.14).

Thank you!

**Comment by shypike** [comment]
Good detective work. I'll see how I can implement this properly in Alpha2.
Straight conversion to ASCII may prevent support for non-english server nams, but I suppose that is just a theoretical problem.

**Comment by sanderjo** [comment]
The problem is not in (non-enlighs) servers names; the problem is in the commands sent in the NNTP SSL session.

**Comment by shypike** [comment]
Can you send me the actual git patch file for this?

**Comment by DooMMasteR** [comment]
this issue is really bad for fedora 22 users as sabnzb is broken there

**Comment by sanderjo** [comment]
Can you explain? It should only happen with SABnzbd 0.8.0 alpha 1 (and you can expect brokeness from an alpha, can't you). Or do you mean it happens for other SAB versions?

**Comment by shypike** [comment]
I have narrowed the issue down to just two lines in newswrapper.py where the username and password are sent to the server. Because all user data is now handled as Unicode, the username and password are also in Unicode.
Can you do me a favour and apply just this patch in newswrapper.py?

Line 297:
`    command = 'authinfo user %s\r\n' % (self.server.username)`
becomes:
`    command = 'authinfo user %s\r\n' % (self.server.username.encode('cp1252', 'replace'))`

Line 311:
`    command = 'authinfo pass %s\r\n' % (self.server.password)`
becomes:
`    command = 'authinfo pass %s\r\n' % (self.server.password.encode('cp1252', 'replace'))`

**Comment by sanderjo** [comment]
Isn't https://github.com/sabnzbd/sabnzbd/commit/9b4102da42830fcb6a9b75445c5ce86587505404 a (different) patch for the same problem? If so, is the test you request still needed? 

Probably better to test the git version or the upcomping 0.8.0 Alpha 2?

**Comment by sanderjo** [comment]
Update:

I tested in a Debian Jessie Docker container (as my Cubox with Debian Jessie/Testing is offline).  Results:


SAB version  | Result with SSL newsserver
------------- | -------------
0.7.20 | no problem
0.8.0 alpha 1 | problem as described in this thread
0.8.0 git version | no problem

So, it is solved in the git version.



FWIW: the docker commands I used:

Start the Jessie container:
```
sudo docker run -it -p 8080:8080 -p 9090:9090 janos/jessie /bin/bash
```

In the container, first install sabnzbd (and git) and run sabnzbd:
```
echo "deb http://ftp.us.debian.org/debian jessie main contrib non-free" > /etc/apt/sources.list
apt-get update
apt-get install sabnzbdplus git 
sabnzbdplus --server 0.0.0.0:8080 -b0

```
Get and run the git version:
```
mkdir git
cd git
git clone https://github.com/sabnzbd/sabnzbd.git
cd sabnzbd/
git checkout
./SABnzbd.py 
```

**Comment by shypike** [comment]
@sanderjo 
I did some debugging and it turns out that only the username and password cause Unicode strings.
The commit solves the issue.
Thank you for all your diagnostic info.
