### ISSUE TITLE
Issues with post-process

### ISSUE THREAD

**Issue by ebaydan777** [sabnzbd/sabnzbd#2104]
I have Synology DSM 7.0.1-42218 Update 2 on 718+ and have been using sabnzbd no problem until recent 3.5.1 update. Now I have issues with post processing using nzbmedia for sickhill and getting this error:

Traceback (most recent call last):
File "/config/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
import nzbToMedia
File "/config/nzbToMedia/nzbToMedia.py", line 727, in <module>
eol.check()
File "/config/nzbToMedia/eol.py", line 99, in check
warn_for_status(version, grace_period)
File "/config/nzbToMedia/eol.py", line 140, in warn_for_status
days_left = lifetime(version)
File "/config/nzbToMedia/eol.py", line 70, in lifetime
time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 9)

Not sure what to do, never seen this error before.

**Comment by sanderjo** [comment]
```
File "/config/nzbToMedia/eol.py", line 70, in lifetime
time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 9)
```

Problem in nzbToMedia, so report there: https://github.com/clinton-hall/nzbToMedia

**Comment by Safihre** [comment]
Not a problem, just you are using a version of that script that's ancient and doesn't know about Python 3.9 yet. You'll just have to update.
