### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'lower'" in nzbstuff.postpone_pars()

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2132]
Noticed this traceback in the log when doing a 1GB test download for the 3.6.0b1 package on bionic/18.04. Single server configured with 2 connections, prio Force, pp +Delete; several articles missing but the job eventually finished fine after repair.

```
2022-03-22 15:58:04,651::DEBUG::[nzbstuff:389] Finishing import on sometestfile-1000MB.vol003+004.par2
2022-03-22 15:58:04,652::DEBUG::[filesystem:1143] [sabnzbd.nzbstuff.finish_import] Loading data for SABnzbd_nzf_nga6f7pe from /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf_nga6f7pe
2022-03-22 15:58:04,653::DEBUG::[assembler:109] Decoding part of /home/ubuntu/Downloads/incomplete/test_download_1000MB/sometestfile-1000MB.part67.rar
2022-03-22 15:58:04,673::DEBUG::[filesystem:904] [sabnzbd.filesystem.load_data] Deleting file /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_article_cq1flwvd
2022-03-22 15:58:04,690::DEBUG::[downloader:906] Thread 2@eu.newsdemon.com: Article NgLuDgGuWrGbEnKpRpNiMvDp-1634895049236@nyuu missing (error=430)
2022-03-22 15:58:04,690::INFO::[nzbstuff:262] Article NgLuDgGuWrGbEnKpRpNiMvDp-1634895049236@nyuu unavailable on all servers, discarding
2022-03-22 15:58:04,690::DEBUG::[nzbstuff:1519] Availability ratio=109.73, bad articles=6, total bytes=1173636182, missing bytes=4766576, par2 bytes=108419252
2022-03-22 15:58:04,708::INFO::[assembler:117] Decoding finished /home/ubuntu/Downloads/incomplete/test_download_1000MB/sometestfile-1000MB.part67.rar
2022-03-22 15:58:04,708::DEBUG::[nzbstuff:463] Removing article database for SABnzbd_nzf_9asu80mk
2022-03-22 15:58:04,709::DEBUG::[filesystem:904] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf_9asu80mk
2022-03-22 15:58:04,710::DEBUG::[assembler:109] Decoding part of /home/ubuntu/Downloads/incomplete/test_download_1000MB/sometestfile-1000MB.vol001+002.par2
2022-03-22 15:58:04,718::DEBUG::[filesystem:904] [sabnzbd.filesystem.load_data] Deleting file /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_article_x2209yfj
2022-03-22 15:58:04,721::INFO::[assembler:117] Decoding finished /home/ubuntu/Downloads/incomplete/test_download_1000MB/sometestfile-1000MB.vol001+002.par2
2022-03-22 15:58:04,722::DEBUG::[nzbstuff:463] Removing article database for SABnzbd_nzf_s_ja5clk
2022-03-22 15:58:04,722::DEBUG::[filesystem:904] [sabnzbd.nzbstuff.remove_admin] Deleting file /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf_s_ja5clk
2022-03-22 15:58:04,725::DEBUG::[nzbstuff:1066] Got md5pack for set sometestfile-1000MB
2022-03-22 15:58:04,725::DEBUG::[nzbstuff:1069] Found duplicate md5pack-setname: sometestfile-1000MB, using set ID
2022-03-22 15:58:04,756::INFO::[notifier:123] Sending notification: Fout - Onherstelbare fout in de Assembler (type=error, job_cat=None)
2022-03-22 15:58:04,726::ERROR::[assembler:206] Onherstelbare fout in de Assembler
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/assembler.py", line 166, in run
    nzo.handle_par2(nzf, filepath)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 1073, in handle_par2
    self.postpone_pars(nzf, setname)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 1026, in postpone_pars
    lparset = parset.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
2022-03-22 15:58:04,963::DEBUG::[nzbstuff:389] Finishing import on sometestfile-1000MB.vol007+008.par2
2022-03-22 15:58:04,964::DEBUG::[filesystem:1143] [sabnzbd.nzbstuff.finish_import] Loading data for SABnzbd_nzf_l9liykv8 from /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf_l9liykv8
2022-03-22 15:58:05,515::DEBUG::[downloader:906] Thread 1@eu.newsdemon.com: Article NuAzUyLjCfGhJxPwOnXgLdHv-1634895050468@nyuu missing (error=430)
2022-03-22 15:58:05,516::INFO::[nzbstuff:262] Article NuAzUyLjCfGhJxPwOnXgLdHv-1634895050468@nyuu unavailable on all servers, discarding
2022-03-22 15:58:05,516::DEBUG::[nzbstuff:1519] Availability ratio=109.66, bad articles=7, total bytes=1173636182, missing bytes=5495653, par2 bytes=108419252
2022-03-22 15:58:05,728::DEBUG::[nzbstuff:389] Finishing import on sometestfile-1000MB.vol015+016.par2
2022-03-22 15:58:05,729::DEBUG::[filesystem:1143] [sabnzbd.nzbstuff.finish_import] Loading data for SABnzbd_nzf__3wz59jx from /home/ubuntu/Downloads/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf__3wz59jx
```

**Comment by Safihre** [comment]
Do you maybe also have the whole log of the download? Probably went wrong somewhere at the start.

**Comment by thezoggy** [comment]
No pars?

**Comment by jcfp** [comment]
[log.txt](https://github.com/sabnzbd/sabnzbd/files/8327922/log.txt)

The traceback happens during the 1000MB test download; there's another 100MB test download before that. I did hit ctrl+c a couple of times, that explains the signal 2 shutdowns.

**Comment by jcfp** [comment]
> No pars?

It's the standard test jobs, afaik these do include ~10% par2 cover.

**Comment by puzzledsab** [comment]
Is https://github.com/sabnzbd/sabnzbd/commit/80a2ffdeadc1bcab2798d30140b6c6f7ccb2d83b intended to help with this issue?

I don't have any solutions but I noticed that https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L1069 is triggered. I think it would be helpful if it also included the set id.
