### ISSUE TITLE
"TypeError: sequence item 0: expected str instance, int found" in database.build_history_info()

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2134]
As reported [here](https://old.reddit.com/r/SABnzbd/comments/tn25bh/sudden_error_with_sabnzbd_seems_to_now_be_unusable/) on reddit, with 3.5.3.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/sabnzbd/sabnzbd/interface.py", line 171, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/app/sabnzbd/sabnzbd/interface.py", line 460, in api
    return api_handler(kwargs)
  File "/app/sabnzbd/sabnzbd/api.py", line 99, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/app/sabnzbd/sabnzbd/api.py", line 580, in _api_history
    history["slots"], history["noofslots"] = build_history(
  File "/app/sabnzbd/sabnzbd/api.py", line 1784, in build_history
    items = get_active_history(postproc_queue, items)
  File "/app/sabnzbd/sabnzbd/api.py", line 1853, in get_active_history
    ) = build_history_info(nzo)
  File "/app/sabnzbd/sabnzbd/database.py", line 470, in build_history_info
    lines.append("%s:::%s" % (key, ";".join(results)))
TypeError: sequence item 0: expected str instance, int found 
```

**Comment by Safihre** [comment]
I think this is fixed in 3.6.0.

**Comment by jcfp** [comment]
Let's hope so, don't have a way to reproduce this myself but the impact seemed rather unpleasant.

**Comment by thezoggy** [comment]
Prob related to the deobfusication history stuff was added. Maybe result was a series of all numbers?

**Comment by Safihre** [comment]
> Prob related to the deobfusication history stuff was added. Maybe result was a series of all numbers?

That was only added in 3.6.0.

**Comment by Safihre** [comment]
Added a safeguard to be sure.
