### ISSUE TITLE
ENGINE Error in HTTPServer.serve (sab 3.5.3, fedora 36 x86_64, python 3.10.4)

### ISSUE THREAD

**Issue by wirerydr** [sabnzbd/sabnzbd#2178]
Hello all - I've been trying to debug a fresh-install of sabnzbd on a newly-installed Fedora 36 host, and have encountered a `ENGINE Error in HTTPServer.serve` error that I'm hoping I can ask for some help in troubleshooting.  I have searched for similar issue reports, but came up with nothing, with the next-closest reports involving **_HTTPServer.tick_**, not **_HTTPserver.serve_**.

I have also tested with the latest git commit (c1b9b72), with the same result.

Platform details, versioning info, and the debug log (including traceback) are all shown below.

I have a working instance on a Fedora 34 host, with the major differences being:  Python 3.9.12, cheroot 8.5.2, and cherrypy 18.6.0).  On the host with the problems, I tried downgrading cheroot and cherrypy to those versions, but experienced the same issue.

Any advice on next troubleshooting steps, or suggestions on what I am doing wrong, would be greatly appreciated.

sabnzbd version: **3.5.3 (Installed from GH release source tarball)**

Platform: **Fedora 36 x86_64**

Python: **3.10.4**

Python Modules (output of 'pip list')
```babelfish          0.6.0
cffi               1.15.0
chardet            4.0.0
Cheetah3           3.2.6
cheroot            8.6.0
CherryPy           18.6.1
configobj          5.0.6
cryptography       36.0.1
feedparser         6.0.8
gpg                1.15.1
guessit            3.4.3
iotop              0.6
jaraco.classes     3.2.1
jaraco.collections 3.5.1
jaraco.context     4.1.1
jaraco.functools   3.5.0
jaraco.text        3.7.0
more-itertools     8.12.0
nftables           0.1
notify2            0.3.1
pip                21.3.1
portend            3.1.0
puremagic          1.11
pycparser          2.21
PyGObject          3.42.0
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2021.3
rebulk             3.1.0
rpm                4.17.0
sabyenc3           4.0.2
selinux            3.3
setuptools         59.6.0
sgmllib3k          1.0.0
six                1.16.0
tempora            5.0.1
zc.lockfile        2.0
```

Debugging Log / Traceback
```
2022-05-15 11:58:27,206::INFO::[SABnzbd:1166] --------------------------------
2022-05-15 11:58:27,207::INFO::[SABnzbd:1167] SABnzbd.py-3.5.3
2022-05-15 11:58:27,207::INFO::[SABnzbd:1177] Commit = bca9f3b753f2d68263ca62c5b677d63458ba56c2
2022-05-15 11:58:27,207::INFO::[SABnzbd:1179] Full executable path = /opt/sabnzbd/sabnzbd-current/SABnzbd.py
2022-05-15 11:58:27,207::INFO::[SABnzbd:1180] Arguments = "/opt/sabnzbd/sabnzbd-current/SABnzbd.py" "--daemon" "--config-file" "/etc/sabnzbd/sabnzbd.ini" "--browser" "0"
2022-05-15 11:58:27,207::INFO::[SABnzbd:1181] Python-version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
2022-05-15 11:58:27,208::INFO::[SABnzbd:1182] Dockerized = False
2022-05-15 11:58:27,208::INFO::[SABnzbd:1183] CPU architecture = x86_64
2022-05-15 11:58:27,209::INFO::[SABnzbd:1186] Platform = posix - Linux-5.17.5-300.fc36.x86_64-x86_64-with-glibc2.35
2022-05-15 11:58:27,209::INFO::[SABnzbd:1192] Preferred encoding = UTF-8
2022-05-15 11:58:27,209::INFO::[SABnzbd:1211] SSL version = OpenSSL 3.0.2 15 Mar 2022
2022-05-15 11:58:27,265::DEBUG::[SABnzbd:1230] Available certificates = {'x509': 131, 'crl': 0, 'x509_ca': 131}
2022-05-15 11:58:27,265::DEBUG::[SABnzbd:1233] Local IPv4 address = 192.168.240.48
2022-05-15 11:58:27,671::DEBUG::[SABnzbd:1234] Public IPv4 address = 1.2.3.4
2022-05-15 11:58:27,671::DEBUG::[SABnzbd:1235] IPv6 address = None
2022-05-15 11:58:27,901::DEBUG::[SABnzbd:1238] CPU Pystone available performance = 166907
2022-05-15 11:58:27,901::DEBUG::[SABnzbd:1239] CPU model = AMD Ryzen 7 2700X Eight-Core Processor
2022-05-15 11:58:27,902::INFO::[SABnzbd:1241] Using INI file /etc/sabnzbd/sabnzbd.ini
2022-05-15 11:58:27,923::DEBUG::[filesystem:1184] [sabnzbd.bpsmeter.read] Loading data for totals10.sab
2022-05-15 11:58:27,923::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for totals10.sab from /opt/sabnzbd/admin/totals10.sab
2022-05-15 11:58:27,923::DEBUG::[downloader:263] Initializing downloader
2022-05-15 11:58:27,923::DEBUG::[downloader:459] Sleep time: 0.001000 seconds
2022-05-15 11:58:27,924::DEBUG::[decoder:69] Initializing decoders
2022-05-15 11:58:27,924::DEBUG::[decoder:117] Initializing decoder Thread-6
2022-05-15 11:58:27,924::DEBUG::[decoder:117] Initializing decoder Thread-7
2022-05-15 11:58:27,924::DEBUG::[decoder:117] Initializing decoder Thread-8
2022-05-15 11:58:27,924::INFO::[postproc:133] Loading postproc queue
2022-05-15 11:58:27,924::DEBUG::[filesystem:1184] [sabnzbd.postproc.load] Loading data for postproc2.sab
2022-05-15 11:58:27,924::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for postproc2.sab from /opt/sabnzbd/admin/postproc2.sab
2022-05-15 11:58:27,924::DEBUG::[filesystem:1184] [sabnzbd.dirscanner.__init__] Loading data for watched_data2.sab
2022-05-15 11:58:27,924::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for watched_data2.sab from /opt/sabnzbd/admin/watched_data2.sab
2022-05-15 11:58:27,924::DEBUG::[filesystem:1184] [sabnzbd.rating.__init__] Loading data for Rating.sab
2022-05-15 11:58:27,924::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for Rating.sab from /opt/sabnzbd/admin/Rating.sab
2022-05-15 11:58:27,925::DEBUG::[filesystem:1184] [sabnzbd.rss.__init__] Loading data for rss_data.sab
2022-05-15 11:58:27,925::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for rss_data.sab from /opt/sabnzbd/admin/rss_data.sab
2022-05-15 11:58:27,925::INFO::[scheduler:188] Scheduling RSS interval task every 60 min (delay=1)
2022-05-15 11:58:27,925::INFO::[scheduler:213] Setting schedule for midnight BPS reset
2022-05-15 11:58:27,925::INFO::[scheduler:216] Setting schedule for server expiration check
2022-05-15 11:58:27,925::INFO::[scheduler:221] Setting scheduler for server quota check
2022-05-15 11:58:27,925::DEBUG::[filesystem:1184] [sabnzbd.nzbqueue.read_queue] Loading data for queue10.sab
2022-05-15 11:58:27,925::DEBUG::[filesystem:1143] [sabnzbd.filesystem.load_admin] Loading data for queue10.sab from /opt/sabnzbd/admin/queue10.sab
2022-05-15 11:58:27,925::DEBUG::[downloader:1166] PAUSED_ALL inactive
2022-05-15 11:58:27,925::INFO::[__init__:321] All processes started
2022-05-15 11:58:27,925::INFO::[SABnzbd:336] Template location for Glitter is /opt/sabnzbd/sabnzbd-current/interfaces/Glitter
2022-05-15 11:58:27,926::INFO::[SABnzbd:336] Template location for Config is /opt/sabnzbd/sabnzbd-current/interfaces/Config
2022-05-15 11:58:27,926::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/unrar']
2022-05-15 11:58:27,926::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-05-15 11:58:27,928::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/7za']
2022-05-15 11:58:27,928::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-05-15 11:58:27,932::INFO::[misc:1161] [sabnzbd.misc.run_command] Running external command: ['/usr/bin/par2', '-h']
2022-05-15 11:58:27,932::DEBUG::[misc:1162] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
2022-05-15 11:58:27,933::INFO::[SABnzbd:423] SABYenc module (v4.0.2)... found!
2022-05-15 11:58:27,934::INFO::[SABnzbd:442] Cryptography module (v36.0.1)... found!
2022-05-15 11:58:27,934::INFO::[SABnzbd:447] par2 binary... found (/usr/bin/par2)
2022-05-15 11:58:27,934::INFO::[SABnzbd:454] UNRAR binary... found (/usr/bin/unrar)
2022-05-15 11:58:27,934::INFO::[SABnzbd:462] UNRAR binary version 6.11
2022-05-15 11:58:27,934::INFO::[SABnzbd:470] 7za binary... found (/usr/bin/7za)
2022-05-15 11:58:27,934::INFO::[SABnzbd:472] 7za binary version 16.02
2022-05-15 11:58:27,934::INFO::[SABnzbd:483] nice binary... found (/usr/bin/nice)
2022-05-15 11:58:27,934::INFO::[SABnzbd:487] ionice binary... found (/usr/bin/ionice)
2022-05-15 11:58:27,947::INFO::[SABnzbd:1298] HTTPS keys are OK
2022-05-15 11:58:27,948::INFO::[SABnzbd:1430] Starting web-interface on mediabox-f36.example.com:9091
2022-05-15 11:58:27,948::INFO::[_cplogging:213] [15/May/2022:11:58:27] ENGINE Bus STARTING
2022-05-15 11:58:28,066::INFO::[_cplogging:213] [15/May/2022:11:58:28] ENGINE Serving on https://mediabox-f36.example.com:9091
2022-05-15 11:58:28,069::INFO::[notifier:123] Sending notification: Error - [15/May/2022:11:58:28] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cheroot/server.py", line 1823, in serve
    self._connections.run(self.expiration_interval)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 203, in run
    self._run(expiration_interval)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 246, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 300, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.10/site-packages/cheroot/ssl/builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib64/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib64/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)
 (type=error, job_cat=None)
2022-05-15 11:58:28,069::ERROR::[_cplogging:213] [15/May/2022:11:58:28] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cheroot/server.py", line 1823, in serve
    self._connections.run(self.expiration_interval)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 203, in run
    self._run(expiration_interval)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 246, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/usr/local/lib/python3.10/site-packages/cheroot/connections.py", line 300, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.10/site-packages/cheroot/ssl/builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib64/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib64/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

2022-05-15 11:58:28,168::INFO::[_cplogging:213] [15/May/2022:11:58:28] ENGINE Serving on http://mediabox-f36.example.com:9090
2022-05-15 11:58:28,169::INFO::[_cplogging:213] [15/May/2022:11:58:28] ENGINE Bus STARTED
2022-05-15 11:58:28,169::INFO::[SABnzbd:1469] Starting SABnzbd.py-3.5.3
2022-05-15 11:58:28,169::DEBUG::[__init__:329] Starting postprocessor
2022-05-15 11:58:28,169::DEBUG::[__init__:332] Starting assembler
2022-05-15 11:58:28,170::DEBUG::[__init__:335] Starting downloader
2022-05-15 11:58:28,170::DEBUG::[__init__:338] Starting decoders
2022-05-15 11:58:28,171::DEBUG::[__init__:341] Starting scheduler
2022-05-15 11:58:28,171::DEBUG::[__init__:344] Starting dirscanner
2022-05-15 11:58:28,172::INFO::[dirscanner:117] Dirscanner starting up
2022-05-15 11:58:28,172::DEBUG::[__init__:347] Starting rating
2022-05-15 11:58:28,172::DEBUG::[__init__:350] Starting urlgrabber
2022-05-15 11:58:28,172::INFO::[notifier:123] Sending notification: SABnzbd - SABnzbd 3.5.3 started (type=startup, job_cat=None)
2022-05-15 11:58:28,173::DEBUG::[SABnzbd:1504] Using 192.168.240.48 as host address for Bonjour and SSDP
2022-05-15 11:58:28,173::INFO::[zconfig:61] No bonjour/zeroconf support installed
2022-05-15 11:58:28,173::INFO::[ssdp:108] Serving SSDP on 192.168.240.48 as SABnzbd
2022-05-15 11:58:28,173::DEBUG::[postproc:231] Completed Download Folder /var/data/media/in/downloads/complete is not on FAT
2022-05-15 11:58:28,197::DEBUG::[misc:1233] Test IPv6: Cannot reach IPv6 test host. Disabling IPv6
2022-05-15 11:58:28,197::DEBUG::[downloader:550] External IPv6 test result: False
2022-05-15 11:58:28,291::DEBUG::[downloader:554] SSL verification test: True
```

**Comment by sanderjo** [comment]
Ah, yes, cherrypy / cheroot SSL errors ...

Does it happen always? At startup? After that?
Does SAB keep running, including web interface?

**Comment by Safihre** [comment]
Indeed a common problem, for which we have no real solution because it happens in a dependency of SABnzbd. It happens because the browser checks for the certificate of the server and then aborts. 
Similar rapports: https://github.com/sabnzbd/sabnzbd/issues?q=is%3Aissue+_ssl.c

Just to be sure, you are still able to use SABnzbd normally, it just throws this error when opening the page in the browser?

**Comment by wirerydr** [comment]
The error logs emit at startup, before I've hit it with any sort of browser client.  When I do browse to it, the login screen displays normally, and seems to function (i.e. it rejects invalid creds, accepts valid ones).

Once I successfully log in, the main window pane starts showing the traceback output.  I haven't tried to queue up any actual downloads, but I have navigated other parts of the app, mostly within the config section.  They all seem to display properly.  When I go back to the main display, again the traceback displays.

When I re-examined my logs, it looks like the traceback is only getting generated when the app is started.  Logging in, and moving around the config screens does not seem to log any fresh tracebacks.  Same for logging out and then back in.

However whatever that traceback was, gets displayed on the main window in sab itself whenever I navigate there.  If I shut down the app and restart it, fresh error output appears in the log....

**Comment by thezoggy** [comment]
been reported by many users over the years (myself included) basically fallout from ssl handoff from browser to client. stuff terminates abruptly or browsers send multiple requests to nego higher tls and the earlier ones get drop. happens if you open up new tab+incognito and refresh. can make it happen in various methods, sadly why i end up having 20+ warnings in sab all the time because of it :/  i spent a bit of time one weekend trying to figure out how to stop it but nothing i could do in sab (or even monkey patching cheroot) could fix it. its a lower level ssl socket issue that we cant do anything about

**Comment by wirerydr** [comment]
Thanks for information, folks - it helps.  Since sab does appear able to start and finish downloads, I guess my only real question left is:  is there any way to suppress the traceback output in the queue display?  As it is now, it totally obscures the regular output, making the queue display totally unreadable.

Thanks again

**Comment by Safihre** [comment]
Click the X icon next to the traceback.
And of course disabling HTTPS will remove the traceback.

It seems to be at start-up that cherrypy does a self-check by connecting to itself, which fails. Resulting in the 2 tracebacks.
