### ISSUE TITLE
Opening "Status and interface options" leads to Traceback in publicipv4(), TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2217]
SAB git version 3.7.0-develop (1c6f2e9d1), on Ubuntu 22.04, python 3.10, on RISC-V SBC, with standard network & DNS, no Docker:

Clicking on "Opening Status and interface options" each time leads to Traceback below.

FWIW: 
* the sabnzbdplus-3.5.1 provided by Ubuntu just works.
* for the sab git version: no correct version of sabyenc3 installed, but I guess that doesn't matter
* manual publicipv4() gives a nice IPv4, witih short time.

```
2022-06-21 21:02:51,159::DEBUG::[getipaddress:149] Public IPv4 address = 1.1.162.65 (in 0.09 seconds)

2022-06-21 21:03:32,234::DEBUG::[getipaddress:101] Local IPv4 address = 192.168.1.6
2022-06-21 21:03:32,274::INFO::[notifier:123] Sending notification: Error - [21/Jun/2022:21:03:32] HTTP  (type=error, job_cat=None)
2022-06-21 21:03:32,240::ERROR::[_cplogging:213] [21/Jun/2022:21:03:32] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/git/sabnzbd/sabnzbd/interface.py", line 180, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/root/git/sabnzbd/sabnzbd/interface.py", line 472, in api
    return api_handler(kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 104, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 426, in _api_status
    return _api_status_table.get(name, (_api_fullstatus, 2))[0](value, kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 417, in _api_fullstatus
    status = build_status(
  File "/root/git/sabnzbd/sabnzbd/api.py", line 1268, in build_status
    info["publicipv4"] = publicipv4()
  File "/root/git/sabnzbd/sabnzbd/getipaddress.py", line 122, in publicipv4
    for item in lookup_result_iv4:
TypeError: 'NoneType' object is not iterable
2022-06-21 21:03:32,294::INFO::[_cplogging:213] [21/Jun/2022:21:03:32] HTTP 
Request Headers:
  Remote-Addr: 3.4.17.26
  HOST: 1.1.162.65:28080
  CONNECTION: keep-alive
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  REFERER: http://1.1.162.65:28080/
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6
```

And FWIW: after clicking on the Refresh arrow in the Status popup, results in another Traceback:

```
2022-06-21 21:08:42,030::INFO::[notifier:123] Sending notification: Error - [21/Jun/2022:21:08:42] HTTP  (type=error, job_cat=None)
2022-06-21 21:08:42,022::ERROR::[_cplogging:213] [21/Jun/2022:21:08:42] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/git/sabnzbd/sabnzbd/interface.py", line 180, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/root/git/sabnzbd/sabnzbd/interface.py", line 472, in api
    return api_handler(kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 104, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 426, in _api_status
    return _api_status_table.get(name, (_api_fullstatus, 2))[0](value, kwargs)
  File "/root/git/sabnzbd/sabnzbd/api.py", line 417, in _api_fullstatus
    status = build_status(
  File "/root/git/sabnzbd/sabnzbd/api.py", line 1234, in build_status
    internetspeed_future = sabnzbd.THREAD_POOL.submit(internetspeed)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
2022-06-21 21:08:42,051::INFO::[_cplogging:213] [21/Jun/2022:21:08:42] HTTP 
Request Headers:
  Remote-Addr: 3.4.17.26
  HOST: 1.1.162.65:28080
  CONNECTION: keep-alive
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  REFERER: http://1.1.162.65:28080/
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-NL,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,en-US;q=0.6
```

```
root@nezha:~/git/sabnzbd# python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabnzbd.getipaddress
>>> sabnzbd.getipaddress.publicipv4()
'1.1.162.65'
>>> 
```

**Comment by sanderjo** [comment]
With SABnzbd 3.6.0, opening the Status popup, immediatly results in

```
2022-06-21 21:38:59,421::DEBUG::[getipaddress:100] Local IPv4 address = 192.168.1.6
2022-06-21 21:38:59,485::INFO::[notifier:123] Sending notification: Error - [21/Jun/2022:21:38:59] HTTP  (type=error, job_cat=None)
2022-06-21 21:38:59,426::ERROR::[_cplogging:213] [21/Jun/2022:21:38:59] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/interface.py", line 180, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/interface.py", line 472, in api
    return api_handler(kwargs)
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/api.py", line 104, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/api.py", line 414, in _api_status
    return _api_status_table.get(name, (_api_fullstatus, 2))[0](value, kwargs)
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/api.py", line 405, in _api_fullstatus
    status = build_status(
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/api.py", line 1256, in build_status
    info["publicipv4"] = publicipv4()
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/getipaddress.py", line 114, in publicipv4
    result = addresslookup4(sabnzbd.cfg.selftest_host())
  File "/root/Downloads/SABnzbd-3.6.0/sabnzbd/getipaddress.py", line 48, in func_wrapper
    return sabnzbd.THREAD_POOL.submit(item, *args, **kwargs).result(max_timeout)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

**Comment by sanderjo** [comment]
If I change `lookup_result_iv4 =` to below, the first Traceback is gone. So something with the timeout decorator causes the problem ... and only if called from the popup window ... ? 


```
    try:
        # look up IPv4 addresses of selftest_host
        lookup_result_iv4 = socket.getaddrinfo(sabnzbd.cfg.selftest_host(), 80, socket.AF_INET)   # addresslookup4(sabnzbd.cfg.selftest_host(>
    except Exception:
        # something very bad: no name resolving of selftest_host
        logging.debug("Failed to detect public IPv4 address: looking up %s failed", sabnzbd.cfg.selftest_host())
        return None
```

**Comment by Safihre** [comment]
Pushed a fix for the crash.
