### ISSUE TITLE
Traceback "'NoneType' object has no attribute 'bytes'"  NzbFile.__eq__(self, other)

### ISSUE THREAD

**Issue by Gogglemex** [sabnzbd/sabnzbd#2295]
Hello!

Every so often Sabnzb crashes with the following traceback. Unfortunately, the auto restart does not work and I have to restart sabnzb manually.

Sabnzb 3.6.1
Fedora 36
Python 3.10

If I should supply any other info, please let me know!

```
2022-09-12 08:45:49,877::INFO::[nzbstuff:262] Article 1265164107.43626.3@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,882::INFO::[nzbstuff:262] Article 1265164107.48584.4@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,882::INFO::[nzbstuff:262] Article 1265164107.56999.5@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,884::INFO::[nzbstuff:262] Article 1265164107.59022.6@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,885::INFO::[nzbstuff:262] Article 1265164107.60157.7@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,886::INFO::[nzbstuff:262] Article 1265164107.67343.8@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,888::INFO::[nzbstuff:262] Article 1265164107.72701.9@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,888::INFO::[nzbstuff:262] Article 1265164107.80679.10@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,888::INFO::[nzbstuff:262] Article 1265164107.89542.11@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,893::INFO::[nzbstuff:262] Article 1265164108.00495.12@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,894::INFO::[nzbstuff:262] Article 1265164108.06187.13@eu.news.astraweb.com unavailable on all servers, discarding
2022-09-12 08:45:49,894::INFO::[nzbstuff:262] Article 1265164108.11662.14@eu.news.astraweb.com unavailable on all servers, discarding
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/share/sabnzb/sabnzbd/downloader.py", line 935, in run
    self.decode(article, nw.data)
  File "/usr/share/sabnzb/sabnzbd/downloader.py", line 523, in decode
    sabnzbd.NzbQueue.register_article(article, success=False)
  File "/usr/share/sabnzb/sabnzbd/nzbqueue.py", line 754, in register_article
    and not sabnzbd.Assembler.partial_nzf_in_queue(nzf)
  File "/usr/share/sabnzb/sabnzbd/assembler.py", line 63, in partial_nzf_in_queue
    return (nzf.nzo, nzf, False) in self.queue.queue
  File "/usr/share/sabnzb/sabnzbd/nzbstuff.py", line 502, in __eq__
    if self.bytes == other.bytes or len(self.decodetable) == len(other.decodetable):
AttributeError: 'NoneType' object has no attribute 'bytes'
```

**Comment by Safihre** [comment]
Apologies for the late reply.
Seems indeed like a bug. 
Is this on regular jobs or ones that Retry was used on?
How many servers do you have?
Do you use automation apps?

**Comment by martijndierckx** [comment]
Same error here using linuxserver docker image 3.6.1:
When will 3.7 be released? Or will there be a fix release?

```
2022-10-03 01:36:29,159::DEBUG::[downloader:908] Thread 30@news.bulknews.eu: Article LHR6Zn-kID-g@6-29o-Xblj6f missing (error=430)
2022-10-03 01:36:29,159::INFO::[nzbstuff:262] Article LHR6Zn-kID-g@6-29o-Xblj6f unavailable on all servers, discarding
2022-10-03 01:36:29,159::DEBUG::[nzbstuff:1538] Availability ratio=106.28, bad articles=58, total bytes=13996210580, missing bytes=229549415, par2 bytes=1042938751
2022-10-03 01:36:29,160::DEBUG::[downloader:908] Thread 29@news.bulknews.eu: Article oQ0fVe-72O-l@v-x93-F3rBkm missing (error=430)
2022-10-03 01:36:29,160::INFO::[nzbstuff:262] Article oQ0fVe-72O-l@v-x93-F3rBkm unavailable on all servers, discarding
2022-10-03 01:36:29,160::DEBUG::[nzbstuff:1538] Availability ratio=106.25, bad articles=59, total bytes=13996210580, missing bytes=233510394, par2 bytes=1042938751
2022-10-03 01:36:29,160::DEBUG::[downloader:908] Thread 2@news.bulknews.eu: Article a9GYza-pdX-m@i-GYu-8mpnUi missing (error=430)
2022-10-03 01:36:29,160::INFO::[nzbstuff:262] Article a9GYza-pdX-m@i-GYu-8mpnUi unavailable on all servers, discarding
2022-10-03 01:36:29,161::DEBUG::[nzbstuff:1538] Availability ratio=106.22, bad articles=60, total bytes=13996210580, missing bytes=237471396, par2 bytes=1042938751
2022-10-03 01:36:29,162::DEBUG::[downloader:908] Thread 3@news.bulknews.eu: Article bQA0FF-n57-9@h-nLL-ejIouD missing (error=430)
2022-10-03 01:36:29,162::INFO::[nzbstuff:262] Article bQA0FF-n57-9@h-nLL-ejIouD unavailable on all servers, discarding
2022-10-03 01:36:29,162::DEBUG::[nzbstuff:1538] Availability ratio=106.19, bad articles=61, total bytes=13996210580, missing bytes=241432879, par2 bytes=1042938751
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/app/sabnzbd/sabnzbd/downloader.py", line 935, in run
    self.decode(article, nw.data)
  File "/app/sabnzbd/sabnzbd/downloader.py", line 523, in decode
    sabnzbd.NzbQueue.register_article(article, success=False)
  File "/app/sabnzbd/sabnzbd/nzbqueue.py", line 754, in register_article
    and not sabnzbd.Assembler.partial_nzf_in_queue(nzf)
  File "/app/sabnzbd/sabnzbd/assembler.py", line 63, in partial_nzf_in_queue
    return (nzf.nzo, nzf, False) in self.queue.queue
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 502, in __eq__
    if self.bytes == other.bytes or len(self.decodetable) == len(other.decodetable):
AttributeError: 'NoneType' object has no attribute 'bytes'
```

**Comment by Safihre** [comment]
You can switch to their beta/unstable tag to get the 3.7 test release.
