### ISSUE TITLE
Restarting because of crashed postprocessor (Issues with Python 3.8?)

### ISSUE THREAD

**Issue by neeo** [sabnzbd/sabnzbd#2390]
It seems that Python 3.8 is causing some issues (at least with Ubuntu). Server is stuck restarting on a loop (Restarting because of crashed postprocessor)

Error log: [exception.log](https://github.com/sabnzbd/sabnzbd/files/10325485/exception.log)

Any idea how to solve this?

Thanks

**Comment by sanderjo** [comment]
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 602, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 291, in run
    process_job(nzo)
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 656, in process_job
    history_db.add_history_db(nzo, workdir_complete, postproc_time, script_log, script_line)
  File "/usr/share/sabnzbdplus/sabnzbd/database.py", line 282, in add_history_db
    t = build_history_info(nzo, storage, postproc_time, script_output, script_line, series_info=True)
  File "/usr/share/sabnzbdplus/sabnzbd/database.py", line 478, in build_history_info
    seriesname, season, episode = sabnzbd.newsunpack.analyse_show(nzo.final_name)[:3]
  File "/usr/share/sabnzbdplus/sabnzbd/newsunpack.py", line 2260, in analyse_show
    job = SeriesSorter(None, name, None, None, force=True)
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 356, in __init__
    super().__init__(nzo, job_name, path, cat, cfg.tv_sort_string(), cfg.tv_categories(), guess, force)
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 89, in __init__
    self.match()
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 362, in match
    self.guess = guess_what(self.original_job_name, sort_type="episode")
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 610, in guess_what
    guess = guessit.api.guessit(digit_fix + name, options=guessit_options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=(removed)
options={'expected_title': [], 'excludes': ['part'], 'date_year_first': True, 'type': 'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 602, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 602, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 291, in run
    process_job(nzo)
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 656, in process_job
    history_db.add_history_db(nzo, workdir_complete, postproc_time, script_log, script_line)
  File "/usr/share/sabnzbdplus/sabnzbd/database.py", line 282, in add_history_db
    t = build_history_info(nzo, storage, postproc_time, script_output, script_line, series_info=True)
  File "/usr/share/sabnzbdplus/sabnzbd/database.py", line 478, in build_history_info
    seriesname, season, episode = sabnzbd.newsunpack.analyse_show(nzo.final_name)[:3]
  File "/usr/share/sabnzbdplus/sabnzbd/newsunpack.py", line 2260, in analyse_show
    job = SeriesSorter(None, name, None, None, force=True)
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 356, in __init__
    super().__init__(nzo, job_name, path, cat, cfg.tv_sort_string(), cfg.tv_categories(), guess, force)
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 89, in __init__
    self.match()
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 362, in match
    self.guess = guess_what(self.original_job_name, sort_type="episode")
  File "/usr/share/sabnzbdplus/sabnzbd/sorting.py", line 610, in guess_what
    guess = guessit.api.guessit(digit_fix + name, options=guessit_options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=(removed)
options={'expected_title': [], 'excludes': ['part'], 'date_year_first': True, 'type': 'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 351, in compile
    return _compile(pattern, flags, ignore_unused, kwargs, _cache_all)
  File "/home/sab/.local/lib/python3.8/site-packages/regex/regex.py", line 602, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by sanderjo** [comment]
I would update  guessit, (also) via pip3.

**Comment by neeo** [comment]
I found a thread in the forum that recommended uninstalling python-regex, and that seamed to fix the issue. Closing this.
