### ISSUE TITLE
SABnzbd on Linux on ChromeOS: repeatedly ERROR " Unable to set arguments ('SABnzbd', 0, '/home/sander/git/sabnzbd/interfaces/Config/templates/staticcfg/images/logo-arrow.svg', 'SABnzbd', 'Queue finished', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list" 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2404]
A bit overdone.
One message / warning should be enough?

Or just disable Enable NotifyOSD ?

```
2023-01-06 15:52:31,357::INFO::[notifier:123] Sending notification: SABnzbd - Queue finished (type=queue_done, job_cat=None)
2023-01-06 15:52:31,358::INFO::[notifier:183] Send to NotifyOSD: SABnzbd / Queue finished
2023-01-06 15:52:31,358::ERROR::[connection:646] Unable to set arguments ('SABnzbd', 0, '/home/sander/git/sabnzbd/interfaces/Config/templates/staticcfg/images/logo-arrow.svg', 'SABnzbd', 'Queue finished', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
2023-01-06 15:52:31,360::INFO::[notifier:189] NotifyOSD not working

```

![image](https://user-images.githubusercontent.com/1273502/211036630-882058a1-eb3f-47d6-9fb0-3536bd4b02e8.png)

**Comment by sanderjo** [comment]
Easy to produce with plain python3 + notify2. 
```
sander@penguin:~$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import notify2
>>> notify2.init("Blabla-init")
True
>>> note = notify2.Notification("title", "this message", "small.png")
>>> note.show()
ERROR:dbus.connection:Unable to set arguments ('Blabla-init', 0, 'small.png', 'title', 'this message', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/.local/lib/python3.9/site-packages/notify2.py", line 222, in show
    nid = dbus_iface.Notify(appname,       # app_name       (spec names)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
>>> 
```
Error is not catchable?
```
>>> try:
...     note.show()
... except:
...     print("not so good")
... 
ERROR:dbus.connection:Unable to set arguments ('Blabla-init', 0, 'small.png', 'title', 'this message', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
not so good
>>> 
```

**Comment by Safihre** [comment]
Does the platform support notifyosd?

**Comment by sanderjo** [comment]
> Does the platform support notifyosd?

I think the problem is there are two platforms involved: ChromeOS as main host OS (with GUI), and debian Linux as guest OS (CLI only)
My hypothesis: Debian has notify2 and certain capabilities (otherwise SAB would not try), but I think Debian is not able to send the OSD to ChromeOS (which has the graphical capabilities).

I had a look at the code. I'm surprised that I can't catch the error from note.show(), but also read notify2 is EOL. So maybe better close this issue with the workaround "disable OSD" as it's not possible anyway? 

FWIW: on my CLI-only Linux VPS, no error message when I enable OSD. So ... there SAB does know it can't send OSD message and doesn't try at all ... ? Let's try ... yes: just the notify2.init() gives a Traceback, so SAB knows OSD is not possible:

```
>>> notify2.init("Blabla-init")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_                                                                                                             owner
    return self.get_name_owner(bus_name)
```
