### ISSUE TITLE
valid utf-8 chars in NZB => weird filenames on disk

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2464]
Related https://github.com/animetosho/Nyuu/issues/103

NZB with valid utf-8 chars:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
	<file poster="blablamannetje &lt;blabla@example.com&gt;" date="1676706806" subject="Hi_Unicode &quot;Hi Kingdom 你好世界.txt&quot; yEnc (1/1) 6">
		<groups>
			<group>alt.binaries.test</group>
		</groups>
		<segments>
			<segment bytes="158" number="1">JgNaGfJoScMvUaLtShRnQeTe-1676706806181@nyuu</segment>
		</segments>
	</file>
</nzb>
```

UTF-8 in XML and NZB is valid. See first line of NZB. So the part `subject="Hi_Unicode &quot;Hi Kingdom 你好世界.txt&quot; yEnc (1/1) 6"` should be valid

However, SAB's resulting filename is garbage:

```
-rw-rw-r--  1 sander sander    6 feb 18 08:58 'Hi Kingdom ä½ å¥½ä¸'$'\302\226''ç'$'\302\225\302\214''.txt'

ls | hd
00000000  48 69 20 4b 69 6e 67 64  6f 6d 20 c3 a4 c2 bd c2  |Hi Kingdom .....|
00000010  a0 c3 a5 c2 a5 c2 bd c3  a4 c2 b8 c2 96 c3 a7 c2  |................|
00000020  95 c2 8c 2e 74 78 74 0a                           |....txt.|
00000028
```
So same-same as the ascii-byte-utf8 conversion problems we saw with python 2?

Anyway:

Some grepperdegrep:

```
$ cat sabnzbd.log | grep -B5 -i kingdom

2023-02-18 08:58:34,884::DEBUG::[getperformance:50] CPU model = Intel(R) Celeron(R) CPU B820 @ 1.70GHz
2023-02-18 08:58:47,369::INFO::[nzbparser:89] Attempting to add chinese_letters_in_post.nzb
2023-02-18 08:58:47,370::INFO::[filesystem:707] Creating directories: /home/sander/Downloads/incomplete/chinese_letters_in_post
2023-02-18 08:58:47,374::INFO::[filesystem:707] Creating directories: /home/sander/Downloads/incomplete/chinese_letters_in_post/__ADMIN__
2023-02-18 08:58:47,374::INFO::[filesystem:1238] Saving /home/sander/Downloads/incomplete/chinese_letters_in_post/__ADMIN__/chinese_letters_in_post.nzb.gz
2023-02-18 08:58:47,378::INFO::[nzbparser:475] File Hi Kingdom 你好世界.txt added to queue
--
2023-02-18 08:58:48,482::INFO::[happyeyeballs:97] Quickest IP address for news.eweka.nl (port 563, preferipv6 False) is 81.171.92.219
2023-02-18 08:58:48,482::DEBUG::[happyeyeballs:99] Happy Eyeballs lookup and port connect took 78 ms
2023-02-18 08:58:48,482::DEBUG::[downloader:200] news.eweka.nl: Connecting to address 81.171.92.219
2023-02-18 08:58:48,559::INFO::[newswrapper:348] 3@news.eweka.nl: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2023-02-18 08:58:49,513::INFO::[downloader:817] Connecting 3@news.eweka.nl finished
2023-02-18 08:58:49,525::DEBUG::[deobfuscate_filenames:111] Checking: Hi Kingdom ä½ å¥½ä¸<U+0096>ç<U+0095><U+008C>
2023-02-18 08:58:49,526::DEBUG::[deobfuscate_filenames:148] Not obfuscated: upperchars >= 2 and lowerchars >= 2  and spacesdots >= 1
2023-02-18 08:58:49,526::INFO::[nzbstuff:1753] Detected filename from yenc or uu: Hi Kingdom 你好世界.txt -> Hi Kingdom ä½ å¥½ä¸<U+0096>ç<U+00<U+0095><U+008C>.txt
2023-02-18 08:58:49,527::DEBUG::[nzbstuff:1869] Saving attributes {'cat': '*', 'pp': 3, 'script': 'None', 'priority': 0, 'final_name': 'chinese_letters_in_post', 'password': '', 'url': None} for chinese_letters_in_post
2023-02-18 08:58:49,528::DEBUG::[assembler:79] Decoding part of /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom ä½ å¥½ä¸<<U+0096>ç<U+0095><U+008C>.txt
2023-02-18 08:58:49,528::DEBUG::[filesystem:1114] [sabnzbd.nzbstuff.save_to_disk] Saving data for SABnzbd_nzo_3w_zxciw in /home/sander/Downloads/incomplete/chinese_letters_in_post/__ADMIN__
2023-02-18 08:58:49,529::INFO::[assembler:87] Decoding finished /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom ä½ å¥½ä¸<<U+0096>ç<U+0095><U+008C>.txt

```

So from that log in time-sequential order:

Good:

`2023-02-18 08:58:47,378::INFO::[nzbparser:475] File Hi Kingdom 你好世界.txt added to queue`

Bad:

`2023-02-18 08:58:49,525::DEBUG::[deobfuscate_filenames:111] Checking: Hi Kingdom ä½ å¥½ä¸<U+0096>ç<U+0095><U+008C>
`

Good and Bad (!) ... good input, bad output?:

`2023-02-18 08:58:49,526::INFO::[nzbstuff:1753] Detected filename from yenc or uu: Hi Kingdom 你好世界.txt -> Hi Kingdom ä½ å¥½ä¸<U+0096>ç<U+00<U+0095><U+008C>.txt`

Bad:

`2023-02-18 08:58:49,528::DEBUG::[assembler:79] Decoding part of /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom ä½ å¥½ä¸<<U+0096>ç<U+0095><U+008C>.txt`

**Comment by sanderjo** [comment]
quoting Anime in other thread:

> If you take the UTF-8 representation of 你 and assume that it's actually latin1/ISO8859-1, you get "ä½ ".
> If you then UTF-8 encode that, you get C3 A4 C2 BD C2 A0, which seems to match what you get.
> 
> My guess is that there's some bad UTF-8 -> latin1 casting going on (i.e. assuming UTF-8 text is actually latin1).

**Comment by animetosho** [comment]
I'm guessing the culprit is [this](https://github.com/sabnzbd/sabctools/blob/36bc90dcadac41f7db56a15fa6bcdd5004841d7a/src/yenc.cc#L126).

yEnc doesn't specify what encoding should be used, however [RFC 3977](https://www.rfc-editor.org/rfc/rfc3977) suggests UTF-8 in NNTP, so it seems like the most logical choice. I don't know if changing latin1 to utf8 would break existing posts out there, but it would be a fix.

**Comment by Safihre** [comment]
Yes, normally that gets fixed by par2 but I guess your test post does not have any par2.
We could add some tests to see what happens for both Latin1 and UTF-8 yenc headers.

**Comment by sanderjo** [comment]
So ... deep down in the C code? Based on the yencode naming?

Let's check the article itself:

```
sander@X501A1:~/git/get_one_nntp_article$ cat mybody-news.eweka.nl-\<JgNaGfJoScMvUaLtShRnQeTe-1676706806181@nyuu\>.bin 
=ybegin part=1 total=1 line=128 size=6 name=Hi Kingdom 你好世界.txt
=ypart begin=1 end=6
r����4
=yend size=6 part=1 pcrc32=31963516 crc32=31963516

```

Yes: utf8 in the ybegin name part!

**Comment by sanderjo** [comment]
> Yes, normally that gets fixed by par2 but I guess your test post does not have any par2.

Indeed, no par2 in the above post.

With par2 indeed correct filename as result:

`-rw-rw-r--  1 sander sander    6 feb 18 12:23 'Hi Kingdom 你好世界.txt'`

Yes, normally that gets fixed by par2 but I guess your test post does not have any par2.

**Comment by sanderjo** [comment]
> I'm guessing the culprit is [this](https://github.com/sabnzbd/sabctools/blob/36bc90dcadac41f7db56a15fa6bcdd5004841d7a/src/yenc.cc#L126).

Without any knowledge I changed that line:

    //Py_output_filename = PyUnicode_DecodeLatin1(start_loc, cur_char - start_loc, NULL);
    Py_output_filename = PyUnicode_DecodeUTF8(start_loc, cur_char - start_loc, NULL);

also changed the sabcools' version to 6.0.1 for logging ... and ... it works on the NZB without par2 ... no more strange chars in the logging / intermediate results nor final result.

Cool. 

```
$ cat .sabnzbd/logs/sabnzbd.log | grep -i -e kingdom -e sabctools

2023-02-18 12:46:03,730::INFO::[SABnzbd:423] SABCTools module (v6.0.1)... found!
2023-02-18 12:46:03,730::INFO::[SABnzbd:424] SABCTools module is using SIMD set: SSSE3
2023-02-18 12:46:03,730::INFO::[SABnzbd:425] SABCTools module is linked to OpenSSL: True
2023-02-18 12:46:41,252::INFO::[nzbparser:475] File Hi Kingdom 你好世界.txt added to queue
2023-02-18 12:46:43,573::DEBUG::[assembler:79] Decoding part of /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom 你好世界.txt
2023-02-18 12:46:43,574::INFO::[assembler:87] Decoding finished /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom 你好世界.txt
2023-02-18 12:46:43,592::DEBUG::[postproc:943] No RAR-volume-number found in /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom 你好世界.txt
2023-02-18 12:46:44,005::DEBUG::[filesystem:798] Moving (overwrite: 0) /home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom 你好世界.txt => /home/sander/Downloads/complete/_UNPACK_chinese_letters_in_post.1/Hi Kingdom 你好世界.txt
2023-02-18 12:46:44,005::DEBUG::[filesystem:872] Renaming "/home/sander/Downloads/incomplete/chinese_letters_in_post/Hi Kingdom 你好世界.txt" to "/home/sander/Downloads/complete/_UNPACK_chinese_letters_in_post.1/Hi Kingdom 你好世界.txt"
2023-02-18 12:46:44,007::DEBUG::[deobfuscate_filenames:247] Extension of /home/sander/Downloads/complete/chinese_letters_in_post.1/Hi Kingdom 你好世界.txt looks common
2023-02-18 12:46:44,007::DEBUG::[deobfuscate_filenames:280] Deobfuscate inspecting biggest file/home/sander/Downloads/complete/chinese_letters_in_post.1/Hi Kingdom 你好世界.txt
2023-02-18 12:46:44,008::DEBUG::[deobfuscate_filenames:111] Checking: Hi Kingdom 你好世界
2023-02-18 12:46:44,009::DEBUG::[deobfuscate_filenames:288] /home/sander/Downloads/complete/chinese_letters_in_post.1/Hi Kingdom 你好世界.txt excluded from deobfuscation because filename does not look obfuscated
```

Result:
```
$ ll /home/sander/Downloads/complete/chinese_letters_in_post.1/
total 12
drwxrwxr-x  2 sander sander 4096 feb 18 12:46  ./
drwxrwxr-x 32 sander sander 4096 feb 18 12:46  ../
-rw-rw-r--  1 sander sander    6 feb 18 12:46 'Hi Kingdom 你好世界.txt'
```

**Comment by sanderjo** [comment]
The bad news: pytest fails

```
sander@X501A1:~/git/sabctools$ pytest
============================================================ test session starts =============================================================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /home/sander/git/sabctools, configfile: pytest.ini
plugins: httpserver-1.0.4, tavern-1.19.0, pyfakefs-4.5.4, flaky-3.7.0, httpbin-1.0.0
collected 51 items                                                                                                                           

tests/test_crc32.py .............................                                                                                      [ 56%]
tests/test_decoder.py ..F..........                                                                                                    [ 82%]
tests/test_encoder.py .                                                                                                                [ 84%]
tests/test_unlocked_ssl.py ........                                                                                                    [100%]

================================================================== FAILURES ==================================================================
_____________________________________________________________ test_special_chars _____________________________________________________________

    def test_special_chars():
        data_plain = read_plain_yenc_file("test_special_chars.txt")
        # We only compare the data and the filename
>       assert python_yenc(data_plain) == sabctools_yenc_wrapper(data_plain)

tests/test_decoder.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = bytearray(b'O\xa8\xe2{1\xa9 \x8a\x9a\x8aQ\x0b\x85\xfd\xf6\x15\xda\xdf\xd1\x1dfN\x12-\xf8$\x9f\x03X{>\xb7\xdd\x00\xb7\x...0\rW\x87TOU\xb5\xe9\xaa\xa0T>r\x94\xa2\xd1\xac\xc7\xc9\xe3\x9f\xf9D\x8bc\xec^\xaf \x91)fd/\rmA4A\xddR0)\x93o"\x9b\xe7')

    def sabctools_yenc_wrapper(data: bytearray) -> Tuple[bytearray, str, Optional[int]]:
>       filename, crc_correct = sabctools.yenc_decode(data)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 24: invalid continuation byte

tests/testsupport.py:69: UnicodeDecodeError
============================================================== warnings summary ==============================================================
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_response
  /usr/lib/python3/dist-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-4
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/home/sander/git/sabctools/tests/test_unlocked_ssl.py", line 154, in run
      self.close()
    File "/home/sander/git/sabctools/tests/test_unlocked_ssl.py", line 136, in close
      self.sslconn.close()
  AttributeError: 'NoneType' object has no attribute 'close'
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_ref_counts_unchanged
  /usr/lib/python3/dist-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-12
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/home/sander/git/sabctools/tests/test_unlocked_ssl.py", line 154, in run
      self.close()
    File "/home/sander/git/sabctools/tests/test_unlocked_ssl.py", line 136, in close
      self.sslconn.close()
  AttributeError: 'NoneType' object has no attribute 'close'
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================== short test summary info ===========================================================
FAILED tests/test_decoder.py::test_special_chars - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 24: invalid continu...
================================================== 1 failed, 50 passed, 2 warnings in 1.85s ==================================================

```

**Comment by animetosho** [comment]
> The bad news: pytest fails

What you did is a valid fix. Unfortunately *test_special_chars.txt* doesn't have valid UTF-8 in the name, so the test fails.  
The test case could get fixed, but unfortunately, a lot of indexers out there [do the wrong thing](https://github.com/animetosho/Nyuu/issues/100), so testing against something that's incorrect (i.e. latin1 encoded) makes sense.

The code could try to decode as UTF-8, then fall back to latin1 if it fails. This improves the likelihood of success, but could fail in specific cases.

Relying on PAR2 is another strategy, though it itself isn't 100% guaranteed to be correct. If the PAR2 was created with MultiPar or ParPar, and being renamed/checked by MultiPar, it should always work (these clients respect the *UniFileN* packet). Whether par2cmdline works probably depends on the system encoding used.  
As for Sabnzbd's own PAR2 handling, it doesn't check *UniFileN*, but [makes a guess](https://github.com/sabnzbd/sabnzbd/blob/9129b681dc372509a1927df320974efe8c643694/sabnzbd/par2file.py#L236) on the "non Unicode" filename, preferring UTF-8. MultiPar/ParPar always puts UTF-8 in this field, so it should always work on PAR2s created by them; par2cmdline, on the other hand, will as well if the system encoding of the creator was UTF-8.

**Comment by Safihre** [comment]
> The code could try to decode as UTF-8, then fall back to latin1 if it fails. This improves the likelihood of success, but could fail in specific cases.

Sounds like a plan!

**Comment by Safihre** [comment]
Will release `sabctools==6.1.0` with the fix.

**Comment by sanderjo** [comment]
With updated sabnzbd and update sabctools ... it works with the no-par2 NZB files posted above! 

Impressive. Thank you.

```
$ cat .sabnzbd/logs/sabnzbd.log | grep -i -e kingdom -e sabctools -e commit

2023-02-18 15:41:07,536::INFO::[SABnzbd:1179] Commit = e9038de81
2023-02-18 15:41:07,967::INFO::[SABnzbd:423] SABCTools module (v6.1.0)... found!
2023-02-18 15:41:07,967::INFO::[SABnzbd:424] SABCTools module is using SIMD set: AVX512VL+VBMI2
2023-02-18 15:41:07,967::INFO::[SABnzbd:425] SABCTools module is linked to OpenSSL: True
2023-02-18 15:41:38,068::INFO::[nzbparser:475] File Hi Kingdom 你好世界.txt added to queue
2023-02-18 15:41:40,143::DEBUG::[assembler:79] Decoding part of /home/sander/Downloads/incomplete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt
2023-02-18 15:41:40,144::INFO::[assembler:87] Decoding finished /home/sander/Downloads/incomplete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt
2023-02-18 15:41:40,149::DEBUG::[postproc:943] No RAR-volume-number found in /home/sander/Downloads/incomplete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt
2023-02-18 15:41:40,157::DEBUG::[filesystem:798] Moving (overwrite: 0) /home/sander/Downloads/incomplete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt => /home/sander/Downloads/complete/_UNPACK_chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt
2023-02-18 15:41:40,157::DEBUG::[filesystem:872] Renaming "/home/sander/Downloads/incomplete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt" to "/home/sander/Downloads/complete/_UNPACK_chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt"
2023-02-18 15:41:40,157::DEBUG::[deobfuscate_filenames:247] Extension of /home/sander/Downloads/complete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt looks common
2023-02-18 15:41:40,157::DEBUG::[deobfuscate_filenames:280] Deobfuscate inspecting biggest file/home/sander/Downloads/complete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt
2023-02-18 15:41:40,157::DEBUG::[deobfuscate_filenames:111] Checking: Hi Kingdom 你好世界
2023-02-18 15:41:40,158::DEBUG::[deobfuscate_filenames:288] /home/sander/Downloads/complete/chinese_char_direct_in_filename/Hi Kingdom 你好世界.txt excluded from deobfuscation because filename does not look obfuscated
```
