### ISSUE TITLE
Traceback on removing job during extraction

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2482]
Latest sab from git, develop branch. On macos 12.6.3

Testing something out on my mac, setting incomplete + complete folder on slow external thumb drive (exfat). 
Using the built in 1G test, it downloaded and in the middle of unpacking (directunpack is enabled) I went to remove the job by clicking the icon in the gui while it is still in the 'queue' and said it was on 06/11.

"Removing job ..." is stuck on the gui and per logs I see a few tracebacks:
```
2023-03-01 01:06:15,150::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:15,343::INFO::[directunpacker:315] DirectUnpacked volume 5 for sometestfile-1GB
2023-03-01 01:06:17,880::INFO::[nzbqueue:392] [sabnzbd.nzbqueue.remove_multiple] Removing job test_download_1000MB
2023-03-01 01:06:17,880::INFO::[nzbstuff:1803] [sabnzbd.nzbqueue.remove] Purging data for job test_download_1000MB (delete_all_data=1)
2023-03-01 01:06:17,909::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:17,967::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,026::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,083::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,141::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,198::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,254::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,309::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,366::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,425::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,481::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,537::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,593::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,649::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,708::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,766::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,825::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,880::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,941::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:18,999::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:19,055::DEBUG::[nzbqueue:746] Discarding article for file sometestfile-1GB.part09.rar: deleted or already post-processing
2023-03-01 01:06:20,967::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:20,969::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:20,970::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:20,971::DEBUG::[filesystem:614] Applying permissions 0o100666 (octal) to /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:20,971::INFO::[assembler:87] Decoding finished /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:20,971::DEBUG::[nzbstuff:441] Removing article database for SABnzbd_nzf__57q5vdo
2023-03-01 01:06:20,971::DEBUG::[filesystem:911] [sabnzbd.nzbstuff.remove_admin] Deleting file /Volumes/test/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf__57q5vdo
2023-03-01 01:06:20,973::INFO::[assembler:368] Error during inspection of RAR-file /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part07.rar
2023-03-01 01:06:20,973::DEBUG::[assembler:369] Traceback: 
Traceback (most recent call last):
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/assembler.py", line 291, in check_encrypted_and_unwanted_files
    zf = rarfile.RarFile(filepath, single_file_check=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 708, in __init__
    self._parse()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 917, in _parse
    self._file_parser.parse()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1028, in parse
    self._parse_real()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1052, in _parse_real
    h = self._parse_header(fd)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1134, in _parse_header
    return self._parse_block_header(fd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1673, in _parse_block_header
    header_crc, pos = load_le32(start_bytes, 0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 2642, in load_le32
    raise BadRarFile("cannot load le32")
sabnzbd.utils.rarfile.BadRarFile: cannot load le32
2023-03-01 01:06:32,170::INFO::[directunpacker:454] Aborting DirectUnpack for sometestfile-1GB
2023-03-01 01:06:32,573::DEBUG::[filesystem:944] Removing dir recursively /Volumes/test/complete/_UNPACK_test_download_1000MB
2023-03-01 01:06:34,534::DEBUG::[articlecache:163] Purging 402 articles from the cache/disk
2023-03-01 01:06:34,534::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:34,534::DEBUG::[directunpacker:334] DirectUnpack Unrar output 
UNRAR 6.21 freeware      Copyright (c) 1993-2023 Alexander Roshal


Extracting from /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part01.rar

Extracting  /Volumes/test/complete/_UNPACK_test_download_1000MB/1GB-explanation.txt  OK
Extracting  /Volumes/test/complete/_UNPACK_test_download_1000MB/1GB.bin
Insert disk with /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part02.rar [C]ontinue, [Q]uit

Extracting from /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part02.rar

...         1GB.bin
Insert disk with /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part03.rar [C]ontinue, [Q]uit

Extracting from /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part03.rar

...         1GB.bin
Insert disk with /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part04.rar [C]ontinue, [Q]uit

Extracting from /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part04.rar

...         1GB.bin
Insert disk with /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part05.rar [C]ontinue, [Q]uit

Extracting from /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part05.rar

...         1GB.bin
2023-03-01 01:06:34,584::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part09.rar
2023-03-01 01:06:34,586::DEBUG::[filesystem:944] Removing dir recursively /Volumes/test/incomplete/test_download_1000MB
2023-03-01 01:06:34,587::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:34,587::DEBUG::[filesystem:614] Applying permissions 0o100666 (octal) to /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:34,587::INFO::[assembler:87] Decoding finished /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:34,588::DEBUG::[nzbstuff:441] Removing article database for SABnzbd_nzf_a7nt_q5j
2023-03-01 01:06:34,588::DEBUG::[filesystem:911] [sabnzbd.nzbstuff.remove_admin] Deleting file /Volumes/test/incomplete/test_download_1000MB/__ADMIN__/SABnzbd_nzf_a7nt_q5j
2023-03-01 01:06:35,393::INFO::[filesystem:948] Cannot remove folder /Volumes/test/incomplete/test_download_1000MB
Traceback (most recent call last):
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/filesystem.py", line 946, in remove_all
    shutil.rmtree(path)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'SABnzbd_nzf_a7nt_q5j'
2023-03-01 01:06:35,396::INFO::[assembler:368] Error during inspection of RAR-file /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part08.rar
2023-03-01 01:06:35,396::INFO::[nzbqueue:233] Saving queue
2023-03-01 01:06:35,396::DEBUG::[assembler:369] Traceback: 
Traceback (most recent call last):
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/assembler.py", line 291, in check_encrypted_and_unwanted_files
    zf = rarfile.RarFile(filepath, single_file_check=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 708, in __init__
    self._parse()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 917, in _parse
    self._file_parser.parse()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1028, in parse
    self._parse_real()
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1052, in _parse_real
    h = self._parse_header(fd)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1134, in _parse_header
    return self._parse_block_header(fd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 1673, in _parse_block_header
    header_crc, pos = load_le32(start_bytes, 0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<USERNAME>/test/sabnzbd/sabnzbd/utils/rarfile.py", line 2642, in load_le32
    raise BadRarFile("cannot load le32")
sabnzbd.utils.rarfile.BadRarFile: cannot load le32
2023-03-01 01:06:35,397::DEBUG::[filesystem:1185] [sabnzbd.nzbqueue.save] Saving data for queue10.sab
2023-03-01 01:06:35,397::DEBUG::[assembler:79] Decoding part of /Volumes/test/incomplete/test_download_1000MB/sometestfile-1GB.part09.rar
```

also, job is still in the incomplete folder:
![Screen Shot 2023-03-01 at 1 19 29 AM](https://user-images.githubusercontent.com/500882/222070497-3cde1972-3a2d-44a4-9ac5-9f36d8b1f91c.png)

**Comment by puzzledsab** [comment]
There might be more issues but FileNotFoundError is probably the most relevant in the log. It seems like a temporary file that has most likely been deleted by another thread while rmtree was processing. I don't know if there's a way for rmtree to ignore those errors. If not then it could try again a few times.

**Comment by thezoggy** [comment]
To me it just looks like removing the job happen from our under the directunpacker. So it's trying to inspect if rar and pukes. So aborting job is failing to kill the unpacker first before removing?

**Comment by puzzledsab** [comment]
It's the missing file SABnzbd_nzf_a7nt_q5j which stops it from deleting the temporary directory, not unrar. I don't know why it's not removed from the queue. That might be related to the unraring.

**Comment by Safihre** [comment]
I removed the 4.0.0a2 specific part, as I am 95% sure this issue is a general problem on slower disks and not related to the release.
I think the solution is related to having locks around the directory operations, which we avoided so far but would be the best solution.

**Comment by puzzledsab** [comment]
The le32 error will happen every time it's trying to read a broken RAR file. It's been like that for a long time. A one line info message would be enough. The FileNotFoundError is a separate issue.

**Comment by Safihre** [comment]
@thezoggy you rapported that rarfile logging at least 5x already 😂 every time I explain that's it just debugging information. But I'll remove it this time 😄

**Comment by thezoggy** [comment]
> @thezoggy you rapported that rarfile logging at least 5x already 😂 every time I explain that it's just debugging information. But I'll remove it this time 😄

I probably just keep reporting because users complain because they see tracebacks in their log which usually means something bad. 

So cleaning it up will definitely be good to reduce those inquiries
