### ISSUE TITLE
OSError: [Errno 29] Invalid seek

### ISSUE THREAD

**Issue by japandler** [sabnzbd/sabnzbd#2507]
Hey there, 
Receiving an auto-pause error when attempting to download things. Seems to be happening on every download I have in my queue. What's interesting is that the files are actually "being created" so to speak, but the error persists, and will continue pausing despite the file being there or not. 

I don't have steps to replicate. but have tried this multiple different write paths to the same effect (attempting to write to a new folder, attempting to write to one that's on a different disk, etc.). 

Attached is sabnzbd.log, but it's missing the pertinent error, so I attached that below as well. 

Let me know what else I can add to here to help debug this issue.

[sabnzbd(2).log](https://github.com/sabnzbd/sabnzbd/files/11013449/sabnzbd.2.log)

```
    fout.write(data)
2023-03-20 03:27:54,935::INFO::[notifier:123] Sending notification: Error - Disk error on creating file /mnt/unionfs/downloads/nzbs/sabnzbd/incomplete/The.Mandalorian.S03E02.1080p.DSNP.WEBRip.DDP5.1.x264-NTb/1bbdc6d422af49ae9c4df7a8aabe70ec.part02.rar (type=error, job_cat=None)
2023-03-20 03:27:54,934::ERROR::[assembler:113] Disk error on creating file /mnt/unionfs/downloads/nzbs/sabnzbd/incomplete/The.Mandalorian.S03E02.1080p.DSNP.WEBRip.DDP5.1.x264-NTb/1bbdc6d422af49ae9c4df7a8aabe70ec.part02.rar
2023-03-20 03:27:54,935::INFO::[assembler:121] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/assembler.py", line 193, in assemble
OSError: [Errno 29] Invalid seek
During handling of the above exception, another exception occurred:
  File "/app/sabnzbd/assembler.py", line 86, in run
  File "/app/sabnzbd/assembler.py", line 178, in assemble
    self.assemble(nzo, nzf, file_done)
    with open(nzf.filepath, "ab", buffering=0) as fout:
PermissionError: [Errno 1] Operation not permitted
2023-03-20 03:27:54,937::INFO::[downloader:395] Pausing
2023-03-20 03:27:54,937::INFO::[notifier:123] Sending notification: SABnzbd - Paused (type=pause_resume, job_cat=None)
2023-03-20 03:27:54,938::INFO::[downloader:415] Forcing disconnect
2023-03-20 03:27:54,938::DEBUG::[downloader:925] Thread 3@********.com: forcing disconnect
2023-03-20 03:27:54,940::DEBUG::[assembler:85] Decoding part of /mnt/unionfs/downloads/nzbs/sabnzbd/incomplete/The.Mandalorian.S03E02.1080p.DSNP.WEBRip.DDP5.1.x264-NTb/1bbdc6d422af49ae9c4df7a8aabe70ec.part03.rar
```

**Comment by Safihre** [comment]
Information is a bit limited, but seems this has to do with the filesystem.
What is this `unionfs`?

**Comment by thezoggy** [comment]
If prob is google rclone mount and user exceeded limits
