### ISSUE TITLE
0.8.x - return nzo_id when adding by addurl

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#251]
right now sonarr has to d/l the nzb and use the addfile api so it gets back a id so it can keep track of the release.. it would be nice if it could get an id back when using addurl. that way the X-DNZB- headers are kept/could be used. Also this would allow sonarr to leverage sab's retry feature and also resolve some issues with sonarr instances that rely on mono as it has some bugs with sites that use chunked transfers which sometimes results in malformed nzb being passed off to sab.

**Comment by Safihre** [comment]
It already does this, you just need to tell it to output JSON when making the request
*&output=json*
Returns:
*{"status":true,"nzo_ids":["SABnzbd_nzo_1su5ad"]}*

**Comment by thezoggy** [comment]
i do agree that when you say use xml/json output when using addfile it spits out a nzo. addurl (which calls addid however does not appear so)

`curl "http://localhost:8092/api?mode=addurl&cat=tv&priority=0&output=json&apikey=cebf71d1cb1122e84faa3b3a0d77bd79&name=https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed"`
I just get back `{"status":true}`. now in 0.8.x this also causes 

```
2015-07-27 09:15:30,280::DEBUG::[interface:424] API-call from ::1 [curl/7.30.0] {'apikey': u'cebf71d1cb1122e84faa3b3a0d77bd79', 'name': u'https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674', 'cat': u'tv', 'priority': u'0', 'r': u'apikey_removed', 'mode': u'addurl', 'output': u'json'}
2015-07-27 09:15:30,305::INFO::[__init__:492] Fetching https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674
2015-07-27 09:15:30,316::INFO::[nzbqueue:257] Saving queue
2015-07-27 09:15:30,319::DEBUG::[__init__:842] Saving data for SABnzbd_nzo_zplcv6 in \\?\D:\test\admin\future
2015-07-27 09:15:30,326::INFO::[__init__:917] Saving data for queue10.sab in D:\test\admin\queue10.sab
2015-07-27 09:15:30,332::INFO::[urlgrabber:96] Grabbing URL https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674
2015-07-27 09:15:33,671::ERROR::[urlgrabber:234] URLGRABBER CRASHED
Traceback (most recent call last):
  File "C:\Program Files (x86)\sabnzbd_0.8.x\sabnzbd\urlgrabber.py", line 197, in run
    f = open(path, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'D:\\test\\admin\\future\\?i=5674.nzb.gz'
2015-07-27 09:15:33,686::DEBUG::[urlgrabber:235] URLGRABBER Traceback: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\sabnzbd_0.8.x\sabnzbd\urlgrabber.py", line 197, in run
    f = open(path, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'D:\\test\\admin\\future\\?i=5674.nzb.gz'
```

**Comment by thezoggy** [comment]
now doing, this actually made it add the nzb, and url fetched (since full url made it to sab):
`curl -G "http://localhost:8092/api?mode=addurl&cat=tv&priority=0&output=json&apikey=cebf71d1cb1122e84faa3b3a0d77bd79&" --data-urlencode "name=https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed"`

sab logs:
```
2015-07-27 09:25:22,628::DEBUG::[interface:424] API-call from ::1 [curl/7.30.0] {'apikey': u'cebf71d1cb1122e84faa3b3a0d77bd79', 'name': u'https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed', 'cat': u'tv', 'priority': u'0', 'mode': u'addurl', 'output': u'json'}
2015-07-27 09:25:22,651::INFO::[__init__:492] Fetching https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed
2015-07-27 09:25:22,667::INFO::[nzbqueue:257] Saving queue
2015-07-27 09:25:22,671::DEBUG::[__init__:842] Saving data for SABnzbd_nzo_aiftx1 in \\?\D:\test\admin\future
2015-07-27 09:25:22,677::INFO::[__init__:917] Saving data for queue10.sab in D:\test\admin\queue10.sab
2015-07-27 09:25:22,683::INFO::[urlgrabber:96] Grabbing URL https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed
2015-07-27 09:25:24,473::INFO::[nzbstuff:654] Replacing spaces with underscores in Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb
2015-07-27 09:25:24,480::INFO::[misc:780] Creating directories: \\?\D:\test\downloads\incomplete\Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb
```

and in the end, still just `{"status":true}` no nzo id being returned.

**Comment by Safihre** [comment]
Oh yes indeed, only addfile. I see Shypike is already on it :P

**Comment by Safihre** [comment]
Added: #276

**Comment by shypike** [comment]
Implemented: https://github.com/sabnzbd/sabnzbd/commit/b8889756d48857e851a6da3925ce57dec45d1e27
