### ISSUE TITLE
4.0b1 - parse_par2_file - traceback on set_id + slice_size

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2521]
User reported this via discord, during download seeing:
```
2023-03-31 01:51:20,219::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E09.720p.HDTV.x264-FiHTV/House.Hunt.S01E09.720p.HDTV.x264-FiHTV.vol-08.par2
2023-03-31 01:51:20,219::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 132, in parse_par2_file
    slice_size = metadata["slice_size"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'slice_size'
2023-03-31 01:51:20,220::DEBUG::[assembler:79] Decoding part of /downloads/incomplete/House.Hunt.S01E08.720p.HDTV.x264-FiHTV/house.hunt.s01e08.720p.hdtv.x264-fihtv.r06
2023-03-31 01:51:20,229::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:20,230::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E09.720p.HDTV.x264-FiHTV/House.Hunt.S01E09.720p.HDTV.x264-FiHTV.vol-010.par2
2023-03-31 01:51:20,232::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E09.720p.HDTV.x264-FiHTV/House.Hunt.S01E09.720p.HDTV.x264-FiHTV.vol-010.par2
2023-03-31 01:51:20,232::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 132, in parse_par2_file
    slice_size = metadata["slice_size"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'slice_size'
2023-03-31 01:51:20,234::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:20,234::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E09.720p.HDTV.x264-FiHTV/House.Hunt.S01E09.720p.HDTV.x264-FiHTV.vol-012.par2
2023-03-31 01:51:20,237::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E09.720p.HDTV.x264-FiHTV/House.Hunt.S01E09.720p.HDTV.x264-FiHTV.vol-012.par2
2023-03-31 01:51:20,237::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 132, in parse_par2_file
    slice_size = metadata["slice_size"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'slice_size'
```

and

```
2023-03-31 01:51:41,839::DEBUG::[filesystem:876] Renaming "/downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/house.hunt.s01e06.720p.hdtv.x264-fihtv.1.rar" to "/downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/house.hunt.s01e06.720p.hdtv.x264-fihtv.rar"
2023-03-31 01:51:41,840::DEBUG::[deobfuscate_filenames:96] Deobfuscate par2 repair/verify finished
2023-03-31 01:51:41,840::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-06.par2
2023-03-31 01:51:41,843::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-06.par2
2023-03-31 01:51:41,843::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 131, in parse_par2_file
    set_id = metadata["set_id"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'set_id'
2023-03-31 01:51:41,845::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:41,845::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-012.par2
2023-03-31 01:51:41,847::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-012.par2
2023-03-31 01:51:41,847::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 131, in parse_par2_file
    set_id = metadata["set_id"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'set_id'
2023-03-31 01:51:41,849::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:41,849::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-04.par2
2023-03-31 01:51:41,851::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-04.par2
2023-03-31 01:51:41,852::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 131, in parse_par2_file
    set_id = metadata["set_id"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'set_id'
2023-03-31 01:51:41,855::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:41,855::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-08.par2
2023-03-31 01:51:41,857::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-08.par2
2023-03-31 01:51:41,857::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 131, in parse_par2_file
    set_id = metadata["set_id"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'set_id'
2023-03-31 01:51:41,862::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:41,862::DEBUG::[deobfuscate_filenames:93] Deobfuscate par2: handling /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-010.par2
2023-03-31 01:51:41,864::INFO::[par2file:172] Par2 parser crashed in file /downloads/complete/tv shows/House.Hunt.S01E06.720p.HDTV.x264-FiHTV/House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-010.par2
2023-03-31 01:51:41,864::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/par2file.py", line 131, in parse_par2_file
    set_id = metadata["set_id"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'set_id'
2023-03-31 01:51:41,869::DEBUG::[deobfuscate_filenames:100] Deobfuscate par2 repair/verify did not find anything to rename
2023-03-31 01:51:41,869::INFO::[postproc:533] Running deobfuscate
```

user is using lsio's sab docker, not using docker mods. confirmed has normal par2cmdline 0.8.1

saf - sent ya user log+nzb for this one as well

**Comment by thezoggy** [comment]
trying nzb myself, seeing the set_id traceback. 

```
2023-04-01 18:42:50,798::INFO::[par2file:172] Par2 parser crashed in file \\?\C:\Users\<USERNAME>\downloads\incomplete\House.Hunt.S01E06.720p.HDTV.x264-FiHTV\House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-09.par2
2023-04-01 18:42:50,798::DEBUG::[par2file:173] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\par2file.py", line 131, in parse_par2_file
KeyError: 'set_id'
```

taking one of the par's and running it manually through par2file it looks like whats going on is that with the partial nzb we compare md5 and return if mismatch:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/par2file.py#L211

which then of course those keys dont get added and later why it throws the traceback because they arent set.

dropping that md5 check for the tested par I see it would have gotten the set_id  but then would have puked on slice_size because doesnt have enough data blocks to get through to get additional data. 

and from multipar output, can see par was wortheles due to no packet/slice:
```
Loading PAR File       :
Packet Slice Status   :  Filename
26     0 Good     : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-01.par2"
26     0 Good     : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-02.par2"
1
27     1 Good     : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-03.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-04.par2"
26     0 Damaged  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-05.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-06.par2"
5
80     4 Good     : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-07.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-08.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-09.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-010.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-011.par2"
0     0 Useless  : "House.Hunt.S01E06.720p.HDTV.x264-FiHTV.vol-012.par2"
```

so anyways, thinking we might could just do this for parse_par2_file
```
        try:
            set_id = metadata["set_id"]
            slice_size = metadata["slice_size"]
        except KeyError:
            set_id = None
            slice_size = 0
```

**Comment by thezoggy** [comment]
> Setting slice_size to zero could cause tracebacks a little later in the same function, when it's used as the denominator in arithmetic operations. Do par2 files with this kind of breakage still serve some purpose or are they always useless?

slice_size = 1 then? or we just set the dict up inside the analyze file so it has the defaults there

now about the par2 and broken files being useless,
even if the par2 is 'broken' it can still be useful because there may be some blocks the par2 app can use. 

in this instance, all the pars were incomplete, but in the end it did not matter because the rarset was fine:
![MultiPar_2023-04-02_11-35-18](https://user-images.githubusercontent.com/500882/229366318-067fcb8f-c099-411d-aecd-4ecc5eaadeea.png)

**Comment by puzzledsab** [comment]
It usually happens because SABnzbd doesn't download the full par2 files so the meta data blocks are missing. It will get the metadata from the par2 file with no blocks so I don't think it matters. I left it like that because it was new code and I didn't know in what ways it could break. Without set_id and slice_size the data aren't usable but we can probably fail in a more quiet way. The stack trace is only printed when debug logging is enabled, though.

**Comment by Safihre** [comment]
@puzzledsab I'm refactoring `par2file` and will fix this in the process.

**Comment by Safihre** [comment]
This NZB is breaking SABnzbd in very weird ways, I know why the files don't get deleted (not part of extrapars) but I have no clue why they are removed.

**Comment by thezoggy** [comment]
@Safihre dunno if related but I recall seeing when the nzb is added it sees some of the files referenced in the nzb multiple times

**Comment by Safihre** [comment]
Wow I finally found the problem:
When an NZF object is created in nzbparser, it already adds its first article to `nzo.first_articles`. However, when we discard an NZF because it's a duplicate file, the first article is not removed from the `nzo.first_articles`. So we end up with a ghost NZF that is still downloaded, but doesn't really get processed correctly.
Now to find a way how to fix that.

**Comment by thezoggy** [comment]
updated to latest, tried file in #2517  now seeing:
```
2023-04-06 16:08:02,529::DEBUG::[par2file:204] Missing essential information for FilePar2Info(filename='<HASH>39679e2.part18.rar', hash16k=b'\xd2p\x1b\xdbI}\x86\xbf\xa4{v\xfe\xa2\x12\x85u', filesize=105216000, filehash=None, has_duplicate=False)
2023-04-06 16:08:02,530::INFO::[par2file:234] Par2 parser crashed in file \\?\C:\sab\downloads\incomplete\The.Kissing.Booth.2018.iNTERNAL.1080p.WEB.x264-STRiFE\<HASH>39679e2.vol127+128.par2
2023-04-06 16:08:02,530::DEBUG::[par2file:235] Traceback: 
Traceback (most recent call last):
  File "C:\Program Files\sabnzbd-dev\sabnzbd\par2file.py", line 212, in parse_par2_file
    crc32 = sabctools.crc32_multiply(crc32, coeff) ^ filecrc32[fileid][slice_nr]
                                                     ~~~~~~~~~^^^^^^^^
KeyError: '<HASH>cdccb96'

2023-04-06 16:08:18,848::INFO::[par2file:234] Par2 parser crashed in file \\?\C:\sab\downloads\incomplete\The.Kissing.Booth.2018.iNTERNAL.1080p.WEB.x264-STRiFE\<HASH>39679e2.vol511+331.par2
2023-04-06 16:08:18,848::DEBUG::[par2file:235] Traceback: 
Traceback (most recent call last):
  File "C:\Program Files\sabnzbd-dev\sabnzbd\par2file.py", line 212, in parse_par2_file
    crc32 = sabctools.crc32_multiply(crc32, coeff) ^ filecrc32[fileid][slice_nr]
                                                     ~~~~~~~~~^^^^^^^^
KeyError: '<HASH>ee50429'
```
