### ISSUE TITLE
Crash in `what_is_most_likely_extension` due to missing file

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2535]
Submitted by user through email.
It's a bit strange to be, because I thought we check if the file exists before we run any of the checks @sanderjo?
Maybe a virus scanner blocked it?

This download also makes me a bit worried now we have `Deobfuscate final filesnames` turned on by default, as this will break this download..
Maybe we should have made it an additional Post-Processing option (e.g. like +Unpack +Delete to also have +Deobfuscate) so we could only enable it by default for `tv` and `movies` category.

```
2023-04-20 17:41:38,874::ERROR::[postproc:600] Post Processing Failed for Tomtom update kaarten 1105 mooi alles in 1 post (see logfile)
2023-04-20 17:41:38,874::INFO::[postproc:601] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.py", line 534, in process_job
  File "sabnzbd\deobfuscate_filenames.py", line 251, in deobfuscate
  File "sabnzbd\utils\file_extension.py", line 286, in what_is_most_likely_extension
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\D:\\Download\\Tomtom update kaarten 1105 mooi alles in 1 post\\connect2internetdb.ver'
```

**Comment by sanderjo** [comment]
Was the file `connect2internetdb.ver` removed in the mean time ... ?

**Comment by Safihre** [comment]
Yes actually!
It seems probably it was extracted from 2 archives:
```
2023-04-20 17:41:38,645::INFO::[deobfuscate_filenames:254] Deobfuscate renaming (adding extension) \\?\D:\Download\Tomtom update kaarten 1105 mooi alles in 1 post\connect2internetdb.ver to \\?\D:\Download\Tomtom update kaarten 1105 mooi alles in 1 post\connect2internetdb.ver.txt
```
So we should make sure all paths are unique.
