### ISSUE TITLE
Files which match a watched extension, but are not valid nzb's, fail to parse and get deleted

### ISSUE THREAD

**Issue by RamonEbdon** [sabnzbd/sabnzbd#2550]
SABnzbd version: 4.0.0
OS: Windows 10 22H2
Category: Watched folder handling

I use a simple watch folder on my browser downloads folder for adhoc nzb's, and I'd like to prevent SABnzbd from attempting to parse all *.gz files and instead only parse *.nzb.gz files.

Right now, SABnzbd attempts to parse things like "openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz" which not only fails, but it removes the file from the downloads/watch folder and deletes it - permanently! Which means, when I forget to save non-nzb *.gz files somewhere else, I usually end up having to go download it again if I don't move it quickly enough. Minor issue, sure, but it's a bit annoying.

The watched extensions are listed under ```VALID_NZB_FILES = (".nzb", ".gz", ".bz2")``` in [constants.py](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/constants.py#LL133C8-L133C8) so one option could be to just make this a configurable parameter instead? Alternatively, it could be made a bit more specific to use .nzb.gz and .nzb.bz2? I guess it comes down to how common are gzipped nzb files that are not *.nzb.gz ?

At the least, I'd prefer if it just left files alone that are unable to be parsed, which might be a contradiction of #2188 😄 

Here's an example error from the log parsing not-an-nzb.gz file which then also gets deleted:
```
2023-05-01 22:10:36,474::INFO::[dirscanner:188] Trying to import ***\downloads\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz
2023-05-01 22:10:37,493::INFO::[nzbparser:84] Attempting to add openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz [***\downloads\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz]
2023-05-01 22:10:37,496::INFO::[filesystem:710] Creating directories: ***\NZBs\incomplete\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz
2023-05-01 22:10:37,497::INFO::[filesystem:710] Creating directories: ***\NZBs\incomplete\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz\__ADMIN__
2023-05-01 22:10:37,497::INFO::[filesystem:1242] Saving ***\NZBs\incomplete\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz\__ADMIN__\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz.nzb.gz
2023-05-01 22:10:38,384::INFO::[notifier:123] Sending notification: Error - Saving ***\NZBs\incomplete\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz\__ADMIN__\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz.nzb.gz failed (type=error, job_cat=None)
2023-05-01 22:10:38,384::ERROR::[filesystem:1250] Saving ***\NZBs\incomplete\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz\__ADMIN__\openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz.nzb.gz failed
2023-05-01 22:10:38,384::INFO::[filesystem:1251] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\filesystem.py", line 1248, in save_compressed
  File "shutil.py", line 197, in copyfileobj
  File "gzip.py", line 301, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 499, in read
  File "gzip.py", line 468, in _read_gzip_header
  File "gzip.py", line 428, in _read_gzip_header
gzip.BadGzipFile: Not a gzipped file (b'# ')
2023-05-01 22:10:38,389::INFO::[notifier:123] Sending notification: Warning - Invalid NZB file openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz, skipping (error: not well-formed (invalid token): line 1, column 0) (type=warning, job_cat=None)
2023-05-01 22:10:38,389::WARNING::[nzbstuff:781] Invalid NZB file openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz, skipping (error: not well-formed (invalid token): line 1, column 0)
2023-05-01 22:10:38,389::INFO::[nzbstuff:782] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\nzbstuff.py", line 778, in __init__
  File "sabnzbd\nzbparser.py", line 380, in nzbfile_parser
  File "xml\etree\ElementTree.py", line 1249, in iterator
  File "xml\etree\ElementTree.py", line 1320, in read_events
  File "xml\etree\ElementTree.py", line 1292, in feed
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
2023-05-01 22:10:38,390::INFO::[nzbstuff:1836] [N/A] Purging data for job openwrt-22.03.5-x86-64-generic-ext4-combined.img.gz (delete_all_data=True)
```

**Comment by thezoggy** [comment]
1) not all gzip files are going to have a .nzb in their name. just like .zip or .7z. So limiting extensions to .nzb.* would reduce functionality for people
2) why not just set your watch folder to a clean folder where you really only in fact place things you want sab to watch?

**Comment by thezoggy** [comment]
But I'll poke around and see what most sites are doing with .gz

**Comment by RamonEbdon** [comment]
All of the recent sources of nzb's I've seen, although admittedly not a whole lot, just use .nzb for single or .zip for multiple. I'm sure I got .nzb.gz from somewhere before, that's why I suggested it, but now I can't actually recall where that was from (or if it's still around).

Whether the watched extensions are changed or not, my main issue was the unexpected deletion of the files and the mismatch between the config screen and what it does. At the least, there should be a consistency alignment between the dirscanner and the settings UI which actually says ".tar.gz", not .gz and nothing about .bz2:
![image](https://user-images.githubusercontent.com/2483849/236668241-fd1206a9-6ddb-4873-8c74-041449d9b7e7.png)

Aside from simply editing the static list that's already there, another alternative would be to create a new entry in sabnzbd.ini which is a list of extensions to watch for meaning users could tailor it as needed. There are a few other extension list config items, so this should be straightforward?

As for deleting non-nzb .gz files, I think that's more just a bug (even if it's deliberate) because .zip files don't get deleted from the watch folder if they don't contain nzb content, so why do .gz files?

**Comment by Safihre** [comment]
@mnightingale Agreed. Want to submit a PR for the changes?

**Comment by mnightingale** [comment]
Which approach do you prefer? or both?

What about enums, they would make the logic a bit easier to follow but would add more noise to a PR.

**Comment by Safihre** [comment]
Both indeed, the enums would be a nice bonus.

For now I already updated the text in the interface to include the actually supported list of file extensions.
