### ISSUE TITLE
Crashed assembler 

### ISSUE THREAD

**Issue by TheLion** [sabnzbd/sabnzbd#2561]
Hi,

I have a strange issue as of just now. 

`Traceback (most recent call last):
  File "sabnzbd\assembler.py", line 93, in run
  File "sabnzbd\assembler.py", line 206, in check_encrypted_and_unwanted
  File "sabnzbd\assembler.py", line 317, in check_encrypted_and_unwanted_files
  File "sabnzbd\utils\rarfile.py", line 723, in setpassword
  File "sabnzbd\utils\rarfile.py", line 917, in _parse
  File "sabnzbd\utils\rarfile.py", line 1028, in parse
  File "sabnzbd\utils\rarfile.py", line 1052, in _parse_real
  File "sabnzbd\utils\rarfile.py", line 1131, in _parse_header
  File "sabnzbd\utils\rarfile.py", line 1665, in _decrypt_header
  File "sabnzbd\utils\rarfile.py", line 2419, in __init__
  File "sabnzbd\utils\rarfile.py", line 120, in __init__
  File "cryptography\hazmat\primitives\ciphers\base.py", line 91, in __init__
  File "cryptography\hazmat\primitives\ciphers\modes.py", line 109, in _check_iv_and_key_length
  File "cryptography\hazmat\primitives\ciphers\modes.py", line 81, in _check_iv_length
ValueError: Invalid IV size (0) for CBC. `

Not sure yet if it particularly has to do with the current job, or is a general issue. 

Any known similar issues? Wasn't able to find on Github.

**Comment by TheLion** [comment]
It turned out to be a bad sector on my hard drive.
