### ISSUE TITLE
bad unicode in filename - unicode error

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2572]
person on discord asked about:
```
2023-05-22 11:15:40,679::INFO::[database:155] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/database.py", line 125, in execute
    self.cursor.execute(command, args)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbd' in position 98: surrogates not allowed
```

debug log:
https://paste.ofcode.org/3aevZ5HndwfWfXSh7zQGgUs

- sab 4.0.1 running in the lscr.io/linuxserver/sabnzbd docker container image on Unraid 6.11.5
- The gzipped nzb does get moved into my history directory. 
- Using radarr to load the nzb (api)

some indexers have it as one of these two:
- `The.Lion.King.1Â½.2004.720p.BluRay.DD5.1.x264-EbP`
- `The.Lion.King.1.2004.720p.BluRay.DD5.1.x264-EbP`

grabbing the nzb from indexer, the file subject (inside nzb looks correct):
`The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP`

however the filename has `+` instead of `½` in rar:
![img](http://zoggy.net/WinRAR_2023-05-22_11-57-21.png)

**Comment by sanderjo** [comment]
Some notes, no solution:

I cannot reproduce on my Ubuntu with that NZB. Indeed strange chars, but no traceback, and all arrives in the correct destination directory.

> grabbing the nzb from indexer, the file subject (inside nzb looks correct):
> The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP

(TBD: does the name come from the .NZB filename, or from the subject ... ?)

Let's check the NZB:

The NZB header says `<?xml version="1.0" encoding="UTF-8"?>` ... OK, so far so good.

Let's check that subject inside the .NZB:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/fb38e0cb-8ffa-4bcd-af6e-724ebd993810)

That c2 bd 2e is not pure ASCII, and AFAIK is not UTF-8.

So then I would say: incorrectly formatted .NZB.


**FWIW python background**

Based on https://stackoverflow.com/a/27367173/14520409

```
>>> print(b'C\xc3N'.decode('utf8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1: invalid continuation byte
>>> 

```
```
>>> print(b'C\xc3N'.decode('utf8','surrogateescape'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 1: surrogates not allowed

>>> 

```
```
>>> print(b'C\xc3N'.decode('utf8','replace'))
C�N

```

**Comment by thezoggy** [comment]
first few lines from the nzb, one includes head info the other one did not. both nzb result in same issue for the user


from one site:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb
PUBLIC "-//newzBin//DTD NZB 1.1//EN"
       "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<!--NZB Generated by: nZEDb 0.7.1.2 April 23, 2017, 12:38 pm +0100-->
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
  <head>
    <meta type="category">Movies &gt; HD</meta>
    <meta type="name">[18962]-[a.b.hdtv.x264EFNet]-[ The.Lion.King.1Â½.2004.720p.BluRay.DD5.1.x264-EbP ]-[07/77] - &quot;The.Lion.King.1Â½.2004.720p.BluRay.DD5.1.x264-EbP.nfo&quot; yEnc</meta>
  </head>
  <file poster="VMrbkz23564ds22-hidef@my.tv (HIDEF)" date="1318937236" subject="[18962]-[#a.b.hdtv.x264@EFNet]-[ The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP ]-[07/77] - &quot;The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP.nfo&quot; yEnc(1/1)">
    <groups>
...
```
from another:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">

<head>
</head>

<file poster="ZngYUPF600PwN58-hidef@my.tv (HIDEF)" date="1318937234" subject="[18962]-[#a.b.hdtv.x264@EFNet]-[ The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP ]-[01/77] - &quot;The.Lion.King.1½.2004.720p.BluRay.DD5.1.x264-EbP-sample-60058.mkv&quot; yEnc (1/129) (1/129)">
 <groups>
...
```

**Comment by sanderjo** [comment]
@thezoggy I cannot reproduce. So can you share the .NZB ?

**Comment by thezoggy** [comment]
> @thezoggy I cannot reproduce. So can you share the .NZB ?

I can, just let me know what email to send them to.

Or if you have access to the sites, one was from nzbfinder the other from drunkenslug

**Comment by Safihre** [comment]
It could be Windows specific?

**Comment by sanderjo** [comment]
> It could be Windows specific?

User is running on Docker (so Linux inside) ... but screenshot is a (rar?) GUI ... on Windows or Linux?
Or the underlying filesystem which the docker host is using ... ?

Problem is this:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/bc9b6eee-4082-4feb-b4ab-e66687079ffb)

... but how can the sequence c3 82 c2 bd turn into that '\udcbd' ? Some overcompensating switching between different encodings ... ?

**Comment by thezoggy** [comment]
> > It could be Windows specific?
> 
> User is running on Docker (so Linux inside) ... but screenshot is a (rar?) GUI ... on Windows or Linux?
> Or the underlying filesystem which the docker host is using ... ?
> 
> Problem is this:
> 
> ![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/bc9b6eee-4082-4feb-b4ab-e66687079ffb)
> 
> ... but how can the sequence c3 82 c2 bd turn into that '\udcbd' ? Some overcompensating switching between different encodings ... ?
> 
> 

The screenshot was from me grabbing the release myself to see what WinRAR reported.

**Comment by sanderjo** [comment]
> The screenshot was from me grabbing the release myself to see what WinRAR reported.

So, on your pure Windows setup, can your SABnzbd doenload that .NZB?

**Comment by thezoggy** [comment]
> > The screenshot was from me grabbing the release myself to see what WinRAR reported.
> 
> So, on your pure Windows setup, can your SABnzbd download that .NZB?

main provider has most of it missing, so has to grab from blocks. but yep completes and extracts just fine..

```
2023-05-24 15:44:11,635::INFO::[nzbparser:90] Attempting to add The.Lion.King.1.2004.720p.BluRay.DD5.1.x264-EbP.nzb
...
2023-05-24 15:47:08,627::DEBUG::[newsunpack:578] rar_unpack(): Newfiles: ['\\\\?\\C:\\Users\\<USERNAME>\\downloads\\complete\\FILM\\_UNPACK_The.Lion.King.1.2004.720p.BluRay.DD5.1.x264-EbP\\The.Lion.King.1+.2004.720p.BluRay.DD5.1.x264-EbP.mkv']
```

let me try the other nzb

**Comment by thezoggy** [comment]
ok radarr:
![firefox_2023-05-24_16-08-25](https://github.com/sabnzbd/sabnzbd/assets/500882/fa79ff32-3995-420c-ba33-e6bb2e0188ff)
sab:
![firefox_2023-05-24_16-08-54](https://github.com/sabnzbd/sabnzbd/assets/500882/864668e2-c2f5-487d-8c7f-45c1981100e9)
![firefox_2023-05-24_16-09-29](https://github.com/sabnzbd/sabnzbd/assets/500882/b4ae27b0-f431-48c7-bcf2-a86f9c834293)

slowly getting there, but looks to be fine like the other nzb

**Comment by sanderjo** [comment]
FWIW:

The '\udcbd' is not valid UTF-8

```
>>> print('\udcbd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbd' in position 0: surrogates not allowed
```

**Comment by sanderjo** [comment]
@thezoggy here's a nice .NZB full of Unicode. Can you check on your system, and let the OP test it?

https://raw.githubusercontent.com/sanderjo/NZBs/master/Unicode_Mix_2023_%E2%8C%9B%F0%9F%9A%A6%F0%9F%90%9E%F0%9F%8D%9E%F0%9F%8C%9E%F0%9F%95%A5%F0%9F%8D%81.nzb

**Comment by thezoggy** [comment]
tried it out on my windows box, worked fine:
![firefox_2023-05-26_11-09-10](https://github.com/sabnzbd/sabnzbd/assets/500882/9fb07f4a-55d0-4816-98df-32a21f4b803a)

but oddly logging doesnt really have anything for it.. no `Unicode_Mix_2023_` anywhere.
```
2023-05-26 11:04:15,270::DEBUG::[postproc:1063] Triggering garbage collection and release of memory
2023-05-26 11:08:28,947::DEBUG::[getperformance:50] CPU model = Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
2023-05-26 11:08:43,638::DEBUG::[misc:222] Parsing category * to attributes: pp=3 script=None prio=0
2023-05-26 11:08:43,642::DEBUG::[nzbstuff:1020] Unwanted Extension: putting last rar after first rar
2023-05-26 11:08:43,643::DEBUG::[nzbstuff:1033] Unwanted Extension: First rar at 1, Last rar at 11
2023-05-26 11:08:43,643::DEBUG::[nzbstuff:959] NZB nzo-info = {}
2023-05-26 11:08:43,645::INFO::[nzbqueue:233] Saving queue
2023-05-26 11:08:43,648::DEBUG::[filesystem:1187] [sabnzbd\nzbqueue.py.save] Saving data for queue10.sab
...
2023-05-26 11:08:47,679::DEBUG::[filesystem:1119] [sabnzbd\filesystem.py.save_admin] Saving data for postproc2.sab in \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin
2023-05-26 11:08:48,410::DEBUG::[postproc:740] Verified sets: {}
2023-05-26 11:08:48,420::DEBUG::[filesystem:505] build_filelists(): joinables: []
2023-05-26 11:08:48,420::DEBUG::[filesystem:506] build_filelists(): zips: []
2023-05-26 11:08:48,421::DEBUG::[filesystem:508] build_filelists(): 7zips: []
2023-05-26 11:08:48,421::DEBUG::[filesystem:509] build_filelists(): ts: []
2023-05-26 11:08:48,424::INFO::[downloader:460] Forcing disconnect
2023-05-26 11:08:48,424::INFO::[filesystem:330] Checking if any resulting filenames need to be sanitized
2023-05-26 11:08:48,428::DEBUG::[filesystem:505] build_filelists(): joinables: []
2023-05-26 11:08:48,428::DEBUG::[filesystem:506] build_filelists(): zips: []
2023-05-26 11:08:48,429::DEBUG::[filesystem:508] build_filelists(): 7zips: []
2023-05-26 11:08:48,429::DEBUG::[filesystem:509] build_filelists(): ts: []
2023-05-26 11:08:48,430::DEBUG::[newsunpack:721] Analyzing rar file ... RAR5 found
2023-05-26 11:08:48,431::DEBUG::[misc:1176] Popen arguments: {'stdout': -1, 'stderr': -2, 'bufsize': 0, 'startupinfo': <subprocess.STARTUPINFO object at 0x0000026BF5B5B5D0>, 'creationflags': 32, 'text': True, 'encoding': 'utf8', 'errors': 'replace'}
2023-05-26 11:08:48,666::DEBUG::[downloader:965] Thread 39@news-us.usenetserver.com: forcing disconnect
2023-05-26 11:08:48,666::INFO::[newsunpack:857] Unpacked 1 files/folders in 0 seconds
2023-05-26 11:08:48,689::DEBUG::[deobfuscate_filenames:89] No additional par2 files found to process
2023-05-26 11:08:48,690::DEBUG::[articlecache:152] Purging 0 articles from the cache/disk
2023-05-26 11:08:48,702::DEBUG::[downloader:965] Thread 32@news-us.usenetserver.com: forcing disconnect
2023-05-26 11:08:48,714::DEBUG::[downloader:965] Thread 26@news-us.usenetserver.com: forcing disconnect
2023-05-26 11:08:48,715::INFO::[postproc:130] Saving postproc queue
2023-05-26 11:08:48,715::DEBUG::[filesystem:1187] [sabnzbd\postproc.py.save] Saving data for postproc2.sab
2023-05-26 11:08:48,716::DEBUG::[filesystem:1119] [sabnzbd\filesystem.py.save_admin] Saving data for postproc2.sab in \\?\C:\Users\zoggy\AppData\Local\sabnzbd\admin
2023-05-26 11:08:48,716::INFO::[downloader:455] Post-processing finished, resuming download
...
2023-05-26 11:08:52,746::INFO::[notifier:123] Sending notification: SABnzbd - Queue finished (type=queue_done, job_cat=None)
```

**Comment by Safihre** [comment]
I'm not sure what to do with this one. If there's anything we _can_ do.

**Comment by sanderjo** [comment]
> I'm not sure what to do with this one. If there's anything we _can_ do.

Indeed.

- Title is incorrect: it's correct unicode
- Problem not reproducable on Linux. And I doubt on Windows. So N=1
- Seems some overcompensating between encodings, probably caused by Radarr (not SAB)

So I would advice to close until reproducable in SABnzbd.

**Comment by thezoggy** [comment]
> I'm not sure what to do with this one. If there's anything we _can_ do.

I agree.
While the user had the same issue with both releases on different nzb from different sites. 
I couldn't replicate it myself with nzb or having radarr send the nzb to sabnzbd (but I tried from windows not via linux+docker). 

Mainly I was just sharing because of the unicode encoding error, as ive not seen that pop up before.

**Comment by Safihre** [comment]
👍
