### ISSUE TITLE
cherrypy error

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2588]
Just moved to a new box with python3.11 and I've seen this error pop up now and then. As far as I can tell everything is working well just wanted to know what it's all about.

`[09/Jun/2023:21:36:39] HTTP 
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    self.body.process()
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 982, in process
    super(RequestBody, self).process()
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 559, in process
    proc(self)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 225, in process_multipart_form_data
    process_multipart(entity)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 217, in process_multipart
    part.process()
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 557, in process
    self.default_proc()
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 717, in default_proc
    self.file = self.read_into_file()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 732, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpreqbody.py", line 671, in read_lines_to_boundary
    raise EOFError('Illegal end of multipart body.')
EOFError: Illegal end of multipart body.`

**Comment by thezoggy** [comment]
you would need to share the sab log that show all the lines that go with this to provide context and such. As you can see there is no mention of sab in that. I can assume something was trying to upload a file to cherrpy but it was malformed/incomplete/aborted. 

Also there are many os and many ways to run sab, we need to know details of your env. docker? which maintainer? which version of sab? 

The webserver error may be harmless but may not, with no info only thing can only assume things.

If the file was coming from an ip that was not you / drive by because you have sab exposed.. then that might be cause to do something.
It may be a completely different thing if you were restarting sab right when something tried to upload a nzb... so then not really a big deal as 3rd party app would prob just retry.

**Comment by thezoggy** [comment]
to make things readable can you edit and wrap the post with three backticks ``` before and after the contents

```
so things look nice and monospaced
```
