### ISSUE TITLE
Multiple Download due to Python Error

### ISSUE THREAD

**Issue by david-steg** [sabnzbd/sabnzbd#2596]
Hello,
I'm using sabnzbd with Radarr together.
by Queue Transfert, the same Movie will be added multiple Times.
![Capture-2](https://github.com/sabnzbd/sabnzbd/assets/71213394/8e657482-1794-4a9a-939a-7a9f65c6340b)

At the same time, to folowing error shows up:
`
[18/Jun/2023:09:02:12]  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpwsgi.py", line 105, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpwsgi.py", line 438, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpwsgi.py", line 244, in __init__
    self.run()
  File "/usr/lib/python3/dist-packages/cherrypy/_cpwsgi.py", line 347, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
cherrypy._cperror.TimeoutError
`

I tested 4.0.2 AND 4.0.3Beta1, same issue..
Python Version: 3.8.10
It run on Ubuntu 20.04 with your apt-repository.

**Comment by sanderjo** [comment]
Do you think both problems are related?

Regarding the cherrypy: that is the webserver of SABnzbd. Are SAB and Radarr on the same machine? Or same LAN? Or across Internet.

As a _workaround_ for multiple downloads: config/switches/#no_dupes

**Comment by david-steg** [comment]
They are on the same Hypervisor, but runs in two different VMs. Same LAN
Maybe, SABnzbd is shortly offline and this is causing an multiple File Queue.

I will try the Workaround, but i think it will just help by the exact same File name.

**Comment by david-steg** [comment]
I tried with Nzbget and i got the same issue... It seems to be more an Radarr Issue.
