### ISSUE TITLE
Fatal error in Downloader Traceback

### ISSUE THREAD

**Issue by amcgready** [sabnzbd/sabnzbd#2667]
I posted on the Discord and was asked to make a new ticket. Every time I launch sab I receive the following error, "Fatal error in Downloader
Traceback (most recent call last):
  File "sabnzbd\downloader.py", line 706, in run
ValueError: too many file descriptors in select()"

Link to debug log: https://1drv.ms/u/s!AudU6MbPBg-4ivkH7ZI9x3ZkA6cEWg?e=It8etv

**Comment by sanderjo** [comment]
```
2023-08-29 08:44:05,355::INFO::[newswrapper:348] 988@news.newshosting.com: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2023-08-29 08:44:05,364::INFO::[downloader:663] 2@news.vipernews.com: Initiating connection
2023-08-29 08:44:05,366::INFO::[notifier:123] Sending notification: Error - Fatal error in Downloader (type=error, job_cat=None)
2023-08-29 08:44:05,366::ERROR::[downloader:765] Fatal error in Downloader
Traceback (most recent call last):
  File "sabnzbd\downloader.py", line 706, in run
ValueError: too many file descriptors in select()

```
Wow: 988+ connections to a newsserver?!
Lower that to 50 and try again. With 50 connections to eweka, I achieve 500 MB/s = 5000 Mbps.

**Comment by mnightingale** [comment]
Edit your config file (sabnzbd.ini) manually and change `connections = 1000` to 100 - or ideally fewer.
I can't remember off-hand where it is on Windows.

Separately we should probably investigate the select() limits on windows and adjust SABs behaviour if required.

**Comment by amcgready** [comment]
Thank you everyone. Changed to fifty connections and that fixed the issue. I'm an idiot and thought since I have the 'unlimited' connections plan I could do the max connections for a server in sab. Obviously that is not the case.

**Comment by sanderjo** [comment]
I tried filling out & saving 2000, and then SAB says "Value must be less than or equal to 1000". 1000? I would say 200 should be the max.

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/912d612a-525c-4f92-a708-c0ed991f9ad1)

**Comment by thezoggy** [comment]
We purposely set it artificially high for future growth. And over the years this is the first time I've heard anyone misconfiguring/having issues with this value being too high.

**Comment by amcgready** [comment]
> 

The sad part is that I have successfully been using sab for years. I have no idea how I managed to make such an obvious error.

**Comment by sanderjo** [comment]
I set it to 1000, did a test download and got the below. Probably limitations in OS or python.
So 1000 does not look useful to me.


![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/05acea68-64e7-48ed-9aaa-a927ce5ba346)


```
ERROR a minute ago Failed to initialize 995@news6.newshosting.com with reason: [Errno 24] Too many open files
ERROR a minute ago Failed to initialize 994@news6.newshosting.com with reason: [Errno 24] Too many open files
ERROR a minute ago Failed to initialize 993@news6.newshosting.com with reason: [Errno 24] Too many open files
```

**Comment by sanderjo** [comment]
FWIW: after "ulimit -n 4096" on my Ubuntu, the above "[Errno 24] Too many open files" does not appear anymore. So that was an OS setting.

Still with the 1000 newsswerver connection, I of course get:

```
WARNING a few seconds ago Too many connections to server news6.newshosting.com [502 Too many connections.]
WARNING a few seconds ago Too many connections to server news6.newshosting.com [502 Too many connections.]
WARNING a few seconds ago Too many connections to server news6.newshosting.com [502 Too many connections.]
```

which is OK, but also (like OP reported):

```
a few seconds ago Fatal error in Downloader
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/downloader.py", line 691, in run
    read, _, _ = select.select(readkeys, (), (), 1.0)
ValueError: filedescriptor out of range in select()
```

... which is not OK: python traceback. And I assume a python limit/problem, not a SAB problem?

**500**

When I lower to 500, no traceback anymore. So safer for python (and OS) to set max to 500?




**Logging**


![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/e2345f28-8b0b-44df-88e5-7dc2e0b4242e)


```
2023-08-30 08:07:42,469::INFO::[notifier:123] Sending notification: Error - Fatal error in Downloader (type=error, job_cat=None)
2023-08-30 08:07:42,469::INFO::[newswrapper:348] 682@news6.newshosting.com: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2023-08-30 08:07:42,469::INFO::[newswrapper:348] 628@news6.newshosting.com: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2023-08-30 08:07:42,467::ERROR::[downloader:750] Fatal error in Downloader
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd/sabnzbd/downloader.py", line 691, in run
    read, _, _ = select.select(readkeys, (), (), 1.0)
ValueError: filedescriptor out of range in select()

...
2023-08-30 08:08:04,781::INFO::[notifier:123] Sending notification: Warning - Restarting because of crashed downloader (type=warning, job_cat=None)
2023-08-30 08:08:04,781::WARNING::[__init__:477] Restarting because of crashed downloader
2023-08-30 08:08:04,781::INFO::[SABnzbd:1579] Performing triggered restart
```

**Comment by mnightingale** [comment]
I agree with reducing the max connection limit but there is still nothing stopping someone setting up multiple servers and exceeding the overall select limit.

https://github.com/sabnzbd/sabnzbd/blob/77518cf1f5eb1162ed0634c6f1f16d4d70df6822/sabnzbd/downloader.py#L690-L691

i.e. if len(readkeys) > 512 randomly take 512 or the first/last 512, but I don't really think it's worth the effort since it would require a user to have several server subscriptions.
