### ISSUE TITLE
Crashes when saving config due to concurrent access

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2685]
We have had intermitting failures of the CI on `test_api_watched_now`.
Turns out the problem is that `CFG_DATABASE` changes size (see traceback below).

I always found the whole setup of the `config.py` very very ugly with all it's `global`'s, just never got around to making a good class-based refactor.
If we do a refactor we can introduce proper locks around this.

For now marking it as `xfail`.

```
2023-09-17T19:08:35.3862707Z Traceback (most recent call last):
2023-09-17T19:08:35.3863442Z   File "c:\users\runneradmin\.virtualenvs\.venv\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
2023-09-17T19:08:35.3863941Z     self._do_respond(path_info)
2023-09-17T19:08:35.3864605Z   File "c:\users\runneradmin\.virtualenvs\.venv\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
2023-09-17T19:08:35.3865110Z     response.body = self.handler()
2023-09-17T19:08:35.3865782Z   File "c:\users\runneradmin\.virtualenvs\.venv\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
2023-09-17T19:08:35.3866308Z     self.body = self.oldhandler(*args, **kwargs)
2023-09-17T19:08:35.3866996Z   File "c:\users\runneradmin\.virtualenvs\.venv\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
2023-09-17T19:08:35.3867516Z     return self.callable(*self.args, **self.kwargs)
2023-09-17T19:08:35.3868015Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\interface.py", line 191, in internal_wrap
2023-09-17T19:08:35.3868441Z     return wrap_func(*args, **kwargs)
2023-09-17T19:08:35.3868872Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\interface.py", line 467, in api
2023-09-17T19:08:35.3869323Z     return api_handler(kwargs)
2023-09-17T19:08:35.3869750Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\api.py", line 105, in api_handler
2023-09-17T19:08:35.3870219Z     response = _api_table.get(mode, (_api_undefined, 2))[0](name, kwargs)
2023-09-17T19:08:35.3870722Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\api.py", line 131, in _api_set_config
2023-09-17T19:08:35.3871100Z     config.save_config()
2023-09-17T19:08:35.3871513Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\decorators.py", line 39, in call_func
2023-09-17T19:08:35.3871910Z     return func(*args, **kw)
2023-09-17T19:08:35.3872339Z   File "D:\a\sabnzbd\sabnzbd\sabnzbd\config.py", line 962, in save_config
2023-09-17T19:08:35.3872741Z     for section in CFG_DATABASE:
2023-09-17T19:08:35.3873112Z RuntimeError: dictionary changed size during iteration
```

**Comment by Safihre** [comment]
We still should do a `class` based refactor..
