### ISSUE TITLE
Error - "Failed making <Directory> (type=error, job_cat=None)"

### ISSUE THREAD

**Issue by bookamp** [sabnzbd/sabnzbd#2687]
I have a docker instance of sabnzbd running on a mac mini. It has been running great, at least until a week ago. Today I noticed that every time I try to download a release, I get errors, specifically sabnzbd is unable to create directories in the mounted drive.

I have portainer installed, so I can login to sabnzbd terminal as root and navigate to the external mount and I can see the folders have not been created. I was able to create folders via the console, logged in as root.

Anyone have thoughts on what could be going on here?

**Here is the sabnzbd download folder settings**

<img src="https://preview.redd.it/vrr72hknwwpb1.png?width=961&format=png&auto=webp&s=edeefc393f351e34e36259c2cbce732cd7eac967" />

**Here is the docker-compose**

```
sabnzbd:

image: linuxserver/sabnzbd:latest

container_name: sabnzbd

restart: always

network_mode: "service:openvpn-client"

user: root

environment:

- TZ=america/new_york

- PUID=0 # was 1000 before, but I changed it to 0 to check if access could be an issue

- PGID=0 # was 1000 before, but I changed it to 0 to check if access could be an issue

volumes:

- /Users/bookmap/Docker/nzb/config/sabnzbd:/config

- /Volumes/media1:/mnt/f

- /Volumes/media2:/mnt/m
```

**Here are the logs:**

2023-09-22 23:10:03 [migrations] started
2023-09-22 23:10:03 [migrations] no migrations found
2023-09-22 23:10:03 ───────────────────────────────────────
2023-09-22 23:10:03 
2023-09-22 23:10:03       ██╗     ███████╗██╗ ██████╗ 
2023-09-22 23:10:03       ██║     ██╔════╝██║██╔═══██╗
2023-09-22 23:10:03       ██║     ███████╗██║██║   ██║
2023-09-22 23:10:03       ██║     ╚════██║██║██║   ██║
2023-09-22 23:10:03       ███████╗███████║██║╚██████╔╝
2023-09-22 23:10:03       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-09-22 23:10:03 
2023-09-22 23:10:03    Brought to you by linuxserver.io
2023-09-22 23:10:03 ───────────────────────────────────────
2023-09-22 23:10:03 
2023-09-22 23:10:03 To support the app dev(s) visit:
2023-09-22 23:10:03 SABnzbd: https://sabnzbd.org/donate
2023-09-22 23:10:03 
2023-09-22 23:10:03 To support LSIO projects visit:
2023-09-22 23:10:03 https://www.linuxserver.io/donate/
2023-09-22 23:10:03 
2023-09-22 23:10:03 ───────────────────────────────────────
2023-09-22 23:10:03 GID/UID
2023-09-22 23:10:03 ───────────────────────────────────────
2023-09-22 23:10:03 
2023-09-22 23:10:03 User UID:    0
2023-09-22 23:10:03 User GID:    0
2023-09-22 23:10:03 ───────────────────────────────────────
2023-09-22 23:10:03 
2023-09-22 23:10:03 [custom-init] No custom files found, skipping...
2023-09-22 23:10:03 2023-09-23 03:10:03,778::INFO::[SABnzbd:1171] --------------------------------
2023-09-22 23:10:03 2023-09-23 03:10:03,779::INFO::[SABnzbd:1172] SABnzbd.py-4.0.3
2023-09-22 23:10:03 2023-09-23 03:10:03,780::INFO::[SABnzbd:1182] Commit = 9fafe64cff631ea6c61e65780f366046b2830108
2023-09-22 23:10:03 2023-09-23 03:10:03,781::INFO::[SABnzbd:1184] Full executable path = /app/sabnzbd/SABnzbd.py
2023-09-22 23:10:03 2023-09-23 03:10:03,782::INFO::[SABnzbd:1185] Arguments = "/app/sabnzbd/SABnzbd.py" "--config-file" "/config" "--server" "::"
2023-09-22 23:10:03 2023-09-23 03:10:03,784::INFO::[SABnzbd:1186] Python-version = 3.11.5 (main, Aug 26 2023, 11:59:23) [GCC 12.2.1 20220924]
2023-09-22 23:10:03 2023-09-23 03:10:03,785::INFO::[SABnzbd:1187] Dockerized = True
2023-09-22 23:10:03 2023-09-23 03:10:03,786::INFO::[SABnzbd:1188] CPU architecture = x86_64
2023-09-22 23:10:03 2023-09-23 03:10:03,788::INFO::[SABnzbd:1191] Platform = posix - Linux-6.3.13-linuxkit-x86_64-with
2023-09-22 23:10:03 2023-09-23 03:10:03,789::INFO::[SABnzbd:1197] Preferred encoding = UTF-8
2023-09-22 23:10:03 2023-09-23 03:10:03,789::INFO::[SABnzbd:1219] SSL version = OpenSSL 3.1.3 19 Sep 2023
2023-09-22 23:10:03 2023-09-23 03:10:03,791::INFO::[SABnzbd:1228] Certifi version = 2023.07.22
2023-09-22 23:10:03 2023-09-23 03:10:03,791::INFO::[SABnzbd:1229] Loaded additional certificates from /lsiopy/lib/python3.11/site-packages/certifi/cacert.pem
2023-09-22 23:10:03 2023-09-23 03:10:03,792::INFO::[SABnzbd:1250] Using INI file /config/sabnzbd.ini
2023-09-22 23:10:03 2023-09-23 03:10:03,795::INFO::[postproc:135] Loading postproc queue
2023-09-22 23:10:03 2023-09-23 03:10:03,796::INFO::[scheduler:190] Scheduling RSS interval task every 60 min (delay=27)
2023-09-22 23:10:03 2023-09-23 03:10:03,797::INFO::[scheduler:201] Scheduling VersionCheck on day 2 at 12:24
2023-09-22 23:10:03 2023-09-23 03:10:03,797::INFO::[scheduler:215] Setting schedule for midnight BPS reset
2023-09-22 23:10:03 2023-09-23 03:10:03,798::INFO::[scheduler:218] Setting schedule for server expiration check
2023-09-22 23:10:03 2023-09-23 03:10:03,798::INFO::[scheduler:223] Setting schedule for server quota check
2023-09-22 23:10:03 2023-09-23 03:10:03,799::INFO::[__init__:325] All processes started
2023-09-22 23:10:03 2023-09-23 03:10:03,800::INFO::[SABnzbd:340] Template location for Glitter is /app/sabnzbd/interfaces/Glitter
2023-09-22 23:10:03 2023-09-23 03:10:03,801::INFO::[SABnzbd:340] Template location for Config is /app/sabnzbd/interfaces/Config
2023-09-22 23:10:03 2023-09-23 03:10:03,803::INFO::[misc:1175] [N/A] Running external command: ['/usr/bin/unrar']
2023-09-22 23:10:03 2023-09-23 03:10:03,804::INFO::[misc:1175] [N/A] Running external command: ['/usr/bin/7z']
2023-09-22 23:10:03 2023-09-23 03:10:03,807::INFO::[misc:1175] [N/A] Running external command: ['/usr/local/bin/par2', '-h']
2023-09-22 23:10:03 2023-09-23 03:10:03,809::INFO::[SABnzbd:425] SABCTools module (v7.0.2)... found!
2023-09-22 23:10:03 2023-09-23 03:10:03,809::INFO::[SABnzbd:426] SABCTools module is using SIMD set: AVX2
2023-09-22 23:10:03 2023-09-23 03:10:03,810::INFO::[SABnzbd:427] SABCTools module is linked to OpenSSL: True
2023-09-22 23:10:03 2023-09-23 03:10:03,810::INFO::[SABnzbd:447] Cryptography module (v41.0.1)... found!
2023-09-22 23:10:03 2023-09-23 03:10:03,811::INFO::[SABnzbd:452] par2 binary... found (/usr/local/bin/par2)
2023-09-22 23:10:03 2023-09-23 03:10:03,812::INFO::[SABnzbd:459] UNRAR binary... found (/usr/bin/unrar)
2023-09-22 23:10:03 2023-09-23 03:10:03,812::INFO::[SABnzbd:467] UNRAR binary version 6.23
2023-09-22 23:10:03 2023-09-23 03:10:03,813::INFO::[SABnzbd:475] 7za binary... found (/usr/bin/7z)
2023-09-22 23:10:03 2023-09-23 03:10:03,814::INFO::[SABnzbd:477] 7za binary version 22.01
2023-09-22 23:10:03 2023-09-23 03:10:03,814::INFO::[SABnzbd:488] nice binary... found (/bin/nice)
2023-09-22 23:10:03 2023-09-23 03:10:03,815::INFO::[SABnzbd:492] ionice binary... found (/bin/ionice)
2023-09-22 23:10:03 2023-09-23 03:10:03,816::INFO::[SABnzbd:1439] Starting web-interface on :::8080
2023-09-22 23:10:03 2023-09-23 03:10:03,817::INFO::[_cplogging:213] [23/Sep/2023:03:10:03] ENGINE Bus STARTING
2023-09-22 23:10:04 [ls.io-init] done.
2023-09-22 23:10:08 /lsiopy/lib/python3.11/site-packages/cherrypy/process/servers.py:416: UserWarning: Unable to verify that the server is bound on 8080
2023-09-22 23:10:08   warnings.warn(msg)
2023-09-22 23:10:08 2023-09-23 03:10:08,951::INFO::[_cplogging:213] [23/Sep/2023:03:10:08] ENGINE Serving on http://:::8080
2023-09-22 23:10:08 2023-09-23 03:10:08,953::INFO::[_cplogging:213] [23/Sep/2023:03:10:08] ENGINE Bus STARTED
2023-09-22 23:10:08 2023-09-23 03:10:08,954::INFO::[SABnzbd:1484] Starting SABnzbd.py-4.0.3
2023-09-22 23:10:08 2023-09-23 03:10:08,962::INFO::[dirscanner:111] Dirscanner starting up
2023-09-22 23:10:08 2023-09-23 03:10:08,963::INFO::[panic:239] Launching browser with http://127.0.0.1:8080/sabnzbd
2023-09-22 23:10:08 2023-09-23 03:10:08,966::INFO::[notifier:123] Sending notification: SABnzbd - SABnzbd 4.0.3 started (type=startup, job_cat=None)
2023-09-22 23:10:09 2023-09-23 03:10:09,048::INFO::[database:558] Scheduled history purge
2023-09-22 23:10:09 2023-09-23 03:10:09,116::INFO::[zconfig:61] No bonjour/zeroconf support installed
2023-09-22 23:10:09 2023-09-23 03:10:09,121::INFO::[ssdp:108] Serving SSDP on 10.8.8.16 as SABnzbd
2023-09-22 23:10:23 2023-09-23 03:10:23,187::INFO::[urlgrabber:400] Fetching https://sabnzbd.org/tests/test_download_1000MB.nzb
2023-09-22 23:10:23 2023-09-23 03:10:23,190::INFO::[nzbqueue:233] Saving queue
2023-09-22 23:10:23 2023-09-23 03:10:23,194::INFO::[notifier:123] Sending notification: NZB added to queue - Trying to fetch NZB from https://sabnzbd.org/tests/test_download_1000MB.nzb (type=download, job_cat=None)
2023-09-22 23:10:23 2023-09-23 03:10:23,195::INFO::[urlgrabber:120] Grabbing URL https://sabnzbd.org/tests/test_download_1000MB.nzb
2023-09-22 23:10:23 2023-09-23 03:10:23,352::INFO::[nzbparser:85] Attempting to add test_download_1000MB.nzb [/config/admin/future/test_download_1000MB.nzb]
2023-09-22 23:10:23 2023-09-23 03:10:23,353::INFO::[nzbqueue:392] [N/A] Removing job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_1000MB.nzb
2023-09-22 23:10:23 2023-09-23 03:10:23,354::INFO::[nzbstuff:1836] [N/A] Purging data for job Trying to fetch NZB from https://sabnzbd.org/tests/test_download_1000MB.nzb (delete_all_data=False)
2023-09-22 23:10:23 2023-09-23 03:10:23,355::INFO::[nzbqueue:233] Saving queue
2023-09-22 23:10:23 2023-09-23 03:10:23,358::INFO::[filesystem:711] Creating directories: /mnt/m/Media/incomplete/test_download_1000MB
2023-09-22 23:10:23 2023-09-23 03:10:23,360::INFO::[filesystem:711] Creating directories: /mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__
2023-09-22 23:10:23 2023-09-23 03:10:23,361::INFO::[notifier:123] Sending notification: Error - Failed making (/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__) (type=error, job_cat=None)
2023-09-22 23:10:23 2023-09-23 03:10:23,361::ERROR::[filesystem:733] Failed making (/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__)
2023-09-22 23:10:23 Traceback (most recent call last):
2023-09-22 23:10:23   File "/app/sabnzbd/sabnzbd/filesystem.py", line 727, in create_all_dirs
2023-09-22 23:10:23     os.mkdir(path_part_combined)
2023-09-22 23:10:23 FileNotFoundError: [Errno 2] No such file or directory: '/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__'
2023-09-22 23:10:23 2023-09-23 03:10:23,363::INFO::[filesystem:1243] Saving /mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz
2023-09-22 23:10:23 2023-09-23 03:10:23,365::INFO::[notifier:123] Sending notification: Error - Saving /mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz failed (type=error, job_cat=None)
2023-09-22 23:10:23 2023-09-23 03:10:23,365::ERROR::[filesystem:1251] Saving /mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz failed
2023-09-22 23:10:23 2023-09-23 03:10:23,367::INFO::[filesystem:1252] Traceback: 
2023-09-22 23:10:23 Traceback (most recent call last):
2023-09-22 23:10:23   File "/app/sabnzbd/sabnzbd/filesystem.py", line 1246, in save_compressed
2023-09-22 23:10:23     with open(full_nzb_path, "wb") as tgz_file:
2023-09-22 23:10:23          ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-22 23:10:23 FileNotFoundError: [Errno 2] No such file or directory: '/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz'
2023-09-22 23:10:23 2023-09-23 03:10:23,370::INFO::[notifier:123] Sending notification: Warning - Invalid NZB file test_download_1000MB.nzb, skipping (error: [Errno 2] No such file or directory: '/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz') (type=warning, job_cat=None)
2023-09-22 23:10:23 2023-09-23 03:10:23,370::WARNING::[nzbstuff:781] Invalid NZB file test_download_1000MB.nzb, skipping (error: [Errno 2] No such file or directory: '/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz')
2023-09-22 23:10:23 2023-09-23 03:10:23,371::INFO::[nzbstuff:782] Traceback: 
2023-09-22 23:10:23 Traceback (most recent call last):
2023-09-22 23:10:23   File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 778, in __init__
2023-09-22 23:10:23     sabnzbd.nzbparser.nzbfile_parser(full_nzb_path, self)
2023-09-22 23:10:23   File "/app/sabnzbd/sabnzbd/nzbparser.py", line 378, in nzbfile_parser
2023-09-22 23:10:23     with gzip.open(full_nzb_path) as nzb_fh:
2023-09-22 23:10:23          ^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-22 23:10:23   File "/usr/lib/python3.11/gzip.py", line 58, in open
2023-09-22 23:10:23     binary_file = GzipFile(filename, gz_mode, compresslevel)
2023-09-22 23:10:23                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-22 23:10:23   File "/usr/lib/python3.11/gzip.py", line 174, in __init__
2023-09-22 23:10:23     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
2023-09-22 23:10:23                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-22 23:10:23 FileNotFoundError: [Errno 2] No such file or directory: '/mnt/m/Media/incomplete/test_download_1000MB/__ADMIN__/test_download_1000MB.nzb.gz'
2023-09-22 23:10:23 2023-09-23 03:10:23,374::INFO::[nzbstuff:1836] [N/A] Purging data for job test_download_1000MB (delete_all_data=True)
2023-09-22 23:10:23 2023-09-23 03:10:23,377::INFO::[notifier:123] Sending notification: URL Fetching failed;  - URL Fetching failed; Empty NZB file test_download_1000MB.nzb
2023-09-22 23:10:23 https://sabnzbd.org/tests/test_download_1000MB.nzb (type=failed, job_cat=None)
2023-09-22 23:10:23 2023-09-23 03:10:23,378::INFO::[postproc:130] Saving postproc queue
2023-09-22 23:10:23 2023-09-23 03:10:23,380::INFO::[postproc:377] Starting Post-Processing on https://sabnzbd.org/tests/test_download_1000MB.nzb => Repair:None, Unpack:None, Delete:None, Script:None, Cat:*
2023-09-22 23:10:23 2023-09-23 03:10:23,381::INFO::[notifier:123] Sending notification: Post-processing - https://sabnzbd.org/tests/test_download_1000MB.nzb (type=pp, job_cat=*)
2023-09-22 23:10:23 2023-09-23 03:10:23,383::INFO::[downloader:462] Forcing disconnect
2023-09-22 23:10:23 2023-09-23 03:10:23,386::INFO::[filesystem:330] Checking if any resulting filenames need to be sanitized
2023-09-22 23:10:23 2023-09-23 03:10:23,388::INFO::[nzbstuff:1836] [N/A] Purging data for job https://sabnzbd.org/tests/test_download_1000MB.nzb (delete_all_data=False)
2023-09-22 23:10:23 2023-09-23 03:10:23,390::INFO::[notifier:123] Sending notification: Download Failed - https://sabnzbd.org/tests/test_download_1000MB.nzb (type=failed, job_cat=*)
2023-09-22 23:10:23 2023-09-23 03:10:23,522::INFO::[database:292] Added job https://sabnzbd.org/tests/test_download_1000MB.nzb to history
2023-09-22 23:10:23 2023-09-23 03:10:23,522::INFO::[postproc:130] Saving postproc queue
2023-09-22 23:10:23 2023-09-23 03:10:23,524::INFO::[downloader:457] Post-processing finished, resuming download

**Comment by bookamp** [comment]
OK. I figured it out. It looks like I cannot have '/' in front of the folder path in the config.
Although I'm not quite sure why this was working until now. I don't think I have updated this config in months.

The change I made is 
![image](https://github.com/sabnzbd/sabnzbd/assets/1390257/3f761508-dd60-4ab7-b46f-074dd4b4eba9)

to 

![image](https://github.com/sabnzbd/sabnzbd/assets/1390257/f6c1dfd9-4f62-4ac2-b5da-23793651b8bb)

I even used the folder browse button to select a folder, and it automatically added a '/' in the front. I removed the / and everything works as it should.

**Comment by thezoggy** [comment]
github is for reporting bugs, not user support.

Please use one of the support channels: [forums](https://forums.sabnzbd.org/), [subreddit](https://www.reddit.com/r/SABnzbd/), [discord ](https://discord.gg/KQzDe7fvNU), or [IRC](https://sabnzbd.org/live-chat.html#) for support/questions.

but just quick things:
1) you dont need to put sab behind vpn if your doing ssl to your usenet service providers
2) you have permission issues, sab cant create the folder.
