### ISSUE TITLE
Traceback [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Kcchouette** [sabnzbd/sabnzbd#2693]
On Sabnzbd 4.1.0, I had this error
I do not know how to reproduce the issue:

```
2023-09-27 19:22:47,815::INFO::[notifier:123] Sending notification: Error - Saving /home/user/incomplete/YYYYY/__ADMIN__/SABnzbd_nzo_svfvl5yr failed (type=error, job_cat=None)
2023-09-27 19:22:47,815::ERROR::[filesystem:1135] Saving /home/user/incomplete/YYYYY/__ADMIN__/SABnzbd_nzo_svfvl5yr failed
2023-09-27 19:22:47,815::INFO::[filesystem:1136] Traceback: 
Traceback (most recent call last):
  File "/home/user/SABnzbd-4.1.0/sabnzbd/postproc.py", line 264, in run
    nzo = self.fast_queue.get(timeout=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/SABnzbd-4.1.0/sabnzbd/postproc.py", line 269, in run
    nzo = self.slow_queue.get(timeout=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/SABnzbd-4.1.0/sabnzbd/filesystem.py", line 1124, in save_data
    with open(path, "wb") as data_file:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/incomplete/YYYYY/__ADMIN__/SABnzbd_nzo_svfvl5yr'
2023-09-27 19:22:47,874::INFO::[postproc:130] Saving postproc queue
```

Cheers

**Comment by thezoggy** [comment]
Please use one of the support channels: [forums](https://forums.sabnzbd.org/), [subreddit](https://www.reddit.com/r/SABnzbd/), [discord ](https://discord.gg/KQzDe7fvNU), or [IRC](https://sabnzbd.org/live-chat.html#) for support/questions.

**Comment by Kcchouette** [comment]
Hello, 
I do not need support or question, I report it for bug fixing

Do not hesitate to close it if needed

**Comment by Safihre** [comment]
It's most likely not a bug but something else.on your system that deleted the folder before SAB could get to it.

**Comment by Kcchouette** [comment]
I find how to reproduce it:
Having a nzb named XXXX.nbz

You download it from sabnzbd, you delete the folder and the content at the end.
Then you put it again in sabnzbd; you should have two XXXX, one in the downloading queue, the other on the finish queue
When the one on the downloading queue is at 90%, delete the one on the finish queue.

You should reproduce my issue

**Comment by Kcchouette** [comment]
@Safihre can you open it again please?

**Comment by Safihre** [comment]
Is the item in history Failed or succeeded?

**Comment by Kcchouette** [comment]
The one in history and in finish queue is succeed

But you have delete it manually on your file system

**Comment by Safihre** [comment]
I think there is potentially a bug here that's already there for a while. I'll take a deeper look.

**Comment by Safihre** [comment]
I implemented some fixes that should prevent this!
