### ISSUE TITLE
Losing Access to SABnzbd after a period of time (again)

### ISSUE THREAD

**Issue by joreilly02** [sabnzbd/sabnzbd#2709]
### SABnzbd version

4.1.0

### Operating system

MacOS Sonoma

### Using Docker image

None

### Description

I am having connection issues again. SABnzbd will work for a period of time, then will be inaccessible through any browser. Looking at the logs, I found the following (I'm sorry, I don't know if this is anything):

Traceback (most recent call last):
  File "cheroot/server.py", line 1277, in communicate
  File "cheroot/server.py", line 710, in parse_request
  File "cheroot/server.py", line 751, in read_request_line
  File "cheroot/server.py", line 301, in readline
  File "_pyio.py", line 574, in readline
  File "_pyio.py", line 553, in nreadahead
  File "_pyio.py", line 1149, in peek
  File "_pyio.py", line 1156, in _peek_unlocked
  File "socket.py", line 706, in readinto
OSError: [Errno 57] Socket is not connected
 (type=warning, job_cat=None)
2023-10-13 17:35:38,573::WARNING::[_cplogging:213] [13/Oct/2023:17:35:38] ENGINE socket.error 57
Traceback (most recent call last):
  File "cheroot/server.py", line 1277, in communicate
  File "cheroot/server.py", line 710, in parse_request
  File "cheroot/server.py", line 751, in read_request_line
  File "cheroot/server.py", line 301, in readline
  File "_pyio.py", line 574, in readline
  File "_pyio.py", line 553, in nreadahead
  File "_pyio.py", line 1149, in peek
  File "_pyio.py", line 1156, in _peek_unlocked
  File "socket.py", line 706, in readinto
OSError: [Errno 57] Socket is not connected

2023-10-13 17:35:38,573::WARNING::[_cplogging:213] [13/Oct/2023:17:35:38] ENGINE socket.error 57
Traceback (most recent call last):
  File "cheroot/server.py", line 1277, in communicate
  File "cheroot/server.py", line 710, in parse_request
  File "cheroot/server.py", line 751, in read_request_line
  File "cheroot/server.py", line 301, in readline
  File "_pyio.py", line 574, in readline
  File "_pyio.py", line 553, in nreadahead
  File "_pyio.py", line 1149, in peek
  File "_pyio.py", line 1156, in _peek_unlocked
  File "socket.py", line 706, in readinto
OSError: [Errno 57] Socket is not connected

[sabnzbd-2.log](https://github.com/sabnzbd/sabnzbd/files/12900177/sabnzbd-2.log)

Please let me know if there's anything you'd like me to do, and thank you so much for your help!

**Comment by thezoggy** [comment]
would need to see DEBUG level logs to really confirm much, but this may be relevant:
https://forums.sabnzbd.org/viewtopic.php?t=25906

as its annoying to work support issues through github.. 

Please use one of the support channels: [forums](https://forums.sabnzbd.org/), [subreddit](https://www.reddit.com/r/SABnzbd/), [discord ](https://discord.gg/KQzDe7fvNU), or [IRC](https://sabnzbd.org/live-chat.html#) for support/questions.
