### ISSUE TITLE
Post-processing was aborted

### ISSUE THREAD

**Issue by Kcchouette** [sabnzbd/sabnzbd#2714]
### SABnzbd version

4.1.0 [b7e3401]

### Operating system

Linux

### Using Docker image

None

### Description

Log:

```
2023-10-20 16:01:06,475::INFO::[filesystem:330] Checking if any resulting filenames need to be sanitized
2023-10-20 16:01:06,537::INFO::[notifier:123] Sending notification: Error - Post Processing Failed for YYYYY (see logfile) (type=error, job_cat=None)
2023-10-20 16:01:06,537::ERROR::[postproc:597] Post Processing Failed for YYYYY (see logfile)
2023-10-20 16:01:06,537::INFO::[postproc:598] Traceback: 
Traceback (most recent call last):
  File "SABnzbd-4.1.0/sabnzbd/postproc.py", line 440, in process_job
    newfiles = sanitize_files(filelist=newfiles)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "SABnzbd-4.1.0/sabnzbd/filesystem.py", line 340, in sanitize_files
    output_filelist.append(renamer(old_path, old_path))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "SABnzbd-4.1.0/sabnzbd/decorators.py", line 39, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "SABnzbd-4.1.0/sabnzbd/filesystem.py", line 856, in renamer
    name = sanitize_filename(name)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "SABnzbd-4.1.0/sabnzbd/filesystem.py", line 237, in sanitize_filename
    if len(utob(name)) + len(utob(ext)) > DEF_FILE_MAX:
           ^^^^^^^^^^
  File "SABnzbd-4.1.0/sabnzbd/encoding.py", line 34, in utob
    return str_in.encode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc91' in position 14: surrogates not allowed
2023-10-20 16:01:06,563::INFO::[notifier:123] Sending notification: Download Failed - YYYYY (type=failed, job_cat=*)
2023-10-20 16:01:06,563::INFO::[notifier:183] Send to NotifyOSD: Download Failed / YYYYY
```

**Comment by sanderjo** [comment]
Garbage in, garbage out. Check your NZB and it contents: there must be garbage: not ASCII, not correct utf-8.

Happens often with non-US-ASCII test (German umlauts etc), which are wrong encoded to fake unicode.

**Comment by mnightingale** [comment]
The behaviour of utob could be improved to not throw the error though.
It looks like where it broke we only want to know the length so it really matter if we used surrogateescape, but for actually picking a filename probably ignore/replace.

i.e. `str_in.encode("utf-8", "surrogateescape")`

I'd need to test it with some broken files

**Comment by Safihre** [comment]
Seems it's an emoji based on Google results:
https://www.google.com/search?q=%5Cudc91

**Comment by sanderjo** [comment]
FWIW

https://en.wikipedia.org/wiki/UTF-8#:~:text=high%20and%20low%20surrogate%20halves%20used%20by%20UTF%2D16%20(U%2BD800%20through%20U%2BDFFF)
So '\udc91'  = U+DC91 (something else than '\xdc91' ) is a not valid unicode sequence. And python is telling that.

**Comment by thezoggy** [comment]
@Kcchouette can you share where you got the nzb (and what it is) so we can go get it ourselves to test / share the nzb ?

**Comment by thezoggy** [comment]
got nzb from user on discord, so its an app.

nzb is fine.. which has rarset..which extracts fine.. then that has rar inside.. which extracts fine. then that rar had application and that application had zip files which sab eventually goes and tries and eventually pukes on

https://privatebin.net/?792f74456c75c44e#b9k4ZMRUDfhLc2ALYVng9tEETLRtXiSLTB42vRA2R6x

**Comment by sanderjo** [comment]
> told user to just use cat to only do +Repair for now for 'apps' s

Why not turn off "Enable recursive unpacking - Unpack archives (rar, zip, 7z) within archives."

Funny: the error is a Code Page (test?) file. Code Page 437 is this case. So, as said, if codepage stuff is tried a utf-8, all kinds of errors can happen, including the surrogate error. I think that does make testing / creating a test case easier.

Curiosity: The privatebin shows the download on Linux/POSIX. Can you or someone else download it on Windows?

**Comment by thezoggy** [comment]
> > told user to just use cat to only do +Repair for now for 'apps' s
> 
> Why not turn off "Enable recursive unpacking - Unpack archives (rar, zip, 7z) within archives."
> 
> Funny: the error is a Code Page (test?) file. Code Page 437 is this case. So, as said, if codepage stuff is tried a utf-8, all kinds of errors can happen, including the surrogate error. I think that does make testing / creating a test case easier.
> 
> Curiosity: The privatebin shows the download on Linux/POSIX. Can you or someone else download it on Windows?
> 
> EDIT
> 
> Can you share the .NZB?

sander/saf, sent you the nzb via email.

@sanderjo you of course could turn off recursive unpacking, but why make everything suffer if you want to just isolate it to 'apps' which you can then just solve with how you handle those jobs. personally ive always done this sort of thing with 'apps/games' type things where you really dont want apps meddling with the download or extract them because of anitvirus/malware stuff firing off on them.. which you want to move to a secure enclave to do stuff with them or may not end up on the same os your downloading them to. 

yes, i grabbed the nzb on my normal setup, which is lsio's sab docker on my unraid. 

i have sab 4.2.0a1 on a windows box, tossing the nzb there... looks like it worked just fine even with recursive unpack... due to log length i tossed it up here: http://zoggy.net/win-2714.txt

**Comment by thezoggy** [comment]
so same app and options are used but windows its fine but linux its not.....

windows you can see newer version of 7zip is used (23.01): 
```
2023-10-20 23:42:36,343::INFO::[misc:1164] [sabnzbd\newsunpack.py.seven_extract_core] Running external command: ['C:\\Program Files\\SABnzbd\\win\\7zip\\7za.exe', 'x', '-y', '-aou', '-ssc-', '-p<removed>', '-o\\\\?\\C:\\Users\\zoggy\\downloads\\complete\\test\\_UNPACK_DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64\\StreamFab 6.1.4.4 (x64)\\App\\StreamFab\\PYthon37\\Lib\\test', '\\\\?\\C:\\Users\\zoggy\\downloads\\complete\\test\\_UNPACK_DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64\\StreamFab 6.1.4.4 (x64)\\App\\StreamFab\\PYthon37\\Lib\\test\\zip_cp437_header.zip']
2023-10-20 23:42:36,344::DEBUG::[misc:1165] Popen arguments: {'stdout': -1, 'stderr': -2, 'bufsize': 0, 'startupinfo': <subprocess.STARTUPINFO object at 0x000001E468B7FB30>, 'creationflags': 32, 'text': True, 'encoding': 'utf8', 'errors': 'replace'}
2023-10-20 23:42:36,364::DEBUG::[newsunpack:967] 7za output: 
7-Zip (a) 23.01 (x86) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
```

vs linux using 22.01
```
2023-10-20 16:48:46,721::INFO::[misc:1164] [sabnzbd.newsunpack.seven_extract_core] Running external command: ['/usr/bin/7zz', 'x', '-y', '-aou', '-ssc', '-p<removed>', '-o/downloads/complete/test/_UNPACK_DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/StreamFab 6.1.4.4 (x64)/App/StreamFab/PYthon37/Lib/test', '/downloads/complete/test/_UNPACK_DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/StreamFab 6.1.4.4 (x64)/App/StreamFab/PYthon37/Lib/test/zip_cp437_header.zip']
2023-10-20 16:48:46,721::DEBUG::[misc:1165] Popen arguments: {'stdout': -1, 'stderr': -2, 'bufsize': 0, 'startupinfo': None, 'creationflags': 0, 'text': True, 'encoding': 'utf8', 'errors': 'replace'}
2023-10-20 16:48:46,724::DEBUG::[newsunpack:967] 7za output: 
7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 64-bit locale=C.UTF-8 Threads:16
 ...
```

let me try and see if i can get 23.01 installed and see if it magically fixes it...

**Comment by thezoggy** [comment]
ok updated my docker,
```
apk del 7zip
apk add 7zip --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main
```

before:
```
# 7zz

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 64-bit locale=C.UTF-8 Threads:16
```
after:
```
# 7zz

7-Zip (z) 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=C.UTF-8 Threads:16 OPEN_MAX:40960
```

now re-trying nzb on linux with 7zip 23.01 - same issue, logs: http://zoggy.net/linux-2714.txt

**Comment by sanderjo** [comment]
> windows its fine but linux its not.....

Yes, that's why I asked. 

- Linux uses utf-8
- Windows (AFAIK) uses cp1252 or so. SABnzbd tells when it starts up. Can you check in the beginning of sabnzbd.log, within the first 20 lines after startup.

So on Windows, the utf-8 surrogate error will not occur.

**Comment by sanderjo** [comment]
> sander/saf, sent you the nzb via email.

Thanks. I tried it on two different Linux systems, and ... no Traceback. Weird

**Comment by Kcchouette** [comment]
For the initial problem, I was using 7zip (the official one) 21.03

I switch to the port p7zip 17.05 and I haven't the problem of post-processing

**Comment by sanderjo** [comment]
So this is about the file blablalbla/PYthon37/Lib/test/zip_cp437_header.zip inside that download.
I've put it here: https://www.appelboor.com/dump/zip_cp437_header.zip

And it looks like it's zip-binary dependent what is seen inside.
* p7zip Version 16.02 only sees US-ASCII chars in the filenames, and throws away non-US-ASCII. And: no error.
* python's zipfile correctly see the non-US-ASCII chars
* @thezoggy 's GUI (rar? zip?) shows the non-US-ASCII chars
* ...

```
$ 7z l zip_cp437_header.zip 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (806C1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 270 bytes (1 KiB)

Listing archive: zip_cp437_header.zip

--
Path = zip_cp437_header.zip
Type = zip
Physical Size = 270

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2010-12-31 13:14:06 ....A            5            7  filename_with_o.txt
2010-12-31 13:14:06 ....A            5            7  filename_without.txt
------------------- ----- ------------ ------------  ------------------------
2010-12-31 13:14:06                 10           14  2 files

```

python's zipfile does see the strange chars:
```
>>> import zipfile
>>> zip = zipfile.ZipFile('zip_cp437_header.zip')
>>> zip.namelist()
['filename_with_æoå.txt', 'filename_without.txt']

```

**Comment by sanderjo** [comment]
FWIW:

I tried things like

`LC_ALL=C 7zz -scsWIN  -sccWIN   l zip_cp437_header.zip`

... but no better result.

**Comment by sanderjo** [comment]
Interesting: on Linux (on ChromeOS), python's zipfile does correctly unzip the zip, and apparantly does the conversion from code page 437 inside the zip to UTF-* on disk.

```
>>> import zipfile
>>> with zipfile.ZipFile('zip_cp437_header.zip', 'r') as zip_ref:
...     zip_ref.extractall()
```
with result:

filename_with_ æ o å .txt


```
-rw-r--r-- 1 sander sander   5 Oct 22 10:13 filename_with_oå.txt
-rw-r--r-- 1 sander sander   5 Oct 22 10:13 filename_without.txt
```

Good. Now let's see which byte values were used

```
$ ls filename_with_* | hd
00000000  66 69 6c 65 6e 61 6d 65  5f 77 69 74 68 5f c3 a6  |filename_with_..|
00000010  6f c3 a5 2e 74 78 74 0a                           |o...txt.|
00000018
```

So 
c3 a6 for æ
c3 a5 for å

Which are the valid & correct UTF-8 values. Hmm ... how is that possible? 

Let's look inside the zip_cp437_header.zip, which luckily is only 270 bytes, and then specifically the file filename_with_....txt

...

```
sander@penguin:~/spelen_zip$ hd zip_cp437_header.zip 
00000000  50 4b 03 04 14 00 02 00  08 00 c3 69 9f 3d 6e 0e  |PK.........i.=n.|
00000010  2a b4 07 00 00 00 05 00  00 00 15 00 00 00 66 69  |*.............fi|
00000020  6c 65 6e 61 6d 65 5f 77  69 74 68 5f 91 6f 86 2e  |lename_with_.o..|
00000030  74 78 74 73 f5 77 e3 e5  02 00 50 4b 03 04 14 00  |txts.w....PK....|
```

So, in the zipfile itself: value 91 resp 86. Which according to cp437 (code page 437, the original code page of the IBM PC.), are indeed 
86	Lower case a with ring above
91	Lower case ae

See https://www.ascii-codes.com/#:~:text=145,91 

So python's unzip is clever enought to know it's cp437 (is that said inside the zip-file, or is it a default), unzip, and then write the filenames as UTF-8. Nice

**Comment by thezoggy** [comment]
So to recap where we are at:

The problematic zip, `zip_cp437_header.zip` when extracted may produce  'invalid' files that sab will puke on, causing the traceback resulting in aborted post processing.

- 7zip 21.07 / 22.01 / 23.01 on linux results in 'invalid' files.
- BusyBox v1.36.1 unzip on linux results in 'invalid' files (see below).
- 7zip 23.01 on windows, results in 'safe' files.
- p7zip 17.05 on linux results in safe files (assumption per op)

This problematic  zip is not essential to the application and just collateral damage that bubbles up due to recursive unpacking.

With games/apps/etc sometimes they actually have archive files for their applications which are expected to be as is, not extracted. So recursive unpacking it is not desired, or even worse if we did and failed leaving partial files or cleaning up said files in the end results in broken output by the original packed expectations. Personally over the years I've either just had another application I used to handle those types of nzb or I only had sab download/repair but not unpack. So it didnt meddle with the contents and I could just simply extract myself.

While we could move recursive unpack from a global option to a per category option, I don't think this would be worth the effort and we might be able to mask issues by just making the logic a bit smarter/put guards on it.

Do we augment recursive unpack?
- only do x nested levels deep (2 iterations?)
- only nest unpack original extension (dont do rar->zip/tar/etc)

For the invalid files produced by 7zip:
- report bug to 7zip as handling is not consistent across platforms (which they note will be the case in their faq)..  anyone have a sourceforge account?

These invalid files could show up at some point from anywhere, so making utob more robust to handle it more gracefully is good.. but we might want to flag and warn user in the pp output in case user needs to review (as the output maybe fallout from outdated software / badly setup env / malform files / whatever)


Just to add this example as this alpine docker has busybox which has posix unzip included so tried that one out:
```
# unzip
BusyBox v1.36.1 (2023-10-09 08:04:29 UTC) multi-call binary.

# unzip zip_cp437_header.zip
Archive:  zip_cp437_header.zip
  inflating: filename_with_?o?.txt
  inflating: filename_without.txt

# ls -lh
-rw-r--r-- 1 root root    5 Oct 22 12:35 'filename_with_'$'\221''o'$'\206''.txt'
-rw-r--r-- 1 root root    5 Oct 22 12:35  filename_without.txt
-rwxrw-rw- 1 abc  abc   270 Sep 21 14:05  zip_cp437_header.zip
```

**Comment by sanderjo** [comment]
I think we have two seperate issues:
* how deep is your ... recursive unpacking. We could limit it to 2, or not go into deep directories. That zip_cp437_header.zip is deep inside a sub-sub-sub-directory and should not get unzipped at all; it's test file for the application itself
* the unzipping is an edge^3 issue: only on Linux, with strange chars inside a zip, and only with certain zip executables. At least: if we can prove it just works with p7zip. If so, SAB can check for that p7zip version and docker creators & users should install that. I hope can check within a docker

**Comment by thezoggy** [comment]
yes, i was trying to make that clear with my post that the handling of broken files is one thing. but then the fact we prob shouldnt have been extracting something so nested in the first place, which can augment the expected outcome of said releases as games/apps a lot of time actually have archives inside...

**Comment by Safihre** [comment]
I agree, currently we go 5 levels deep _on top_ of the regular Incomplete to Complete unpacking.. That's a lot.
So, limit it to the regular unpack + 2 levels?

And I will just fix this encoding bug with a `try/except` around the `DEF_FILE_MAX` check.

**Comment by thezoggy** [comment]
just to follow up, tried removing 7zip and installing p7zip
```
apk del 7zip
apk add --update --no-cache p7zip

# 7zz

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 64-bit locale=C.UTF-8 Threads:16
```
looks the same as just normal 7zip.. not sure how to identify its really the port though.

failed with p7zip for me:
![sab](http://zoggy.net/2023-10-23_12-58-32.png)

pulling latest sab code, and back to normal 7zz (22.01) that lsio sab comes with.
with being restricted to 2 levels, now things do pp just fine and show "Unpack nesting too deep" as final entry. (doesnt look like we log this though)

![2023-10-23_14-50-17](https://github.com/sabnzbd/sabnzbd/assets/500882/bb6d38cf-ff2a-4f3f-8410-5e37ff6f0cdc)

but i see the zips that it would have been too deep to unpack were just deleted due to cleanup..

and unrelated to the original issue, i see our 'sample' detection being a bit too greedy which of course also removing expected files that someone might expect to be part of an app/crack/etc.
```
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/distutils/tests/Setup.sample
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/distutils/tests/Setup.sample
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/gdb_sample.py
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/gdb_sample.py
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest.py
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest.py
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest_no_docstrings.py
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest_no_docstrings.py
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest_no_doctests.py
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/Lib/test/sample_doctest_no_doctests.py
2023-10-23 14:45:05,075::INFO::[postproc:1176] Removing unwanted sample file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/tcl/tix8.4.3/demos/samples/Sample.tcl
2023-10-23 14:45:05,075::DEBUG::[filesystem:916] [sabnzbd.postproc.remove_samples] Deleting file /downloads/complete/test/DVDFab.StreamFab.PORTABLE.MULTi.6.1.4.4.WiN.x64/App/StreamFab/PYthon37/tcl/tix8.4.3/demos/samples/Sample.tcl
```

**Comment by Kcchouette** [comment]
For me, `7zz` is not part of p7zip, but of 7zip

The p7zip is indicated like that, and is at the version 17.04
```
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04
```

> Tried within a Ubuntu docker, and neither with p7zip nor 7zip nor unzip, I can correctly unpack zip_cp437_header.zip: error resp strange chars resp strange chars. Even not OK with python's zip.

> So I wonder how @Kcchouette did that ... ?
Using p7zip:
```
$ 7z x 'zip_cp437_header.zip' 

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs x64)

Scanning the drive for archives:
1 file, 270 bytes (1 KiB)        

Extracting archive: zip_cp437_header.zip
--
Path = zip_cp437_header.zip
Type = zip
Physical Size = 270

Everything is Ok

Files: 2
Size:       10
Compressed: 270
```

I have two file (using ls):
`'filename_with_'$'\302\221''o'$'\302\206''.txt'`
`filename_without.txt`
