### ISSUE TITLE
issues with cherrypy.process.plugins.ThreadManager since upgrading to 4.2.0

### ISSUE THREAD

**Issue by dephcon** [sabnzbd/sabnzbd#2764]
### SABnzbd version

4.2.0

### Operating system

lsio container

### Using Docker image

None

### Description

upgraded just now from 4.1 to 4.2 using the lsio container on unraid and I see this in my logs:

```2024-01-03 18:50:25,459::ERROR::[_cplogging:213] [03/Jan/2024:18:50:25] ENGINE Error in 'start_thread' listener <function get_db_connection at 0x1551af652c00>
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/__init__.py", line 213, in get_db_connection
    cherrypy.thread_data.history_db = sabnzbd.database.HistoryDB()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/decorators.py", line 44, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/database.py", line 63, in __init__
    self.connect()
  File "/app/sabnzbd/sabnzbd/database.py", line 82, in connect
    version = self.cursor.fetchone()["user_version"]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

2024-01-03 18:50:25,460::ERROR::[_cplogging:213] [03/Jan/2024:18:50:25] ENGINE Error in 'acquire_thread' listener <bound method ThreadManager.acquire_thread of <cherrypy.process.plugins.ThreadManager object at 0x1551b11e37d0>>
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/process/plugins.py", line 741, in acquire_thread
    self.bus.publish('start_thread', i)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: TypeError("'NoneType' object is not subscriptable")

2024-01-03 18:50:25,477::ERROR::[_cplogging:213] [03/Jan/2024:18:50:25]  Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpwsgi.py", line 184, in trap
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpwsgi.py", line 104, in __call__
    return self.nextapp(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpwsgi.py", line 423, in tail
    return self.response_class(environ, start_response, self.cpapp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpwsgi.py", line 236, in __init__
    self.run()
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpwsgi.py", line 311, in run
    request, resp = self.cpapp.get_serving(local, remote, scheme, sproto)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cptree.py", line 148, in get_serving
    cherrypy.engine.publish('acquire_thread')
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: TypeError("'NoneType' object is not subscriptable")``` 
it loops that a few times, restarts the container then rinse/repeat.

**Comment by Safihre** [comment]
I think this is related to the missing `commit` in 4.2.0.
Will close for now.
