### ISSUE TITLE
Radarr cannot import on 4.2.0 but on 4.1.0 works

### ISSUE THREAD

**Issue by cdemi** [sabnzbd/sabnzbd#2769]
### SABnzbd version

4.2.0

### Operating system

Ubuntu

### Using Docker image

linuxserver

### Description

Basically when the Sab download finishes, Radarr throws the error "Download doesn't contain the intermediate path. Skipping". Since I have the "Delete from history setting" upon the error it deletes it from Sab immediately (I suspect #2767 is related to this).

The exact same NZB works when requested from Radarr to 4.1.0 but not to 4.2.0

There is also [a thread on Reddit](https://www.reddit.com/r/SABnzbd/comments/18uzq3z/radarr_not_pulling_files_from_sabnzbd/). 

This is the Radarr log if it helps:

```
[Fatal] RadarrErrorPipeline: Request Failed. GET /api/v3/manualimport

[v5.3.0.8410] System.ArgumentException: The string can't be left empty, null or consist of only whitespaces. (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Radarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 96
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId, Nullable`1 movieId, Boolean filterExistingFiles) in ./Radarr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 86
   at lambda_method306(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by thezoggy** [comment]
dupe of #2767 
just restart you sab container

**Comment by cdemi** [comment]
Yes, restarting the container fixes it. Thanks!

**Comment by bilinz** [comment]
Same issue and once I restarted as suggested it works again :)

**Comment by Safihre** [comment]
If anyone has Debug logging from it happening, please share!

**Comment by thezoggy** [comment]
> If anyone has Debug logging from it happening, please share!

heres one from discord earlier:
https://privatebin.net/?b32f836a271fab38#3WGTwNGFFipQbXLYnEqtqXPSEVzJnPXwbS9z2QBxbJRS
