### ISSUE TITLE
Scheduled RSS read fails since 4.2.0

### ISSUE THREAD

**Issue by schumi4** [sabnzbd/sabnzbd#2771]
### SABnzbd version

4.2.1

### Operating system

Debian

### Using Docker image

linuxserver

### Description

Scheduled RSS reading throws the following error:

```
Error during scheduler execution: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/utils/kronos.py", line 293, in __call__
    self.execute()
  File "/app/sabnzbd/sabnzbd/utils/kronos.py", line 304, in execute
    self.action(*self.args, **self.kw)
  File "/app/sabnzbd/sabnzbd/rss.py", line 461, in run
    self.run_feed(feed, download=True, ignoreFirst=True)
  File "/app/sabnzbd/sabnzbd/decorators.py", line 44, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/rss.py", line 398, in run_feed
    _HandleLink(
  File "/app/sabnzbd/sabnzbd/rss.py", line 632, in _HandleLink
    sabnzbd.urlgrabber.add_url(
  File "/app/sabnzbd/sabnzbd/urlgrabber.py", line 408, in add_url
    future_nzo = NzbObject(
                 ^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 738, in __init__
    self.handle_duplicate_action()
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 2006, in handle_duplicate_action
    self.purge_data()
  File "/app/sabnzbd/sabnzbd/decorators.py", line 44, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 1817, in purge_data
    remove_data(self.nzo_id, self.admin_path)
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 1179, in remove_data
    path = os.path.join(path, _id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```
Worked without errors on 4.1.0.

**Comment by Safihre** [comment]
Interesting. Disable Duplicate Detection for now and it will work again. Have to investigate.

**Comment by schumi4** [comment]
I downgraded to 4.1.0 for now as disabling duplicate detection downloads the same files after every read again and again.

**Comment by Safihre** [comment]
Found the problem. 
Thanks for reporting!
