### ISSUE TITLE
Error during scheduler execution

### ISSUE THREAD

**Issue by 4np** [sabnzbd/sabnzbd#2776]
### SABnzbd version

4.2.1

### Operating system

Synology DSM 7.2.1-69057 Update 1

### Using Docker image

linuxserver

### Description

I just pulled the 4.2.1 image from Linuxserver, and I am seeing a Python error for the scheduler:

```
Error during scheduler execution: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/utils/kronos.py", line 293, in __call__
    self.execute()
  File "/app/sabnzbd/sabnzbd/utils/kronos.py", line 304, in execute
    self.action(*self.args, **self.kw)
  File "/app/sabnzbd/sabnzbd/rss.py", line 461, in run
    self.run_feed(feed, download=True, ignoreFirst=True)
  File "/app/sabnzbd/sabnzbd/decorators.py", line 44, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/rss.py", line 398, in run_feed
    _HandleLink(
  File "/app/sabnzbd/sabnzbd/rss.py", line 632, in _HandleLink
    sabnzbd.urlgrabber.add_url(
  File "/app/sabnzbd/sabnzbd/urlgrabber.py", line 408, in add_url
    future_nzo = NzbObject(
                 ^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 738, in __init__
    self.handle_duplicate_action()
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 2006, in handle_duplicate_action
    self.purge_data()
  File "/app/sabnzbd/sabnzbd/decorators.py", line 44, in call_func
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 1817, in purge_data
    remove_data(self.nzo_id, self.admin_path)
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 1179, in remove_data
    path = os.path.join(path, _id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by Safihre** [comment]
Will push 4.2.2Beta1 with the fix. You should be able to get that pretty soon from Linuxserver.

**Comment by 4np** [comment]
Ah sorry, I just noticed I created a duplicate of #2771
