### ISSUE TITLE
Pre-Q script failing - missing show_analysis   fields

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2788]
### SABnzbd version

4.2.2rc2

### Operating system

windows

### Using Docker image

None

### Description

User on discord reporting issue with pre-q script 
> Trying to use Clean.py from https://trash-guides.info/Downloaders/SABnzbd/scripts/ but no luck. I used to have it working but now it's just not doing anything.

He noted he has python 3.12 installed. 

snippet from logs:
```
2024-01-28 01:11:14,034::DEBUG::[sorting:657] Initial guess for The.Fifth.Estate.S49E03.XviD-AFG[eztv.re].avi is MatchesDict({'title': 'The Fifth Estate', 'season': 49, 'episode': 3, 'video_codec': 'Xvid', 'release_group': 'AFG[eztv.re]', 'container': 'avi', 'mimetype': 'video/avi', 'type': 'episode'})
2024-01-28 01:11:14,035::INFO::[misc:1230] [sabnzbd\newsunpack.py.pre_queue] Running external command: ['python.exe', 'F:\\Clean.py', 'The.Fifth.Estate.S49E03.XviD-AFG[eztv.re].avi', '', 'tv', '', '', '1005840041', 'alt.binaries.wtfnzb.hotel alt.binaries.wtfnzb.juliet alt.binaries.wtfnzb.golf alt.binaries.wtfnzb.bravo alt.binaries.wtfnzb.india alt.binaries.wtfnzb.alpha alt.binaries.wtfnzb.charlie alt.binaries.wtfnzb.kilo alt.binaries.wtfnzb.delta']

...
2024-01-28 01:11:14,142::INFO::[newsunpack:2192] Pre-queue script returned 1 and output=
Traceback (most recent call last):
  File "F:\Clean.py", line 25, in <module>
    (scriptname, nzbname, postprocflags, category, script, prio, downloadsize, grouplist, showname, season, episodenumber, episodename, is_proper, resolution, decade, year, month, day, job_type) = sys.argv
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 19, got 8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Clean.py", line 29, in <module>
    (scriptname, nzbname, postprocflags, category, script, prio, downloadsize, grouplist, showname, season, episodenumber, episodename) = sys.argv
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 12, got 8)
```

can see that it only did up to grouplist, with it missing the arguments past. which look to be all the ones that come from the show_analysis ?
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L2168C9-L2168C22

asked user to enable debug, upgraded to 4.2.2rc2 (was 4.2.1) and re-tested, same issue. 

4.2.2rc2 logs: https://pastebin.com/dNRDRNLD

**Comment by thezoggy** [comment]
had dur moment, this trash script was wrongly updated for the post queue changes

**Comment by Safihre** [comment]
This is as expected. In 4.2.0 the input to prequeue was changed and this is mentioned in the Changelog.
The example script at the bottom of the wiki page shows the correct parsing.
The lines you refer to can be accessed as environment variables!

**Comment by thezoggy** [comment]
ok this is confusing, we change the arguments for pre-queue script in 4.x now multiple times it looks like.. with this latest 4.2 removing the previously added ones?

so now scripts that were working broke and the ones that got previously updated for the last update now are broken?

**Comment by Safihre** [comment]
Yes. Indeed. 
Since it's not a very commonly used feature I decided it was acceptable.
