### ISSUE TITLE
Web Interface Problem 400 Bad Request

### ISSUE THREAD

**Issue by numetaler** [sabnzbd/sabnzbd#2816]
### SABnzbd version

Linuxserver.io Docker 4.2.2[f30607]

### Operating system

Synology NAS DS918+

### Using Docker image

linuxserver

### Description

Hello,

I have a strange Problem Accessing the Webinterface. On My Windows 10 PC  (Version 22H2 (Build 19045.4046)) with Firefox 123.0 i geht this error:

> 400 Bad Request
> Illegal key 'ys-api/dvr/entry/grid_upcoming'
> 
> `Traceback` (most recent call last):
>   File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 734, in process_headers
>     self.cookie.load(value)
>   File "/usr/lib/python3.11/http/cookies.py", line 532, in load
>     self.__parse_string(rawdata)
>   File "/usr/lib/python3.11/http/cookies.py", line 596, in __parse_string
>     self.__set(key, rval, cval)
>   File "/usr/lib/python3.11/http/cookies.py", line 488, in __set
>     M.set(key, real_value, coded_value)
>   File "/usr/lib/python3.11/http/cookies.py", line 353, in set
>     raise CookieError('Illegal key %r' % (key,))
> http.cookies.CookieError: Illegal key 'ys-api/dvr/entry/grid_upcoming'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 666, in _do_respond
>     self.process_headers()
>   File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 736, in process_headers
>     raise cherrypy.HTTPError(400, str(exc))
> cherrypy._cperror.HTTPError: (400, "Illegal key 'ys-api/dvr/entry/grid_upcoming'")

When im using edge on the same machine the webinterface works fine. Haven't tested Chrome since its not installed.

I get the same Error when using Chromium on an arm64 Ubuntu 22.04  running  on an Orange Pi 5 Plus (RK3588),
whilst the Web interface works perfect on my Raspberry Pi 5 with Raspberry Pi Os (Debian Bookworm)  and either Chromium or Firefox. 

My first thoughts were that the problem is on the NAS, but then i discovered that i can access the Webinterface fine with my android Phone wich led me  trying the different PC's as described above.
Before using the Docker i also tried a Synology package wich gave me the same error.  Then i tried the latest Docker release.

Thank you for your great Work!

**Comment by numetaler** [comment]
Found the Bug.... Deleted the cookie and now it works fine

**Comment by numetaler** [comment]
Found the "bug"... Deleted the cookie and now it works fine
