### ISSUE TITLE
fatal error in downloader with giganews

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2822]
### SABnzbd version

4.2.3

### Operating system

docker

### Using Docker image

linuxserver

### Description

passing along user issue from discord, having issues with sab downloading with giganews still.  was on 4.2.3 but had him try latest dev and still same problem

4.2.3:
```
ERROR 17 minutes ago Fatal error in Downloader
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/downloader.py", line 693, in process_nw_worker
    self.process_nw(read_fds[nw_queue.get()])
  File "/app/sabnzbd/sabnzbd/downloader.py", line 734, in process_nw
    if nw.status_code not in (220, 222) and not done:
       ^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/newswrapper.py", line 98, in status_code
    return int(self.data[:3])
           ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: b'Mes'
WARNING 17 minutes ago 43@news.giganews.com: Received unknown status code 221 for article MbSnHdAzDjKuKfYxLmCuCiSd-1710192926464@nyuu
```

4.3.0-dev
```
ERROR a minute ago Fatal error in Downloader
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/downloader.py", line 693, in process_nw_worker
    self.process_nw(read_fds[nw_queue.get()])
  File "/app/sabnzbd/sabnzbd/downloader.py", line 732, in process_nw
    if nw.status_code != 222 and not done:
       ^^^^^^^^^^^^^^
  File "/app/sabnzbd/sabnzbd/newswrapper.py", line 98, in status_code
    return int(self.data[:3])
           ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: b'Org'
```

**Comment by thezoggy** [comment]
guessing its related to https://github.com/sabnzbd/sabnzbd/issues/2821  ?

**Comment by Safihre** [comment]
No, I seem to have forgotten to cherry pick  a commit from 4.2 branch  😱

**Comment by sanderjo** [comment]
> Apart from the fatal error in the downloader, that _unknown status code 221 for article MbSnHdAzDjKuKfYxLmCuCiSd-1710192926464@nyuu_ might also require attention. Giganews at it again?

The RFC https://www.rfc-editor.org/rfc/rfc3977.txt does mention 221, in response to a HEAD command:

```
   Response code 221 (multi-line)
      Generated by: HEAD
      2 arguments: n message-id
      Meaning: article headers follow.
```

So is this a response to a HEAD command from SAB? From https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newswrapper.py#L168-L172 ?

**Comment by Safihre** [comment]
@thezoggy Can you ask the user to test the latest `develop`?

**Comment by thezoggy** [comment]
Will do..
