### ISSUE TITLE
sqlite3.OperationalError: no such column: archive

### ISSUE THREAD

**Issue by cloudbr34k84** [sabnzbd/sabnzbd#2847]
### SABnzbd version

4.3.0 [b07b434]

### Operating system

NAS

### Using Docker image

linuxserver

### Description

Hi there, i started getting SQL error. Im unsure how this has changed. Not the biggest techy. If someone can point me in the right direction how to troubleshoot this, would be great

```
sqlite3.OperationalError: no such column: archive
2024-05-02 14:59:57,820::ERROR::[database:146] SQL Command Failed, see log
2024-05-02 14:59:57,821::INFO::[database:147] SQL: SELECT COUNT(*) FROM history WHERE name LIKE ? AND archive IS NULL
2024-05-02 14:59:57,821::INFO::[database:148] Arguments: ['%%']
2024-05-02 14:59:57,821::INFO::[database:149] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/database.py", line 120, in execute
    self.cursor.execute(command, args)
sqlite3.OperationalError: no such column: archive
2024-05-02 14:59:57,822::ERROR::[database:146] SQL Command Failed, see log
2024-05-02 14:59:57,822::INFO::[database:147] SQL: SELECT * FROM history WHERE name LIKE ? AND archive IS NULL ORDER BY completed desc LIMIT ?, ?
2024-05-02 14:59:57,823::INFO::[database:148] Arguments: ['%%', 0, 1000000]
2024-05-02 14:59:57,823::INFO::[database:149] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/database.py", line 120, in execute
    self.cursor.execute(command, args)
sqlite3.OperationalError: no such column: archive
```
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/15183967/sabnzbd.log)

```
version: "3.9"
networks:
  traefik:
    external: true
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - 8089:8080
    volumes:
      - /volume1/docker/sabnzbd/config:/config:z
      - /volume1/media/usenet/complete:/complete:z
      - /volume1/media/usenet/incomplete:/incomplete:z
    labels:      
      - "traefik.http.services.${SVCName}.loadbalancer.server.port=8080"
      # - "traefik.http.routers.${SVCName}.middlewares=auth@file"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Docker Containers"
    extends:
      file: ../common-services-app.yml
      service: app
    networks:
      - default
  ```

**Comment by cloudbr34k84** [comment]
sorted!

**Comment by sanderjo** [comment]
your sqlite database (in ~/.sabnzbd/admin/history1.db) is broken.

Solution:

1. stop SABnzbd 
2. remove `~/.sabnzbd/admin/history1.db`. As you use docker ... it's certainly inside your docker, but probably also on your host's filesystem, in the shared directory
3. start SABnzbd

Specific:

`sqlite3.OperationalError: no such column: archive
`
That's the problem. "archive" is a column name in history1.db ... and apparantly that's missing.

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/1d00c308-45ef-4de1-9a41-f11246a47bc8)
