### ISSUE TITLE
windows notifications fail - missing module

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2849]
### SABnzbd version

4.3.0

### Operating system

Windows 10

### Using Docker image

None

### Description

user reported issue on irc, could replicate myself with 4.3.0 windows install:
```
2024-05-02 17:44:33,920::DEBUG::[notifier:527] Sending Windows notification
2024-05-02 17:44:33,923::INFO::[notifier:542] Failed to send Windows notification
2024-05-02 17:44:33,923::DEBUG::[notifier:543] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\notifier.py", line 538, in send_windows
  File "windows_toasts\toasters.py", line 135, in show_toast
  File "windows_toasts\toasters.py", line 40, in _build_adaptable_data
ModuleNotFoundError: No module named 'winrt.windows.foundation.collections'
```

**Comment by thezoggy** [comment]
installed 4.3.1 windows binary, confirmed windows native toast notifications work now  on win10
