### ISSUE TITLE
apprise notifications not working

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2851]
### SABnzbd version

4.3.0

### Operating system

Windows 10

### Using Docker image

None

### Description

saw reddit report of apprise not working ( https://www.reddit.com/r/SABnzbd/comments/1cij6ul/apprise_notifications_in_43/ ) , trying myself on my windows box i can confirm as well it does not work due to missing items..

added default `mailto://user:pw@fastmail.com` and tried doing test... 
```
2024-05-02 22:32:09,088::INFO::[api:853] Sending Apprise notification
2024-05-02 22:32:09,088::DEBUG::[notifier:292] Sending Apprise notification
2024-05-02 22:32:09,089::DEBUG::[AppriseLocale:126] Could not load translation path: C:\Program Files\SABnzbd\apprise\i18n\en
2024-05-02 22:32:09,092::INFO::[notifier:157] Sending notification: Error - [02/May/2024:22:32:09] HTTP  (type=error, job_cat=None)
2024-05-02 22:32:09,091::ERROR::[_cplogging:213] [02/May/2024:22:32:09] HTTP 
Traceback (most recent call last):
  File "cherrypy\_cprequest.py", line 638, in respond
  File "cherrypy\_cprequest.py", line 697, in _do_respond
  File "cherrypy\lib\encoding.py", line 223, in __call__
  File "cherrypy\_cpdispatch.py", line 54, in __call__
  File "sabnzbd\interface.py", line 190, in internal_wrap
  File "sabnzbd\interface.py", line 469, in api
  File "sabnzbd\api.py", line 115, in api_handler
  File "sabnzbd\api.py", line 854, in _api_test_apprise
  File "sabnzbd\notifier.py", line 354, in send_apprise
  File "apprise\Apprise.py", line 288, in add
  File "apprise\Apprise.py", line 132, in instantiate
  File "apprise\plugins\__init__.py", line 450, in url_to_dict
  File "apprise\manager.py", line 627, in __contains__
  File "apprise\manager.py", line 184, in load_modules
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\SABnzbd\\apprise\\plugins'
```

**Comment by Safihre** [comment]
https://github.com/orgs/pyinstaller/discussions/8446

**Comment by thezoggy** [comment]
installed 4.3.1 windows binary, confirmed apprise notifications work now
