### ISSUE TITLE
clicking search icon results in traceback "ValueError: invalid literal for int() with base 10: 'False'" with current github version 4.3.2 [8aa53fd] 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2887]
### SABnzbd version

8aa53fd

### Operating system

Ubuntu Linux

### Using Docker image

None

### Description

github version 4.3.2 [[8aa53fd](https://github.com/sabnzbd/sabnzbd/commit/8aa53fd)] : In http://127.0.0.1:8080/sabnzbd/config/, as soon as I click on the looking glass, I get the error below, both on console and GUI

No problem with regular sabnzbdplus-4.3.2 from PPA

Fresh git clone in another dir => same traceback
```
2024-06-18 18:01:27,103::INFO::[notifier:157] Sending notification: Error - [18/Jun/2024:18:01:27] HTTP  (type=error, job_cat=None)
2024-06-18 18:01:27,102::ERROR::[_cplogging:213] [18/Jun/2024:18:01:27] HTTP 
Traceback (most recent call last):
  File "/home/sander/.local/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/sander/.local/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/sander/.local/lib/python3.10/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/sander/.local/lib/python3.10/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/sander/git/sabnzbd/sabnzbd/interface.py", line 190, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/home/sander/git/sabnzbd/sabnzbd/interface.py", line 2162, in index
    return template_filtered_response(
  File "/home/sander/git/sabnzbd/sabnzbd/interface.py", line 381, in template_filtered_response
    return Template(file=file, searchList=[search_list_copy], compilerSettings=CHEETAH_DIRECTIVES).respond()
  File "_home_sander_git_sabnzbd_interfaces_Config_templates_config_notify_tmpl.py", line 350, in respond
ValueError: invalid literal for int() with base 10: 'False'
2024-06-18 18:01:27,106::INFO::[_cplogging:213] [18/Jun/2024:18:01:27] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: 127.0.0.1:8080
  CONNECTION: keep-alive
  SEC-CH-UA: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
  ACCEPT: */*
  X-REQUESTED-WITH: XMLHttpRequest
  SEC-CH-UA-MOBILE: ?0
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
  SEC-CH-UA-PLATFORM: "Linux"
  SEC-FETCH-SITE: same-origin
  SEC-FETCH-MODE: cors
  SEC-FETCH-DEST: empty
  REFERER: http://127.0.0.1:8080/sabnzbd/config/
  ACCEPT-ENCODING: gzip, deflate, br, zstd
  ACCEPT-LANGUAGE: nl-NL,nl;q=0.9,en-US;q=0.8,en-NL;q=0.7,en;q=0.6

```

**Comment by sanderjo** [comment]
To rulet out, I tried downgrading to 18.9.0, but still the same traceback.

```
$ python3 -m pip install cherrypy==18.9.0
Defaulting to user installation because normal site-packages is not writeable
Collecting cherrypy==18.9.0
  Using cached CherryPy-18.9.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: cheroot>=8.2.1 in /home/sander/.local/lib/python3.10/site-packages (from cherrypy==18.9.0) (10.0.1)
Requirement already satisfied: portend>=2.1.1 in /home/sander/.local/lib/python3.10/site-packages (from cherrypy==18.9.0) (3.2.0)
Requirement already satisfied: more-itertools in /home/sander/.local/lib/python3.10/site-packages (from cherrypy==18.9.0) (10.3.0)
Requirement already satisfied: zc.lockfile in /home/sander/.local/lib/python3.10/site-packages (from cherrypy==18.9.0) (3.0.post1)
Requirement already satisfied: jaraco.collections in /home/sander/.local/lib/python3.10/site-packages (from cherrypy==18.9.0) (5.0.0)
Requirement already satisfied: jaraco.functools in /home/sander/.local/lib/python3.10/site-packages (from cheroot>=8.2.1->cherrypy==18.9.0) (4.0.1)
Requirement already satisfied: tempora>=1.8 in /home/sander/.local/lib/python3.10/site-packages (from portend>=2.1.1->cherrypy==18.9.0) (5.5.1)
Requirement already satisfied: jaraco.text in /home/sander/.local/lib/python3.10/site-packages (from jaraco.collections->cherrypy==18.9.0) (3.8.1)
Requirement already satisfied: setuptools in /home/sander/.local/lib/python3.10/site-packages (from zc.lockfile->cherrypy==18.9.0) (70.0.0)
Requirement already satisfied: pytz in /home/sander/.local/lib/python3.10/site-packages (from tempora>=1.8->portend>=2.1.1->cherrypy==18.9.0) (2024.1)
Requirement already satisfied: jaraco.context>=4.1 in /home/sander/.local/lib/python3.10/site-packages (from jaraco.text->jaraco.collections->cherrypy==18.9.0) (4.3.0)
Using cached CherryPy-18.9.0-py3-none-any.whl (348 kB)
DEPRECATION: devscripts 2.22.1ubuntu1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of devscripts or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: cherrypy
  Attempting uninstall: cherrypy
    Found existing installation: CherryPy 18.10.0
    Uninstalling CherryPy-18.10.0:
      Successfully uninstalled CherryPy-18.10.0
Successfully installed cherrypy-18.9.0

```

**Comment by sanderjo** [comment]
And removing that specific commit with 
```
git rebase --onto b8fd9e6e31aa98351fcdafc3293ce164c871b124^ b8fd9e6e31aa98351fcdafc3293ce164c871b124
```
... and no Traceback. Proof

**Comment by sanderjo** [comment]
magnifying glass better wording? Lost in translation?

Google does understand looking glass: https://www.google.com/search?q=looking+glass+icon

Anyway: I mean this icon:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/cbf8dd6f-ccea-4124-96dd-12b9b0231b83)

**Comment by thezoggy** [comment]
aye, yeah magnifying glass works. or just 'search icon'.
So clicking that icon shows search prompt, but I can see the xhr config/notify request which throws 500 with the error.  

But anyways for saf to replicate, just click on 'notifications' in the config and you will see the issue

**Comment by sanderjo** [comment]
> just click on 'notifications' in the config and you will see the issue

Brrrrrrr. That's worse: the whole SAB GUI crashes. Luckily clicking Back takes you back to the SAB GUI

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/f781992e-58f1-44f4-8c73-61a8d762c57a)

**Comment by mnightingale** [comment]
https://github.com/sabnzbd/sabnzbd/blob/8aa53fd43ff4fcf68a6bf6198edb3609c28f8edd/interfaces/Config/templates/config_notify.tmpl#L61

Is the first one, another a few lines down.

Should be `<!--#if $email_full then ...`

Thats's not all the instances of the same problem though, might be worth checking any other pages also.

**Comment by Safihre** [comment]
Will fix.
