### ISSUE TITLE
No Connections/Downloads

### ISSUE THREAD

**Issue by BearTi** [sabnzbd/sabnzbd#289]
Hi,

I installed sabnzbdplus on my Raspberry 2 yesterbday, but have some problems:

I installed it via apt-get.
I configured my usenet-server -> "server-check" tells me that everhing is alright and a connection was established.

But when I load a NZB file the download doesn´t start and under "status" -> "connection=0" is displayed. 
With my other usenetclient on windows it works perfectly.

Uninstalled and installed it again it a few time, but no idea...

Any idea?
Thanks

**Comment by thezoggy** [comment]
the usenet server check is just seeing if it can talk to your usp. trying to load a nzb theres many other things involved.. does sab have the rights to write to the admin folder? does it have space for the item? etc.. go look at the status page and view debug logs for more info.

**Comment by BearTi** [comment]
Thanks for the tips... I´ve set every folder with the right permission (I created an extra user for sabnzbd...).

The error logs doesn´t contain anything but the sabnzbd.log conatains the following:

2015-08-23 18:47:02,762::INFO::[sabnzbdplus:1390] Starting web-interface on 0.0.0.0:4444
2015-08-23 18:47:03,784::INFO::[_cplogging:55] [23/Aug/2015:18:47:03] ENGINE Bus STARTING
2015-08-23 18:47:03,795::INFO::[_cplogging:55] [23/Aug/2015:18:47:03] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-08-23 18:47:59,606::ERROR::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0xc34f10>>
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 4444 not bound on '0.0.0.0'

2015-08-23 18:47:59,608::ERROR::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 184, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 4444 not bound on '0.0.0.0'

2015-08-23 18:47:59,609::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Bus STOPPING
2015-08-23 18:47:59,611::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 4444)) already shut down
2015-08-23 18:47:59,626::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Stopped thread '_TimeoutMonitor'.
2015-08-23 18:47:59,627::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Bus STOPPED
2015-08-23 18:47:59,628::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Bus EXITING
2015-08-23 18:47:59,629::INFO::[_cplogging:55] [23/Aug/2015:18:47:59] ENGINE Bus EXITED
2015-08-23 18:47:59,630::ERROR::[sabnzbdplus:1405] Failed to start web-interface:
Traceback (most recent call last):
  File "/usr/bin/sabnzbdplus", line 1397, in main
    cherrypy.engine.start()
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 184, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 90, in start
    ServerAdapter.start(self)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 62, in start
    self.wait()
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 103, in wait
    wait_for_occupied_port(host, port)
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 275, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 4444 not bound on '0.0.0.0'
2015-08-23 18:47:59,636::ERROR::[sabnzbdplus:302] Fehler beim Starten der Weboberfl▒che. : Port 4444 not bound on '0.0.0.0'
2015-08-23 18:47:59,637::INFO::[__init__:325] SABnzbd shutting down...
2015-08-23 18:47:59,638::INFO::[__init__:846] Saving data for bookmarks.sab in /home/mlrtimpi/sabnzbd/admin/bookmarks.sab
2015-08-23 18:47:59,640::INFO::[urlgrabber:70] URLGrabber shutting down
2015-08-23 18:47:59,642::INFO::[__init__:846] Saving data for watched_data.sab in /home/mlrtimpi/sabnzbd/admin/watched_data.sab
2015-08-23 18:47:59,644::INFO::[dirscanner:254] Dirscanner shutting down
2015-08-23 18:47:59,645::INFO::[postproc:83] Saving postproc queue
2015-08-23 18:47:59,646::INFO::[__init__:846] Saving data for postproc1.sab in /home/mlrtimpi/sabnzbd/admin/postproc1.sab
2015-08-23 18:47:59,648::INFO::[nzbqueue:170] Saving queue
2015-08-23 18:47:59,649::INFO::[__init__:846] Saving data for queue9.sab in /home/mlrtimpi/sabnzbd/admin/queue9.sab
2015-08-23 18:47:59,651::INFO::[__init__:846] Saving data for rss_data.sab in /home/mlrtimpi/sabnzbd/admin/rss_data.sab
2015-08-23 18:47:59,653::INFO::[__init__:846] Saving data for bookmarks.sab in /home/mlrtimpi/sabnzbd/admin/bookmarks.sab
2015-08-23 18:47:59,655::INFO::[__init__:846] Saving data for watched_data.sab in /home/mlrtimpi/sabnzbd/admin/watched_data.sab
2015-08-23 18:47:59,657::INFO::[postproc:83] Saving postproc queue
2015-08-23 18:47:59,658::INFO::[__init__:846] Saving data for postproc1.sab in /home/mlrtimpi/sabnzbd/admin/postproc1.sab
2015-08-23 18:47:59,660::INFO::[__init__:385] All processes stopped

Any idea?
The error "Failed to start web-interface:" is weird, because I can access the webinterface...

**Comment by shypike** [comment]
SABnzbd may have trouble figuring out what your local IP address is. Try the real local IP instead of 0.0.0.0

**Comment by BearTi** [comment]
I set the "real IP" in "/etc/default/sabnzbdplus".

Bit I got the same error "IOError: Port 4444 not bound on '192.168.1.50'"

But, as wrote above, I can access the webinterface...

Ah... I am running sabnzbd on a raspberry pi 2 b

**Comment by shypike** [comment]
Please check out our forum http://forums.sabnzbd.org
There is quite some info about running SABnzbd on Rasberry PI.

**Comment by BearTi** [comment]
Thanks! Now I am on version 0.7.20, but with the same problem :-( My downloads are not starting,,,
