### ISSUE TITLE
Windows on ARM / Snapdragon: unrar and par2 not found ... because of uname machine CPU arch detection

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2892]
### SABnzbd version

4.3.2, Windows x86_64 exe version

### Operating system

Windows on ARM / Snapdragon Elite X

### Using Docker image

None

### Description

See https://forums.sabnzbd.org/viewtopic.php?p=132134#p132134

Cause of the problem is https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L119 and https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/__init__.py#L40

Workaround: use the 32-bit (or if possible: 64-bit) x86 exe, just like we do a loose check for 7za.

Real solution: find out what Windows on ARM / Snapdragon Elite X reports for `platform.uname().machine` (pity: not specified in https://docs.python.org/3/library/platform.html#platform.machine )

EDIT: it's in the logging provide by the user
```
2024-06-24 05:39:35,746::INFO::[SABnzbd:1161] CPU architecture = ARM64
2024-06-24 05:39:35,764::INFO::[SABnzbd:1164] Platform = nt - Windows-11-10.0.26100-SP0
```
from
`logging.info("CPU architecture = %s", platform.uname().machine)`

/EDIT

 and handle it a bit more clever. And/or start using unrar for Windows on ARM (as soon as it's there; not yet on https://www.rarlab.com/download.htm).

```
2024-06-24 05:39:35,746::INFO::[SABnzbd:1159] Python-version = 3.12.3 (tags/v3.12.3:f6650f9, Apr 9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

2024-06-24 05:35:44,890::INFO::[notifier:157] Sending notification: Fout - par2-programma niet gevonden. (type=error, job_cat=None)
2024-06-24 05:35:44,890::ERROR::[SABnzbd:453] par2-programma niet gevonden.
2024-06-24 05:35:44,891::INFO::[notifier:157] Sending notification: Fout - unrar-programma niet gevonden. (type=error, job_cat=None)
2024-06-24 05:35:44,891::ERROR::[SABnzbd:468] unrar-programma niet gevonden.

2024-06-24 05:35:44,891::INFO::[SABnzbd:473] 7za binary... found (C:\Program Files\SABnzbd\win\7zip\7za.exe)
```

Where "niet gevonden" is a certain language for "NOT found"

```
po/main/nl.po-62-msgid "unrar binary... NOT found"
po/main/nl.po:63:msgstr "unrar-programma niet gevonden."
```

From https://www.qualcomm.com/developer/blog/2022/04/porting-your-apps-windows-snapdragon

"with the new Windows 11 application binary interface (API) target called ARM64EC (where EC stands for emulation compatible), it can now run both emulated and native **64-bit code** in the same process with near-native performance"

... so not 32-bit applications, to which SABnzbd falls back for rar and par2 if sabnzbd.WIN64 is False?

Although ... the 32-bit 7za.exe does work? Or at least: is detected.  Weird.

Hopefully the user reporting the problem can do provide the requested feedback.

**Comment by sanderjo** [comment]
@thezoggy  do you still have that Windows-on-ARM laptop? Does current sanzbd work?

SABnzbd x86 did work for me on Windows on ARM (https://github.com/sabnzbd/sabctools/issues/63#issuecomment-1768544814) ... so what is different. Maybe different python platform.uname() behaviour?

**Comment by thezoggy** [comment]
we don't include winarm utilities (par/unrar) so you'd just have to replace existing with them (as we don't have logic to detect to use a different file, I've called this out back during the multipar->par2-turbo change)

Then also arm python won't build certain libs due to lack of support..so you'd have to use x86/x64 python. 

which makes the utility detection part wonky since it won't say winarm, but the python arch.

**Comment by mnightingale** [comment]
Windows ARM VM on MacBook M2 using `platform.uname().machine` reports `ARM64`.
It reports ARM64 regardless of using AMD64 or ARM64 CPython releases.

Maybe it doesn't make sense to bundle the ARM binaries until SAB can be ran on Windows with it?
Do you know what needs upgrading/replacing?

**Comment by sanderjo** [comment]
> we don't include winarm utilities (par/unrar) so you'd just have to replace existing with them (as we don't have logic to detect to use a different file, I've called this out back during the multipar->par2-turbo change)
> 
> Then also arm python won't build certain libs due to lack of support..so you'd have to use x86/x64 python.
> 
> which makes the utility detection part wonky since it won't say winarm, but the python arch.

I think you're thinking a few steps ahead: native Win-ARM. I would say that is not the case here and now: the user on Win-ARM is using the SABnzbd.exe so the x86_64 exe, so with included python x86_64 and the included x86 executables for unrar, par2, 7za, sabctools.
That should work on Win-ARM thanks to the x86_emulation. There is "just" something going wrong with uname machine detection logic in SABnzbd.

So back to my question: do you still have access to the Windows-on-ARM machine you menitoned last year? That could help with this case. If not, I'll have to ask the user to do further testing.

**Comment by sanderjo** [comment]
> Windows ARM VM on MacBook M2 using `platform.uname().machine` reports `ARM64`.
> It reports ARM64 regardless of using AMD64 or ARM64 CPython releases.

Yes, because it's native. And because we provided a native ARM64 SABnzbd for Apple Silicon. No emulation in place.

**Comment by mnightingale** [comment]
> Yes, because it's native. And because we provided a native ARM64 SABnzbd for Apple Silicon. No emulation in place.

I understand, I'm just saying it finds the underlying OS architecture regardless which Python it is using.

> 2024-06-24 05:35:44,837::INFO::[SABnzbd:1159] Python-version = 3.12.3 (tags/v3.12.3:f6650f9, Apr 9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
2024-06-24 05:35:44,837::INFO::[SABnzbd:1160] Dockerized = False
2024-06-24 05:35:44,837::INFO::[SABnzbd:1161] CPU architecture = ARM64

Hence from that user log, they are using x64 Python but it detects `platform.uname().machine` as ARM64.

So as a workaround maybe add a WINARM64 and for now tell it to use the x64 binaries until/unless native builds are possible.

SABnzbd-4.3.2-win-setup.exe has only installed win\unrar\x64\unrar.exe etc. which is why the current failover to use the x86 versions doesn't work.

**Comment by thezoggy** [comment]
some notes from before, 
```
installed python 3.11.7 for winarm

PS C:\Users\zoggy> pyenv install 3.11.7-arm
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.11.7-arm ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.11.7/python-3.11.7-arm64.exe
:: [Downloading] ::  To   C:\Users\zoggy\.pyenv\pyenv-win\install_cache\python-3.11.7-arm64.exe
:: [Installing] ::  3.11.7-arm ...
:: [Info] :: completed! 3.11.7-arm

set as python version to use (only one)

PS C:\Users\zoggy> pyenv global 3.11.7-arm
PS C:\Users\zoggy> python3 -V
Python 3.11.7

to note
PS C:\dummy\sabnzbd> python -c "import platform;print(platform.uname())"
uname_result(system='Windows', node='win11-arm', release='10', version='10.0.22631', machine='ARM64')

PS C:\dummy\sabnzbd> which pip3
/c/Users/zoggy/.pyenv/pyenv-win/shims/pip3

upgrade pip/wheel

PS C:\dummy\sabnzbd> python3 -m pip install --upgrade pip wheel
Requirement already satisfied: pip in c:\users\zoggy\.pyenv\pyenv-win\versions\3.11.7-arm\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
  Downloading pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl.metadata
  Downloading wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.4 MB/s eta 0:00:00
Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 3.4 MB/s eta 0:00:00
Installing collected packages: wheel, pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.2 wheel-0.42.0

unable to install ciffi

PS C:\dummy\sabnzbd> pip3 install --upgrade -r requirements.txt
Ignoring pyobjc-core: markers 'sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-Cocoa: markers 'sys_platform == "darwin"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32" and sys_platform != "darwin"' don't match your environment
Collecting sabctools==8.1.0 (from -r requirements.txt (line 3))
  Downloading sabctools-8.1.0.tar.gz (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.7/234.7 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cheetah3==3.2.6.post1 (from -r requirements.txt (line 4))
  Using cached Cheetah3-3.2.6.post1-py3-none-any.whl
Collecting cffi==1.16.0 (from -r requirements.txt (line 5))
  Downloading cffi-1.16.0.tar.gz (512 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.9/512.9 kB 10.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.11.7-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.11.7-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.11.7-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\msvc.py", line 233, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-c5zoni8d\overlay\Lib\site-packages\setuptools\msvc.py", line 190, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

can see its not happy, missing build tools...

> To set up native Arm support for Python, you need native Arm C build tools. 
> As explained in Arm documentation, you can install them using a standalone installer or through Visual Studio 2022 Community for desktop development with C++.
> This ensures that native Arm C build tools are present. Alternatively, you can use a standalone installer for the build tools.

https://visualstudio.microsoft.com/visual-cpp-build-tools/
-- https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.x_with_Visual_Studio_2022_.28x86.2C_x64.2C_ARM.2C_ARM64.29

Run installer.. select 'desktop development with c++' which wants to take up 7G!  language pack is 3.5G alone (have to install). cant do since limited hdd space on this box
```

**Comment by thezoggy** [comment]
just to see if anything has changed since i last meddled with it all. installing 3.12.4-arm

```
PS C:\dummy\sabnzbd> git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean


PS C:\dummy> pyenv uninstall  -a
pyenv: Confirm uninstall all? (Y/N): Y
pyenv: Successfully uninstalled 3.11.7-arm

PS C:\dummy> pyenv install 3.12.4-arm
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.12.4-arm ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.12.4/python-3.12.4-arm64.exe
:: [Downloading] ::  To   C:\Users\zoggy\.pyenv\pyenv-win\install_cache\python-3.12.4-arm64.exe
:: [Installing] ::  3.12.4-arm ...
:: [Info] :: completed! 3.12.4-arm

PS C:\dummy> pyenv global 3.12.4-arm
```
installing req for sab

```
PS C:\dummy\sabnzbd> python -m pip install --upgrade pip wheel
Requirement already satisfied: pip in c:\users\zoggy\.pyenv\pyenv-win\versions\3.12.4-arm\lib\site-packages (24.0)
Collecting pip
  Downloading pip-24.1-py3-none-any.whl.metadata (3.6 kB)
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Downloading pip-24.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.1 MB/s eta 0:00:00
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 1.7 MB/s eta 0:00:00
Installing collected packages: wheel, pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-24.1 wheel-0.43.0

PS C:\dummy\sabnzbd> pip3 install --upgrade -r .\requirements.txt
Ignoring pyobjc-core: markers 'sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-Cocoa: markers 'sys_platform == "darwin"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32" and sys_platform != "darwin"' don't match your environment
Collecting apprise==1.8.0 (from -r .\requirements.txt (line 3))
  Downloading apprise-1.8.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.1 MB/s eta 0:00:00
Collecting sabctools==8.2.3 (from -r .\requirements.txt (line 4))
  Downloading sabctools-8.2.3.tar.gz (256 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.7/256.7 kB 15.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting CT3==3.3.3.post1 (from -r .\requirements.txt (line 5))
  Downloading CT3-3.3.3.post1.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 19.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi==1.16.0 (from -r .\requirements.txt (line 6))
  Using cached cffi-1.16.0.tar.gz (512 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zoggy\AppData\Local\Temp\pip-build-env-csqqegf1\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

so no change. of course if i install amd64 python i can make stuff works. but its detected as amd64 as thats what python is running. so same as before
```

**Comment by Safihre** [comment]
Yeah I could release winarm64 wheels for sabctools because we use cibuildwheels, but all the other depencies don't have it..

**Comment by mnightingale** [comment]
@thezoggy it might be better to take this discussion elsewhere; I think for this issue it should be quite a small small fix to get SAB to use the included x64 binaries if it detects ARM64 since it sounds like even if it was using an ARM build of Python it would have to use some x64 binaries anyway.

Nethertheless I did get a bit closer once build tools are installed https://gist.github.com/mnightingale/64c62e65d79613636b240a3488b95646

**Comment by thezoggy** [comment]
> @thezoggy it might be better to take this discussion elsewhere; I think for this issue it should be quite a small fix to get SAB to use the included x64 binaries if it detects ARM64 since it sounds like even if it was using an ARM build of Python it would have to use some x64 binaries anyway.
> 
> Nethertheless I did get a bit closer once build tools are installed https://gist.github.com/mnightingale/64c62e65d79613636b240a3488b95646 edit: commit upgrading winrt is broken, reverting to 2.0.1 gets it further.

The arm64 detection only works if the user is running arm64 python. which if they are..they cant install all the requirements. They have to use amd64 python, which then detection would view it as a amd64. Which is why i was saying that the fix for those that really want to run sab on winarm is just to go grab the winarm binaries and drop it into sab to replace the ones we provide if they want optimized ones. Which is easy for par2cmdline-turbo but less so for unrar as its not built natively. For all this is why back when we added par2cmdline-turbo for windows it was decided to not include the winarm version since it just didnt make sense when not everything else would benefit.

**Comment by sanderjo** [comment]
> They have to use amd64 python, which then detection would view it as a amd64.

Does your statement match with the user's logging ?

```
2024-06-24 05:35:44,837::INFO::[SABnzbd:1159] Python-version = 3.12.3 (tags/v3.12.3:f6650f9, Apr 9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
2024-06-24 05:35:44,837::INFO::[SABnzbd:1160] Dockerized = False
2024-06-24 05:35:44,837::INFO::[SABnzbd:1161] CPU architecture = ARM64
```

**Comment by thezoggy** [comment]
> > They have to use amd64 python, which then detection would view it as a amd64.
> 
> Does your statement match with the user's logging ?
> 
> ```
> 2024-06-24 05:35:44,837::INFO::[SABnzbd:1159] Python-version = 3.12.3 (tags/v3.12.3:f6650f9, Apr 9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
> 2024-06-24 05:35:44,837::INFO::[SABnzbd:1160] Dockerized = False
> 2024-06-24 05:35:44,837::INFO::[SABnzbd:1161] CPU architecture = ARM64
> ```

when i last tested it did, but tossing 4.3.2 on that laptop i see

```
2024-06-24 16:43:53,632::INFO::[SABnzbd:1159] Python-version = 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
2024-06-24 16:43:53,632::INFO::[SABnzbd:1160] Dockerized = False
2024-06-24 16:43:53,648::INFO::[SABnzbd:1161] CPU architecture = ARM64
```

so yeah just tossing arm64 in the amd64 logic makes it pretty easy fix to atleast have x64 binaries work (even if they arent optimized)

**Comment by sanderjo** [comment]
> tossing 4.3.2 on that laptop

Can you verify the patched binary on https://github.com/sabnzbd/sabnzbd/actions/runs/9652508167 -> scroll down to "Windows installer" works on your Windows on ARM laptop? Verify that sabnzbd.log says unrar and par2 are found.

Thanks.

**Comment by thezoggy** [comment]
> > tossing 4.3.2 on that laptop
> 
> Can you verify the patched binary on https://github.com/sabnzbd/sabnzbd/actions/runs/9652508167 -> scroll down to "Windows installer" works on your Windows on ARM laptop? Verify that sabnzbd.log says unrar and par2 are found.
> 
> Thanks.

yep, resolves those warnings
```
2024-06-24 16:56:05,581::INFO::[SABnzbd:424] SABCTools module (v8.2.3)... found!
2024-06-24 16:56:05,597::INFO::[SABnzbd:425] SABCTools module is using SIMD set: SSSE3
2024-06-24 16:56:05,597::INFO::[SABnzbd:426] SABCTools module is linked to OpenSSL: True
2024-06-24 16:56:05,597::INFO::[SABnzbd:446] Cryptography module (v42.0.8)... found!
2024-06-24 16:56:05,597::INFO::[SABnzbd:449] MultiPar binary... found (C:\Program Files\SABnzbd\win\multipar\par2j64.exe)
2024-06-24 16:56:05,597::INFO::[SABnzbd:452] par2 binary... found (C:\Program Files\SABnzbd\win\par2\x64\par2.exe)
2024-06-24 16:56:05,597::INFO::[SABnzbd:459] UNRAR binary... found (C:\Program Files\SABnzbd\win\unrar\x64\UnRAR.exe)
2024-06-24 16:56:05,597::INFO::[SABnzbd:474] 7za binary... found (C:\Program Files\SABnzbd\win\7zip\7za.exe)
```
and testing each of those binaries from cli, they display their help/version info just fine
