### ISSUE TITLE
division by zero in Downloader.maybe_block_server

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2963]
### SABnzbd version

4.4.0b1

### Operating system

ubuntu 22.04/jammy

### Using Docker image

None

### Description

Got a bunch of 400 and 482 errors over the course of several minutes on a less reliable (freebie/test) server...:
```
2024-11-12 16:22:12,791::DEBUG::[downloader:864] Server login problem: 400 Too many connections for your host.
2024-11-12 16:22:13,658::DEBUG::[downloader:864] Server login problem: 482 too many connections for your user
```
...which is nothing out of the ordinary. But then, this happened:
```
2024-11-12 16:22:24,327::INFO::[downloader:616] 2@SERVER_ADDR: Initiating connection
2024-11-12 16:22:24,348::INFO::[newswrapper:336] 2@SERVER_ADDR: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2024-11-12 16:22:24,370::INFO::[downloader:751] Connecting 2@SERVER_ADDR finished
2024-11-12 16:22:24,733::DEBUG::[bpsmeter:351] Speed: 7.5 MB/s
2024-11-12 16:22:24,970::DEBUG::[assembler:80] Decoding part of /home/USER/downloads/incomplete/JOBNAME/FILE
2024-11-12 16:22:28,296::INFO::[downloader:949] Thread 3@SERVER_ADDR: Timed out
2024-11-12 16:22:28,307::INFO::[notifier:157] Sending notification: Error - Fatal error in Downloader (type=error, job_cat=None)
2024-11-12 16:22:28,307::ERROR::[downloader:686] Fatal error in Downloader
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/downloader.py", line 567, in run
    self.maybe_block_server(server)
  File "/usr/share/sabnzbdplus/sabnzbd/downloader.py", line 493, in maybe_block_server
    if server.optional and server.active and (server.bad_cons / server.threads) > 3:
 ZeroDivisionError: division by zero
2024-11-12 16:22:36,721::INFO::[notifier:157] Sending notification: Warning - Restarting because of crashed downloader (type=warning, job_cat=None)
2024-11-12 16:22:36,721::WARNING::[__init__:457] Restarting because of crashed downloader
2024-11-12 16:22:36,721::INFO::[sabnzbdplus:1540] Performing triggered restart
```

**Comment by sanderjo** [comment]
so server.threads is 0? 
And thus (server.bad_cons / server.threads) is infinity, and thus definitely > 3 ? (Note: assuming server.bad_cons  > 0)

If so, the line could be:

`if server.optional and server.active and ((server.threads == 0) or (server.bad_cons / server.threads) > 3):`

shoud work?

![image](https://github.com/user-attachments/assets/0e9ed7c4-a0a0-4f73-ab9c-403c730a4dcf)

![image](https://github.com/user-attachments/assets/d53afd6a-2751-4567-b50f-599811afa8ef)

**Comment by Safihre** [comment]
The problem is that we only decrease the counter, we never increase it again when connections come back.. @thezoggy also reported that and I have been aware of it for a while.
Just never fixed it.
But this seems a good reason to fix it.
