### ISSUE TITLE
4.4.0 regression: Failed to send Windows notification (No module named 'winrt.windows.foundation.collections')

### ISSUE THREAD

**Issue by bughit** [sabnzbd/sabnzbd#2994]
### SABnzbd version

4.4.0

### Operating system

win10 22h2

### Using Docker image

None

### Description

This is logged when sending a test notification:

```
2024-12-15 08:53:38,543::INFO::[api:812] Sending test notification
2024-12-15 08:53:38,543::DEBUG::[notifier:529] Sending Windows notification
2024-12-15 08:53:38,546::INFO::[notifier:544] Failed to send Windows notification
2024-12-15 08:53:38,547::DEBUG::[notifier:545] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\notifier.py", line 540, in send_windows
  File "windows_toasts\toasters.py", line 138, in show_toast
  File "windows_toasts\toasters.py", line 40, in _build_adaptable_data
ModuleNotFoundError: No module named 'winrt.windows.foundation.collections'
```

4.3.3 is ok

**Comment by Safihre** [comment]
Fixed in https://github.com/sabnzbd/sabnzbd/commit/4b99d04454e589328e309a1cdf340b9f246d174f
