### ISSUE TITLE
ENGINE socket.error 1 - ENGINE Unhandled error while processing an incoming connection SSLEOFError

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#3006]
### SABnzbd version

4.4.1

### Operating system

unraid

### Using Docker image

binhex

### Description

Started seeing this on 4.4.0 and now 4.4.1. Will get a batch of SSL related errors show up randomly.

Recent example:
```
2024-12-22 16:15:16,644::DEBUG::[interface:144] Request GET /api from 192.168.0.250 [okhttp/4.12.0] {'mode': 'queue', 'start': '0', 'output': 'json', 'REMOVED': '<REMOVED>'}
2024-12-22 16:15:21,635::INFO::[notifier:157] Sending notification: Warning - [22/Dec/2024:16:15:21] ENGINE socket.error 1
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1281, in communicate
    req.parse_request()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 714, in parse_request
    success = self.read_request_line()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 755, in read_request_line
    request_line = self.rfile.readline()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 305, in readline
    data = self.rfile.readline(256)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 558, in readline
    b = self.read(nreadahead())
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 49, in read
    val = super().read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1068, in read
    return self._read_unlocked(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1108, in _read_unlocked
    chunk = self.raw.read(wanted)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2570)
 (type=warning, job_cat=None)
2024-12-22 16:15:21,635::WARNING::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE socket.error 1
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1281, in communicate
    req.parse_request()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 714, in parse_request
    success = self.read_request_line()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 755, in read_request_line
    request_line = self.rfile.readline()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 305, in readline
    data = self.rfile.readline(256)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 558, in readline
    b = self.read(nreadahead())
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 49, in read
    val = super().read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1068, in read
    return self._read_unlocked(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1108, in _read_unlocked
    chunk = self.raw.read(wanted)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2570)

2024-12-22 16:15:21,636::WARNING::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE socket.error 1
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1281, in communicate
    req.parse_request()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 714, in parse_request
    success = self.read_request_line()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 755, in read_request_line
    request_line = self.rfile.readline()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 305, in readline
    data = self.rfile.readline(256)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 558, in readline
    b = self.read(nreadahead())
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 49, in read
    val = super().read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1068, in read
    return self._read_unlocked(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1108, in _read_unlocked
    chunk = self.raw.read(wanted)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2570)

2024-12-22 16:15:21,637::ERROR::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE Unhandled error while processing an incoming connection SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1281, in communicate
    req.parse_request()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 714, in parse_request
    success = self.read_request_line()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 755, in read_request_line
    request_line = self.rfile.readline()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 305, in readline
    data = self.rfile.readline(256)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 558, in readline
    b = self.read(nreadahead())
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 49, in read
    val = super().read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1068, in read
    return self._read_unlocked(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1108, in _read_unlocked
    chunk = self.raw.read(wanted)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2570)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/workers/threadpool.py", line 166, in _process_connections_until_interrupted
    keep_conn_open = conn.communicate()
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1310, in communicate
    self._conditional_error(req, '500 Internal Server Error')
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1353, in _conditional_error
    req.simple_response(response)
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1119, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 738, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2417)

2024-12-22 16:15:21,638::ERROR::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE Unhandled error while processing an incoming connection SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')
Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1281, in communicate
    req.parse_request()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 714, in parse_request
    success = self.read_request_line()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 755, in read_request_line
    request_line = self.rfile.readline()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 305, in readline
    data = self.rfile.readline(256)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 558, in readline
    b = self.read(nreadahead())
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 49, in read
    val = super().read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1068, in read
    return self._read_unlocked(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_pyio.py", line 1108, in _read_unlocked
    chunk = self.raw.read(wanted)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SYS] unknown error (_ssl.c:2570)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/workers/threadpool.py", line 166, in _process_connections_until_interrupted
    keep_conn_open = conn.communicate()
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1310, in communicate
    self._conditional_error(req, '500 Internal Server Error')
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1353, in _conditional_error
    req.simple_response(response)
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/server.py", line 1119, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/sabnzbd/venv/lib/python3.12/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 738, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2417)

2024-12-22 16:15:40,250::DEBUG::[interface:144] Request GET /api from 172.18.0.13 [Radarr/5.17.0.9555 (alpine 3.21.0)] {'mode': 'queue', 'start': '0', 'limit': '0', 'category': 'radarr', 'REMOVED': '<REMOVED>', 'output': 'json'}
```

I thought it was when the container was being updated but cant seem to replicate it.  looking at the timing nzb360 (is the okhttp user-agent) which looks like always the thing thats before the first event...

collapsed entries from above:
```
2024-12-22 16:15:16,644::DEBUG::[interface:144] Request GET /api from 192.168.0.250 [okhttp/4.12.0] {'mode': 'queue', 'start': '0', 'output': 'json', 'REMOVED': '<REMOVED>'}
2024-12-22 16:15:21,635::INFO::[notifier:157] Sending notification: Warning - [22/Dec/2024:16:15:21] ENGINE socket.error 1
2024-12-22 16:15:21,635::WARNING::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE socket.error 1
2024-12-22 16:15:21,636::WARNING::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE socket.error 1
2024-12-22 16:15:21,637::ERROR::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE Unhandled error while processing an incoming connection SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')
2024-12-22 16:15:21,638::ERROR::[_cplogging:213] [22/Dec/2024:16:15:21] ENGINE Unhandled error while processing an incoming connection SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2417)')
2024-12-22 16:15:40,250::DEBUG::[interface:144] Request GET /api from 172.18.0.13 [Radarr/5.17.0.9555 (alpine 3.21.0)] {'mode': 'queue', 'start': '0', 'limit': '0', 'category': 'radarr', 'REMOVED': '<REMOVED>', 'output': 'json'}
```

just tossing this here in case others report / figure out more info

nzb360: v19.4

```
# docker exec -it binhex-sabnzbd /bin/bash
[root@1fd56e06a8de /]# python3 -V
Python 3.12.7
[root@1fd56e06a8de /]# openssl version
OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)

# cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
IMAGE_ID=archlinux
IMAGE_VERSION=2024.11.01
```

**Comment by sanderjo** [comment]
The below at the moment I activated HTTPS in the GUI.
I could not reproduce

Ubuntu 24.04, with sabnzbdplus 4.4.1 [d897936] from PPA

And: #CherrypyAlert 


```
2024-12-23 23:16:42,220::INFO::[ssdp:108] Serving SSDP on 192.168.1.100 as SABnzbd
2024-12-23 23:16:50,405::DEBUG::[misc:798] CPU model = Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
2024-12-23 23:16:54,849::INFO::[notifier:157] Sending notification: Warning - [23/Dec/2024:23:16:54] ENGINE socket.error 8
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 141, in respond
    self.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 223, in write
    self.req.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1133, in write
    self.conn.wfile.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)
 (type=warning, job_cat=None)
2024-12-23 23:16:54,849::WARNING::[_cplogging:213] [23/Dec/2024:23:16:54] ENGINE socket.error 8
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 141, in respond
    self.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 223, in write
    self.req.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1133, in write
    self.conn.wfile.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)

```

**Comment by sanderjo** [comment]
I saw the same when activating HTTPS.
Ubuntu 24.04, sabnzbdplus 4.4.1 [d897936] from PPA.

And ... #CherrypyAlert 
```
2024-12-23 23:16:50,405::DEBUG::[misc:798] CPU model = Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
2024-12-23 23:16:54,849::INFO::[notifier:157] Sending notification: Warning - [23/Dec/2024:23:16:54] ENGINE socket.error 8
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 141, in respond
    self.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 223, in write
    self.req.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1133, in write
    self.conn.wfile.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)
 (type=warning, job_cat=None)
2024-12-23 23:16:54,849::WARNING::[_cplogging:213] [23/Dec/2024:23:16:54] ENGINE socket.error 8
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 141, in respond
    self.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/wsgi.py", line 223, in write
    self.req.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1133, in write
    self.conn.wfile.write(chunk)
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 68, in write
    res = super().write(val, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 24, in write
    self._flush_unlocked()
  File "/usr/lib/python3/dist-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 725, in write
    return self._sock.send(b)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)

2024-12-23 23:21:00,593::INFO::[config:999] Writing settings to INI file /home/sander/.sabnzbd/sabnzbd.ini
2024-12-23 23:21:03,482::INFO::[api:720] Restart requested by API
2024-12-23 23:21:04,484::INFO::[sabnzbdplus:1544] Performing triggered restart

```

**Comment by Safihre** [comment]
Cryptography isn't involved into the https :) only cheroot and cherrypy, but those haven't been updated in a year.

**Comment by sanderjo** [comment]
I want to stay away from the rabbithole calles "Cherrypy & SSL", so just some remarks:

binhex sabnzbd container running on my ubuntu, with Chrome connected to it via https://127.0.0.1:8090/ : **no** "ENGINE socket" errors. So what is causing that on your binhex sabnzbd? A web client connecting? Underlying OS (Unraid?)? ... something else ... ?

However, I must confess: as soon as in Chrome  I click on something in the SAB interface, the docker stdout / stderr says

```
2024-12-27 21:02:48,682 DEBG 'start-script' stdout output:
2024-12-27 21:02:48,682::INFO::[_cplogging:213] [27/Dec/2024:21:02:48] ENGINE Client ('172.17.0.1', 47226) lost — peer dropped the TLS connection suddenly, during handshake: (1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] ssl/tls alert certificate unknown (_ssl.c:1000)')
```

So is the current binhex sabnzbd setup pickier?

What if you use lsio sabnzbd docker?

And if everything fails: Can you monkey-patch out the _cplogging messaging and the traceback?

**Comment by sanderjo** [comment]
So an additional suspect: the cloudflare connection (reverse proxy? tunnel?). Maybe it sends heartbeats to SABnzbd's SSL port, which the current binhex doesn't like.

Temporarily turn off the cloudflare connection, and see if the errors and tracebacks are gone?
