### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by fgeck** [sabnzbd/sabnzbd#3008]
### SABnzbd version

4.4.0

### Operating system

TalOS 1.9.0 -> Kubernetes 1.32.0

### Using Docker image

Other --> ghcr.io/onedr0p/sabnzbd:4.4

### Description

Hello,

I have an installation of sabnzbd as a kubernetes deployment (details see below) in my homelab server.
The container randomly logs the error below. Unfortunately I cannot see a pattern when it occurs, but it is triggered somehow automatically (seems like some socket is failing).
Based on the log I cannot pin down where exactly the exception is thrown. First I thought it is maybe related to #2734 but based on the logs I don't think so.

Sabnzbd itself is working fine. I can add Servers and I was able to successfully download and unzip the 100Mb test file.
I attached my redacted ini file: [sabnzbd.log](https://github.com/user-attachments/files/18269576/sabnzbd.log)

Log Level: Info
```log
2024-12-29 13:36:08,015::INFO::[SABnzbd:1139] Console logging only
2024-12-29 13:36:08,016::INFO::[SABnzbd:1142] --------------------------------
2024-12-29 13:36:08,016::INFO::[SABnzbd:1143] SABnzbd.py-4.4.1
2024-12-29 13:36:08,016::INFO::[SABnzbd:1153] Commit = d897936da564ee5564a697dfcfd5eec5824b0d0c
2024-12-29 13:36:08,016::INFO::[SABnzbd:1155] Full executable path = /app/SABnzbd.py
2024-12-29 13:36:08,016::INFO::[SABnzbd:1156] Arguments = "/app/SABnzbd.py" "--browser" "0" "--server" "0.0.0.0:10097" "--config-file" "/config/sabnzbd.ini" "--disable-file-log" "--console"
2024-12-29 13:36:08,016::INFO::[SABnzbd:1157] Python-version = 3.13.1 (main, Dec  9 2024, 20:39:36) [GCC 14.2.0]
2024-12-29 13:36:08,016::INFO::[SABnzbd:1158] Dockerized = False
2024-12-29 13:36:08,016::INFO::[SABnzbd:1159] CPU architecture = x86_64
2024-12-29 13:36:08,019::INFO::[SABnzbd:1162] Platform = posix - Linux-6.12.5-talos-x86_64-with
2024-12-29 13:36:08,019::INFO::[SABnzbd:1168] Preferred encoding = UTF-8
2024-12-29 13:36:08,019::INFO::[SABnzbd:1190] SSL version = OpenSSL 3.3.2 3 Sep 2024
2024-12-29 13:36:08,021::INFO::[SABnzbd:1199] Certifi version = 2024.08.30
2024-12-29 13:36:08,021::INFO::[SABnzbd:1200] Loaded additional certificates from /usr/local/lib/python3.13/site-packages/certifi/cacert.pem
2024-12-29 13:36:08,021::INFO::[SABnzbd:1210] Using INI file /config/sabnzbd.ini
2024-12-29 13:36:08,022::INFO::[postproc:143] Loading postproc queue
2024-12-29 13:36:08,023::INFO::[scheduler:190] Scheduling RSS interval task every 60 min (delay=2)
2024-12-29 13:36:08,023::INFO::[scheduler:200] Scheduling version check in 10 minutes and daily at 15:51
2024-12-29 13:36:08,023::INFO::[scheduler:215] Setting schedule for midnight auto history-purge
2024-12-29 13:36:08,023::INFO::[scheduler:224] Setting schedule for midnight BPS reset
2024-12-29 13:36:08,023::INFO::[scheduler:233] Setting schedule for midnight server expiration check
2024-12-29 13:36:08,023::INFO::[scheduler:242] Setting schedule for server quota check
2024-12-29 13:36:08,023::INFO::[__init__:303] All processes started
2024-12-29 13:36:08,024::INFO::[SABnzbd:340] Template location for Glitter is /app/interfaces/Glitter
2024-12-29 13:36:08,024::INFO::[SABnzbd:340] Template location for Config is /app/interfaces/Config
2024-12-29 13:36:08,024::INFO::[misc:1260] [N/A] Running external command: ['/usr/bin/unrar']
2024-12-29 13:36:08,027::INFO::[misc:1260] [N/A] Running external command: ['/usr/bin/7zz']
2024-12-29 13:36:08,030::INFO::[misc:1260] [N/A] Running external command: ['/usr/local/bin/par2', '-V']
2024-12-29 13:36:08,032::INFO::[SABnzbd:425] SABCTools module (v8.2.5)... found!
2024-12-29 13:36:08,032::INFO::[SABnzbd:426] SABCTools module is using SIMD set: SSSE3
2024-12-29 13:36:08,032::INFO::[SABnzbd:427] SABCTools module is linked to OpenSSL: True
2024-12-29 13:36:08,032::INFO::[SABnzbd:447] Cryptography module (v44.0.0)... found!
2024-12-29 13:36:08,033::INFO::[SABnzbd:453] par2 binary... found (/usr/local/bin/par2)
2024-12-29 13:36:08,033::INFO::[SABnzbd:460] UNRAR binary... found (/usr/bin/unrar)
2024-12-29 13:36:08,033::INFO::[SABnzbd:468] UNRAR binary version 7.01
2024-12-29 13:36:08,033::INFO::[SABnzbd:475] 7za binary... found (/usr/bin/7zz)
2024-12-29 13:36:08,033::INFO::[SABnzbd:477] 7za binary version 24.08
2024-12-29 13:36:08,034::INFO::[SABnzbd:483] nice binary... found (/bin/nice)
2024-12-29 13:36:08,034::INFO::[SABnzbd:487] ionice binary... found (/bin/ionice)
2024-12-29 13:36:08,035::INFO::[SABnzbd:1404] Starting web-interface on 0.0.0.0:10097
2024-12-29 13:36:08,035::INFO::[_cplogging:213] [29/Dec/2024:13:36:08] ENGINE Bus STARTING
2024-12-29 13:36:08,142::INFO::[_cplogging:213] [29/Dec/2024:13:36:08] ENGINE Serving on http://0.0.0.0:10097
2024-12-29 13:36:08,142::INFO::[_cplogging:213] [29/Dec/2024:13:36:08] ENGINE Bus STARTED
2024-12-29 13:36:08,143::INFO::[SABnzbd:1443] Starting SABnzbd.py-4.4.1
2024-12-29 13:36:08,151::INFO::[dirscanner:112] Dirscanner starting up
2024-12-29 13:36:08,153::INFO::[notifier:157] Sending notification: SABnzbd - SABnzbd 4.4.1 started (type=startup, job_cat=None)
2024-12-29 13:36:08,154::INFO::[zconfig:61] No bonjour/zeroconf support installed
2024-12-29 13:36:08,156::INFO::[ssdp:108] Serving SSDP on 10.244.0.135 as SABnzbd

--------------- 2024-12-29 13:39:08 now the error starts to happen (at about 3min after start):
Exception ignored in: <function IOBase.__del__ at 0x7efde64740e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
```

Log Level: Debug
```log
2024-12-29 13:22:30,269::DEBUG::[interface:144] Request GET /api from 10.244.0.95 (X-Forwarded-For: 192.168.178.201) [Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0] {'mode': 'queue', 'start': '0', 'limit': '20', 'output': 'json', 'apikey': '', '_': '1735474830757'}
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IOBase.__del__ at 0x7fcdc3a680e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/_pyio.py", line 418, in __del__
    self.close()
  File "/usr/local/lib/python3.13/_pyio.py", line 1313, in close
    self.flush()
  File "/usr/local/lib/python3.13/_pyio.py", line 1274, in flush
    self._flush_unlocked()
  File "/usr/local/lib/python3.13/site-packages/cheroot/makefile.py", line 33, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "/usr/local/lib/python3.13/socket.py", line 737, in write
    return self._sock.send(b)
OSError: [Errno 9] Bad file descriptor
2024-12-29 13:22:30,312::DEBUG::[interface:144] Request GET /api from 10.244.0.95 (X-Forwarded-For: 192.168.178.201) [Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0] {'mode': 'history', 'failed_only': '0', 'start': '0', 'limit': '10', 'archive': '0', 'last_history_update': '1', 'output': 'json', 'apikey': '', '_': '1735474830758'}
```

My Setup is as Follows:

Local Client (Firefox Mac) --> Router --> Kubernetes Load Balancer (Traefik) --> Routes based on Ingressroute to K8s Service --> to Pod of deployment

Here are my K8s resources:

Service & Deployment:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
    - protocol: TCP
      port: 10097
      targetPort: 10097
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: '@daily'
    keel.sh/trigger: poll
  labels:
    app.kubernetes.io/group: media
    app.kubernetes.io/name: sabnzbd
  name: sabnzbd
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/group: media
        app.kubernetes.io/name: sabnzbd
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: TZ
          value: Europe/Berlin
        - name: UMASK
          value: "0022"
        - name: UMASK_SET
          value: "0022"
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: SABNZBD__HOST_WHITELIST_ENTRIES
          value: "dl.{{ .Values.edge.domain }}, sabnzbd, sabnzbd.default, sabnzbd.default.svc, sabnzbd.default.svc.cluster, sabnzbd.default.svc.cluster.local"
        - name: SABNZBD__PORT
          value: "10097"
        image: ghcr.io/onedr0p/sabnzbd:4.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 10097
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: sabnzbd
        ports:
        - containerPort: 10097
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 10097
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 10097
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: sabnzbd-config
        - mountPath: /mnt/data
          name: sabnzbd-data
        - mountPath: /dev/shm
          name: devshm
        - mountPath: /shared
          name: shared
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/logs
          name: varlogs
        - mountPath: /var/run
          name: varrun
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
        - 568
      serviceAccount: default
      serviceAccountName: default
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 60
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-pvc
      - name: sabnzbd-data
        persistentVolumeClaim:
          claimName: sabnzbd-data-pvc
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: devshm
      - emptyDir: {}
        name: shared
      - emptyDir:
          medium: Memory
          sizeLimit: 6Gi
        name: tmp
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: varlogs
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: varrun
```

Ingressroute:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app: sabnzbd
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`dl.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    services:
    - kind: Service
      name: sabnzbd
      namespace: media
      passHostHeader: true
      port: 10097
      scheme: http
```

PVs & PVCs for storing config (longhorn volume) and downloaded data (nfs)
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv
  namespace: media
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      backingImage: ""
      numberOfReplicas: "1"
    volumeHandle: sabnzbd-longhorn-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: sabnzbd-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-data-pv
spec:
  storageClassName: dummy
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /share/data/downloads
    server: {{ .Values.global.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data-pvc
spec:
  storageClassName: dummy
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: sabnzbd-data-pv
```

**Comment by sanderjo** [comment]
So: traceback in cherrypy / cheroot (sab's webserver) -> socket -> send

"OSError: [Errno 9] Bad file descriptor" ... first google hit: 'You get this error message if a Python file was closed from "the outside", ie not from the file object's close() method.' (with on Linux everything a file).

So, with your setup, could it be an underlying OS / layer is closing/disabling/cleaning up that socket?
FWIW: I don't how to force-create such a situation.

Google "OSError: [Errno 9] Bad file descriptor" combined with "docker" (and k8s) gives 'interesting' results. Among which this endless thread (without solution): https://github.com/benoitc/gunicorn/issues/1877

FWIW: I cannot reproduce with `docker run -p 8080:8080  ghcr.io/onedr0p/sabnzbd:4.4.1`

The usual narrowing:
* does it happen with an older version of onedr0p/sabnzbd ?
* does it happen when nothing is access the sabnzbd webinterface (including API)?
* ...

**Comment by fgeck** [comment]
> So, with your setup, could it be an underlying OS / layer is closing/disabling/cleaning up that socket?
tbh. I assume so yes --> so thanks for moving the Bug to Support. I opened the issue also to document the solution once 

found that in case someone else runs into this issue one can find it.

> does it happen with an older version of onedr0p/sabnzbd ?
With 4.4.1 - yes
With 4.3.3 - yes
With 4.3 - yes

---> So after those tests I am 100% sure the problem is somewhere in my setup.

> does it happen when nothing is access the sabnzbd webinterface (including API)?

After 10min. nothing is logged when I do not access the webinterface / API. --> Should be related to a websocket in the webinterface

> what if you put a reverse proxy in front of the sabnzbd docker?

The Traefik LoadBalancer in my setup is the reverse proxy. As referenced in the `IngressRoute` above I allow `web, websecure` traffik which is port 80 and 443. I would exepect Websocket communication to work over those ports without special tweaking.

> can you reproduce on a simpler setup?

Unfortunately not. Running the image via docker-compose and behind a traefik as reverse proxy works.

**Comment by sanderjo** [comment]
I don't know if that is related. I would do it like this: remove Traefik from the path (so: direct connection to SABnzbd), and see if it happens again.

But: the web access is short-lived. Indeed each second: it's a SABnzbd setting: Wrench -> Web interface -> Refresh rate. So play with that? Set to disabled, and see if it still happens? Both with and without Traefik involved.

The thing is: SABnzbd writes to the socket, but it's not there anymore. So is the OS (docker) terminating that? Maybe  Traefik can trigger that ...  Traefik closes that connection, and SABnzbd is sending something to it afterwards?

So: experiment with that.

More hardcore stuff (possible won't help, just for fun): inside the docker, run `netstat --all -p -c  | grep -i python3`. On my SABnzbd downloading stuff, I get

```
tcp    71479      0 brixit:38338            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp    90837      0 brixit:38366            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   117288      0 brixit:34108            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp    93420      0 brixit:34106            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp        0      0 brixit:38396            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   103352      0 brixit:34076            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp    46336      0 brixit:38412            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp    41992      0 brixit:38380            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp    35864      0 brixit:38400            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   377928      0 brixit:34064            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp    26064      0 brixit:38418            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   113240      0 brixit:38352            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   227972      0 brixit:34126            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp    15928      0 brixit:38428            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp    74901      0 brixit:34090            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp    31722      0 brixit:38402            185.90.196.65:https     ESTABLISHED 288119/python3      
tcp   160728      0 brixit:34054            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp   311390      0 brixit:34138            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp   398598      0 brixit:34118            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp        0      0 brixit:34042            185.90.196.70:nntps     ESTABLISHED 288119/python3      
tcp6       0      0 [::]:http-alt           [::]:*                  LISTEN      288119/python3      
tcp6       0      0 brixit:http-alt         zwarte:43622            ESTABLISHED 288119/python3      
tcp6       0      0 brixit:http-alt         zwarte:43612            ESTABLISHED 288119/python3      
tcp6       0      0 brixit:http-alt         zwarte:43618            ESTABLISHED 288119/python3      
tcp6       0      0 brixit:http-alt         zwarte:43626            ESTABLISHED 288119/python3   ``

```
The https and nntps is the downloading.
The http-alt is the webinterface

Also: lsof, and only the webinterface:

```
root@brixit:~# lsof -P -i tcp | grep 288119 | grep :8080
python3   288119              sander    8u  IPv6 2329807      0t0  TCP *:8080 (LISTEN)
python3   288119              sander   36u  IPv6 2477734      0t0  TCP brixit:8080->zwarte:48754 (ESTABLISHED)
python3   288119              sander   51u  IPv6 2477736      0t0  TCP brixit:8080->zwarte:48772 (ESTABLISHED)
```

To show the age of connections of PID 288119 (which is SABnzbd on my system):

```
root@brixit:~# lsof -P -i tcp | awk '{print $2,$4}' | tr -d 'u' | sort -u | while read pid fd; do stat --printf "%z %N\n" /proc/$pid/fd/$fd ; done | sort -r | grep 288119
stat: cannot statx '/proc/PID/fd/FD': No such file or directory
2024-12-30 11:34:38.681454716 +0100 '/proc/288119/fd/50' -> 'socket:[2479759]'
2024-12-30 11:14:02.054177032 +0100 '/proc/288119/fd/48' -> 'socket:[2479758]'
2024-12-30 11:14:02.054177032 +0100 '/proc/288119/fd/47' -> 'socket:[2444273]'
2024-12-30 11:14:02.054177032 +0100 '/proc/288119/fd/10' -> 'socket:[2448458]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/8' -> 'socket:[2329807]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/46' -> 'socket:[2479757]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/43' -> 'socket:[2479756]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/42' -> 'socket:[2479755]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/41' -> 'socket:[2479754]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/40' -> 'socket:[2479753]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/39' -> 'socket:[2479752]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/38' -> 'socket:[2479751]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/37' -> 'socket:[2479750]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/36' -> 'socket:[2479749]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/35' -> 'socket:[2479748]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/33' -> 'socket:[2479747]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/32' -> 'socket:[2479746]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/31' -> 'socket:[2479745]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/30' -> 'socket:[2479744]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/29' -> 'socket:[2476426]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/28' -> 'socket:[2476425]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/27' -> 'socket:[2476424]'
2024-12-30 11:13:04.331919453 +0100 '/proc/288119/fd/16' -> 'socket:[2476423]'

```

**Comment by sanderjo** [comment]
And a general remark:

Virtual environments (docker, kubernetes, lxd/lxc, proxmox VE, Unraid) seem to do specials things to their guests, like (suddenly?) limiting CPU usage, connections, RAM usage ... with mysterious effects on SABnzbd. It's like pulling the carpet from under SABnzbd.
