### ISSUE TITLE
sab 0.8.x -- crashing post processor

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#368]
name of file (150 char without .ext): `Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee`

nzb: http://poke.sickbeard.com/getnzb/c44515dee78fca23f6645c3c851c8264.nzb

snippet of console:
```
2015-10-14 10:04:27,641::ERROR::[postproc:515] Post Processing Failed for Late.Show.with.Ste
Goddesses.720p.CBS.WEB (Path exceeds 260, repair by "par2" is not possible)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\sabnzbd_0.8.x\sabnzbd\postproc.py", line 189, in run
    process_job(nzo)
  File "C:\Program Files (x86)\sabnzbd_0.8.x\sabnzbd\postproc.py", line 525, in process_job
    emailer.endjob(dirname, cat, all_ok, clip_path(workdir_complete), nzo.bytes_downloaded,
UnboundLocalError: local variable 'dirname' referenced before assignment

2015-10-14 10:04:35,176::INFO::[__init__:1034] Restarting because of crashed postprocessor
```

log entries during the event:
```
2015-10-14 10:04:25,878::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,878::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,878::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,894::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,894::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,894::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,908::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,908::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,908::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,924::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,924::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:25,924::INFO::[assembler:88] Decoding \\?\C:\Users\user_\downloads\incomplete\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Ze\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.nzb yenc
2015-10-14 10:04:25,986::INFO::[assembler:88] Decoding \\?\C:\Users\user_\downloads\incomplete\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Ze\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.r10 yenc
2015-10-14 10:04:27,625::DEBUG::[assembler:366] file in rar file: Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv
2015-10-14 10:04:27,625::INFO::[__init__:911] \\?\C:\Users\user_\downloads\incomplete\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Ze\__ADMIN__\SABnzbd_nzo_b0d8vs removed
2015-10-14 10:04:27,625::INFO::[nzbqueue:250] Saving queue
2015-10-14 10:04:27,625::INFO::[__init__:921] Saving data for queue10.sab in C:\Users\user_\AppData\Local\sabnzbd\admin\queue10.sab
2015-10-14 10:04:27,641::INFO::[postproc:83] Saving postproc queue
2015-10-14 10:04:27,641::INFO::[downloader:263] Waiting for post-processing to finish
2015-10-14 10:04:27,641::INFO::[__init__:921] Saving data for postproc2.sab in C:\Users\user_\AppData\Local\sabnzbd\admin\postproc2.sab
2015-10-14 10:04:27,641::INFO::[postproc:280] Starting PostProcessing on Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEB => Repair:True, Unpack:True, Delete:True, Script:None, Cat:bypass
2015-10-14 10:04:27,641::ERROR::[postproc:515] Post Processing Failed for Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEB (Path exceeds 260, repair by "par2" is not possible)
2015-10-14 10:04:35,176::INFO::[__init__:1034] Restarting because of crashed postprocessor
```

config > special > folder_max_length == 128

this is on win7 sp1 x64 with sab 0.8.x latest dev. nzb d/ls just fine in newsbin... looks like the big difference on why it works for them is because inside the job name they use a short temp folder when doing the work, vs sab that uses the job name.. thus you can easily exceed path limits when nzb name is long... can see at the start of the nzb addition when it backs it up:
```
2015-10-14 10:01:13,029::INFO::[__init__:569] Backing up \\?\C:\Users\user_\downloads\incomplete\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Ze\__ADMIN__\Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.nzb.gz
```

**Comment by shypike** [comment]
Two separate issues.
1. The crash is due to a variable not being set, that's easy to fix.
2. The "incomplete" path still has the 260 limit, which is a par2.exe problem. However it should be possible the shorten the folder names in "incomplete". Who cares if they're shortened.

**Comment by shypike** [comment]
SABnzbd actually already reduces the path to below 128.
I cannot reproduce the crash like you show it.

**Comment by thezoggy** [comment]
okay updated to latest dev, trying again. add nzb, pasted url to nzb (noted above), left everything default. which is normal priority, +Delete processing, None script, nothing for folder/tag. shows that the relative folder for the cat page is `C:\Users\zoggy\downloads\complete` 

alright.. loaded nzb.. it finished.. same issue but at least this time sab didnt crash/restart. just the par message..
```
2015-10-14 18:47:55,500::INFO::[postproc:83] Saving postproc queue
2015-10-14 18:47:55,500::INFO::[downloader:263] Waiting for post-processing to finish
2015-10-14 18:47:55,500::INFO::[__init__:921] Saving data for postproc2.sab in C:\Users\zoggy\AppData\Local\sabnzbd\admin\postproc2.sab
2015-10-14 18:47:55,500::INFO::[postproc:280] Starting PostProcessing on Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEB => Repair:True, Unpack:True, Delete:True, Script:None, Cat:*
2015-10-14 18:47:55,516::ERROR::[postproc:515] Post Processing Failed for Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEB (Path exceeds 260, repair by "par2" is not possible)
```

**Comment by shypike** [comment]
Please email a debug log.

**Comment by shypike** [comment]
Gotcha. The check is whether any <b>file</b> path exceeds 260, because that is the limitation of par2.exe.
In this case that's certainly true.
The fix will be to limit the "incomplete" path much further.

**Comment by thezoggy** [comment]
updated to latest, testing nzb again. will report back shortly with results

**Comment by thezoggy** [comment]
side note.. looks like the series dupe detection, **Detect duplicate episodes in series** does not handle air-by-date releases (should parse YYYY as season then MM-DD/DD-MM as the episode).
Also looks like only `S##E##` format is handled, not `#x##`.

**Comment by thezoggy** [comment]
so loaded same nzb, duplicate job was handled just fine:

folder:
`Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEB.1`

file inside (full name):
`Late.Show.with.Stephen.Colbert.2015.10.13.Sarah.Silverman.Elijah.Wood.The.Legend.of.Zelda.Symphony.of.the.Goddesses.720p.CBS.WEBRip.AAC2.0.H264-monkee.mkv`

so looks like this is good to go

**Comment by shypike** [comment]
@thezoggy
> looks like the series dupe detection, Detect duplicate episodes in series does not handle air-by-date releases (should parse YYYY as season then MM-DD/DD-MM as the episode).
Also looks like only S##E## format is handled, not #x##.

Air-by-date isn't supported at all by the Series sorting method (which is used for duplicate detection).
0x01 notation is supported and works.
