### ISSUE TITLE
SAB fails to run on newly updated centos server

### ISSUE THREAD

**Issue by lpallard1** [sabnzbd/sabnzbd#385]
Since last update of my centos 7 server, SAB is refusing to start.  It used to work for several months on this server until the update done with yum today.

Other applications were having problems so I decided to restart fresh with a new install of centos. This is still not working but now it is the only applicvation still misbehaving.  From the logs:

2015-11-07 20:33:50,365::INFO::[SABnzbd:1238] --------------------------------
2015-11-07 20:33:50,365::INFO::[SABnzbd:1239] SABnzbd.py-0.8.x (rev=unknown)
2015-11-07 20:33:50,365::INFO::[SABnzbd:1251] Platform = posix
2015-11-07 20:33:50,365::INFO::[SABnzbd:1252] Python-version = 2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
2015-11-07 20:33:50,365::INFO::[SABnzbd:1253] Arguments = /var/www/html/sabnzbd/SABnzbd.py --daemon --config-file=/var/www/html/sabnzbd-data/sabnzbd.ini -s 0.0.0.0
2015-11-07 20:33:50,365::INFO::[SABnzbd:1298] Read INI file /var/www/html/sabnzbd-data/sabnzbd.ini
2015-11-07 20:33:50,425::INFO::[__init__:958] Loading data for rss_data.sab from /var/www/html/sabnzbd-data/admin/rss_data.sab
2015-11-07 20:33:50,425::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/rss_data.sab missing
2015-11-07 20:33:50,426::INFO::[__init__:958] Loading data for totals10.sab from /var/www/html/sabnzbd-data/admin/totals10.sab
2015-11-07 20:33:50,426::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/totals10.sab missing
2015-11-07 20:33:50,426::INFO::[__init__:958] Loading data for totals9.sab from /var/www/html/sabnzbd-data/admin/totals9.sab
2015-11-07 20:33:50,426::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/totals9.sab missing
2015-11-07 20:33:50,431::INFO::[postproc:89] Loading postproc queue
2015-11-07 20:33:50,431::INFO::[__init__:958] Loading data for postproc2.sab from /var/www/html/sabnzbd-data/admin/postproc2.sab
2015-11-07 20:33:50,431::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/postproc2.sab missing
2015-11-07 20:33:50,431::INFO::[__init__:958] Loading data for queue10.sab from /var/www/html/sabnzbd-data/admin/queue10.sab
2015-11-07 20:33:50,432::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/queue10.sab missing
2015-11-07 20:33:50,432::INFO::[__init__:958] Loading data for queue9.sab from /var/www/html/sabnzbd-data/admin/queue9.sab
2015-11-07 20:33:50,432::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/queue9.sab missing
2015-11-07 20:33:50,432::INFO::[__init__:958] Loading data for watched_data2.sab from /var/www/html/sabnzbd-data/admin/watched_data2.sab
2015-11-07 20:33:50,432::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/watched_data2.sab missing
2015-11-07 20:33:50,432::INFO::[__init__:958] Loading data for Rating.sab from /var/www/html/sabnzbd-data/admin/Rating.sab
2015-11-07 20:33:50,433::INFO::[__init__:961] /var/www/html/sabnzbd-data/admin/Rating.sab missing
2015-11-07 20:33:50,433::INFO::[scheduler:190] Setting schedule for midnight BPS reset
2015-11-07 20:33:50,433::INFO::[downloader:241] Resuming
2015-11-07 20:33:50,443::INFO::[__init__:348] All processes started
2015-11-07 20:33:50,444::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Glitter
2015-11-07 20:33:50,444::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Config
2015-11-07 20:33:50,463::INFO::[SABnzbd:483] _yenc module... found!
2015-11-07 20:33:50,464::INFO::[SABnzbd:491] par2 binary... found (/usr/bin/par2)
2015-11-07 20:33:50,464::INFO::[SABnzbd:496] par2-classic binary... found (/usr/bin/par2)
2015-11-07 20:33:50,464::INFO::[SABnzbd:499] unrar binary... found (/usr/bin/unrar)
2015-11-07 20:33:50,464::INFO::[SABnzbd:504] unzip binary... found (/usr/bin/unzip)
2015-11-07 20:33:50,464::INFO::[SABnzbd:510] 7za binary... found (/usr/bin/7za)
2015-11-07 20:33:50,464::INFO::[SABnzbd:517] nice binary... found (/usr/bin/nice)
2015-11-07 20:33:50,464::INFO::[SABnzbd:521] ionice binary... found (/usr/bin/ionice)
2015-11-07 20:33:50,464::INFO::[SABnzbd:526] pyOpenSSL... found (True)
2015-11-07 20:33:50,465::INFO::[SABnzbd:1358] SSL version OpenSSL 1.0.1e-fips 11 Feb 2013
2015-11-07 20:33:50,465::INFO::[SABnzbd:1359] SSL potentially supported protocols ['SSLv2', 'SSLv23', 'SSLv3', 'TLSv1']
2015-11-07 20:33:50,465::INFO::[SABnzbd:1360] SSL actually supported protocols ['t1', 'v23', 'v3', 'v2']
2015-11-07 20:33:50,468::INFO::[SABnzbd:1506] Starting web-interface on 0.0.0.0:8080
2015-11-07 20:33:50,469::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Bus STARTING
2015-11-07 20:33:50,472::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-11-07 20:33:50,475::ERROR::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/var/www/html/sabnzbd/cherrypy/process/servers.py", line 206, in _start_http_thread
    self.httpserver.start()
  File "/var/www/html/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 1973, in start
    raise socket.error(msg)
error: No socket could be created -- (('::1', 8080, 0, 0): [Errno 99] Cannot assign requested address)

2015-11-07 20:33:50,475::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Bus STOPPING
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::1', 8080)) already shut down
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE HTTP Server None already shut down
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Stopped thread '_TimeoutMonitor'.
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Bus STOPPED
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Bus EXITING
2015-11-07 20:33:50,476::INFO::[_cplogging:216] [07/Nov/2015:20:33:50] ENGINE Bus EXITED

As you can see "ENGINE Error in HTTP server: shutting down".  Port 8080 is NOT used by another process and confirmed by "netstat -ant | grep 8080".

**Comment by lpallard1** [comment]
I have tried to manually start SAB with python directly (python SABnzbd.py) and I still cannot access server_ip:8080 but the terminal output is

2015-11-07 21:34:51,662::INFO::[SABnzbd:1238] --------------------------------
2015-11-07 21:34:51,662::INFO::[SABnzbd:1239] SABnzbd.py-0.8.x (rev=unknown)
2015-11-07 21:34:51,663::INFO::[SABnzbd:1251] Platform = posix
2015-11-07 21:34:51,663::INFO::[SABnzbd:1252] Python-version = 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
2015-11-07 21:34:51,663::INFO::[SABnzbd:1253] Arguments = /var/www/html/sabnzbd/SABnzbd.py
2015-11-07 21:34:51,663::INFO::[SABnzbd:1298] Read INI file /root/.sabnzbd/sabnzbd.ini
2015-11-07 21:34:51,663::INFO::[misc:433] download_dir directory: /root/Downloads/incomplete does not exist, try to create it
2015-11-07 21:34:51,665::INFO::[__init__:958] Loading data for rss_data.sab from /root/.sabnzbd/admin/rss_data.sab
2015-11-07 21:34:51,665::INFO::[__init__:961] /root/.sabnzbd/admin/rss_data.sab missing
2015-11-07 21:34:51,666::INFO::[__init__:958] Loading data for totals10.sab from /root/.sabnzbd/admin/totals10.sab
2015-11-07 21:34:51,666::INFO::[__init__:961] /root/.sabnzbd/admin/totals10.sab missing
2015-11-07 21:34:51,666::INFO::[__init__:958] Loading data for totals9.sab from /root/.sabnzbd/admin/totals9.sab
2015-11-07 21:34:51,666::INFO::[__init__:961] /root/.sabnzbd/admin/totals9.sab missing
2015-11-07 21:34:51,674::INFO::[postproc:89] Loading postproc queue
2015-11-07 21:34:51,674::INFO::[__init__:958] Loading data for postproc2.sab from /root/.sabnzbd/admin/postproc2.sab
2015-11-07 21:34:51,675::INFO::[__init__:961] /root/.sabnzbd/admin/postproc2.sab missing
2015-11-07 21:34:51,677::INFO::[__init__:958] Loading data for queue10.sab from /root/.sabnzbd/admin/queue10.sab
2015-11-07 21:34:51,677::INFO::[__init__:961] /root/.sabnzbd/admin/queue10.sab missing
2015-11-07 21:34:51,677::INFO::[__init__:958] Loading data for queue9.sab from /root/.sabnzbd/admin/queue9.sab
2015-11-07 21:34:51,677::INFO::[__init__:961] /root/.sabnzbd/admin/queue9.sab missing
2015-11-07 21:34:51,678::INFO::[__init__:958] Loading data for watched_data2.sab from /root/.sabnzbd/admin/watched_data2.sab
2015-11-07 21:34:51,678::INFO::[__init__:961] /root/.sabnzbd/admin/watched_data2.sab missing
2015-11-07 21:34:51,678::INFO::[__init__:958] Loading data for Rating.sab from /root/.sabnzbd/admin/Rating.sab
2015-11-07 21:34:51,678::INFO::[__init__:961] /root/.sabnzbd/admin/Rating.sab missing
2015-11-07 21:34:51,679::INFO::[scheduler:190] Setting schedule for midnight BPS reset
2015-11-07 21:34:51,679::INFO::[downloader:241] Resuming
2015-11-07 21:34:51,689::INFO::[__init__:348] All processes started
2015-11-07 21:34:51,690::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Glitter
2015-11-07 21:34:51,690::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Config
2015-11-07 21:34:51,701::INFO::[SABnzbd:483] _yenc module... found!
2015-11-07 21:34:51,701::INFO::[SABnzbd:491] par2 binary... found (/usr/bin/par2)
2015-11-07 21:34:51,701::INFO::[SABnzbd:496] par2-classic binary... found (/usr/bin/par2)
2015-11-07 21:34:51,701::INFO::[SABnzbd:499] unrar binary... found (/usr/bin/unrar)
2015-11-07 21:34:51,701::INFO::[SABnzbd:504] unzip binary... found (/usr/bin/unzip)
2015-11-07 21:34:51,701::INFO::[SABnzbd:510] 7za binary... found (/usr/bin/7za)
2015-11-07 21:34:51,702::INFO::[SABnzbd:517] nice binary... found (/usr/bin/nice)
2015-11-07 21:34:51,702::INFO::[SABnzbd:521] ionice binary... found (/usr/bin/ionice)
2015-11-07 21:34:51,702::INFO::[SABnzbd:526] pyOpenSSL... found (True)
2015-11-07 21:34:51,702::INFO::[SABnzbd:1358] SSL version OpenSSL 1.0.1e-fips 11 Feb 2013
2015-11-07 21:34:51,702::INFO::[SABnzbd:1359] SSL potentially supported protocols ['SSLv2', 'SSLv23', 'SSLv3', 'TLSv1']
2015-11-07 21:34:51,702::INFO::[SABnzbd:1360] SSL actually supported protocols ['t1', 'v23', 'v3', 'v2']
2015-11-07 21:34:51,704::INFO::[SABnzbd:1506] Starting web-interface on 127.0.0.1:8080
2015-11-07 21:34:51,704::INFO::[_cplogging:216] [07/Nov/2015:21:34:51] ENGINE Bus STARTING
2015-11-07 21:34:51,707::INFO::[_cplogging:216] [07/Nov/2015:21:34:51] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-11-07 21:34:51,808::INFO::[_cplogging:216] [07/Nov/2015:21:34:51] ENGINE Serving on http://127.0.0.1:8080
2015-11-07 21:34:51,809::INFO::[_cplogging:216] [07/Nov/2015:21:34:51] ENGINE Bus STARTED
2015-11-07 21:34:51,810::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2015-11-07 21:34:51,810::INFO::[panic:265] Launching browser with http://127.0.0.1:8080/sabnzbd
2015-11-07 21:34:52,311::INFO::[SABnzbd:1578] Starting SABnzbd.py-0.8.x
2015-11-07 21:34:52,314::INFO::[dirscanner:302] Dirscanner starting up
2015-11-07 21:34:52,315::INFO::[urlgrabber:69] URLGrabber starting up

Trying "python SABnzbd.py -s 0.0.0.0" yields to 

2015-11-07 21:35:53,072::INFO::[SABnzbd:1238] --------------------------------
2015-11-07 21:35:53,072::INFO::[SABnzbd:1239] SABnzbd.py-0.8.x (rev=unknown)
2015-11-07 21:35:53,073::INFO::[SABnzbd:1251] Platform = posix
2015-11-07 21:35:53,073::INFO::[SABnzbd:1252] Python-version = 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
2015-11-07 21:35:53,073::INFO::[SABnzbd:1253] Arguments = /var/www/html/sabnzbd/SABnzbd.py -s 0.0.0.0
2015-11-07 21:35:53,073::INFO::[SABnzbd:1298] Read INI file /root/.sabnzbd/sabnzbd.ini
2015-11-07 21:35:53,082::INFO::[__init__:958] Loading data for rss_data.sab from /root/.sabnzbd/admin/rss_data.sab
2015-11-07 21:35:53,082::INFO::[__init__:958] Loading data for totals10.sab from /root/.sabnzbd/admin/totals10.sab
2015-11-07 21:35:53,082::INFO::[__init__:961] /root/.sabnzbd/admin/totals10.sab missing
2015-11-07 21:35:53,082::INFO::[__init__:958] Loading data for totals9.sab from /root/.sabnzbd/admin/totals9.sab
2015-11-07 21:35:53,082::INFO::[__init__:961] /root/.sabnzbd/admin/totals9.sab missing
2015-11-07 21:35:53,089::INFO::[postproc:89] Loading postproc queue
2015-11-07 21:35:53,089::INFO::[__init__:958] Loading data for postproc2.sab from /root/.sabnzbd/admin/postproc2.sab
2015-11-07 21:35:53,090::INFO::[__init__:958] Loading data for queue10.sab from /root/.sabnzbd/admin/queue10.sab
2015-11-07 21:35:53,090::INFO::[__init__:958] Loading data for watched_data2.sab from /root/.sabnzbd/admin/watched_data2.sab
2015-11-07 21:35:53,091::INFO::[__init__:958] Loading data for Rating.sab from /root/.sabnzbd/admin/Rating.sab
2015-11-07 21:35:53,091::INFO::[__init__:961] /root/.sabnzbd/admin/Rating.sab missing
2015-11-07 21:35:53,091::INFO::[scheduler:190] Setting schedule for midnight BPS reset
2015-11-07 21:35:53,092::INFO::[downloader:241] Resuming
2015-11-07 21:35:53,103::INFO::[__init__:348] All processes started
2015-11-07 21:35:53,104::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Glitter
2015-11-07 21:35:53,104::INFO::[SABnzbd:355] Web dir is /var/www/html/sabnzbd/interfaces/Config
2015-11-07 21:35:53,115::INFO::[SABnzbd:483] _yenc module... found!
2015-11-07 21:35:53,115::INFO::[SABnzbd:491] par2 binary... found (/usr/bin/par2)
2015-11-07 21:35:53,116::INFO::[SABnzbd:496] par2-classic binary... found (/usr/bin/par2)
2015-11-07 21:35:53,116::INFO::[SABnzbd:499] unrar binary... found (/usr/bin/unrar)
2015-11-07 21:35:53,116::INFO::[SABnzbd:504] unzip binary... found (/usr/bin/unzip)
2015-11-07 21:35:53,116::INFO::[SABnzbd:510] 7za binary... found (/usr/bin/7za)
2015-11-07 21:35:53,116::INFO::[SABnzbd:517] nice binary... found (/usr/bin/nice)
2015-11-07 21:35:53,116::INFO::[SABnzbd:521] ionice binary... found (/usr/bin/ionice)
2015-11-07 21:35:53,116::INFO::[SABnzbd:526] pyOpenSSL... found (True)
2015-11-07 21:35:53,117::INFO::[SABnzbd:1358] SSL version OpenSSL 1.0.1e-fips 11 Feb 2013
2015-11-07 21:35:53,117::INFO::[SABnzbd:1359] SSL potentially supported protocols ['SSLv2', 'SSLv23', 'SSLv3', 'TLSv1']
2015-11-07 21:35:53,117::INFO::[SABnzbd:1360] SSL actually supported protocols ['t1', 'v23', 'v3', 'v2']
2015-11-07 21:35:53,119::INFO::[SABnzbd:1506] Starting web-interface on 0.0.0.0:8080
2015-11-07 21:35:53,120::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Bus STARTING
2015-11-07 21:35:53,122::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-11-07 21:35:53,124::ERROR::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/var/www/html/sabnzbd/cherrypy/process/servers.py", line 206, in _start_http_thread
    self.httpserver.start()
  File "/var/www/html/sabnzbd/cherrypy/wsgiserver/wsgiserver2.py", line 1973, in start
    raise socket.error(msg)
error: No socket could be created -- (('::1', 8080, 0, 0): [Errno 99] Cannot assign requested address)

2015-11-07 21:35:53,124::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Bus STOPPING
2015-11-07 21:35:53,124::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::1', 8080)) already shut down
2015-11-07 21:35:53,125::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE HTTP Server None already shut down
2015-11-07 21:35:53,125::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Stopped thread '_TimeoutMonitor'.
2015-11-07 21:35:53,125::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Bus STOPPED
2015-11-07 21:35:53,125::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Bus EXITING
2015-11-07 21:35:53,125::INFO::[_cplogging:216] [07/Nov/2015:21:35:53] ENGINE Bus EXITED

I therefore conclude that something has changed in python with the last centos update.  The site from where I followed the instructions carefully has no mention of such issue.

**Comment by thezoggy** [comment]
the error points you to your problem:
` error: No socket could be created -- (('::1', 8080, 0, 0): [Errno 99] Cannot assign requested address)`

your trying to start sab on 0.0.0.0... 
` 2015-11-07 21:35:53,073::INFO::[SABnzbd:1253] Arguments = /var/www/html/sabnzbd/SABnzbd.py -s 0.0.0.0`

from the wiki:

* 127.0.0.1 or [::1] or localhost = Access from this computer only

* empty = Finds and listens on your local (ipv4) ip address. Used for accessing from other computers. localhost will not work anymore so update your bookmarks.

* 0.0.0.0 = Listens on multiple interfaces (both local IP and localhost). Recommended if you are not running vista. Vista prefers ipv6 so your ipv4 ip address (192.168.x.x) won't work which means forwarding the ports may not work. Note for Ubuntu users on Karmic (9.10): if 0.0.0.0 doesn't seem to work for you, try the actual internal or external IP you want to use.

**Comment by lpallard1** [comment]
Totally agree with you, removing the "-s 0.0.0.0" alltogether fixes the issue.  I guess thats what happens when you follow the instructions of someone pretenting everything works on their end..

This is good to know though, because I didnt know SAB could run on specific IP's.. That would have saved me some hassle in the past with a different setup.

Thanks for pointing that out thezoggy!
