### ISSUE TITLE
AttributeError: '_ThreadData' object has no attribute 'history_db'

### ISSUE THREAD

**Issue by YipYup** [sabnzbd/sabnzbd#473]
v1.0.0 RC1
Ubuntu LTS 14.04 64-bits

[14/Feb/2016:10:19:04] HTTP Traceback (most recent call last): File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond response.body = self.handler() File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 217, in __call__ self.body = self.oldhandler(*args, **kwargs) File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 61, in __call__ return self.callable(*self.args, **self.kwargs) File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 471, in scriptlog history_db = cherrypy.thread_data.history_db AttributeError: '_ThreadData' object has no attribute 'history_db'

**Comment by YipYup** [comment]
I got this again when selecting to "retry" a download. I did not choose a supplemental nzb file.

URL hit: http://sabnzbd.sspgs.ut.usa.fed.geektoast.net/sabnzbd/history/retry_pp

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1034, in retry_pp
    retry_job(kwargs.get('job'), kwargs.get('nzbfile'), kwargs.get('password'))
  File "/usr/share/sabnzbdplus/sabnzbd/api.py", line 1577, in retry_job
    history_db = cherrypy.thread_data.history_db
AttributeError: '_ThreadData' object has no attribute 'history_db'
Powered by CherryPy 3.8.0

**Comment by shypike** [comment]
Must be some race condition. We're already looking into this.
Trying the action again solves the problem?

**Comment by shypike** [comment]
Should be fixed by a3bed4689f14c05b3580a8c50e4327970e4c7369
