### ISSUE TITLE
Does anyone know what problem this is?

### ISSUE THREAD

**Issue by zeon** [sabnzbd/sabnzbd#485]
The symptom was that I could never fetch the nzb file from my index site and I found this error is filled up in my log.

	
[18/Feb/2016:07:00:27] Traceback (most recent call last): File "/share/MD0_DATA/.qpkg/SABnzbdplus/cherrypy/_cprequest.py", line 98, in run hook() File "/share/MD0_DATA/.qpkg/SABnzbdplus/cherrypy/_cprequest.py", line 58, in __call__ return self.callback(**self.kwargs) File "/share/MD0_DATA/.qpkg/SABnzbdplus/cherrypy/lib/auth.py", line 58, in basic_auth if check_auth(users, encrypt): File "/share/MD0_DATA/.qpkg/SABnzbdplus/cherrypy/lib/auth.py", line 10, in check_auth ah = httpauth.parseAuthorization(cherrypy.request.headers['authorization']) File "/share/MD0_DATA/.qpkg/SABnzbdplus/cherrypy/lib/httpauth.py", line 180, in parseAuthorization parser = AUTH_SCHEMES[auth_scheme] KeyError: 'ntlm'

**Comment by thezoggy** [comment]
what version of sabnzbd? where did you get it from (package manager? looks like a nas?) is there more log messages? happen after restart? etc etc etc

**Comment by shypike** [comment]
@zeon It looks like your indexer requires NTLM login ,which is very unusual for a web server and isn't supported by SABnzbd. Which indexer is it?

**Comment by zeon** [comment]
It's omgwtfnzbs and I just checked and found out my vip is expired. Sorry my bad. Case closed
