### ISSUE TITLE
HTTP Server crash

### ISSUE THREAD

**Issue by DamnDam** [sabnzbd/sabnzbd#50]
The http server crashes about once a day here. Here is the log dump :

    2012-08-21 08:00:00,007::INFO::[downloader:252] Bandwidth limit set to 1024
    2012-08-21 14:00:00,005::INFO::[downloader:252] Bandwidth limit set to 512
    2012-08-22 02:00:00,000::INFO::[downloader:252] Bandwidth limit set to 0
    2012-08-22 08:00:00,002::INFO::[downloader:252] Bandwidth limit set to 1024
    2012-08-22 14:00:00,003::INFO::[downloader:252] Bandwidth limit set to 512
    2012-08-22 17:50:57,547::ERROR::[_cplogging:55] [22/Aug/2012:17:50:57] ENGINE Error in HTTP server: shutting down
    Traceback (most recent call last):
      File "/cfg/sabnzbd/cherrypy/process/servers.py", line 75, in _start_http_thread
      File "/cfg/sabnzbd/cherrypy/wsgiserver/__init__.py", line 1655, in start
        self.tick()
      File "/cfg/sabnzbd/cherrypy/wsgiserver/__init__.py", line 1703, in tick
        s, addr = self.socket.accept()
      File "<string>", line 4, in accept
      File "/usr/lib/python2.7/socket.py", line 202, in accept
    error: [Errno 24] Trop de fichiers ouverts

(Translation from french: [Errno 24] Too many open files)

**Comment by wamatt** [comment]
```log
2015-04-25 22:15:48,276::ERROR::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/process/servers.py", line 75, in _start_http_thread
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/wsgiserver/__init__.py", line 1655, in start
    self.tick()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/wsgiserver/__init__.py", line 1703, in tick
    s, addr = self.socket.accept()
  File "<string>", line 4, in accept
  File "/usr/local/python/lib/python2.7/socket.py", line 202, in accept
error: [Errno 24] Too many open files

2015-04-25 22:15:48,277::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Bus STOPPING
2015-04-25 22:15:48,279::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
2015-04-25 22:15:48,307::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
2015-04-25 22:15:48,349::ERROR::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/process/servers.py", line 75, in _start_http_thread
    self.httpserver.start()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/wsgiserver/__init__.py", line 1655, in start
    self.tick()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/wsgiserver/__init__.py", line 1703, in tick
    s, addr = self.socket.accept()
  File "/usr/local/python/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 24] Too many open files

2015-04-25 22:15:48,351::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Bus STOPPING
2015-04-25 22:15:48,352::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) already shut down
2015-04-25 22:15:48,353::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) already shut down
2015-04-25 22:15:48,355::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Stopped thread '_TimeoutMonitor'.
2015-04-25 22:15:48,357::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Bus STOPPED
2015-04-25 22:15:48,358::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Bus EXITING
2015-04-25 22:15:48,359::INFO::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Bus EXITED
2015-04-25 22:15:48,403::ERROR::[_cplogging:55] [25/Apr/2015:22:15:48] ENGINE Error in 'stop' listener <bound method _TimeoutMonitor.stop of <cherrypy._TimeoutMonitor object at 0x7f61ceaa6190>>
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/process/wspbus.py", line 147, in publish
    output.append(listener(*args, **kwargs))
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/cherrypy/process/plugins.py", line 411, in stop
    self.thread.join()
AttributeError: 'NoneType' object has no attribute 'join'
```

fwiw I'm having the same issue (frequent crashes). Synology DS1511+ and SABnzbd `0.7.20`. Also use Sickbeard and CouchPotato.

I've now set ulimit to 10240 as per @hsrawat suggestion, and will wait and see, if that solves it.

**Comment by wamatt** [comment]
So changing the ulimit didn't really help. As others said, the issue started happening when I enabled HTTPS only. 

The API is also used with Sickbeard and Couch

**Comment by hsrawat** [comment]
setting ulimit -n will only delay the symptom. Wondering if you are hitting this issue.
https://bitbucket.org/cherrypy/cherrypy/issue/1286/frequent-cherrypy-webserver-restart-lead

**Comment by wamatt** [comment]
@hsrawat looks promising. Any luck getting it committed to CherryPy?

**Comment by hsrawat** [comment]
I @wamatt Not sure how to push team Cherrypy. I have been using this patch for more than one year now. Unless you think I should be able to commit.

**Comment by Safihre** [comment]
Any update on this? @hsrawat or @wamatt, these issues still occur?

**Comment by wamatt** [comment]
@Safihre I'm not sure as I've been using nzbget more recently, sorry!
