### ISSUE TITLE
Problems in case of non-UTF-8 LANG & special characters in filenames

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#543]
**Short**

if LANG is something without UTF-8 (check with ```locale``` command), and there are special characters in the filenames unpacked, SABnzbd will give errors.
Workaround: set LANG to something valid with UTF-8
Proposal: Let SABnzbd detect & warn

**Long**

See https://forums.sabnzbd.org/viewtopic.php?f=11&t=19713&start=60#p105492

So: if LANG is something without UTF-8, and there are special characters in the filenames unpacked, SABnzbd will give errors like:
```
2016-04-10 15:01:33,800::INFO::[postproc:520] Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sabnzbd/postproc.py", line 354, in process_job
    unpack_error, newfiles = unpack_magic(nzo, short_path(workdir), short_complete, flag_delete, one_folder, (), (), (), (), ())
  File "/usr/local/lib/python2.7/site-packages/sabnzbd/newsunpack.py", line 270, in unpack_magic
    xjoinables, xzips, xrars, xsevens, xts, depth)
  File "/usr/local/lib/python2.7/site-packages/sabnzbd/newsunpack.py", line 208, in unpack_magic
    xjoinables, xzips, xrars, xsevens, xts = build_filelists(workdir, workdir_complete)
  File "/usr/local/lib/python2.7/site-packages/sabnzbd/newsunpack.py", line 1616, in build_filelists
    for root, dirs, files in os.walk(workdir_complete):
  File "/usr/local/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 36: invalid continuation byte
```
or
```
ERROR: write error ( /home/sander/Downloads/complete/_UNPACK_Special filenames SQJ/stuff-to-be-uploaded/????? ??? ?? ???? ??.bin)
```

Easy to reproduce (on Linux and FreeBSD, and maybe OSX):
```
LANG= ./SABnzbd.py
```
and then download a post with special character filenames in it (like https://www.binsearch.info/index.php?q=Special+filenames+SQJ )

Solution outside SABnzbd:
```
LANG=en_US.utf8 ./SABnzbd.py
```
I don't know the solution inside SABnzbd; In SABnzbd.py there is already this code:
```
# Make sure UTF-8 is default 8bit encoding
if not hasattr(sys, "setdefaultencoding"):
    reload(sys)
try:
    sys.setdefaultencoding('utf-8')
except:
    print 'Sorry, you MUST add the SABnzbd folder to the PYTHONPATH environment variable'
    print 'or find another way to force Python to use UTF-8 for string encoding.'
    sys.exit(1)
```
and
```
import locale
import __builtin__
try:
    locale.setlocale(locale.LC_ALL, "")
    __builtin__.__dict__['codepage'] = locale.getlocale()[1] or 'cp1252'
except:
    # Work-around for Python-ports with bad "locale" support
    __builtin__.__dict__['codepage'] = 'cp1252'
```
but that doesn't seem to work: 
With ```LANG=``` the logging (for which I added a line) says:
```
2016-04-12 21:03:03,048::DEBUG::[SABnzbd:1371] Preferred Encoding is ANSI_X3.4-1968
```
... so the ```sys.setdefaultencoding('utf-8')``` didn't work, did it?

So:
1) I don't know the solution within SABnzbd
2) A warning + instruction within SABnzbd (+ in the FAQ) could be useful

**Comment by thezoggy** [comment]
1) solution came from sickbeard which has been in use for many years now without issues...
https://github.com/midgetspy/Sick-Beard/blob/development/SickBeard.py#L179

2) the print message should tell people enough?

**Comment by Safihre** [comment]
But the solution and print message doesn't seem to be working? At least for this guy and Sander it let's it run Sab anyway.. Changing the setting from within Sab isn't possible?

**Comment by shypike** [comment]
@thezoggy What do you mean?
a) The solution in SABnzbd comes from SickBeard
b) SickBeard has a working solution which SABnzbd could implement

**Comment by sanderjo** [comment]
Are we sure it works within/for Sickbeard? I will create a real test, but so far the results don't look good:

I get
```
sander@haring:~/encoding$ python someencoding.py
UTF-8
sander@haring:~/encoding$ LANG= python someencoding.py
ANSI_X3.4-1968
```

based on this code based on the sickbeard snippet:
```
sander@haring:~/encoding$ cat someencoding.py
import sys,locale

if True:
    someencoding = None

    try:
        locale.setlocale(locale.LC_ALL, "")
        someencoding = locale.getpreferredencoding()
    except (locale.Error, IOError):
        pass

    # For OSes that are poorly configured I'll just randomly force UTF-8
    if not someencoding or someencoding in ('ANSI_X3.4-1968', 'US-ASCII', 'ASCII'):
        someencoding = 'UTF-8'

    if not hasattr(sys, "setdefaultencoding"):
        reload(sys)

    try:
        # pylint: disable=E1101
        # On non-unicode builds this will raise an AttributeError, if encoding type is not valid it throws a LookupError
        sys.setdefaultencoding(someencoding)
    except:
        sys.exit("Sorry, you MUST add the Sick Beard folder to the PYTHONPATH environment variable\n" +
            "or find another way to force Python to use " + someencoding + " for string encoding.")

print locale.getpreferredencoding()
```

**Comment by thezoggy** [comment]
its worked for the past 5? years in sb..

**Comment by sanderjo** [comment]
Let's go to the basics.
First create setup:
```
dd if=/dev/urandom of=random-5MB.bin bs=1M count=5
mv random-5MB.bin 안녕하세요세계.bin
rar a Special-Korean-Characters -v10m m0 안녕하세요세계.bin
rm 안녕하세요세계.bin
```
And now this goes wrong (simulating a user setup where LANG has no UTF-8 setting):
```
$ LANG= unrar x Special-Korean-Characters.rar 

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from Special-Korean-Characters.rar

Cannot create ???????.bin
No such file or directory
No files to extract
```
General Python code to do a unrar:
```
import locale
from subprocess import call
print locale.getpreferredencoding() 
call(["unrar", "x", "Special-Korean-Characters.rar"])
```
leads the same error with LANG set to something without UTF-8:
```
$ LANG= python unp2.py 
ANSI_X3.4-1968

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from Special-Korean-Characters.rar

Cannot create ???????.bin
No such file or directory
No files to extract
```
So, the question is: how can we avoid that error, and thus override the LANG setting **within** Python?

I have not found a way to do that, but I understand @thezoggy says it can be done with the SIckbeard he's pointing to. So let's try that (and please post correct code if I didn't get it correctly):
```
import locale
from subprocess import call

# From Sickbeard:
import sys
if True:

    settingformerlyknownasSickbearSysEncoding = None

    try:
        locale.setlocale(locale.LC_ALL, "")
        settingformerlyknownasSickbearSysEncoding = locale.getpreferredencoding()
    except (locale.Error, IOError):
        pass

    # For OSes that are poorly configured I'll just randomly force UTF-8
    if not settingformerlyknownasSickbearSysEncoding or settingformerlyknownasSickbearSysEncoding in ('ANSI_X3.4-1968', 'US-ASCII', 'ASCII'):
        settingformerlyknownasSickbearSysEncoding = 'UTF-8'

    if not hasattr(sys, "setdefaultencoding"):
        reload(sys)

    try:
        # pylint: disable=E1101
        # On non-unicode builds this will raise an AttributeError, if encoding type is not valid it throws a LookupError
        sys.setdefaultencoding(settingformerlyknownasSickbearSysEncoding)
    except:
        sys.exit("Sorry, you MUST add the Sick Beard folder to the PYTHONPATH environment variable\n" +
            "or find another way to force Python to use " + settingformerlyknownasSickbearSysEncoding + " for string encoding.")
# /Sickbeard

print locale.getpreferredencoding() 
call(["unrar", "x", "Special-Korean-Characters.rar"])
```
Let's try out:
```
$ LANG= python unp3.py 
ANSI_X3.4-1968

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from Special-Korean-Characters.rar

Cannot create ???????.bin
No such file or directory
No files to extract
```
So ... IMHO no solution with the Sickbeard Python code. Please correct me with Python code if I'm wrong.

**Comment by sanderjo** [comment]
A very brute-force override within the code: force-set LANG to something with UTF within the subprocess call. So if a user has a non-UTF setting in LANG, just override it within the external command call:
```
import locale
import subprocess
print locale.getpreferredencoding() 
print subprocess.Popen("LANG=en_US.utf8 unrar x Special-Korean-Characters.rar", shell=True, stdout=subprocess.PIPE).stdout.read()
```
... works:
```
$ LANG= python unp4.py 
ANSI_X3.4-1968

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from Special-Korean-Characters.rar

Extracting  안녕하세요세계.bin                                               OK 
All OK
```

Wow ... ugly, but it works.
A bit more environment aware: detect the first UTF-8 that is installed, and use that:
```
import locale
import subprocess
print locale.getpreferredencoding() 

firstUTFfound = subprocess.Popen("locale -a | grep utf8 | head -1", shell=True, stdout=subprocess.PIPE).stdout.read()
print "First UTF Found:", firstUTFfound
command = "LANG=" + firstUTFfound + " unrar x Special-Korean-Characters.rar"
print subprocess.Popen(command, shell=True, stdout=subprocess.PIPE).stdout.read()
```
result:
```
$ LANG= python unp5.py 
ANSI_X3.4-1968
First UTF Found: en_AG.utf8


UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from Special-Korean-Characters.rar

Extracting  안녕하세요세계.bin                                               OK 
All OK

```

**Comment by Safihre** [comment]
@sanderjo Can you see where the Sickbeard code goes wrong? Why does this line not do what it is supposed to do?
```python
         sys.setdefaultencoding(settingformerlyknownasSickbearSysEncoding)
```

**Comment by sanderjo** [comment]
@Safihre My hypothesis is that that Python call sys.setdefaultencoding() only works for plain Python calls, not for external commands.

**Comment by Safihre** [comment]
Guess it works because Sickbeard doesn't have to call external tools?

So what should we do? Can we re-start SABnzbd with that LANG parameter from within Python?
Or should we throw 
```
WARNING: System not running with UTF-8 encoding, downloads with non-latin characters in file names will fail
``` 
when 
```
 'utf' not in locale.getpreferredencoding() 
```

For example? If you never download something with UTF-8 characters, it's not a breaking problem..

**Comment by shypike** [comment]
It's indeed the external programs.
The problem is that, on Windows, the console doesn't really support UTF-8 and SABnzbd interprets output as if it is 8-bit ASCII in the local codepage. For Korean that is likely not correct.
Maybe we should try to check whether the captured names are in fact UTF-8 and not 8-bit codepage stuff. I think unrar always outputs UTF-8, but I'm not sure of par2. The latter's variants have different ways of dealing with names.

**Comment by sanderjo** [comment]
@shypike I was already working on that check ... but it doesn't work!

```
$ python what-kind-of-files-inside-that-rar.py 
filename: 안녕하세요세계.bin 25 UTF-8
filename: plain-characters.bin 20 ascii
```

But:
```
$ LANG= python what-kind-of-files-inside-that-rar.py 
filename: ???????.bin 11 ascii
filename: plain-characters.bin 20 ascii
```
... ouch!

**Comment by Safihre** [comment]
But in Sander's example it's not reading the output of unrar that fails, it's unrar _itself_ that fails to do it's job because it's started from a non-UTF-8 environment, right?
So what can we do about that.. the user's system is being weird..
And isn't this only a problem on Unix, not on OSX/Win?

**Comment by sanderjo** [comment]
This is code that does a forced LANG=...UTF-8 setting to read the contents of a rar file:
 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess

def whatisthisOLDdoesnotwork(s):
    if isinstance(s, str):
        print "ordinary string"
    elif isinstance(s, unicode):
        print "unicode string"
    else:
        print "not a string"

def whatisthis(s):
	try:
	    s.decode('ascii')
            return "ascii"
	except:
	    pass # print "Not Ascii"
	try:
	    s.decode('utf8')
	    return "UTF-8"
	except:
	    pass # print "Not UTF-8"
	return "don't know"


#command = "unrar lb Special-Korean-Characters.rar"

command = "unrar lb Special-Korean-and-Plain-Characters.rar"
firstUTFfound = subprocess.Popen("locale -a | grep utf8 | head -1", shell=True, stdout=subprocess.PIPE).stdout.read()
print "First UTF Found:", firstUTFfound
command = "LANG=" + firstUTFfound + command


allfiles = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE).stdout.read()
#print allfiles
for line in allfiles.split('\n'):
    filename = line.rstrip()
    if len(filename) > 0:
        print "filename:", filename, len(filename), whatisthis(filename)
```

**Comment by sanderjo** [comment]
Good:
```
$ unrar lb Special-German-Characters.rar 
gefühlsmäßig.bin

```
Not good:
```
$ LANG= unrar lb Special-German-Characters.rar 
gef?hlsm?ssig.bin
```
Hard-core setting of LANG to something with utf8 in it:
```
$ LANG=$(locale -a | grep utf8 | head -1) unrar lb Special-German-Characters.rar 
gefühlsmäßig.bin
```

**Comment by sanderjo** [comment]
I tested SAB 1.0.0 on Windows 7 ... and that does not look good for the Korean text:

Result:
```
18-04-2016  18:52    <DIR>          .
18-04-2016  18:52    <DIR>          ..
12-04-2016  20:11        10.485.760 gefühlsmäßig.bin
12-04-2016  20:16        10.485.760 PlainText.bin
12-04-2016  20:11        10.485.760 ????? ??? ?? ???? ??.bin
12-04-2016  20:11        10.485.760 ??????????.bin
```
The sabnzbd.log doesn't look good either:

```
2016-04-18 18:51:41,859::DEBUG::[assembler:366] file in rar file: stuff-to-be-uploaded/Ã”Ã­Ã¬Ã”Ã¡Â£Ã”Ã¡Ã§Ã”Ã¡Ã¦Ã”Ã¡â•£ Ã”Ã¡â•‘Ã”Ã¡Ã¼Ã”Ã¡Ã„ Ã”Ã¡Ã¼Ã”Ã¡Ã„ Ã”Ã¡Ã–Ã”Ã¡Ã¦Ã”Ã¡Ã¼Ã”Ã¡Ã– Ã”Ã¡Ã¼Ã”Ã¡Ã„.bin
2016-04-18 18:51:41,859::DEBUG::[assembler:366] file in rar file: stuff-to-be-uploaded/Ã½Ã²ÃªÃ™Ã Ã²ÃÃ²Ã¿Ã½Ã¤Â©Ã½ÃœÃ¶Ã™â–‘Â®Ã™â–“Ã²Ã½Ã—Ã Ã™Ã¯ÃªÃ™Ã¯Ã±.bin
2016-04-18 18:51:41,861::DEBUG::[assembler:366] file in rar file: stuff-to-be-uploaded/Ã”Ã­Ã¬Ã”Ã¡Â£Ã”Ã¡Ã§Ã”Ã¡Ã¦Ã”Ã¡â•£ Ã”Ã¡â•‘Ã”Ã¡Ã¼Ã”Ã¡Ã„ Ã”Ã¡Ã¼Ã”Ã¡Ã„ Ã”Ã¡Ã–Ã”Ã¡Ã¦Ã”Ã¡Ã¼Ã”Ã¡Ã– Ã”Ã¡Ã¼Ã”Ã¡Ã„.bin
2016-04-18 18:51:41,861::DEBUG::[assembler:366] file in rar file: stuff-to-be-uploaded/Ã½Ã²ÃªÃ™Ã Ã²ÃÃ²Ã¿Ã½Ã¤Â©Ã½ÃœÃ¶Ã™â–‘Â®Ã™â–“Ã²Ã½Ã—Ã Ã™Ã¯ÃªÃ™Ã¯Ã±.bin
```

python.exe tells ```cp1252``` for locale.getpreferredencoding(), which is enumerated here: http://www.cp1252.com/

**Comment by shypike** [comment]
We can force the LANG variable to a value and pass that to unrar.
But in my past experience, unrar always just used UTF-8 regardless of what the file system setting of the Linux system are. I may be mistaken, of course and maybe unrar changed over releases.
I'll look at this a bit later.

**Comment by thezoggy** [comment]
yes, the python env inside the app is different than the user env outside of the app.. so be careful on trying to 'replicate' what sab would be doing. i've never had windows shell do utf-8.. its always the cp1252.. but inside python its never had a problem doing utf-8.. 

because theres a difference from the filesystem being able to do unicode and the terminal/display showing unicode. hence.. making a unicode filename in explorer works, but listing the directory contents in cmd you see ? (font doesnt support the char).

**Comment by sanderjo** [comment]
The below worked and overwrote the empty "LANG=" (thus not UTF-8) of the environment, and resulted in correct Korean filenames:

```
import subprocess

#plain:
command = ['/usr/bin/unrar x Special-Korean-Characters.rar']

# LANG set to somthing with UTF-8
command = ['LANG=en_US.utf8 /usr/bin/unrar x Special-Korean-Characters.rar']

print "Command is", command

need_shell = True
if True:
    print "Go!"
    p = subprocess.Popen(command, shell=need_shell, stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    proc = p.stdout
    while 1:
        line = proc.readline()
        if not line:
            break
        print line.rstrip()
```

I tried to put it into SABNzbd.py resp newsunpack, but I can't get it working:

```
2016-04-18 21:02:03,156::DEBUG::[newsunpack:636] Analyzing rar file ... rar4 (or lower) signature found
2016-04-18 21:02:03,157::DEBUG::[newsunpack:637] Running unrar ['LANG=en_US.utf8 /usr/bin/unrar', 'x', '-idp', '-o-', '-or', '-p-', '/home/sander/Downloads/temp/files-with-special-characters.2/files-with-special-characters.part1.rar', '/home/sander/Downloads/complete/_UNPACK_files-with-special-characters/']
2016-04-18 21:02:03,177::ERROR::[newsunpack:489] Error "[Errno 2] No such file or directory" while running rar_unpack on files-with-special-characters
2016-04-18 21:02:03,177::DEBUG::[newsunpack:490] Traceback: 
Traceback (most recent call last):
  File "/home/sander/git/sabnzbd-12april2016/sabnzbd/newsunpack.py", line 479, in rar_unpack
    one_folder, nzo, rar_set, extraction_path)
  File "/home/sander/git/sabnzbd-12april2016/sabnzbd/newsunpack.py", line 571, in rar_extract
    fail, new_files, rars = rar_extract_core(rarfile, numrars, one_folder, nzo, setname, extraction_path, password)
  File "/home/sander/git/sabnzbd-12april2016/sabnzbd/newsunpack.py", line 640, in rar_extract_core
    startupinfo=stup, creationflags=creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2016-04-18 21:02:03,179::INFO::[newsunpack:258] Unrar finished on /home/sander/Downloads/temp/files-with-special-characters.2
```

... but see my next post.

**Comment by thezoggy** [comment]
yes, you have to be careful of double decode/encoding... otherwise you can easily end up with invalid paths...

**Comment by sanderjo** [comment]
My proposal: only log the locale.getpreferredencoding(), but do not try to fix.

Reason:
the problem only occurs if 1) no Unicode in LANG setting, AND 2) unicode characters in rar file (AND 3) Linux/Unix). That looks rare, and most of all: the user can set the LANG setting. 

So ... do not touch from within SABnzbd.

**Comment by sanderjo** [comment]
Reference downloads:

https://nzbindex.com/search/?q=Special-Characters--german-korean-braille

https://www.binsearch.info/index.php?q=Special-Characters--german-korean-braille&m=&max=25&adv_g=&adv_age=999&adv_sort=date&xminsize=&xmaxsize=&font=&postdate=

... with inside the RAR these files:

```
Braille-⡵⡶⡷⡸⡹⡺-signs.bin
Deutsch-ist-gefühlsmäßig.bin
Korean-안녕하세요세계-stuff.bin
```
