### ISSUE TITLE
1.0.1RC1 - EOFError: Illegal end of multipart body.

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#557]
This is from 1.0.1RC1 [4eb486d] on Debian using Glitter.

This happened when adding a ~5mb NZB.  I originally tried dragging and dropping and nothing happened, so then I browsed and selected it and nothing happened, so I did it a third time and finally it (caught up?) spit out these errors:

```	
ERROR 04/29/2016 08:09 [29/Apr/2016:08:09:48] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 540, in process
    proc(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 223, in process_multipart_form_data
    process_multipart(entity)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 215, in process_multipart
    part.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 538, in process
    self.default_proc()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 710, in default_proc
    self.file = self.read_into_file()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 725, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 651, in read_lines_to_boundary
    raise EOFError("Illegal end of multipart body.")
EOFError: Illegal end of multipart body.
ERROR 04/29/2016 08:09 [29/Apr/2016:08:09:46] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 540, in process
    proc(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 223, in process_multipart_form_data
    process_multipart(entity)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 215, in process_multipart
    part.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 538, in process
    self.default_proc()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 710, in default_proc
    self.file = self.read_into_file()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 725, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 651, in read_lines_to_boundary
    raise EOFError("Illegal end of multipart body.")
EOFError: Illegal end of multipart body.
ERROR 04/29/2016 08:09 [29/Apr/2016:08:09:45] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 540, in process
    proc(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 223, in process_multipart_form_data
    process_multipart(entity)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 215, in process_multipart
    part.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 538, in process
    self.default_proc()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 710, in default_proc
    self.file = self.read_into_file()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 725, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 651, in read_lines_to_boundary
    raise EOFError("Illegal end of multipart body.")
EOFError: Illegal end of multipart body.
```

3 attempts to add, so 3 errors, that makes sense.  I tried adding the same NZB to a 0.7.20 install on Windows 7 and it worked just fine.

So I went back to 1.0.1RC1 and enabled debug logging and re-added the NZB a fourth time and pulled the full rundown from the log:

```
2016-04-29 08:20:22,270::INFO::[_cplogging:216] [29/Apr/2016:08:20:22] HTTP 
Request Headers:
  AUTHORIZATION: Basic <snip>=
  COOKIE: ys-torrentGrid=<snip>
  Remote-Addr: <snip>
  Content-Length: 4858560
  USER-AGENT: <snip>
  CONNECTION: keep-alive
  REFERER: https://<snip>:1234/sabnzbd/
  X-REQUESTED-WITH: XMLHttpRequest
  DNT: 1
  HOST: <snip>:1234
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: multipart/form-data; boundary=---------------------------55001768913008
  ACCEPT-ENCODING: gzip, deflate, br
2016-04-29 08:20:22,270::ERROR::[_cplogging:216] [29/Apr/2016:08:20:22] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 540, in process
    proc(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 223, in process_multipart_form_data
    process_multipart(entity)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 215, in process_multipart
    part.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 538, in process
    self.default_proc()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 710, in default_proc
    self.file = self.read_into_file()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 725, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 651, in read_lines_to_boundary
    raise EOFError("Illegal end of multipart body.")
EOFError: Illegal end of multipart body.
```

**Comment by shypike** [comment]
Can you email the NZB to bugs@sabnzbd.org?
Please add the URL of this issue.
Did you use Add+Browse for the last log?
Which Debian and what kind of hardware are you using, also which web browser?

The trouble seems to lie in the CherryPy web framework we use, which was upgraded for 1.0.0

**Comment by albino1** [comment]
It turns out I'm getting it on several NZBs.  I've tried 4 or 5 now, including ones that I've previously downloaded just a couple of hours ago, and they're all giving the same error.  I pulled some small old test NZBs from last year and those seem to work.  This is a fresh install of SABnzbd, I only set it up a few hours ago, and the first 5+ downloads all worked just fine.

* I'm using the Add NZB button in the center of the page, then going to Browse -> Add.

* 64bit Debian Wheezy

* Intel Xeon E3-1245

* Firefox 46.0 on Windows 7.  I tried on Chrome 49 and got the same error.

* I tried restarting SAB from the GUI, but that didn't fix it.

Since it's happening on a bunch of NZBs, some of which worked only an hour ago, I'm thinking it's not NZB-specific, but something else.  I literally didn't change any settings between my last completed download and adding the next file.

**< 5 minutes later >**

It seems to have gone away now?  I've added a couple dozen NZBs, deleted them, then re-added them again in both Chrome and Firefox and they've all been successful -- including the one from the logs above that failed at least 10 times in a row in my earlier tests.

So whatever the problem was, it appears to have gone away.  I didn't change a single setting during all of this.

**Comment by thezoggy** [comment]
was your antivirus/firewall causing issues?

**Comment by albino1** [comment]
Nope, this was on a fresh install of Debian Wheezy with a fresh install of SAB 1.0.1RC1.

For what it's worth, I've since added a couple dozen more files over the last 2 days and other than that stretch where it happened 30+ times over the course of half an hour, it hasn't happened since.

I don't have any way to reproduce the problem since I have no idea what happened in the first place, so you can probably close this issue.  If it starts happening again I can re-open it, but I'm not even sure what more information I could give.
