### ISSUE TITLE
Upgraded to 1.0.2 Major Error

### ISSUE THREAD

**Issue by thorrrr** [sabnzbd/sabnzbd#575]
After upgrading to fix the too many connection error i am greeted with more errors

ALso still getting connection errors see [here ](https://dl.dropboxusercontent.com/u/92887/Faststone%20Capture/connections.jpg)

File "cherrypy\_cpwsgi.pyo", line 180, in trap
  File "cherrypy\_cpwsgi.pyo", line 99, in __call__
  File "cherrypy\_cpwsgi.pyo", line 410, in tail
  File "cherrypy\_cpwsgi.pyo", line 234, in __init__
  File "cherrypy\_cpwsgi.pyo", line 306, in run
  File "cherrypy\_cptree.pyo", line 132, in get_serving
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:07] ENGINE Error in 'acquire_thread' listener >
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "cherrypy\process\plugins.pyo", line 703, in acquire_thread
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:07]  Traceback (most recent call last):
  File "cherrypy\_cpwsgi.pyo", line 180, in trap
  File "cherrypy\_cpwsgi.pyo", line 99, in __call__
  File "cherrypy\_cpwsgi.pyo", line 410, in tail
  File "cherrypy\_cpwsgi.pyo", line 234, in __init__
  File "cherrypy\_cpwsgi.pyo", line 306, in run
  File "cherrypy\_cptree.pyo", line 132, in get_serving
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:07] ENGINE Error in 'acquire_thread' listener >
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "cherrypy\process\plugins.pyo", line 703, in acquire_thread
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:07]  Traceback (most recent call last):
  File "cherrypy\_cpwsgi.pyo", line 180, in trap
  File "cherrypy\_cpwsgi.pyo", line 99, in __call__
  File "cherrypy\_cpwsgi.pyo", line 410, in tail
  File "cherrypy\_cpwsgi.pyo", line 234, in __init__
  File "cherrypy\_cpwsgi.pyo", line 306, in run
  File "cherrypy\_cptree.pyo", line 132, in get_serving
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:07] ENGINE Error in 'acquire_thread' listener >
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "cherrypy\process\plugins.pyo", line 703, in acquire_thread
  File "cherrypy\process\wspbus.pyo", line 223, in publish
ChannelFailures: TypeError("'NoneType' object has no attribute '__getitem__'",)
ERROR 18/05/2016 11:53 [18/May/2016:11:53:03] ENGINE Error in 'start_thread' listener 
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "sabnzbd\__init__.pyo", line 203, in connect_db
  File "sabnzbd\database.pyo", line 53, in get_history_handle
  File "sabnzbd\database.pyo", line 83, in __init__
  File "sabnzbd\database.pyo", line 104, in connect
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR 18/05/2016 11:53 SQL Command Failed, see log
ERROR 18/05/2016 11:53 [18/May/2016:11:53:02] ENGINE Error in 'start_thread' listener 
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "sabnzbd\__init__.pyo", line 203, in connect_db
  File "sabnzbd\database.pyo", line 53, in get_history_handle
  File "sabnzbd\database.pyo", line 83, in __init__
  File "sabnzbd\database.pyo", line 104, in connect
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR 18/05/2016 11:53 SQL Command Failed, see log
ERROR 18/05/2016 11:53 [18/May/2016:11:53:01] ENGINE Error in 'start_thread' listener 
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 205, in publish
  File "sabnzbd\__init__.pyo", line 203, in connect_db
  File "sabnzbd\database.pyo", line 53, in get_history_handle
  File "sabnzbd\database.pyo", line 83, in __init__
  File "sabnzbd\database.pyo", line 104, in connect
TypeError: 'NoneType' object has no attribute '__getitem__'

Any ideas

**Comment by shypike** [comment]
The blunt method is to remove the history database file. It's in you user profile, look for history1.db.
Cannot remember this was reported earlier on Windows.

**Comment by shypike** [comment]
Possibly some odd startup scenario can create conditions for this to happen.
So far, the only thing we can do, is making the code more robust in case of unexpected events.
Will be done in 1.1.0Beta2.

**Comment by shypike** [comment]
Attempt to prevent this kind problems: commit 6c24a1c63074ea441eaffbf33c84a15a506b0f55
