### ISSUE TITLE
Version 1.x <-- i.e. any fails to load 

### ISSUE THREAD

**Issue by Waveform2** [sabnzbd/sabnzbd#589]
Long time user and happy to provide whatever you need to get a read on this it just bails with the option of terminate or console, ive been running 7.x and before every update flawlessly!

**Comment by shypike** [comment]
That's very little info to go on.
Operating system? What exactly shows on the screen?

**Comment by Waveform2** [comment]
As i said a window APPEARS saying terminate or console, click termiate it closes, click console it opens the unix console (Apple whatever). 

Thats as much info as i have as i know not how to give more if you tell me i will provide but on screen thats it.

**Comment by Waveform2** [comment]
PS I love your software it is awesome and ive never had an issue with any build till now ta d.

**Comment by shypike** [comment]
Assuming you're using Apple OS X.
Open Applications->Utilities->Terminal
Then type
```
/Applications/SABnzbd.app/Contents/MacOS/SABnzbd --console
```
Then hit Enter
Look for error messages in the resulting output.

**Comment by Waveform2** [comment]
predator:/ derek$ /Applications/SABnzbd.app/Contents/MacOS/SABnzbd --console
Traceback (most recent call last):
  File "/Applications/SABnzbd.app/Contents/Resources/__boot__.py", line 54, in <module>
    _run()
  File "/Applications/SABnzbd.app/Contents/Resources/__boot__.py", line 49, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/SABnzbd.app/Contents/Resources/SABnzbd.py", line 85, in <module>
    import sabnzbd
  File "sabnzbd/__init__.pyc", line 73, in <module>
  File "platform.pyc", line 809, in mac_ver
  File "platform.pyc", line 786, in _mac_ver_xml
  File "plistlib.pyc", line 78, in readPlist
  File "plistlib.pyc", line 401, in parse
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: dlopen(/Applications/SABnzbd.app/Contents/Resources/lib/python2.7/lib-dynload/pyexpat.so, 2): Symbol not found: _XML_SetHashSalt
  Referenced from: /Applications/SABnzbd.app/Contents/Resources/lib/python2.7/lib-dynload/pyexpat.so
  Expected in: /usr/lib/libexpat.1.dylib
 in /Applications/SABnzbd.app/Contents/Resources/lib/python2.7/lib-dynload/pyexpat.so
2016-06-12 13:25:21.999 SABnzbd[45436:2602341] SABnzbd+ Error

**Comment by Waveform2** [comment]
Thanks btw for the help

**Comment by Waveform2** [comment]
If you want me to run it via sudo or anything just say thnx derek

**Comment by thezoggy** [comment]
can you show us the output of: `python -V`

**Comment by Waveform2** [comment]
Python 2.7.10

**Comment by shypike** [comment]
Please try the Beta1 release of 1.1.0
