### ISSUE TITLE
CherryPy Errors - ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#595]
I've gotten something along these lines twice in the last few days, both times after having been away from SABnzbd for hours and while it was Paused.  When I click the tab it'll sometimes take a second and then popup a group of errors like the ones below.  The errors appear to be very old, but they suddenly appear in the GUI.  It's not reproducible in any way I can find.  The only thing I can think of is that maybe it's related to hybernating/resuming on a laptop and the connection getting interrupted to SAB and the CherryPy server, but honestly I have no idea.

1.0.2 [b7e2bd9] on Debian Wheezy using Glitter.

```python
2016-06-13 08:15:18,774::INFO::[__init__:941] Saving data for postproc2.sab in /home/<username>/.sabnzbd/admin/postproc2.sab
2016-06-13 12:05:28,566::ERROR::[_cplogging:216] [13/Jun/2016:12:05:28]  
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/lib/auth.py", line 65, in basic_auth
    if check_auth(users, encrypt):
  File "/usr/share/sabnzbdplus/cherrypy/lib/auth.py", line 11, in check_auth
    ah = httpauth.parseAuthorization(request.headers['authorization'])
  File "/usr/share/sabnzbdplus/cherrypy/lib/httpauth.py", line 183, in parseAuthorization
    params = parser(auth_params)
  File "/usr/share/sabnzbdplus/cherrypy/lib/httpauth.py", line 163, in _parseBasicAuthorization
    username, password = base64_decode(auth_params).split(":", 1)
ValueError: need more than 1 value to unpack
2016-06-13 12:05:28,580::INFO::[_cplogging:216] [13/Jun/2016:12:05:28] HTTP 
Request Headers:
  AUTHORIZATION: Basic <auth string>
  HOST: 123.45.67.54
  CONNECTION: close
  Remote-Addr: 98.76.54.32
2016-06-13 12:05:28,580::ERROR::[_cplogging:216] [13/Jun/2016:12:05:28] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 650, in respond
    self.hooks.run('on_start_resource')
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 114, in run
    raise exc
ValueError: need more than 1 value to unpack
2016-06-13 12:05:31,789::ERROR::[_cplogging:216] [13/Jun/2016:12:05:31]  
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/lib/auth.py", line 65, in basic_auth
    if check_auth(users, encrypt):
  File "/usr/share/sabnzbdplus/cherrypy/lib/auth.py", line 11, in check_auth
    ah = httpauth.parseAuthorization(request.headers['authorization'])
  File "/usr/share/sabnzbdplus/cherrypy/lib/httpauth.py", line 183, in parseAuthorization
    params = parser(auth_params)
  File "/usr/share/sabnzbdplus/cherrypy/lib/httpauth.py", line 163, in _parseBasicAuthorization
    username, password = base64_decode(auth_params).split(":", 1)
ValueError: need more than 1 value to unpack
2016-06-13 12:05:31,789::INFO::[_cplogging:216] [13/Jun/2016:12:05:31] HTTP 
Request Headers:
  AUTHORIZATION: Basic <auth string>
  HOST: 123.45.67.57
  CONNECTION: close
  Remote-Addr: 98.76.54.32
2016-06-13 12:05:31,790::ERROR::[_cplogging:216] [13/Jun/2016:12:05:31] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 650, in respond
    self.hooks.run('on_start_resource')
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 114, in run
    raise exc
ValueError: need more than 1 value to unpack
```

**Comment by shypike** [comment]
Are you using a username and password?
From the looks of it, it seems a clear bug in the CherryPy framework.

Maybe worth trying 1.1.0Beta1, which uses a more recent version of CherryPy (and allowed us to create a better login function).

**Comment by thezoggy** [comment]
@albino1 - you may want to change your pw since you posted your basic auth string...

**Comment by albino1** [comment]
@shypike I do use a username/password.  

In regards to updating, before posting the issue I tried doing an upgrade using `apt-get upgrade sabnbdplus` to see if it happened on the newer version as well, but that didn't find anything to upgrade.  Maybe I'm doing something wrong, but that's how I went from 1.0.1 to 1.0.2.  FWIW in my sources.list I have:

`deb http://ppa.launchpad.net/jcfp/ppa/ubuntu precise main`

@thezoggy I randomized that auth string before posting it, but you're right, why even tempt anyone, so I went ahead and removed it.  Thanks for looking out for me :)

**Comment by jcfp** [comment]
@albino1 you need to use _apt-get dist-upgrade_ rather than just upgrade or apt will hold stuff back if upgrading involves adding or removing packages.

**Comment by albino1** [comment]
Thanks @jcfp, but that gave me this error:

```
 # apt-get dist-upgrade sabnzbdplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  sabnzbdplus-theme-glitter sabnzbdplus-theme-plush sabnzbdplus-theme-smpl
The following packages will be upgraded:
  sabnzbdplus
1 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
Need to get 2,092 kB of archives.
After this operation, 82.9 kB disk space will be freed.
Do you want to continue [Y/n]? y
Err http://ppa.launchpad.net/jcfp/ppa/ubuntu/ precise/main sabnzbdplus all 1.0.2-0ubuntu1~jcfp2~precise
  404  Not Found
Failed to fetch http://ppa.launchpad.net/jcfp/ppa/ubuntu/pool/main/s/sabnzbdplus/sabnzbdplus_1.0.2-0ubuntu1~jcfp2~precise_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by jcfp** [comment]
That's just outdated repository information, did you forget to run _apt-get update_ ?

**Comment by albino1** [comment]
That worked, thanks!

Forgive my noobishness, but why did I need to run a system wide `apt-get update` before I can run just an update for a specific program like SAB?

**Comment by thezoggy** [comment]
because its not one package.. notice each theme was its own package.. 
`sabnzbdplus-theme-glitter sabnzbdplus-theme-plush sabnzbdplus-theme-smpl`

they were removed upon updating as jcfp now just combined it all so it keeps things simple and to eliminate people not updating the sab set of packaged by doing `sabnzbd*`

**Comment by albino1** [comment]
Ah, I see.  Thanks for the explanation.

**Comment by albino1** [comment]
Closing until the error appears in 1.1.0Beta1.
