### ISSUE TITLE
watched folder error

### ISSUE THREAD

**Issue by fnnf1** [sabnzbd/sabnzbd#603]
by click on the butten "watched folder read" than i get an error like this:

[18/Jun/2016:19:31:42] HTTP Traceback (most recent call last): File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/cherrypy/_cprequest.py", line 670, in respond response.body = self.handler() File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/cherrypy/lib/encoding.py", line 217, in __call__ self.body = self.oldhandler(*args, **kwargs) File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/cherrypy/_cpdispatch.py", line 61, in __call__ return self.callable(*self.args, **self.kwargs) File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/interface.py", line 450, in tapi return api_handler(kwargs) File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/api.py", line 105, in api_handler response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs) File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/api.py", line 675, in _api_watched_now sabnzbd.dirscanner.dirscan() File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/dirscanner.py", line 421, in dirscan DirScanner.do.scan() File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/dirscanner.py", line 400, in scan run_dir(dirscan_dir, None) File "/storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/sabnzbd/dirscanner.py", line 329, in run_dir if os.path.isdir(path) or path in self.ignored or filename[0] == '.': File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Generic.x86_64-6.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/genericpath.py", line 41, in isdir UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 18: ordinal not in range(128)

pls help me

**Comment by shypike** [comment]
What is your watched folder path?

**Comment by fnnf1** [comment]
my folder is on the same system but on an external drive.  i took a few nzb´s in the folder and it loads sometimes the nzb´s in to sabnzbd. sometimes it loads a half of files. but the error is always when i click the watched folder button.

sorry for my english :-)
