### ISSUE TITLE
AttributeError: 'module' object has no attribute '_urljoin' when deleting par2 files from NZB 

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#622]
SAB 1.1.0RC1 with Glitter

Paused SAB, add a NZB to SAB, clicked on "Edit NZB details", selected a few files, and clicked on "Remove all selected files" which results in the traceback below.

After that the selected files are still in the view, but a "forbidden" icon appears when I hover above them. And the total download size is smaller. So the it seems the files I wanted to delete are half-gone.

```
2016-07-12 08:51:32,155::INFO::[__init__:945] Saving data for queue10.sab in /home/sander/.sabnzbd/admin/queue10.sab
2016-07-12 08:52:04,955::INFO::[_cplogging:217] [12/Jul/2016:08:52:04] HTTP 
Request Headers:
  REFERER: http://127.0.0.1:8080/sabnzbd/
  HOST: 127.0.0.1:8080
  CONNECTION: keep-alive
  Remote-Addr: ::ffff:127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.8,nl;q=0.6
  ACCEPT-ENCODING: gzip, deflate, sdch
  COOKIE: session=2f91901a-9d8c-42e9-887e-4a74a6c70d55
2016-07-12 08:52:04,956::ERROR::[_cplogging:217] [12/Jul/2016:08:52:04] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 649, in default
    return self.bulk_operation(nzo_id, kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 803, in bulk_operation
    url = cherrypy._urljoin(self.__root, nzo_id)
AttributeError: 'module' object has no attribute '_urljoin'
```

![screenshot from 2016-07-12 08 53 31](https://cloud.githubusercontent.com/assets/1273502/16757843/9b277e94-480e-11e6-9f65-43c5df2cb9af.png)

**Comment by Safihre** [comment]
Already fixed:
https://github.com/Safihre/sabnzbd/commit/7383c47791563fb3dffb49c1b57634562eba0395

But didn't make a PR yet because still unsure if we're sticking with CherryPy 6 with it's new dependency on six.py? @shypike

**Comment by shypike** [comment]
@Safihre   We're sticking with CP6, I will add six as a module.
There's a reason one shouldn't use underscore-methods, so your fix is needed anyway.
