### ISSUE TITLE
Crash on load folder name with diachritics

### ISSUE THREAD

**Issue by axel584** [sabnzbd/sabnzbd#630]
When I start the program, i've got a crash : 

```
axel@axel-B85M-D2V:/usr/share/applications$ sabnzbdplus
Traceback (most recent call last):
  File "/usr/bin/sabnzbdplus", line 1884, in <module>
    main()
  File "/usr/bin/sabnzbdplus", line 1050, in main
    res, msg = config.read_config(inifile)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 31, in newFunction
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/config.py", line 687, in read_config
    return _read_config(path)
  File "/usr/share/sabnzbdplus/sabnzbd/config.py", line 735, in _read_config
    CFG = configobj.ConfigObj(lines, default_encoding='cp1252', encoding='cp1252')
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1399, in _handle_bom
    return self._decode(infile, self.encoding)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1517, in _decode
    infile[i] = line.decode(encoding)
  File "/usr/lib/python2.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 17: character maps to <undefined>

```

My config file contains some diacritics : 

```
(...)
download_dir = Elŝutujo/incomplete
size_limit = 0
enable_par_cleanup = 1
safe_postproc = 1
cache_dir = cache
complete_dir = Elŝutujo/complete
replace_illegal = 1
(...)
```

I think it's the "S circumflex" which make the crash.

I didn't have this problem with an old version (0.7), I just clone de git repository and try to launch it.

Thank you for your help,

Axel

**Comment by shypike** [comment]
Operating system?

**Comment by axel584** [comment]
Ubuntu 16.4

```
axel@axel-B85M-D2V:~$ uname -a
Linux axel-B85M-D2V 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by axel584** [comment]
I've solved the problem : it was an old configuration file with the last version of sabnzbd.
I've move the ~/.sabnzbd to ~/.sabnzbd-old and start again... and it's work.
