### ISSUE TITLE
'module' object has no attribute '_urljoin'

### ISSUE THREAD

**Issue by pmele** [sabnzbd/sabnzbd#631]
Web Interface page: /nzb/SABnzbd_nzo_WtNema/
Using Safari on Mac to -
Linux Mint 17.2
AMD 64
Version: 1.1.0RC1 [aa12e21]
Python: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014   [t1, v23, v3]
pyOpenSSL: 0.13
yEnc: Check

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 661, in default
    self.save_details(nzo_id, args, kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 778, in save_details
    raise dcRaiser(cherrypy._urljoin(self.__root, '../queue/'), {})
AttributeError: 'module' object has no attribute '_urljoin'
Powered by CherryPy 6.0.2

**Comment by Safihre** [comment]
Already fixed, RC2 came out yesterday that includes the fix. 

If you are using the JCFP repository it might take a tiny but more time before it's updated :)

**Comment by pmele** [comment]
What?  That was quick!  Haha - excellent

**Comment by sanderjo** [comment]
See here: https://github.com/sabnzbd/sabnzbd/issues/622
