### ISSUE TITLE
sab 1.1.0RC1 -- cherrypy timeout

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#635]
```
 [22/Jul/2016:15:35:42]  Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 183, in trap
    return func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 102, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 414, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 237, in __init__
    self.run()
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 353, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError
```

![sab](http://zoggy.net/firefox_2016-07-23_22-48-17.png)

logs already rolled.. so dont have much.. but pretty pointless block of error in glitter with little to no context..  also tracebacks in a ui is no good..

**Comment by thezoggy** [comment]
got access to the box.. ui only provides .log but the actual folder has log.#.. .. would be nice if glitter/ui could get to the next file...

so looking at the log I see a TON of these tracebacks.. at the first one:

```
2016-07-22 14:29:33,910::DEBUG::[downloader:811] Trigger planned server resume test.xennanews.com
2016-07-22 15:20:33,635::ERROR::[_cplogging:217] [22/Jul/2016:15:20:33]  Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 183, in trap
    return func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 102, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 414, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 237, in __init__
    self.run()
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 353, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

... same traceback repeating over and over ...

2016-07-22 15:35:42,839::ERROR::[_cplogging:217] [22/Jul/2016:15:35:42]  Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 183, in trap
    return func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 102, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 414, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 237, in __init__
    self.run()
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 353, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

2016-07-22 20:04:58,257::INFO::[__init__:650] Adding Girl.Meets.World.S03E08.HDTV.x264-W4F.nzb
```

so I'm guessing something got locked up on the box then it started working..

**Comment by thezoggy** [comment]
probably nothing really related to sab...  will auto close if I cant find anymore within the next few days
