### ISSUE TITLE
sab 1.1.0RC2 -- glitter erronous error

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#636]
error for saving admin folder reported in glitter, however everything worked just fine.
![sab](http://zoggy.net/firefox_2016-07-23_03-28-11.png)

havent dug into it, but I assume it error saved on the folder.. it retried/cleanuped folder and worked on the next time.. thus the error being reported is a little premature/pointless.

**Comment by thezoggy** [comment]
relevant log entries:
```
2016-07-23 03:26:22,174::DEBUG::[assembler:337] file in rar file: JWXJN8cPzMowm3Gs3u2MH2v1iNOPqx5J3D85BsAtBu.mkv
2016-07-23 03:26:22,174::INFO::[assembler:88] Decoding \\?\C:\Users\zoggy\downloads\incomplete\Mr.Robot.S02E03.eps2.1 k3rnel-\JWXJN8cPzMowm3Gs3u2MH2v1iNOPqx5J3D85BsAtBu.vol003+004.par2 yenc
2016-07-23 03:26:22,204::INFO::[assembler:88] Decoding \\?\C:\Users\zoggy\downloads\incomplete\Mr.Robot.S02E03.eps2.1 k3rnel-\JWXJN8cPzMowm3Gs3u2MH2v1iNOPqx5J3D85BsAtBu.vol001+002.par2 yenc
2016-07-23 03:26:22,210::ERROR::[__init__:892] Saving \\?\C:\Users\zoggy\downloads\incomplete\Mr.Robot.S02E03.eps2.1 k3rnel-\__ADMIN__\SABnzbd_nzo_wi7zd0 failed
2016-07-23 03:26:22,211::INFO::[__init__:893] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\__init__.pyo", line 882, in save_data
RuntimeError: dictionary changed size during iteration
2016-07-23 03:26:22,213::INFO::[__init__:945] Saving data for totals10.sab in C:\Users\zoggy\AppData\Local\sabnzbd\admin\totals10.sab
2016-07-23 03:26:22,246::INFO::[assembler:88] Decoding \\?\C:\Users\zoggy\downloads\incomplete\Mr.Robot.S02E03.eps2.1 k3rnel-\JWXJN8cPzMowm3Gs3u2MH2v1iNOPqx5J3D85BsAtBu.vol007+008.par2 yenc
2016-07-23 03:26:22,329::INFO::[__init__:936] \\?\C:\Users\zoggy\downloads\incomplete\Mr.Robot.S02E03.eps2.1 k3rnel-\__ADMIN__\SABnzbd_nzo_wi7zd0 removed
2016-07-23 03:26:22,331::INFO::[nzbqueue:251] Saving queue
2016-07-23 03:26:22,331::INFO::[__init__:945] Saving data for queue10.sab in C:\Users\zoggy\AppData\Local\sabnzbd\admin\queue10.sab
2016-07-23 03:26:22,332::INFO::[postproc:83] Saving postproc queue
```

**Comment by thezoggy** [comment]
so looks like it may be something more.. unexpected  mutable dict changes?

**Comment by shypike** [comment]
Lack of semaphores probably, will look into that.
Normal operation is not disturbed because everything is still in memory.
The next save may work fine.

**Comment by Safihre** [comment]
@shypike I am also getting it a few times during my testing now, this is with ```self.reset_all_try_lists() ``` instead of ```sabnzbd.NzbQueue.do.reset_all_try_lists() ```.
However there is no prospective_par2 in the log anywhere near these errors, so something else is doing the changes.
```
2016-08-09 14:03:22,757::INFO::[assembler:88] Decoding \\?\C:\SABnzbd\StarDrive.2.Linux-ACTiVATED\act-stardrive2linux.r10 yenc
2016-08-09 14:03:22,770::ERROR::[__init__:874] Saving \\?\C:\SABnzbd\StarDrive.2.Linux-ACTiVATED\__ADMIN__\SABnzbd_nzo_9w2gq3 failed
2016-08-09 14:03:22,773::INFO::[__init__:875] Traceback: 
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Documents\GitHub\sabnzbd\sabnzbd\__init__.py", line 864, in save_data
    pickler.dump(data)
RuntimeError: dictionary changed size during iteration
2016-08-09 14:03:22,785::INFO::[__init__:927] Saving data for totals10.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\totals10.sab
```
And then the **same** file again, 30 seconds later! 
Both are preceded by a decoding and then followed by saving of totals10.sab.
Coincidence? I'll keep testing.
```
2016-08-09 14:03:52,776::INFO::[assembler:88] Decoding \\?\C:\SABnzbd\StarDrive.2.Linux-ACTiVATED\act-stardrive2linux.r21 yenc
2016-08-09 14:03:52,815::ERROR::[__init__:874] Saving \\?\C:\SABnzbd\StarDrive.2.Linux-ACTiVATED\__ADMIN__\SABnzbd_nzo_9w2gq3 failed
2016-08-09 14:03:52,844::INFO::[__init__:875] Traceback: 
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Documents\GitHub\sabnzbd\sabnzbd\__init__.py", line 864, in save_data
    pickler.dump(data)
RuntimeError: dictionary changed size during iteration
2016-08-09 14:03:52,854::INFO::[__init__:927] Saving data for totals10.sab in C:\Users\<USERNAME>\AppData\Local\sabnzbd\admin\totals10.sab
```

**Comment by shypike** [comment]
This is the totals file, which can in principle suffer from the same problem. Saving while being updated.
The dict change can only happen when a server is added (or a backup server is used for the first time).
I just don't understand why this didn't happen before.
In this case, the solution might be to just copy the dictionary before saving. The size is quite small.

**Comment by shypike** [comment]
Pushed this: c28a9ea1920197b101cf5c76d9e3c065e842fe30
