### ISSUE TITLE
Restarting crashed dirscanner

### ISSUE THREAD

**Issue by puzich** [sabnzbd/sabnzbd#644]
The dirscanner is always restarting. I thought, that the producing error is in the file watched_data2.sab and deleted it, but that isn't causing the issue. 

I'm using version 1.0.3 on my Synology NAS.

**Comment by Safihre** [comment]
Could you maybe set the logging to +Debug and then post the relevant log lines here when it happens?

**Comment by puzich** [comment]
I set it to +Debug, but the only lines I get are the following:

2016-08-06 12:28:30,250::INFO::[__init__:1072] Restarting crashed dirscanner
2016-08-06 12:28:30,251::INFO::[__init__:965] Loading data for watched_data2.sab from /usr/local/sabnzbd/var/admin/watched_data2.sab

I think, that isn't helping you 😩

**Comment by Safihre** [comment]
What did you set as your NZB scan directory? Does the folder exist?

Regarding the logging you need to set it to +Debug (like you did :) ), then wait for it to crash again and then download the log using the Download logging button. Only in the downloaded-log will be the traceback about why it actually crashed!

**Comment by puzich** [comment]
Indeed. The folder exists. I've set it again, to be sure. 
It worked perfectly, until I made an update from 0.7.x to the 1.0.3 version. 

Currently, I restarted SABnzbd to be sure, that I get the debug messaged. Below, they are, but for the dirscanner, there aren't any debug messages:

2016-08-06 12:37:07,124::INFO::[SABnzbd:1594] Starting SABnzbd.py-1.0.3
2016-08-06 12:37:07,125::DEBUG::[__init__:361] Starting postprocessor
2016-08-06 12:37:07,126::DEBUG::[__init__:364] Starting assembler
2016-08-06 12:37:07,127::DEBUG::[__init__:367] Starting downloader
2016-08-06 12:37:07,129::DEBUG::[scheduler:202] Starting scheduler
2016-08-06 12:37:07,131::DEBUG::[__init__:372] Starting dirscanner
2016-08-06 12:37:07,132::INFO::[dirscanner:302] Dirscanner starting up
2016-08-06 12:37:07,133::DEBUG::[__init__:377] Starting urlgrabber
2016-08-06 12:37:07,134::INFO::[urlgrabber:69] URLGrabber starting up
2016-08-06 12:37:40,184::INFO::[__init__:1072] Restarting crashed dirscanner
2016-08-06 12:37:40,186::INFO::[__init__:965] Loading data for watched_data2.sab from /usr/local/sabnzbd/var/admin/watched_data2.sab
2016-08-06 12:38:13,233::INFO::[__init__:1072] Restarting crashed dirscanner
2016-08-06 12:38:13,234::INFO::[__init__:965] Loading data for watched_data2.sab from /usr/local/sabnzbd/var/admin/watched_data2.sab

**Comment by Safihre** [comment]
Weird! Could you maybe try and create a new folder and switch the watched-dir to that folder?
Maybe there's some leftover NZB or filename the dirscanner is choking on. Is there anything in the watched-dir?

**Comment by puzich** [comment]
Very good idea! I changed the watched folder and it works again now. Thanks a lot!

But I don't know, which file in the old directory was causing this issue. But who cares... 😉

**Comment by Safihre** [comment]
So there are still files left in your old directory? Can you transfer them
one by one to the new directory and see which one causes the problem?
Would be helpful to us :)

**Comment by sanderjo** [comment]
Or, if there are too many files, do this:

Move half of the files out of the directory, let SAB run, see if the dirscanner crashes. If so, the faulty file is in the remaining files. Continue the process of moving half of the remaining files out.
If  dirscanner does not crash, swap the files. 'Hopefully' the dirscanner crashes. Continu the process likewise.

**Comment by sanderjo** [comment]
OK, I found it:

After reading the source sabnzbd/dirscanner.py, I can reproduce the problem: the good old `path = os.path.join(folder, filename)` combined with Unicode (as of SAB 1.0) and a non-Unicode NZB filename with a strange character (non-ASCII, with non-Unicode encoding)

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/sander/git/sabnzbd/sabnzbd/dirscanner.py", line 314, in run
    self.scan()
  File "/home/sander/git/sabnzbd/sabnzbd/dirscanner.py", line 400, in scan
    run_dir(dirscan_dir, None)
  File "/home/sander/git/sabnzbd/sabnzbd/dirscanner.py", line 328, in run_dir
    path = os.path.join(folder, filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 28: invalid start byte

2016-08-07 00:55:20,747::INFO::[__init__:945] Saving data for rss_data.sab in /home/sander/.sabnzbd/admin/rss_data.sab
2016-08-07 00:55:20,767::INFO::[rss:584] Finished scheduled RSS read-outs
2016-08-07 00:55:24,276::INFO::[__init__:1076] Restarting crashed dirscanner
```

Code to produce such a filename:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import shutil

doelfile = u"mein Freund der Baron von Münchhausen.nzb".encode('cp437')
shutil.copy("x.nzb",doelfile)
```

```
sander@flappie:~/Downloads/sab-watch$ ll
total 232
drwxrwxr-x   2 sander sander   4096 aug  7 00:58 ./
drwxr-xr-x 110 sander sander 135168 aug  6 21:01 ../
-rw-rw-r--   1 sander sander  91735 aug  7 00:54 mein Freund der Baron von M?nchhausen.nzb
s
```

Next step ... I don't know. In other threads this problem (non-ASCII, with non-Unicode encoding) appeared hard/impossible to solve.

**Comment by sanderjo** [comment]
I created a solution in dirscanner.py. I'll test it a bit more, and then release it.

**Comment by sanderjo** [comment]
@puzich 

Can you confirm or show the contents of your dirscan directory? Is there a file with strange characters?

**Comment by puzich** [comment]
Your guessing has been right. There are some directories with non-ascii characters in. On the linux command line, you see an question mark, but connected with smb or afp you see a asien character.

**Comment by sanderjo** [comment]
OK. 

One more check: in sabnzbd.log, can you find the line with `Preferred encoding =` and post what it says?

Example from my log:
```
2016-08-07 12:02:16,615::INFO::[SABnzbd:1337] Preferred encoding = UTF-8
```

**Comment by shypike** [comment]
@sanderjo  Please publish your solution. The dirscanner should not crash, not even on a poorly configured system.

**Comment by sanderjo** [comment]
@shypike Can you please first read https://github.com/sabnzbd/sabnzbd/issues/646 with possible solutions?

My current 'solution' is removing chars >= 128 from the file name. Which works, but maybe the other solutions (like downgrading path to ASCII-encoding) are better.

**Comment by puzich** [comment]
@sanderjo 
my encoding is the follwing:
`2016-08-06 22:55:22,473::INFO::[SABnzbd:1261] Preferred encoding = UTF-8`
