### ISSUE TITLE
Sabnzbd Error: " cannot find 'have_unzip' "

### ISSUE THREAD

**Issue by seanvree** [sabnzbd/sabnzbd#667]
Running Sabnzbd on Windows 10 Ent as a service.

I can get to the GUI and it's running and downloading, but when I click on config, I get this error:

Traceback (most recent call last): File "cherrypy_cprequest.pyo", line 670, in respond File "cherrypy\lib\encoding.pyo", line 220, in call File "cherrypy_cpdispatch.pyo", line 60, in call File "sabnzbd\interface.pyo", line 1281, in index File "Program_Filesx86_SABNZBd_interfaces_Config_templates_config_tmpl.py", line 258, in respond NotFound: cannot find 'have_unzip' Powered by CherryPy 6.0.2

**Comment by shypike** [comment]
How did you install SABnzbd?
It looks like you're mixing code and user interface templates from different releases.

**Comment by sanderjo** [comment]
Two parallel threads on the same subject? See https://forums.sabnzbd.org/viewtopic.php?f=2&t=21312

**Comment by Safihre** [comment]
And on Reddit too: https://m.reddit.com/r/usenet/comments/4zex3c/weird_error_in_sabnzbd/

**Comment by Safihre** [comment]
He fixed it:
https://m.reddit.com/r/usenet/comments/4zex3c/weird_error_in_sabnzbd/d6wevpw
Close this.
