### ISSUE TITLE
smtp2go -- Unknown authentication failure in mail server

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#694]
earlier tonight in the sab channel there was a user having problems with sab 1.1.0 on trying to send emails when using mail.smtp2go.com ( https://www.smtp2go.com/ ). he has two machines with sab on each, both have the same problem and each have different python versions installed:

`Python Version: 	2.7.12 (default, Jul 1 2016, 15:12:24) [GCC 5.4.0 20160609] [UTF-8]`
`Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2] [UTF-8]`

logs:
```
2016-10-01 01:37:29,014::INFO::[dirscanner:318] Dirscanner starting up
2016-10-01 01:37:29,016::DEBUG::[__init__:357] Starting urlgrabber
2016-10-01 01:37:29,026::INFO::[urlgrabber:71] URLGrabber starting up
2016-10-01 01:37:35,912::INFO::[apikey=<APIKEY>] Sending test email
2016-10-01 01:37:35,925::DEBUG::[emailer:77] Connecting to server mail.smtp2go.com:2525
2016-10-01 01:37:36,588::DEBUG::[emailer:90] Non-SSL mail server detected reconnecting to server mail.smtp2go.com:2525
2016-10-01 01:37:36,655::DEBUG::[emailer:104] TLS mail server detected
2016-10-01 01:37:36,777::ERROR::[emailer:37] Unknown authentication failure in mail server
```

when accessing the notify directly he could see the trace back:
```
2016-10-01 01:21:46,563::INFO::[_cplogging:217] [01/Oct/2016:01:21:46] HTTP 
Request Headers:
  REFERER: http://127.0.0.1:8085/sabnzbd/config/notify/
  HOST: 127.0.0.1:8085
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
2016-10-01 01:21:46,563::ERROR::[_cplogging:217] [01/Oct/2016:01:21:46] HTTP 
Traceback (most recent call last):
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/interface.py", line 514, in tapi
    return api_handler(kwargs)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/api.py", line 112, in api_handler
    response = _api_table.get(mode, (_api_undefined, 2))[0](name, output, kwargs)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/api.py", line 744, in _api_test_email
    test=kwargs)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/emailer.py", line 248, in endjob
    return send_with_template('email', parm, test)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/emailer.py", line 203, in send_with_template
    ret = send(message.respond(), recipient, test)
  File "/home/jblanton/Desktop/SABnzbd-1.1.0/sabnzbd/emailer.py", line 116, in send
    mailconn.login(email_account, email_pwd)
  File "/usr/lib/python2.7/smtplib.py", line 607, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "/usr/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
```

he believes it is due to:
http://bugs.python.org/issue5285

I had him try gmail and that worked..  says he does not have any unicode or anything funky for the email/pw being used for smtp2go.

**Comment by thezoggy** [comment]
just creating an issue here about it, in case we get others..

**Comment by joshuablanton** [comment]
Just to clarify, I didn't drop the try block. I commented out the following except portion:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/emailer.py#L122
In order to see the trace back.

I was able to get it to work by making the following change:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/emailer.py#L115
Line was modified to read as follows:
`mailconn.login(email_account.encode('utf-8'), email_pwd.encode('utf-8'))`

**Comment by Safihre** [comment]
@shypike is there any harm in utf8 encoding it by default?

**Comment by shypike** [comment]
It probably should have been done like that in the first place.

**Comment by thezoggy** [comment]
so it sounds like we should just encode the values before passing to the login.. 
we prob should validate that sending unicode data in to/from/username/pw/body/header is all okay.. 

really wish we had some test sets :(

**Comment by sanderjo** [comment]
On http://stackoverflow.com/a/20862445 I found this:

> As asked I'll post this as an answer. The error that you faced is a feature of Python's HMAC. It does not accept unicode. This feature is described here.
> 
> HMAC is a function which works at byte level. For this reason in Python 3 it accepts only bytes. In Python 2 we don't have bytes so it accepts only str.

So let's test some things:

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hmac

>>> hmac.new('key','msg')
<hmac.HMAC instance at 0x7fadda452fc8>

>>> hmac.new('key'.encode('utf-8'),'msg')
<hmac.HMAC instance at 0x7fadda452fc8>

>>> hmac.new(u'key','msg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

```
OK ... so encode(utf-8) is good, u'key' is bad ...

So if you have u'key', first encode('utf-8') it:
```
>>> hmac.new('key'.encode('utf-8'),'msg')
<hmac.HMAC instance at 0x7fadda452fc8>
```

On http://stackoverflow.com/a/13212528 I found this:

> "What is the difference between UTF-8 and Unicode?"
> 
> UTF-8 and Unicode cannot be compared. 
> Unicode is a character set used to translate characters into numbers.
> UTF-8 is an encoding used to translate numbers into binary data. 


HTH

**Comment by sanderjo** [comment]
PS: 

> I had him try gmail and that worked

**Hypothesis**: the user used an MX host of gmail.com (so gmail-smtp-in.l.google.com.), which does not require a username/password, which the user did not fill out in SABnzbd, so the ```if``` is False, and the mailconn.login() was not called, thus not raising the exception.

```
        # Authentication
        if (email_account != "") and (email_pwd != ""):
            try:
                mailconn.login(email_account, email_pwd)
```
