### ISSUE TITLE
Dragging a directory to the web ui causes error

### ISSUE THREAD

**Issue by OmgImAlexis** [sabnzbd/sabnzbd#765]
I was expecting it to just add all of the files inside of the dir but instead I got this.

```
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 1001, in process
    super(RequestBody, self).process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 558, in process
    proc(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 223, in process_multipart_form_data
    process_multipart(entity)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 215, in process_multipart
    part.process()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 556, in process
    self.default_proc()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 715, in default_proc
    self.file = self.read_into_file()
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 730, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "/usr/share/sabnzbdplus/cherrypy/_cpreqbody.py", line 669, in read_lines_to_boundary
    raise EOFError("Illegal end of multipart body.")
EOFError: Illegal end of multipart body.
```

**Comment by Safihre** [comment]
Uploading a directory seems to be specific to Chrome, think it's too much of a specific use case to implement.
Will just make sure it doesn't crash anymore on directories!
