### ISSUE TITLE
RSS fetch error

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#777]
Since update to 1.2.0 [1be50eb] I get this error:

```
2017-01-15 23:21:47,121::INFO::[_cplogging:219] [15/Jan/2017:23:21:47] HTTP 
Request Headers:
  REFERER: http://sabnzbd.xyz.private:8080/config/rss/
  HOST: sabnzbd.xyz.private:8080
  CONNECTION: keep-alive
  Remote-Addr: 192.168.123.75
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate
  COOKIE: login_cookie=ce9487...aff4d1; login_salt=312
2017-01-15 23:21:47,122::ERROR::[_cplogging:219] [15/Jan/2017:23:21:47] HTTP 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1985, in index
    ignoreFirst=self.__refresh_ignore, readout=readout)
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 71, in run_feed
    return __RSS.run_feed(feed, download, ignoreFirst, force=force, readout=readout)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 32, in newFunction
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/rss.py", line 308, in run_feed
    feed_parsed = feedparser.parse(uri.replace('feed://', 'http://'))
  File "/usr/share/sabnzbdplus/sabnzbd/utils/feedparser.py", line 4018, in parse
    saxparser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 341, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/usr/share/sabnzbdplus/sabnzbd/utils/feedparser.py", line 1850, in startElementNS
    self.unknown_starttag(localname, attrsD.items())
  File "/usr/share/sabnzbdplus/sabnzbd/utils/feedparser.py", line 674, in unknown_starttag
    return method(attrsD)
  File "/usr/share/sabnzbdplus/sabnzbd/utils/feedparser.py", line 1779, in _start_newznab_attr
    context['newznab'][attrsD['name']] = attrsD['value']
KeyError: 'value'
```

**Comment by Safihre** [comment]
Could you send me the feed URL you get this with to safihre@sabnzbd.org?

**Comment by ggzengel** [comment]
Thank you for your help.
I have applied your bugfix and it's working now.
Do you still need some info from me for enhancement because I have only a few RSS request per day and they are all used.

**Comment by Safihre** [comment]
No need for the RSS's anymore, thanks! Glad it's working.
