### ISSUE TITLE
Crashed Assembler

### ISSUE THREAD

**Issue by computerk** [sabnzbd/sabnzbd#782]
So I am running Sab on a VM windows server 2012 and it keeps crashing
Heres some +debug any ideas as what is happening?
```
2017-01-18 16:31:15,020::INFO::[_cplogging:219] [18/Jan/2017:16:31:15] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.1.23', 8080)) shut down
2017-01-18 16:31:15,020::INFO::[_cplogging:219] [18/Jan/2017:16:31:15] ENGINE Stopped thread '_TimeoutMonitor'.
2017-01-18 16:31:15,020::INFO::[_cplogging:219] [18/Jan/2017:16:31:15] ENGINE Bus STOPPED
2017-01-18 16:31:15,020::INFO::[_cplogging:219] [18/Jan/2017:16:31:15] ENGINE Bus EXITING
2017-01-18 16:31:15,020::INFO::[_cplogging:219] [18/Jan/2017:16:31:15] ENGINE Bus EXITED
2017-01-18 16:31:15,020::INFO::[__init__:390] SABnzbd shutting down...
2017-01-18 16:31:15,020::INFO::[urlgrabber:67] URLGrabber shutting down
2017-01-18 16:31:15,161::INFO::[dirscanner:307] Dirscanner shutting down
2017-01-18 16:31:16,688::INFO::[downloader:498] Shutting down
```

**Comment by Safihre** [comment]
We are aware of the problem, but still trying to figure it out.

Could you run this test-version of SABnzbd? It won't crash and it will show the warnings we need to fix things. It's a standalone version, so just shutdown your current SABnzbd and click `SABnzbd.exe`.
https://www.dropbox.com/s/ug84lj2vgcwffn7/SABnzbd-1.2.0TEST2-win32-bin.zip?dl=1

If you do get warnings, could you post them here?

**Comment by computerk** [comment]
So I ran this test build and didn't have any errors until I tried to move the incomplete folder outside of the VM Server , Here are my lerrors from that. Once I switched back to temp folder on host it was fine.

2017-01-19 07:26:37,907::WARNING::[assembler:384] Error during inspection of RAR-file Z:\ISENQ5~5\GC3NXP~E.1\girlfriends.guide.to.divorce.s03e02.1080p.web.x264-heat.r00
Traceback (most recent call last):
  File "sabnzbd\assembler.pyo", line 322, in check_encrypted_and_unwanted_files
  File "sabnzbd\utils\rarfile.pyo", line 667, in __init__
  File "sabnzbd\utils\rarfile.pyo", line 847, in _parse
  File "sabnzbd\utils\rarfile.pyo", line 385, in _get_rar_version
  File "sabnzbd\utils\rarfile.pyo", line 2407, in __init__
IOError: [Errno 2] No such file or directory: 'Z:\\ISENQ5~5\\GC3NXP~E.1\\girlfriends.guide.to.divorce.s03e02.1080p.web.x264-heat.r00'
2017-01-19 07:26:37,923::INFO::[assembler:87] Decoding \\?\Z:\incomplete\Girlfriends.Guide.to.Divorce.S03E02.1080p.WEB.x264-H.1\girlfriends.guide.to.divorce.s03e02.1080p.web.x264-heat.r01 yenc
2017-01-19 07:26:39,783::INFO::[assembler:87] Decoding \\?\Z:\incomplete\Girlfriends.Guide.to.Divorce.S03E02.1080p.WEB.x264-H.1\girlfriends.guide.to.divorce.s03e02.1080p.web.x264-heat.r02 yenc
2017-01-19 07:26:41,183::WARNING::[assembler:384] Error during inspection of RAR-file Z:\ISENQ5~5\GC3NXP~E.1\girlfriends.guide.to.divorce.s03e02.1080p.web.x264-heat.r02

**Comment by Safihre** [comment]
Thanks for trying!
Hope you're willing to test another version for me? I can't reproduce it on my own PC unfortunately.
https://www.dropbox.com/s/liv5qa3zf6wwju0/SABnzbd-1.2.0TEST3-win32-bin.zip?dl=1

It it works without problems also on the incomplete folder outside the VM, could you try to download [this encrypted post ](https://www.binsearch.info/?b=Test_d3wTVngAjyoOV9Ozy3NUQpwxB&g=alt.binaries.test&p=Yenc%40power-post.org+%28Yenc-PP-A%26A%29&max=250) and see if it correctly detects it as encrypted? 
If it doesn't detect it after 25% no need to download the rest, it's just some random encrypted post I found.

**Comment by computerk** [comment]
No problem so same results with new test_build, inside the VM fine outside no good.
I am installing vm tools on the server here to see if anything is of conccern there>

2017-01-19 08:56:34,490::INFO::[nzbqueue:258] Saving queue
2017-01-19 08:56:34,490::INFO::[__init__:970] Saving data for queue10.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\queue10.sab
2017-01-19 08:56:34,506::INFO::[postproc:85] Saving postproc queue
2017-01-19 08:56:34,506::INFO::[__init__:970] Saving data for postproc2.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\postproc2.sab
2017-01-19 08:56:34,520::INFO::[postproc:304] Starting Post-Processing on Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS => Repair:True, Unpack:True, Delete:True, Script:None, Cat:*
2017-01-19 08:56:34,536::INFO::[postproc:617] Starting verification and repair of Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS
2017-01-19 08:56:34,552::INFO::[__init__:927] \\?\Z:\incomplete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS\__ADMIN__\__verified__ missing
2017-01-19 08:56:34,552::INFO::[postproc:638] Running verification and repair on set jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.sample
2017-01-19 08:56:34,615::INFO::[newsunpack:981] Quick-check for jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.sample is OK, skipping repair
2017-01-19 08:56:34,631::INFO::[newsunpack:1055] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.sample.par2
2017-01-19 08:56:34,661::INFO::[postproc:638] Running verification and repair on set jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks
2017-01-19 08:56:34,693::INFO::[newsunpack:981] Quick-check for jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks is OK, skipping repair
2017-01-19 08:56:34,693::INFO::[newsunpack:1055] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.par2
2017-01-19 08:56:34,709::INFO::[postproc:712] Verification and repair finished for Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS
2017-01-19 08:56:34,723::INFO::[misc:835] Creating directories: \\?\C:\Users\Administrator\Downloads\complete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.1
2017-01-19 08:56:34,723::INFO::[postproc:376] Running unpack_magic on Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS
2017-01-19 08:56:35,338::INFO::[newsunpack:230] Unrar starting on Z:\ISENQ5~5\J7BQCW~G
2017-01-19 08:56:35,348::INFO::[newsunpack:452] Extracting rarfile Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.rar (belonging to jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks) to C:\Users\ADMINI~1\DOWNLO~1\complete\_UNPAC~1.1
2017-01-19 08:56:36,855::INFO::[assembler:87] Decoding \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\trumps.triumphant.year.2016.720p.hdtv.x264-deadpool.rar yenc
2017-01-19 08:56:39,227::INFO::[assembler:87] Decoding \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\trumps.triumphant.year.2016.720p.hdtv.x264-deadpool.r00 yenc
2017-01-19 08:56:43,392::INFO::[newsunpack:729] Unpacked 1 files/folders in 8 seconds
2017-01-19 08:56:43,394::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.rar
2017-01-19 08:56:43,427::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r00
2017-01-19 08:56:43,450::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r01
2017-01-19 08:56:43,474::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r02
2017-01-19 08:56:43,500::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r03
2017-01-19 08:56:43,530::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r04
2017-01-19 08:56:43,559::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r05
2017-01-19 08:56:43,584::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r06
2017-01-19 08:56:43,605::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r07
2017-01-19 08:56:43,628::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r08
2017-01-19 08:56:43,635::INFO::[assembler:87] Decoding \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\trumps.triumphant.year.2016.720p.hdtv.x264-deadpool.r01 yenc
2017-01-19 08:56:43,650::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r09
2017-01-19 08:56:43,676::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r10
2017-01-19 08:56:43,698::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r11
2017-01-19 08:56:43,723::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r12
2017-01-19 08:56:43,753::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r13
2017-01-19 08:56:43,767::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14
2017-01-19 08:56:43,796::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r15
2017-01-19 08:56:43,819::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r16
2017-01-19 08:56:43,852::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r17
2017-01-19 08:56:43,881::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r18
2017-01-19 08:56:43,904::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r19
2017-01-19 08:56:43,920::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r20
2017-01-19 08:56:43,948::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r21
2017-01-19 08:56:43,963::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r22
2017-01-19 08:56:43,996::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r23
2017-01-19 08:56:44,017::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r24
2017-01-19 08:56:44,049::INFO::[newsunpack:234] Unrar finished on Z:\ISENQ5~5\J7BQCW~G
2017-01-19 08:56:44,061::INFO::[postproc:381] unpack_magic finished on Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS
2017-01-19 08:56:44,153::ERROR::[misc:873] Failed moving Z:\incomplete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r15 to C:\Users\Administrator\Downloads\complete\_UNPACK_Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.1\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r15
2017-01-19 08:56:44,155::INFO::[misc:874] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\misc.pyo", line 869, in move_to_path
  File "shutil.pyo", line 82, in copyfile
![capture1](https://cloud.githubusercontent.com/assets/873624/22116597/d37367e2-de25-11e6-8574-5b5ad703dafa.PNG)

**Comment by Safihre** [comment]
Interesting, but this seems to be a different error! So we fixed the crashing Assembler and detection of Encrypted job still works.
This other errors seem a bit odd, it tries to move things but can't. Maybe it's an unrelated permissions issue?
Also the things it tries to move seem like things that should be part of the main unrar and removed in that step.

**Comment by Safihre** [comment]
Does it say anything else after
```
Traceback (most recent call last):
  File "sabnzbd\misc.pyo", line 869, in move_to_path
  File "shutil.pyo", line 82, in copyfile
```
Maybe there's a bit more in that traceback?

**Comment by computerk** [comment]
Traceback (most recent call last):
  File "sabnzbd\misc.pyo", line 869, in move_to_path
  File "shutil.pyo", line 82, in copyfile
IOError: [Errno 2] No such file or directory: u'\\\\?\\Z:\\incomplete\\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\\trumps.triumphant.year.2016.720p.hdtv.x264-deadpool.r03'
2017-01-19 08:57:04,545::INFO::[postproc:574] Cleaning up Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL (keep_basic=True)
2017-01-19 08:57:04,568::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_wwf4px removed
2017-01-19 08:57:04,581::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_t266io removed
2017-01-19 08:57:04,608::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_cxc3lq removed
2017-01-19 08:57:04,622::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_hzjaer removed
2017-01-19 08:57:04,638::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_0xrcv2 removed
2017-01-19 08:57:04,650::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_2dnf__ removed
2017-01-19 08:57:04,665::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_ivqmmm removed
2017-01-19 08:57:04,701::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_gp60xd removed
2017-01-19 08:57:04,719::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_4s7mqx removed
2017-01-19 08:57:04,729::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_vtuzoi removed
2017-01-19 08:57:04,739::INFO::[__init__:961] \\?\Z:\incomplete\Trumps.Triumphant.Year.2016.720p.HDTV.x264-DEADPOOL.1\__ADMIN__\SABnzbd_nzf_nj8qls removed
2017-01-19 08:57:04,789::INFO::[postproc:85] Saving postproc queue
2017-01-19 08:57:04,789::INFO::[__init__:970] Saving data for postproc2.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\postproc2.sab
2017-01-19 08:57:04,790::INFO::[downloader:291] Post-processing finished, resuming download
2017-01-19 08:57:06,753::INFO::[nzbqueue:258] Saving queue
2017-01-19 08:57:06,895::INFO::[__init__:970] Saving data for queue10.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\queue10.sab
2017-01-19 08:57:06,895::INFO::[__init__:970] Saving data for totals10.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\totals10.sab
2017-01-19 08:57:06,895::INFO::[__init__:970] Saving data for rss_data.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\rss_data.sab
2017-01-19 08:57:06,911::INFO::[__init__:970] Saving data for watched_data2.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\watched_data2.sab
2017-01-19 08:57:06,911::INFO::[postproc:85] Saving postproc queue
2017-01-19 08:57:06,911::INFO::[__init__:970] Saving data for postproc2.sab in C:\Users\Administrator\AppData\Local\sabnzbd\admin\postproc2.sab
2017-01-19 08:57:06,911::INFO::[postproc:815] Queue has finished, launching: None (None)

**Comment by Safihre** [comment]
Could you switch logging to Debug in the Status window and then do another download? After that send the whole log to safihre@sabnzbd.org (bit long to post it here :P) 

Thanks!

**Comment by computerk** [comment]
I updated my VMware tools and same results

**Comment by Safihre** [comment]
@computerk did you see my message above? Think we cross posted exactly at the same time :)

**Comment by computerk** [comment]
File sent you can see that one moved fine and the other one had issues so not sure if that can be permissions? 👍

**Comment by Safihre** [comment]
@shypike do you have any clue what's going on?
The logs clearly show this `.r14` file being deleted, but then somehow it tries to move it
```
2017-01-19 11:59:43,112::DEBUG::[newsunpack:474] rar_unpack(): Rars: [...u'Z:\\ISENQ5~5\\J7BQCW~G.2\\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14', ...]
2017-01-19 11:59:43,112::DEBUG::[newsunpack:475] rar_unpack(): Newfiles: [u'Z:\\complete\\_YJBTK~C\\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.mkv']
...
2017-01-19 11:59:43,482::INFO::[newsunpack:481] Deleting Z:\ISENQ5~5\J7BQCW~G.2\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14
...
2017-01-19 11:59:44,006::INFO::[newsunpack:234] Unrar finished on Z:\ISENQ5~5\J7BQCW~G.2
2017-01-19 11:59:44,032::DEBUG::[newsunpack:1650] build_filelists(): joinables: []
2017-01-19 11:59:44,033::DEBUG::[newsunpack:1651] build_filelists(): zips: []
.. NO rars found:
2017-01-19 11:59:44,033::DEBUG::[newsunpack:1652] build_filelists(): rars: []
2017-01-19 11:59:44,033::DEBUG::[newsunpack:1653] build_filelists(): 7zips: []
2017-01-19 11:59:44,033::DEBUG::[newsunpack:1654] build_filelists(): ts: []
2017-01-19 11:59:44,035::INFO::[postproc:381] unpack_magic finished on Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS
2017-01-19 11:59:44,042::DEBUG::[misc:860] Moving. Old path:\\?\Z:\incomplete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.2\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14 new path:\\?\Z:\complete\_UNPACK_Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14 overwrite?:0
2017-01-19 11:59:44,042::DEBUG::[misc:1284] Renaming "\\?\Z:\incomplete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.2\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14" to "\\?\Z:\complete\_UNPACK_Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14"
2017-01-19 11:59:44,046::ERROR::[misc:873] Failed moving Z:\incomplete\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.2\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14 to Z:\complete\_UNPACK_Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14
2017-01-19 11:59:44,046::INFO::[misc:874] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\misc.pyo", line 869, in move_to_path
  File "shutil.pyo", line 82, in copyfile
IOError: [Errno 2] No such file or directory: u'\\\\?\\Z:\\incomplete\\Jimmy.Kimmel.2017.01.18.Bill.Maher.HDTV.x264-CROOKS.2\\jimmy.kimmel.2017.01.18.bill.maher.hdtv.x264-crooks.r14'
```

The moving uses
```python
for root, _dirs, files in os.walk(workdir):
``` 
Could there be some delay between deleting and actually being gone?

**Comment by computerk** [comment]
Thanks for solving this Safihre 🥇
