### ISSUE TITLE
RSS 500 error / problem with rss_data.sab

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#787]
I run sabnzbd from source on Linux and am on the latest dev version. I use RSS feeds quite a lot, and there is now a problem with them. I first noticed this problem on Wednesday, 2017-01-18. It took me a while to see what is happening. 

It seems to me that every time a new item in one of my RSS feeds is found and downloaded, then that feed's portion in rss_data.sab gets corrupted somehow. At least when I try to access these feeds in sabnzbd I get a 500 server error and a traceback is displayed in red. It's also in the logs:

```2017-01-21 18:46:02,345::ERROR::[_cplogging:219] [21/Jan/2017:18:46:02] HTTP 
Traceback (most recent call last):
  File "/home/abc/.sabnzbd/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/abc/.sabnzbd/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/abc/.sabnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 2011, in index
    return template.respond()
  File "_home_abc__sabnzbd_interfaces_Config_templates_config_rss_tmpl.py", line 1561, in respond
KeyError: 'cat'
```

or:

```2017-01-22 13:51:17,509::ERROR::[_cplogging:219] [22/Jan/2017:13:51:17] HTTP 
Traceback (most recent call last):
  File "/home/abc/.sabnzbd/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/abc/.sabnzbd/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/abc/.sabnzbd/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 1998, in index
    conf['downloaded'], conf['matched'], conf['unmatched'] = GetRssLog(active_feed)
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 2841, in GetRssLog
    done.append(make_item(job))
  File "/home/abc/.sabnzbd/sabnzbd/interface.py", line 2804, in make_item
    job['baselink'] = get_base_url(job['url'])
KeyError: 'url'
```

These are the two basic patterns, KeyError url and sometimes KeyError cat.

Deleting the feeds in questions and recreating them from scratch helps, as does deleting the rss_data.sab file. But in both cases, I lose the history of jobs already downloaded (for the affected feeds or even for all feeds), and auto-download of new items might be impaired.

Speculation: Does sabnzbd damage the rss_data.sab file when writing to it after a new feed item was found and auto-downloaded?

**Comment by Safihre** [comment]
You're right. Those fields were not saved when a job was fetched.
Fixed it (still has to be merged).

**Comment by anonvoy** [comment]
That was quick. Thanks.
