### ISSUE TITLE
SSL routines, SSL_CTX_use_certificate, 'ca md too weak'

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#811]
Got the following in a [debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854234):
```
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/wsgiserver2.py", line 1948, in start
    self.bind(af, socktype, proto)
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/wsgiserver2.py", line 2002, in bind
    self.socket = self.ssl_adapter.bind(self.socket)
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/ssl_pyopenssl.py", line 180, in bind
    self.context = self.get_context()
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/ssl_pyopenssl.py", line 200, in get_context
    c.use_certificate_file(self.certificate)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 596, in use_certificate_file
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'SSL_CTX_use_certificate', 'ca md too weak')]
```
User is running 1.1.1 on debian testing, so python/openssl/etc are all reasonably new. Apparently this is happening with recent sab-generated certs, but I haven't been able to reproduce the issue so far even in a vm using the exact same os and version.

Ideas? Seen this traceback before? For full logging, submitter contact info and my attempts to extract extra info see the linked bug report.

**Comment by thezoggy** [comment]
Per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847743

It sounds like the cert generated was just done on old openssl/awhile ago. 

I would ask for the cert so we can validate... Or they can just move that cert out and try generating a new one and see.if it's all good now.

**Comment by Safihre** [comment]
Let him upgrade to 1.2.0. 
In 1.2.0 we don't use pyOpenSSL anymore and he can use the re-generate certificate button (the refresh icon next to the certificate path) in the Config.

**Comment by jcfp** [comment]
Thanks for your comments, guys. Issue reported gone after removing existing certs.

**Comment by Safihre** [comment]
:+1:
