### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jouty** [sabnzbd/sabnzbd#841]
Hi,

I receive lot of time this error and then it shutdown and restart

2017-03-01 19:50:29,922::INFO::[__init__:969] Saving data for totals10.sab in /home/sab/.sabnzbd/admin/totals10.sab
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/srv/data/Downloads/SABnzbd-1.2.2/sabnzbd/assembler.py", line 85, in run
    filepath = get_filepath(long_path(cfg.download_dir.get_path()), nzo, filename)
  File "/srv/data/Downloads/SABnzbd-1.2.2/sabnzbd/decorators.py", line 32, in newFunction
    return f(*args, **kw)
  File "/srv/data/Downloads/SABnzbd-1.2.2/sabnzbd/misc.py", line 992, in get_filepath
    if os.path.exists(fullPath):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 70: ordinal not in range(128)

**Comment by sanderjo** [comment]
`filepath = get_filepath(long_path(cfg.download_dir.get_path()), nzo, filename)`

So what is your download dir? Any non-ASCII in there?

**Comment by Safihre** [comment]
Can be re-opened if issue reoccurs.

**Comment by jouty** [comment]
sorry for the late answer 
1) Download dir /srv/data/Download
2) Yes there was a specific char in the nzb file i didn't see due encrypt name
3) Preferred encoding = ANSI_X3.4-1968

So the problem was in the 2)
Thx @sanderjo @Safihre

**Comment by sanderjo** [comment]
> Preferred encoding = ANSI_X3.4-1968

Yep. That's where the problem comes from. Solve that, and everything will be OK.
It has to do with "locales". See https://forums.sabnzbd.org/viewtopic.php?f=11&t=22483&hilit=locales how someone solved that on his Linux / Ubuntu.

As of as SAB 2.0.0 Alpha1, you get a big warning if you're on Linux/Unix and Encoding is not UTF.
