### ISSUE TITLE
SAB 2.0.0 Alpha on Debian 9.0 on ARM: "SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#845]
With SAB 2.0.0 Alpha on Debian 9.0 Stretch on ARM, I get
```
SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)
```
(Turning off HTTPS listening (so `enable_https = 0`), and SAB 2.0.0 starts up again.)

Full log:
```
2017-03-05 20:14:45,327::INFO::[sabnzbdplus:1144] sabnzbdplus-2.0.0Alpha1 (rev=6e7eb9dec4c88e729a7506b4810a0f9d93d45987)
2017-03-05 20:14:45,329::INFO::[sabnzbdplus:1145] Full executable path = /usr/bin/sabnzbdplus
2017-03-05 20:14:45,331::INFO::[sabnzbdplus:1157] Platform = posix
2017-03-05 20:14:45,332::INFO::[sabnzbdplus:1158] Python-version = 2.7.13 (default, Jan 19 2017, 14:48:08) 


2017-03-05 20:14:47,293::INFO::[sabnzbdplus:397] SABYenc module (v2.7.0)... found!
2017-03-05 20:14:47,295::INFO::[sabnzbdplus:407] Cryptography module (v1.7.1)... found!

2017-03-05 20:14:47,309::INFO::[sabnzbdplus:1250] SSL version OpenSSL 1.1.0e  16 Feb 2017
2017-03-05 20:14:47,311::INFO::[sabnzbdplus:1251] SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']
2017-03-05 20:14:47,318::INFO::[sabnzbdplus:1366] Starting web-interface on :::9090
2017-03-05 20:14:47,320::INFO::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Bus STARTING
2017-03-05 20:14:47,337::INFO::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-05 20:14:47,835::INFO::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Serving on http://:::8080
2017-03-05 20:14:47,945::ERROR::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x761d5c50>>
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 207, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 167, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "/usr/share/sabnzbdplus/cherrypy/_cpserver.py", line 158, in httpserver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi_server.py", line 64, in __init__
    self.server_adapter.ssl_certificate_chain)
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/ssl_builtin.py", line 56, in __init__
    self.context.load_cert_chain(certificate, private_key)
SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)

2017-03-05 20:14:47,951::ERROR::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 245, in start
    self.publish('start')
  File "/usr/share/sabnzbdplus/cherrypy/process/wspbus.py", line 225, in publish
    raise exc
ChannelFailures: SSLError(336245134, u'[SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)')

2017-03-05 20:14:47,955::INFO::[_cplogging:219] [05/Mar/2017:20:14:47] ENGINE Bus STOPPING
```

**Comment by sanderjo** [comment]
Seems the same as here https://github.com/SickRage/SickRage/issues/2917

Workaround for SR: https://github.com/SickRage/SickRage/issues/2917#issuecomment-273193392

**Comment by sanderjo** [comment]
I stopped SABnzbd, (re)moved server.cert/.key, restarted SABnzbd, activated HTTPS, restarted SAB, and it did start both on HTTP and HTTPS, but with the traceback below.


```
2017-03-05 20:32:45,392::INFO::[_cplogging:219] [05/Mar/2017:20:32:45] ENGINE Serving on https://:::9090
2017-03-05 20:32:45,403::ERROR::[_cplogging:219] [05/Mar/2017:20:32:45] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

2017-03-05 20:32:45,607::INFO::[_cplogging:219] [05/Mar/2017:20:32:45] ENGINE Serving on http://:::8080
```

**Comment by sanderjo** [comment]
Some notes:

Via https://github.com/pyca/cryptography/issues/2299 I arrived on https://github.com/pyca/cryptography/issues/2299#issue-103565682 ... which suggest a problem with Cryptography and GIL ... ? Something for you, @Safihre ;-) ?

Or maybe caused by PyOpenSSL, as discussed here https://github.com/jdf76/plugin.video.youtube/issues/14#issuecomment-274216743

**Comment by Safihre** [comment]
`Error`... Well, wat can we do about this? If even cryptography can't do it..

**Comment by sanderjo** [comment]
So it is a Cryptography module problem? Not SSL? Or am I confusing things?

My suggestion:
- split this thread. Is that possible at all on Github?
- Thread 1: mark as known. Maybe let SAB detect if server.cert/key are too weak for SSL 1.1.0 and then regenerate?
- Thread 2: mark as known, and "won't solve"?

**Comment by Safihre** [comment]
Probably a OpenSSL version, Python version and cryptography version thing.

Indeed, for now we just mark this is as known. Not sure what to really do about it, since we can't just catch the word `Error` in general.

**Comment by sanderjo** [comment]
FWIW / related to "SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2699)"

Analysis of the old server.cert:

```
sander@cubox:~/.sabnzbd/admin$ openssl x509 -text -noout -in old/server.cert | grep Signature
    Signature Algorithm: md5WithRSAEncryption
    Signature Algorithm: md5WithRSAEncryption
```


And the new:

```
sander@cubox:~/.sabnzbd/admin$ openssl x509 -text -noout -in server.cert | grep Signature
    Signature Algorithm: sha256WithRSAEncryption
    Signature Algorithm: sha256WithRSAEncryption
```
So maybe SSL 1.1.0 is refusing the old md5 stuff?

**Comment by thezoggy** [comment]
A person on IRC recently had this problem, he had two Sab installs one with the issue and one without... The openssl version was different... Since it was windows the openssl version is part of Python, so all he had to do was upgrade.python and all was good.

**Comment by Safihre** [comment]
@sanderjo Another user on Reddit experiencing this problem:
https://www.reddit.com/r/usenet/comments/5yr8mm/python_error_when_restarting_sabnzbd/

So HTTPS will not work at all on these systems? Or it will just thrown that error?

**Comment by sanderjo** [comment]
`error: [Errno 0] Error` deserves its own page: https://github.com/sabnzbd/sabnzbd/issues/853

**Comment by sanderjo** [comment]
Follow up to the X.509 check stuff in https://github.com/sabnzbd/sabnzbd/issues/845#issuecomment-284409688

My hope/suggestion is to check that within SABnzbd/python like this: https://cryptography.io/en/latest/x509/reference/

And if MD5 (or SHA1), and self-signed by SAB, then generate new key (with SHA2)

Notes
This issue will happen only if you have an existing working SAB, and upgrade the OS
Workaround is to manually remove the keys

**Comment by Safihre** [comment]
@sanderjo We discussed this also with @shypike before, I already made a PR about a year ago where we indeed would auto-detect the quality of the certificates and regenerate them if it was too bad.
But we decided not to do this, because then people would unexpectedly get shown a warning from their browsers because the certificates changed.

**Comment by sanderjo** [comment]
OK, then somone will need to do a manual removal if he/she gets the error message in the subject.

**Comment by thezoggy** [comment]
prob should add the ssl related things to the wiki page so we have a common place to say.. if you run into this.. do x. (which almost always has been regen certs)
