### ISSUE TITLE
non-fatal traceback "ENGINE Error in HTTPServer.tick" "error: [Errno 0] Error"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#853]
I'm opening a separate issue on the 'ENGINE Error in HTTPServer.tick` -> `error: [Errno 0] Error`.
See https://github.com/sabnzbd/sabnzbd/issues/845#issuecomment-284254495

The traceback is **non-fatal**: both HTTP and HTTPS are working.

This happens on Debian 9.0 stretch with Python 2.7.13 and OpenSSL 1.1.0e. I think it's related to Cherrypy

```
2017-03-11 22:05:07,905::INFO::[sabnzbdplus:1250] SSL version OpenSSL 1.1.0e  16 Feb 2017
2017-03-11 22:05:07,907::INFO::[sabnzbdplus:1251] SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']
2017-03-11 22:05:07,935::INFO::[sabnzbdplus:1366] Starting web-interface on :::9090
2017-03-11 22:05:07,937::INFO::[_cplogging:219] [11/Mar/2017:22:05:07] ENGINE Bus STARTING
2017-03-11 22:05:07,951::INFO::[_cplogging:219] [11/Mar/2017:22:05:07] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-11 22:05:08,402::INFO::[_cplogging:219] [11/Mar/2017:22:05:08] ENGINE Serving on https://:::9090
2017-03-11 22:05:08,413::ERROR::[_cplogging:219] [11/Mar/2017:22:05:08] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/share/sabnzbdplus/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

2017-03-11 22:05:08,617::INFO::[_cplogging:219] [11/Mar/2017:22:05:08] ENGINE Serving on http://:::8080
2017-03-11 22:05:08,621::INFO::[_cplogging:219] [11/Mar/2017:22:05:08] ENGINE Bus STARTED
2017-03-11 22:05:08,623::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2017-03-11 22:05:08,624::INFO::[sabnzbdplus:1404] Starting sabnzbdplus-2.0.0Beta1
```

```
sander@cubox:~$ sudo netstat -apon | grep LISTEN | grep python
tcp6       0      0 :::8080                 :::*                    LISTEN      30380/python         off (0.00/0/0)
tcp6       0      0 :::9090                 :::*                    LISTEN      30380/python         off (0.00/0/0)
```

**Comment by Safihre** [comment]
Isn't it an error of Python's SSL lib? Seems like it's an error thrown by the underlying SSL socket that Python doesn't know how to handle.
What causes it though? Bad certificates?
It's also not of the `SSLError` type, is it?

**Comment by thezoggy** [comment]
`2017-03-11 22:05:08,402::INFO::[_cplogging:219] [11/Mar/2017:22:05:08] ENGINE Serving on https://:::9090`

what if its not being bound to  `::` or if you just try the v6 address does it work?
> curious to know if `::` is wrongly getting parsed before port

**Comment by OldskoolOrion** [comment]
Debian enforces 4096 nowadays, since they believe 2048 are getting increasingly insecure.
Might be smart considering the switch to libreSSL as well once you guys dive into that.
OpenSSL's codebase is horrible and poorly maintained after OBSD donated it to the collaborative org.
Try read the code they made of it since it's out of OpenBSD's hands... I really can't follow it and my guess and the original creators sure thing, is that they can't either.. it's spaghetti.. That's why the original group started libreSSL to clean up the code.. check last 2.5 years... LibreSSL ADDED functionality and cut nearly 500.000 lines of code making the package smaller - OpenSSL didn't add functionality - just more CVE's popped up and it GREW 40% in size.

That doesn't make sense :-)

Anyway... besides the point that was.. but the 4096 key is a real thing :-)

**Comment by sanderjo** [comment]
Hi @OldskoolOrion , just checking: with 4096 and 2048 you're referring to the bits in the key, which currently is 2048 for SAB's self-generated key:
```

sander@Streamer13:~/.sabnzbd/admin$ openssl x509 -text -noout -in server.cert | grep -e 2048 -e 4096
                Public-Key: (2048 bit)
```
If so, that's quite something, because I checked, and my Let's encrypt is also 2048 bit.

**Comment by OldskoolOrion** [comment]
I didn't do my homework in the sab-sourcecode or the dependencies they use so yes... u did everything mighty fine and well documented... so it's not you :-)
what it exactly is.. needs more work :-)  shame.. this would have been such a nice easy fix if it would have solved it.. non fatal or not.. thats a message u'd rather not see

**Comment by sanderjo** [comment]
Just to be sure, and thanks to @Safihre , I let SABnzbd create 4096 keys

In https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L1233, change 2048 to 4096
Then `rm ~/.sabnzbd/admin/server.*`, and start SABnzbd. 

Result: same error message. So not a key length thing.



```
2017-03-12 11:45:47,054::INFO::[SABnzbd:1262] SSL version OpenSSL 1.1.0e  16 Feb 2017
2017-03-12 11:45:47,056::INFO::[SABnzbd:1263] SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']


2017-03-12 11:46:23,567::INFO::[misc:1234] Self-signed certificates generated successfully
2017-03-12 11:46:23,574::INFO::[SABnzbd:1378] Starting web-interface on :::9090
2017-03-12 11:46:23,576::INFO::[_cplogging:219] [12/Mar/2017:11:46:23] ENGINE Bus STARTING
2017-03-12 11:46:23,589::INFO::[_cplogging:219] [12/Mar/2017:11:46:23] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-12 11:46:23,906::INFO::[_cplogging:219] [12/Mar/2017:11:46:23] ENGINE Serving on https://:::9090
2017-03-12 11:46:23,917::ERROR::[_cplogging:219] [12/Mar/2017:11:46:23] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/sander/SABnzbd-2.0.0Beta1/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/home/sander/SABnzbd-2.0.0Beta1/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/sander/SABnzbd-2.0.0Beta1/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

2017-03-12 11:46:24,121::INFO::[_cplogging:219] [12/Mar/2017:11:46:24] ENGINE Serving on http://:::8080
2017-03-12 11:46:24,124::INFO::[_cplogging:219] [12/Mar/2017:11:46:24] ENGINE Bus STARTED
2017-03-12 11:46:24,126::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2017-03-12 11:46:24,128::INFO::[SABnzbd:1416] Starting SABnzbd.py-2.0.0Beta1

```

**Comment by sanderjo** [comment]
FWIW: Older SAB versions:

SAB 1.0.2 (with python-openssl): no error
SAB 1.1.0: no error
SAB 1.2.0 (with cryptography, right?): error

So it's something related to the module cryptography? And I could/should have discovered it in SAB 1.2.0 ... 

No problem with SABnzbd-1.0.2 (with python-openssl installed):
```
2017-03-12 12:36:53,071::INFO::[SABnzbd:1372] SSL version OpenSSL 1.1.0e  16 Feb 2017
2017-03-12 12:36:53,073::INFO::[SABnzbd:1373] pyOpenSSL version 16.2.0
2017-03-12 12:36:53,075::INFO::[SABnzbd:1374] SSL potentially supported protocols ['SSLv23', 'TLS', 'TLSv1', 'TLSv1_1', 'TLSv1_2']
2017-03-12 12:36:53,076::INFO::[SABnzbd:1375] SSL actually supported protocols ['t12', 't11', 't1', 'v23']
2017-03-12 12:36:53,084::INFO::[SABnzbd:1522] Starting web-interface on :::9090
2017-03-12 12:36:53,088::INFO::[_cplogging:216] [12/Mar/2017:12:36:53] ENGINE Bus STARTING
2017-03-12 12:36:53,108::INFO::[_cplogging:216] [12/Mar/2017:12:36:53] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-12 12:36:53,325::INFO::[_cplogging:216] [12/Mar/2017:12:36:53] ENGINE Serving on https://:::9090
2017-03-12 12:36:53,533::INFO::[_cplogging:216] [12/Mar/2017:12:36:53] ENGINE Serving on http://:::8080
2017-03-12 12:36:53,536::INFO::[_cplogging:216] [12/Mar/2017:12:36:53] ENGINE Bus STARTED
2017-03-12 12:36:53,538::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2017-03-12 12:36:53,542::DEBUG::[notifier:112] Sending registration to localhost:23053
2017-03-12 12:36:53,545::DEBUG::[notifier:102] Checking icon
2017-03-12 12:36:53,561::DEBUG::[notifier:219] To : localhost:23053 <<class 'gntp.GNTPRegister'>>
2017-03-12 12:36:53,564::DEBUG::[growler:201] Cannot register with Growl [Errno 111] Connection refused
2017-03-12 12:36:54,123::DEBUG::[misc:616] Checked for a new release, cur= 1000299, latest= 1020199 (on https://sabnzbd.org/downloads.html), latest_test= 2000041 (on https://sabnzbd.org/downloads.html)
2017-03-12 12:36:54,125::INFO::[SABnzbd:1594] Starting SABnzbd.py-1.0.2
```

SABnzbd 1.2.0 shows the same error as SABnzbd 2
```
2017-03-12 12:38:48,416::INFO::[SABnzbd:1299] SSL version OpenSSL 1.1.0e  16 Feb 2017
2017-03-12 12:38:48,417::INFO::[SABnzbd:1300] SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']
2017-03-12 12:38:48,424::INFO::[SABnzbd:1439] Starting web-interface on :::9090
2017-03-12 12:38:48,426::INFO::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Bus STARTING
2017-03-12 12:38:48,446::INFO::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-12 12:38:48,765::INFO::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Serving on https://:::9090
2017-03-12 12:38:48,779::ERROR::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/sander/versies-van-sab/SABnzbd-1.2.0/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/home/sander/versies-van-sab/SABnzbd-1.2.0/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/sander/versies-van-sab/SABnzbd-1.2.0/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

2017-03-12 12:38:48,990::INFO::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Serving on http://:::8080
2017-03-12 12:38:48,994::INFO::[_cplogging:219] [12/Mar/2017:12:38:48] ENGINE Bus STARTED
2017-03-12 12:38:48,996::INFO::[zconfig:64] No Bonjour/ZeroConfig support installed
2017-03-12 12:38:48,998::INFO::[SABnzbd:1477] Starting SABnzbd.py-1.2.0
```

**Comment by Safihre** [comment]
In 1.2.0 we removed the dependency on pyOpenSsl and use python ssl directly. Probably pyOpenSsl filters this error out. 

Wonder sometimes if we should start using it again, but then I remember what a mess it is because the version of pyOpenSsl also has to correctly match python/OpenSSL/cherrypy version.

**Comment by OldskoolOrion** [comment]
Looking into it myself.. and comparing with libressl vs openssl - i'm thinking it might very well be the crappy state openssl is in nowadays. It doesn't break anything so no need to rush into anything. It inspired me to finally get to checking and comparing :-)

**Comment by Safihre** [comment]
We're completely bound to what python implements. So with the huge hassle it was to get OpenSSL integrated, I doubt there will be an option to change it for anything else before I'm old and grey :P 
And even then it would be in Python 3 and not 2, which would mean massive rewrite of Sabnzbd..

**Comment by thezoggy** [comment]
what about if we just try to import pyopenssl as openssl before native openssl? as i dont recall us using any pyopenssl exclusive things.. that way people that want to use pyopenssl (debian) can.. and those that dont.. dont.. gives the flexibility of the choice to the user?

**Comment by Safihre** [comment]
@thezoggy The functions don't overlap, so can't just `import pyopenssl as ssl` or something like that.

**Comment by sanderjo** [comment]
I wrote "I think it is something upstream: OpenSSL, Python, Cryptography and/or Cherrypi (and/or GIL).
And it (so far) only happens on Debian 9 "Stretch" / Testing. So let's see what happens in the next months", and @safihre marked it as "Other Software", so I'm closing this issue.

Just let's see how this evolves in ... let's say ... july 2017.

**Comment by binhex** [comment]
> And it (so far) only happens on Debian 9 "Stretch
Just to let you know, this also now happens on Arch Linux x64 running Python 2.7.13 and OpenSSL 1.1.0e

**Comment by jallakim** [comment]
You all probably know, but this is still an "issue", even in the final release of Stretch (and probably all distros that uses newer OpenSSL or whatnot).

Maybe reopen this issue so that we can track the progress of it being "solved"?

**Comment by Safihre** [comment]
Currently we have no good idea how to solve this.

**Comment by jallakim** [comment]
I know, hence "solved" :-D

**Comment by Safihre** [comment]
@jallakim @sanderjo 
I don't think upstream Python is aware of this bug.
Will try to submit a bug report.

**Comment by Safihre** [comment]
Could you test something for me?
Could you run
```
pip install cherrypy --upgrade
pip install pyopenssl --upgrade
```
And then run this python script where you replace `YOUR_PATH` by the path to the SABnzbd self-signed certs:
```python
import cherrypy

print cherrypy.__version__

class RootServer:
    @cherrypy.expose
    def index(self, **keywords):
        return "it works!"

if __name__ == '__main__':
    server_config={
        'server.socket_host': '127.0.0.1',
        'server.socket_port': 4400,
        'server.ssl_module': 'builtin',
        #'server.ssl_module':'pyopenssl',
        'server.ssl_certificate':'YOUR_PATH/server.cert',
        'server.ssl_private_key':'YOUR_PATH/server.key'
    }

    cherrypy.config.update(server_config)
    cherrypy.quickstart(RootServer())
```

Does it throw the error?
If so, can you run the script again, but now change this section:
```python
        #'server.ssl_module': 'builtin',
        'server.ssl_module':'pyopenssl',
```

**Comment by sanderjo** [comment]
Result:

```
root@07605dded10a:/# python safihre_test1.py 
11.0.0
[10/Aug/2017:16:22:00] ENGINE Listening for SIGHUP.
[10/Aug/2017:16:22:00] ENGINE Listening for SIGTERM.
[10/Aug/2017:16:22:00] ENGINE Listening for SIGUSR1.
[10/Aug/2017:16:22:00] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[10/Aug/2017:16:22:00] ENGINE Started monitor thread '_TimeoutMonitor'.
[10/Aug/2017:16:22:00] ENGINE Started monitor thread 'Autoreloader'.
[10/Aug/2017:16:22:01] ENGINE Serving on https://127.0.0.1:4400
[10/Aug/2017:16:22:01] ENGINE Bus STARTED
[10/Aug/2017:16:22:01] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1485, in start
    self.tick()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1560, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/lib/python2.7/dist-packages/cheroot/ssl/builtin.py", line 73, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error


```
resp
```
root@07605dded10a:/# python safihre_test2.py 
11.0.0
[10/Aug/2017:16:23:36] ENGINE Listening for SIGHUP.
[10/Aug/2017:16:23:36] ENGINE Listening for SIGTERM.
[10/Aug/2017:16:23:36] ENGINE Listening for SIGUSR1.
[10/Aug/2017:16:23:36] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[10/Aug/2017:16:23:36] ENGINE Started monitor thread '_TimeoutMonitor'.
[10/Aug/2017:16:23:36] ENGINE Started monitor thread 'Autoreloader'.
[10/Aug/2017:16:23:36] ENGINE Serving on https://127.0.0.1:4400
[10/Aug/2017:16:23:36] ENGINE Bus STARTED


```

**Comment by sanderjo** [comment]
To see if the problem is in Python or Cherrypy, I grabbed together some code, of which I'm not 100% sure it's correct.
Conclusion: I can **NOT** reproduce the problem with pure python (still on Debian:Unstable). 


So maybe the problem is in Cherrypy ... ?

Code:
```
import socket, ssl

print "Start"
context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile="/root/.sabnzbd/admin/server.cert", keyfile="/root/.sabnzbd/admin/server.key")

bindsocket = socket.socket()
bindsocket.bind(('localhost', 9999))
bindsocket.listen(5)

while True:
    newsocket, fromaddr = bindsocket.accept()
    sslsoc = context.wrap_socket(newsocket, server_side=True)
    request = sslsoc.read()
    print(request)

print "Klaar"

```

Start SSL-server, with the SAB-keys, in the background:
```
root@0415ac50e8d1:/# python sander_server_test.py  &
[1] 6093
root@0415ac50e8d1:/# Start
```
It starts up without problems. 

Try to connect ... which works:
```

root@0415ac50e8d1:/# openssl s_client  -connect 127.0.0.1:9999
CONNECTED(00000003)
depth=0 L = SABnzbd, O = SABnzbd
verify error:num=18:self signed certificate
verify return:1
depth=0 L = SABnzbd, O = SABnzbd
verify return:1
---
Certificate chain
 0 s:/L=SABnzbd/O=SABnzbd
   i:/L=SABnzbd/O=SABnzbd
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDCDCCAfCgAwIBAgIUaIUp0NBrGN+9OBE4S7j26YhQhSQwDQYJKoZIhvcNAQEL
BQAwJDEQMA4GA1UEBwwHU0FCbnpiZDEQMA4GA1UECgwHU0FCbnpiZDAeFw0xNzA4
MTAxOTI0NDlaFw0yNzA1MTAxOTI0NDlaMCQxEDAOBgNVBAcMB1NBQm56YmQxEDAO
BgNVBAoMB1NBQm56YmQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDl
6uE2pW/eNA+Oob37DT6ycPmDVSjF0uIWmDmrKiXhOxSxywuzeYoI/ZE6ADcIffoF
TdL6ycow3k2n+J+NxQsdt1e7QrUm14W0O0Eg9wU+K7u8kvVKjf9hH2v1LDzRD5rR
rZH6oJctWVI0np4gu6gVl6ltRQPjxV6GCAgeBYUz5qBt4rvF7Et8PPOMsRS2pbPV
Yf1FfiHCTmuQEowbNHherpBvBccAkHRL7w3F3W5bxthP9HYQYg+uDFU3aXB2fc8y
Vet60GtV6bBMKZiW7LdI9LMLh09JnnTEZXhRNUrEjonomSLuQkzC0OHcxIV+R0EF
OroeiiCd6rgofNSYz15XAgMBAAGjMjAwMC4GA1UdEQEB/wQkMCKCCWxvY2FsaG9z
dIIJMTI3LjAuMC4xggoxNzIuMTcuMC4yMA0GCSqGSIb3DQEBCwUAA4IBAQCjFq6l
+kaJ3ugO+IiUDUZPBGuUsKnqowIwlpu6cuMpz9SZ/7YlRTCw3AxS3G61nKeoicDc
ta37zVyYh3CcTy+wHkvgsk7r+RLAz7lxpSv8K53YUBcfeEsJlzgQ77SWX2EqJogJ
HC3foX9/dpqjKWBEKmQRa5YtHuwcKvi1yfShmq18lEWREYKRQ5cbOZu/oJ/GBFwB
SecT7KFm7VNSu29xaXuPXdGg4xq5bXZgFsiqj4pVAROqIkwQUpBmnsp21Myr9uI7
F/AEkOF+omt8djWJxOsH9v/N4v3Q52fqMVrqaNt9qmBSuh+oHknuohPLNIDXRPV5
hF/rFkzLanQ/QXgn
-----END CERTIFICATE-----
subject=/L=SABnzbd/O=SABnzbd
issuer=/L=SABnzbd/O=SABnzbd
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1405 bytes and written 269 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 33401E35A2AF8FAFB03E6061C1AA7F5D67A82F1299FEF94DCFE740C96FFB2DF7
    Session-ID-ctx: 
    Master-Key: B878942D14736E87B59337AB12B6BA7B19C59431D39A5CBF89ACB55F796CF7969987A3040617EE5DDF68CCCF61B55029
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - aa 30 97 9d f0 cf 1f 8a-43 4c 62 10 4d 6a 16 b6   .0......CLb.Mj..
    0010 - bc e4 34 6a e4 a1 4e 25-7d 20 9b e0 6d 02 39 e2   ..4j..N%} ..m.9.
    0020 - 2e 23 f8 65 d9 c2 89 7d-8c 50 7f 4e 03 60 98 17   .#.e...}.P.N.`..
    0030 - 80 76 cc d0 bc 75 6f 35-8a 34 51 a4 4a b0 a7 4f   .v...uo5.4Q.J..O
    0040 - 3e f1 a4 b3 4d 01 20 53-da d8 32 83 31 11 06 9d   >...M. S..2.1...
    0050 - fb 94 7d 33 23 60 52 a8-58 d8 10 5d 02 19 01 f1   ..}3#`R.X..]....
    0060 - df 63 59 94 e0 1f 88 80-d6 1c 7a 06 71 93 c4 49   .cY.......z.q..I
    0070 - f1 c0 2a 94 04 47 74 ff-27 9f 06 9c b8 09 76 80   ..*..Gt.'.....v.
    0080 - d2 de 19 11 ce ac 20 72-a8 83 af cd c1 b6 d8 80   ...... r........
    0090 - 6f 26 fc 38 c2 1b 32 a1-88 c6 27 9a a8 87 da f9   o&.8..2...'.....

    Start Time: 1502393462
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: yes
---
hello there
hello there

ik ben sander

^C
root@0415ac50e8d1:/# 
```

**Comment by Safihre** [comment]
Would it be the auto-handshake? That's the only difference I notice.
What happens if you try:
```python
import socket, ssl

print "Start"
context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile="/root/.sabnzbd/admin/server.cert", keyfile="/root/.sabnzbd/admin/server.key")

bindsocket = socket.socket()
bindsocket.bind(('localhost', 9999))
bindsocket.listen(5)

while True:
    newsocket, fromaddr = bindsocket.accept()
    sslsoc = context.wrap_socket(newsocket, do_handshake_on_connect=True, server_side=True)
    request = sslsoc.read()
    print(request)

print "Klaar"
```

**Comment by sanderjo** [comment]
That works too:
```
python sander_server_test_2.py &
```


```
root@0415ac50e8d1:/# openssl s_client  -connect 127.0.0.1:9111
CONNECTED(00000003)
depth=0 L = SABnzbd, O = SABnzbd
verify error:num=18:self signed certificate
verify return:1
depth=0 L = SABnzbd, O = SABnzbd
verify return:1
---
Certificate chain
 0 s:/L=SABnzbd/O=SABnzbd
   i:/L=SABnzbd/O=SABnzbd
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDCDCCAfCgAwIBAgIUaIUp0NBrGN+9OBE4S7j26YhQhSQwDQYJKoZIhvcNAQEL
BQAwJDEQMA4GA1UEBwwHU0FCbnpiZDEQMA4GA1UECgwHU0FCbnpiZDAeFw0xNzA4
MTAxOTI0NDlaFw0yNzA1MTAxOTI0NDlaMCQxEDAOBgNVBAcMB1NBQm56YmQxEDAO
BgNVBAoMB1NBQm56YmQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDl
6uE2pW/eNA+Oob37DT6ycPmDVSjF0uIWmDmrKiXhOxSxywuzeYoI/ZE6ADcIffoF
TdL6ycow3k2n+J+NxQsdt1e7QrUm14W0O0Eg9wU+K7u8kvVKjf9hH2v1LDzRD5rR
rZH6oJctWVI0np4gu6gVl6ltRQPjxV6GCAgeBYUz5qBt4rvF7Et8PPOMsRS2pbPV
Yf1FfiHCTmuQEowbNHherpBvBccAkHRL7w3F3W5bxthP9HYQYg+uDFU3aXB2fc8y
Vet60GtV6bBMKZiW7LdI9LMLh09JnnTEZXhRNUrEjonomSLuQkzC0OHcxIV+R0EF
OroeiiCd6rgofNSYz15XAgMBAAGjMjAwMC4GA1UdEQEB/wQkMCKCCWxvY2FsaG9z
dIIJMTI3LjAuMC4xggoxNzIuMTcuMC4yMA0GCSqGSIb3DQEBCwUAA4IBAQCjFq6l
+kaJ3ugO+IiUDUZPBGuUsKnqowIwlpu6cuMpz9SZ/7YlRTCw3AxS3G61nKeoicDc
ta37zVyYh3CcTy+wHkvgsk7r+RLAz7lxpSv8K53YUBcfeEsJlzgQ77SWX2EqJogJ
HC3foX9/dpqjKWBEKmQRa5YtHuwcKvi1yfShmq18lEWREYKRQ5cbOZu/oJ/GBFwB
SecT7KFm7VNSu29xaXuPXdGg4xq5bXZgFsiqj4pVAROqIkwQUpBmnsp21Myr9uI7
F/AEkOF+omt8djWJxOsH9v/N4v3Q52fqMVrqaNt9qmBSuh+oHknuohPLNIDXRPV5
hF/rFkzLanQ/QXgn
-----END CERTIFICATE-----
subject=/L=SABnzbd/O=SABnzbd
issuer=/L=SABnzbd/O=SABnzbd
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1405 bytes and written 269 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 5E53A2056EBAD63797253E0CAE536A9C1A2159BC6DC28A4B2FB7B26D0E0F9809
    Session-ID-ctx: 
    Master-Key: 9ACECB5E803B9946B17AB5BCC54859EDEF5ED6E2EBF15AA33A28519EDFDC4FC97F419B3F1D41986EB82B50EF1C9D6A93
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 2f 0d 42 0a b6 1d 3e de-d4 09 e9 c2 11 fd 28 d9   /.B...>.......(.
    0010 - e1 e1 a2 fe 0d 04 e6 98-f2 e9 92 e2 87 e7 44 b0   ..............D.
    0020 - 07 c1 28 36 d6 80 ad 53-bc c2 02 a2 f3 d4 38 08   ..(6...S......8.
    0030 - 7a f2 dc 05 db 74 dc 28-8f 21 77 d9 ad 5c ca ff   z....t.(.!w..\..
    0040 - c5 c3 73 fc 32 0d 49 2b-f3 af 7e e4 01 ac 88 29   ..s.2.I+..~....)
    0050 - 37 84 a5 a2 f6 17 ad 60-3e 81 90 78 b6 b0 3c 80   7......`>..x..<.
    0060 - 10 77 9e e5 e7 38 44 aa-09 cb ad b0 34 9f c6 d0   .w...8D.....4...
    0070 - ef a7 0f 84 d8 c7 24 a2-55 a5 59 a0 95 2c 2b ec   ......$.U.Y..,+.
    0080 - 33 54 db a6 e6 2f b0 d6-b3 86 54 99 3c db 03 fa   3T.../....T.<...
    0090 - 6c 08 bb 6c 25 73 83 85-a2 cd a8 27 8c 01 cf ac   l..l%s.....'....

    Start Time: 1502415475
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: yes
---
daar ben ik weer
daar ben ik weer

```

**Comment by sanderjo** [comment]
A few notes:
* my report was on Debian 9.
* The recent tests were on Debian Unstable
* I created a fresh Debian 9 Docker (see https://github.com/sabnzbd/sabnzbd/issues/1000) and it still shows the originally reported problem.

**Comment by Safihre** [comment]
The error will now be caught/suppresses until the underlying issue is resolved.

**Comment by sanderjo** [comment]
Ah, with the (monkey?) patch in https://github.com/sabnzbd/sabnzbd/commit/d3628a1eb7c40b213cc6f42f35ec40649ae12653

**Comment by Safihre** [comment]
Yes indeed, since cherrypy seems to have no clue what is causing it 🐑

**Comment by Rodgelius** [comment]
I have had the same error, but i use docker and change "FROM python" to "FROM python:3.4.9" in my Dockerfile. So I haven't this problem now. Good luck!

**Comment by thezoggy** [comment]
note that cherrypy finally took care of this in chroot:
https://github.com/cherrypy/cheroot/commit/42bc79d860e0c8423de98fffad9bf1a65a4b35aa#diff-92452e628c6d9dcfef53e854eacd1d63

**Comment by Safihre** [comment]
Finally! Since in Py3-version we will just pip-supplied CherryPy we can benefit from it then.

**Comment by stereon** [comment]
同样在Ubuntu18.04 安装遇到这个错误：
环境信息：
python3.6.9
OpenSSL 1.1.1

报错信息：
[ERROR   ] [08/Nov/2022:08:08:57] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1552, in start
    self.tick()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1616, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python3.6/ssl.py", line 1158, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

解决方法：
apt install pyopenssl
pip3m install cherrypy --upgrade
