### ISSUE TITLE
sab - 2.0.0b1 -- cherrypy logging

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#862]
appending `-w` to enable cherrpy logging doesn't work:
```
C:\Program Files (x86)\sabnzbd_git>python SABnzbd.py -f C:\test\sabnzbd.ini --clean --new -w

Usage: None [-f <configfile>] <other options>

Options marked [*] are stored in the config file

Options:
  -f  --config-file <ini>  Location of config file
  -s  --server <srv:port>  Listen on server:port [*]
  -t  --templates <templ>  Template directory [*]
  -2  --template2 <templ>  Secondary template dir [*]

  -l  --logging <0..2>     Set logging level (-1=off, 0= least, 2= most) [*]
  -w  --weblogging         Enable cherrypy access logging

  -b  --browser <0..1>     Auto browser launch (0= off, 1= on) [*]
  -d  --daemon             Use when run as a service

      --force              Discard web-port timeout (see Wiki!)
  -h  --help               Print this message
  -v  --version            Print version information
  -c  --clean              Remove queue, cache and logs
  -p  --pause              Start in paused mode
      --repair             Add orphaned jobs from the incomplete folder to the queue
      --repair-all         Try to reconstruct the queue from the incomplete folder
                           with full data reconstruction
      --https <port>       Port to use for HTTPS server
      --log-all            Log all article handling (for developers)
      --console            Force console logging for OSX app
      --new                Run a new instance of SABnzbd
      --ipv6_hosting <0|1> Listen on IPv6 address [::1]
```

and putting it as the first argument, causes it to crash because its not reading the actual .ini to know what to port to start up since 8082 is already taken:
```
C:\Program Files (x86)\sabnzbd_git>python SABnzbd.py -w -f C:\test\sabnzbd.ini --clean --new
2017-03-15 17:12:05,503::INFO::[SABnzbd:1155] --------------------------------
2017-03-15 17:12:05,506::INFO::[SABnzbd:1156] SABnzbd.py-develop (rev=unknown)
2017-03-15 17:12:05,509::INFO::[SABnzbd:1157] Full executable path = C:\Program Files (x86)\sabnzbd_git\SABnzbd.py
2017-03-15 17:12:05,515::INFO::[SABnzbd:1165] Platform=Windows-7-6.1.7601-SP1 (=Vista+ x64) Class=nt
2017-03-15 17:12:05,519::INFO::[SABnzbd:1170] Python-version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
2017-03-15 17:12:05,523::INFO::[SABnzbd:1171] Arguments = SABnzbd.py -w -f C:\test\sabnzbd.ini --clean --new
...
2017-03-15 17:12:05,829::INFO::[SABnzbd:1378] Starting web-interface on 192.168.0.2:8082
[15/Mar/2017:17:12:05] ENGINE Bus STARTING
2017-03-15 17:12:05,832::INFO::[_cplogging:219] [15/Mar/2017:17:12:05] ENGINE Bus STARTING
[15/Mar/2017:17:12:05] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-03-15 17:12:05,842::INFO::[_cplogging:219] [15/Mar/2017:17:12:05] ENGINE Started monitor thread '_TimeoutMonitor'.
[15/Mar/2017:17:12:11] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x0000000003848160>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 207, in publish
    output.append(listener(*args, **kwargs))
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\servers.py", line 172, in start
    wait_for_free_port(*self.bind_addr)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\servers.py", line 443, in wait_for_free_port
    raise IOError('Port %r not free on %r' % (port, host))
IOError: Port 8082 not free on '192.168.0.2'

[15/Mar/2017:17:12:11] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 245, in start
    self.publish('start')
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 223, in publish
    level=40, traceback=True)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 517, in log
    self.publish('log', msg, level)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 225, in publish
    raise exc
ChannelFailures: TypeError('not enough arguments for format string',)

2017-03-15 17:12:11,654::ERROR::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 245, in start
    self.publish('start')
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 223, in publish
    level=40, traceback=True)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 517, in log
    self.publish('log', msg, level)
  File "C:\Program Files (x86)\sabnzbd_git\cherrypy\process\wspbus.py", line 225, in publish
    raise exc
ChannelFailures: TypeError('not enough arguments for format string',)

[15/Mar/2017:17:12:11] ENGINE Bus STOPPING
2017-03-15 17:12:11,704::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Bus STOPPING
[15/Mar/2017:17:12:11] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.2', 8082)) already shut down
2017-03-15 17:12:11,710::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('192.168.0.2', 8082)) already shut down
[15/Mar/2017:17:12:11] ENGINE Stopped thread '_TimeoutMonitor'.
2017-03-15 17:12:11,726::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Stopped thread '_TimeoutMonitor'.
[15/Mar/2017:17:12:11] ENGINE Bus STOPPED
2017-03-15 17:12:11,730::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Bus STOPPED
[15/Mar/2017:17:12:11] ENGINE Bus EXITING
2017-03-15 17:12:11,733::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Bus EXITING
[15/Mar/2017:17:12:11] ENGINE Bus EXITED
2017-03-15 17:12:11,736::INFO::[_cplogging:219] [15/Mar/2017:17:12:11] ENGINE Bus EXITED
```

if sab read the .ini it would have started on 8092:
```
C:\Program Files (x86)\sabnzbd_git>grep "port = 8" C:\test\sabnzbd.ini
port = 8092
```

**Comment by thezoggy** [comment]
looks like `--weblogging` does work.. dumping cherrpy logs to file and sending them to sab console

**Comment by thezoggy** [comment]
https://github.com/sabnzbd/sabnzbd/pull/863
