### ISSUE TITLE
sab -- 1.2.3 - broken on vista

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#873]
from irc:

> I just installed the latest Windows version 1.2.3 and it won't start up...
```
Traceback (most recent call last):   
File "SABnzbd.py", line 84, in <module>   
File "sabnzbd\__init__.pyo", line 104, in <module>   
File "sabnzbd\nzbqueue.pyo", line 43, in <module>   
File "sabnzbd\downloader.pyo", line 42, in <module>   
File "sabnzbd\utils\happyeyeballs.pyo", line 23, in <module>   
File "ssl.pyo", line 98, in <module>   File "_ssl.pyo", line
```

someone suggested they try 1.2.2
> https://github.com/sabnzbd/sabnzbd/releases/download/1.2.2/SABnzbd-1.2.2-win32-setup.exe

once installed, it worked for them. they tried 1.2.3 again.. broken. tried 2.0.0RC1 and it worked.

**Comment by Safihre** [comment]
We know: https://forums.sabnzbd.org/viewtopic.php?f=2&t=22531
Due to py2exe copying system DLLs with the new cryptography version that break on some windows versions/settings. 
I fixed it for 2.0.0 RC1. 

Since 2.0.0 is so close I'm not releasing another 1.2.x, they can just use RC1.

**Comment by thezoggy** [comment]
good to know, never have seen this one before

**Comment by Safihre** [comment]
Yeah I also thought I had seen everything and took care of everything :sweat_smile:
But then I saw in the build-script that SP already had to remove a couple of these unwanted DLL's that py2exe copies in.
