### ISSUE TITLE
NotFound: cannot find 'ssl_version' when going to /config/ 

### ISSUE THREAD

**Issue by seedstorms** [sabnzbd/sabnzbd#886]
Hi,

Somewhat randomly, I'm getting the below error when I try to go to the config/settings page. I haven't really gone to it in a couple of months, and I have done Ubuntu package updates several times since then, so I'm wondering if something broke it?

Please let me know if you need anything else.

I'm running sabnzbdplus/xenial,xenial,now 2.0.0~rc2-0ubuntu1~jcfp1~xenial all [installed]
on Ubuntu stretch/sid

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1276, in index
    return msg
  File "cheetah__usr_share_sabnzbdplus_interfaces_Config_templates_config_tmpl_1491320064_11_69800.py", line 171, in respond
NotFound: cannot find 'ssl_version'
```

**Comment by Safihre** [comment]
Something didn't go well during an upgrade and a template or python file was not upgraded. 
Try removing sabnzbd and reinstalling it. Your settings will stay preserved.

**Comment by seedstorms** [comment]
Thanks, this fixed it.
