### ISSUE TITLE
urlgrabber crash with unicode error

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#898]
On startup with latest dev, win 10, python 2.7.13

```
2017-04-15 18:25:04,214::ERROR::[urlgrabber:271] URLGRABBER CRASHED
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\urlgrabber.py", line 228, in run
    path = os.path.join(path, filename)
  File "C:\Python\2.7.13\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 45: invalid start byte
2017-04-15 18:25:04,233::DEBUG::[urlgrabber:272] URLGRABBER Traceback:
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\urlgrabber.py", line 228, in run
    path = os.path.join(path, filename)
  File "C:\Python\2.7.13\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 45: invalid start byte
```

**Comment by Safihre** [comment]
We will need a sample NZB to test! Do you know which one was the culprit?

**Comment by sanderjo** [comment]
> can't decode byte 0x8e

Doesn't this have to do with a funny character (non-ASCII, and non-Unicode) in the path name or filename?

Meaning of 0x8e in, for example:

https://en.wikipedia.org/wiki/Code_page_437: Ä
https://en.wikipedia.org/wiki/Windows-1252: Ž
https://en.wikipedia.org/wiki/Windows-1251: Ћ

**Comment by labrys** [comment]
Unfortunately I don't have an nzb for you or filename.  Logs have rolled over and a restart gives no traceback.

**Comment by Safihre** [comment]
Will close it now, let us know if you find (another) URL/file that causes this so we debug!
