### ISSUE TITLE
Delete API Call not deleting files

### ISSUE THREAD

**Issue by Ninjouz** [sabnzbd/sabnzbd#900]
Hey guys,

I have an issue with current 2.0.0 release.

I've set to download a movie through Radarr that periodically scan the history to see if the download completed / failed. I've set up Radarr to ask Sab to deleted failed jobs with their associated files.

The issue is triggered with a password protected release. Here's the edited logs : 

```
INFO::[__init__:677] Adding Password.Protected.Release-Group.nzb
INFO::[misc:893] Creating directories: /usenet/zzIncomplete/Password.Protected.Release-Group
INFO::[postproc:313] Starting Post-Processing on Password.Protected.Release-Group => Repair:True, Unpack:True, Delete:True, Script:None, Cat:radarr
INFO::[postproc:626] Starting verification and repair of Password.Protected.Release-Group
INFO::[newsunpack:1018] Quick-check for 88ewH8Sf.7z is OK, skipping repair
INFO::[newsunpack:1092] Deleting /usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.par2
INFO::[postproc:721] Verification and repair finished for Password.Protected.Release-Group
INFO::[misc:893] Creating directories: /usenet/movies_radarr/Password.Protected.Release-Group
INFO::[postproc:386] Running unpack_magic on Password.Protected.Release-Group
:DEBUG::[newsunpack:1772] build_filelists(): 7zips: [u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.010', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.002', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.004', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.005', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.003', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.009', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.013', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.011', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.001', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.006', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.007', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.008', u'/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.012']
INFO::[newsunpack:270] 7za starting on /usenet/zzIncomplete/Password.Protected.Release-Group
INFO::[newsunpack:882] Starting extract on 7zip set/file: /usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z
DEBUG::[newsunpack:958] Starting 7za: ['/usr/bin/7za', 'x', '-y', '-aou', '-tsplit', '-ssc', '-p', '-o/usenet/movies_radarr/Password.Protected.Release-Group', '/usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.001']
DEBUG::[newsunpack:964] 7za output:
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: /usenet/zzIncomplete/Password.Protected.Release-Group/88ewH8Sf.7z.001

Extracting  88ewH8Sf.7z

Everything is Ok

Size:       9386477516
Compressed: 9386477516

INFO::[newsunpack:273] 7za finished on /usenet/zzIncomplete/Password.Protected.Release-Group
INFO::[newsunpack:270] 7za starting on /usenet/zzIncomplete/Password.Protected.Release-Group
2017-04-16 09:39:48,614::INFO::[newsunpack:882] Starting extract on 7zip set/file: /usenet/movies_radarr/Password.Protected.Release-Group/88ewH8Sf.7z
2017-04-16 09:39:48,614::DEBUG::[newsunpack:958] Starting 7za: ['/usr/bin/7za', 'x', '-y', '-aou', '-t7z', '-ssc', '-p', '-o/usenet/movies_radarr/Password.Protected.Release-Group', '/usenet/movies_radarr/Password.Protected.Release-Group/88ewH8Sf.7z']
2017-04-16 09:39:48,913::DEBUG::[newsunpack:964] 7za output:
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: /usenet/movies_radarr/Password.Protected.Release-Group/88ewH8Sf.7z

Error: Can not open encrypted archive. Wrong password?

ERROR::[newsunpack:923] Unpacking failed, archive requires a password (88ewH8Sf.7z)
INFO::[newsunpack:273] 7za finished on /usenet/zzIncomplete/Password.Protected.Release-Group
INFO::[postproc:391] unpack_magic finished on Password.Protected.Release-Group
```

Then Radarr scanned the history list and asked for a delete : 

```
DEBUG::[interface:486] API-call from 127.0.0.1 [Radarr/0.2.0.614 (Linux 4.2)] {'apikey': u'(removed)', 'name': u'delete', 'value': u'SABnzbd_nzo_xxxxx', 'del_
files': u'1', 'mode': u'history', 'output': u'json'}
```

Every temp files in the working path (/usenet/zzIncomplete) were deleted if any were left but the password protected file in was already moved to the final destination and was left behind.

I think that as there were 2 levels of 7zip, the 1st step remuxed the multipart 7z files to one in the final directory. The 2nd step was stucked on the password.

Maybe you should deleted from both paths when del_files is true and job is failed ?

Thanks !

**Comment by Ninjouz** [comment]
Another one, but I think it's pretty much related to the 2step remux / extract with password thing.

I tried to download manually the release and found the password.
So I let it failed by intent in order to use the Retry button which show the popup where u can put the password.

But it failed. Here's the debug logs : 

```
DEBUG::[nzbqueue:200] Repair job Password.Protected.Release-Group without stored NZB
INFO::[misc:1422] Cannot remove folder /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__
INFO::[misc:1422] Cannot remove folder /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__
INFO::[__init__:929] /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__/__renames__ missing
INFO::[nzbstuff:1090] File eLn9R82e.nfo added to job
INFO::[postproc:87] Saving postproc queue
INFO::[__init__:971] Saving data for postproc2.sab in /home/sabnzbd/sabnzbdplus/admin/postproc2.sab
INFO::[postproc:313] Starting Post-Processing on Password.Protected.Release-Group => Repair:True, Unpack:True, Delete:True, Script:detox.sh, Cat:movies
INFO::[postproc:626] Starting verification and repair of Password.Protected.Release-Group
DEBUG::[__init__:933] Loading data for __verified__ from /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__/__verified__
INFO::[postproc:669] No par2 sets found, running obfuscated check on Password.Protected.Release-Group
DEBUG::[postproc:680] Checking par2 signature of eLn9R82e.nfo
INFO::[postproc:703] No par2 sets for Password.Protected.Release-Group
DEBUG::[newsunpack:1769] build_filelists(): joinables: []
DEBUG::[newsunpack:1770] build_filelists(): zips: []
DEBUG::[newsunpack:1771] build_filelists(): rars: []
DEBUG::[newsunpack:1772] build_filelists(): 7zips: []
DEBUG::[newsunpack:1773] build_filelists(): ts: []
DEBUG::[__init__:899] Saving data for __verified__ in /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__
INFO::[postproc:721] Verification and repair finished for Password.Protected.Release-Group
INFO::[misc:893] Creating directories: /usenet/HD/Password.Protected.Release-Group.1
INFO::[postproc:386] Running unpack_magic on Password.Protected.Release-Group
DEBUG::[newsunpack:1769] build_filelists(): joinables: []
DEBUG::[newsunpack:1770] build_filelists(): zips: []
DEBUG::[newsunpack:1771] build_filelists(): rars: []
DEBUG::[newsunpack:1772] build_filelists(): 7zips: []
DEBUG::[newsunpack:1773] build_filelists(): ts: []
INFO::[postproc:391] unpack_magic finished on Password.Protected.Release-Group
DEBUG::[misc:918] Moving. Old path: /usenet/zzIncomplete/Password.Protected.Release-Group/eLn9R82e.nfo New path: /usenet/HD/.1080p.BluRay.x264-LOST.1/eLn9R82e.nfo Overwrite: 0
DEBUG::[misc:1351] Renaming "/usenet/zzIncomplete/Password.Protected.Release-Group/eLn9R82e.nfo" to "/usenet/HD/Password.Protected.Release-Group.1/eLn9R82e.nfo"
ERROR::[postproc:551] Post Processing Failed for Password.Protected.Release-Group ()
INFO::[postproc:553] Traceback:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 483, in process_job
    dirname, job_result)
  File "/usr/share/sabnzbdplus/sabnzbd/newsunpack.py", line 175, in external_processing
    'avg_bps': int(nzo.avg_bps_total / nzo.avg_bps_freq),
ZeroDivisionError: integer division or modulo by zero
INFO::[misc:1249] Found a password that was set by the user: xxxxxxxx
INFO::[misc:1249] Found a password that was set by the user: xxxxxxxx
INFO::[misc:1249] Found a password that was set by the user: xxxxxxxx
INFO::[postproc:583] Cleaning up Password.Protected.Release-Group (keep_basic=True)
INFO::[__init__:962] /usenet/zzIncomplete/Password.Protected.Release-Group/__ADMIN__/SABnzbd_nzf_Txf_gq removed
INFO::[postproc:87] Saving postproc queue
INFO::[__init__:971] Saving data for postproc2.sab in /home/sabnzbd/sabnzbdplus/admin/postproc2.sab
INFO::[downloader:300] Post-processing finished, resuming download
```

**Comment by thezoggy** [comment]
to avoid ZeroDivisionError we either need to try/catch for it.. or just look for it in advanced like:
`'avg_bps': = int(nzo.avg_bps_total / nzo.avg_bps_freq) if nzo.avg_bps_freq != 0 else 0`

**Comment by Safihre** [comment]
Have fixed the ZeroDivisionError.

Regarding the deleting:
While I understand your idea, it might not work for everybody. What if someone downloaded a whole season of a show and we only succeeded to unpack 22 out of 23 episodes. Would we really want to delete everything just because of this 1 broken show?
In this case, where a chunk of unpacking was actually successful, it is too hard to determine for SAB what is wrong with the second part and if it's safe to delete. So we kind of just want to user to figure it out and take manual action.

**Comment by Ninjouz** [comment]
Yeah, I understand what you mean.
In my case, I try to be totally automated and as such I ask Sonarr/Radarr to delete failed download (because there can be a bunch of "old" nzb not present in my usenet provider and thus spamming my history).
So I cant really be aware of any failed download unless I'm monitoring Sab and it's download folder permanently.
I mean if Sonarr wanted to download a season pack that went well apart from one episode, I wouldn't see it and 22 files out of 23 would stay in my download folder forever until my cleaning job passes days after.

But yeah it's a tough case to solve and maybe not so important after all. I just want your software to be perfect as a long time user ;)

Anyway, did you have a look about post 2 with the retry button not working with the second 7z file ?

Thanks !!

**Comment by Safihre** [comment]
Can you maybe share or send me the NZB? Safihre@sabnzbd.org

**Comment by Safihre** [comment]
Received NZB and solved the problem and also improved 7zip support a bit.
