### ISSUE TITLE
Problem building python2-sabyenc 3.0.2-3 on Arch linux

### ISSUE THREAD

**Issue by assafalon** [sabnzbd/sabnzbd#913]
Hi,

I am having trouble installing python2-sabyenc 3.0.2-3 using yaourt. 
It worked fine until about a week ago, then I reinstalled and it is unable to build ever since with a weird random number related issue.

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from setuptools import setup, Extension
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/usr/lib/python2.7/email/utils.py", line 27, in <module>
    import random
  File "/usr/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/usr/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by assafalon** [comment]
[SOLVED]
This is apparently a python python-2-2.7.13-2 issue.
I was able to solve this by downgrading to python-2-2.7.13-1 as suggested here:
[https://archlinuxarm.org/forum/viewtopic.php?f=15&t=11647](url)

**Comment by thezoggy** [comment]
to note from that url, `import random` fails on that version of arch / python.
```
% python2
Python 2.7.13 (default, Apr 24 2017, 20:01:05)
[GCC 6.3.1 20170306] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import random
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/usr/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
```

not sure if we want to code a try/catch to exit and warn people about it?
