### ISSUE TITLE
URLGRABBER CRASHED

### ISSUE THREAD

**Issue by Veldkornet** [sabnzbd/sabnzbd#914]
I get this error every now and then...
```
URLGRABBER CRASHED
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/urlgrabber.py", line 220, in run
    if 'TypeError: argument of type 'NoneType' is not iterable
```
If I just retry the .nzb again, it seems to work properly.

Using the [linuxserver.io docker image](https://hub.docker.com/r/linuxserver/sabnzbd/).
SABnzbd Version:	2.0.0 [55c4bef]
Python Version:	2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] [UTF-8]

**Comment by thezoggy** [comment]
can you post the actual log as that traceback should have a few more lines..  and question about workflow, do you see this happen when sab is being feed a url via a 3rd party app?

**Comment by Veldkornet** [comment]
The nzb's come from SickRage. I've seen that it's more common when it all of a sudden needs to fetch a few, like 4-5 for example. 

I'll reproduce the issue and get the log

**Comment by Safihre** [comment]
@Veldkornet Any news on this? Logs would be helpful, maybe we can see what error is not caught. It's this line, so clearly it's not getting data:
```python
                if '<nzb' in data and misc.get_ext(filename) != '.nzb':
```

**Comment by Safihre** [comment]
Then it wouldn't give a `NoneType` error, since it would just be an empty string `''`.

**Comment by Veldkornet** [comment]
Still waiting for it to happen again, the logs were purged after the I had initially created the issue

**Comment by Safihre** [comment]
@Veldkornet Did not happen again?

**Comment by Veldkornet** [comment]
Nope, looks to have been resolved indirectly by something. I'll close the issue for now.

**Comment by labrys** [comment]
@Safihre Actually I'm getting this still on 43c238b7f117fdc0ea4a8a2ca9ba77667bcbdf75. URLs are all from third-party app (Medusa).

**Comment by Safihre** [comment]
@labrys Did it move the job to the history with `URL Fetching failed`?

**Comment by labrys** [comment]
I'm not sure, the logs had rolled over.  I think it happens when a backlog search triggers and adds a lot of downloads in a short period.  I'll try and snag logs for the next time it happens.

**Comment by Safihre** [comment]
I think I have caught the issue now (maybe do a `git pull` when you have the time) so will leave this open then for few more weeks to see if it re-occurs.

**Comment by labrys** [comment]
Here's the most recent crash.
```
2017-06-23 07:51:12,799::DEBUG::[__init__:915] Loading data for SABnzbd_nzf_taydrp from \\?\G:\tmp\nzb\downloads\Girls.S06E08.What.Will.We.Do.This.Time.About\__ADMIN__\SABnzbd_nzf_taydrp
2017-06-23 07:51:12,821::INFO::[__init__:943] \\?\C:\Users\Tech\AppData\Local\sabnzbd\admin\future\SABnzbd_nzo_zvbdoo removed
2017-06-23 07:51:12,825::INFO::[nzbqueue:271] Saving queue
2017-06-23 07:51:12,828::INFO::[__init__:951] Saving data for queue10.sab in C:\Users\Tech\AppData\Local\sabnzbd\admin\queue10.sab
2017-06-23 07:51:12,832::ERROR::[urlgrabber:271] URLGRABBER CRASHED
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\urlgrabber.py", line 220, in run
    if '<nzb' in data and misc.get_ext(filename) != '.nzb':
TypeError: argument of type 'NoneType' is not iterable
2017-06-23 07:51:12,861::DEBUG::[urlgrabber:272] URLGRABBER Traceback:
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\urlgrabber.py", line 220, in run
    if '<nzb' in data and misc.get_ext(filename) != '.nzb':
TypeError: argument of type 'NoneType' is not iterable
2017-06-23 07:51:12,987::DEBUG::[decoder:114] Decoding x0xjOwANKZ@1491235312.189890eVBpnXjejviMP
2017-06-23 07:51:12,996::DEBUG::[nzbstuff:1264] Download Quality: enough=True, have=1005044628, need=909952366, ratio=1.1045024614
2
```

**Comment by labrys** [comment]
Also for some reason clicking on show logging in the UI returns logs from Jun 20th not current logs.

**Comment by Safihre** [comment]
Did you do a `git pull` ? I made an update to fix this yesterday, is it included?

**Comment by labrys** [comment]
No as I mentioned I had not yet done a git pull (was waiting on the log for the other issue first).

**Comment by Safihre** [comment]
@labrys Did you get any more of these in the past 2 weeks?

**Comment by labrys** [comment]
No haven't had any of these lately.
