### ISSUE TITLE
Insert disk with <RARFILE> [C]ontinue, [Q]uit

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#984]
Disk out of space caused scrolling error "Insert disk with <RARFILE> [C]ontinue, [Q]uit".  Shutdown from gui and CTL-C did not end task.  Had to manually kill the process.

**Comment by Safihre** [comment]
So the Complete folder ran out of disk space, right? 
And rolling error, you mean like constantly new sabnzbd Warning/Error in the interface?

**Comment by Safihre** [comment]
Which version (commit) was this on actually?

**Comment by labrys** [comment]
My temporary download folder and complete folder are both on the same drive, which ran out of space.  The scrolling error was in the shell stdout (i run from source on windows with an open shell window).
This was on commit 56bf484e77e65845685eb57e4168c5b4116d4767.

**Comment by Safihre** [comment]
@labrys Maybe you can do a `git pull`?
Added some changes, let me know if this happens again when you run out of disk-space.

**Comment by labrys** [comment]
Ok will do, but I don't often run out of disk space, maybe if I get the time I'll try to force it.

**Comment by labrys** [comment]
Finally got a chance to force the out of disk space error (with 28d4f527b87932c86d89c17fec2c0f2ae6ca7418).  This time I got the following scrolling in stdout:
```
2017-08-13 18:40:56,996::ERROR::[__init__:876] Failure in tempfile.mkstemp
2017-08-13 18:40:56,999::INFO::[__init__:877] Traceback:
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\__init__.py", line 870, in get_new_id
    fd, path = tempfile.mkstemp('', 'SABnzbd_%s_' % prefix, folder)
  File "C:\Python\2.7.13\lib\tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\Python\2.7.13\lib\tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 28] No space left on device
```
And the following in the UI:
![image](https://user-images.githubusercontent.com/1867464/29253938-d6bac10a-8057-11e7-9b28-5204cf94366d.png)

Could not shut down from the UI nor CTRL-C from shell.

**Comment by labrys** [comment]
Looks like I get the same thing with 3188eef92d2e2b699145a65d305f638bfa82be96

**Comment by Safihre** [comment]
Wow, then you really must have almost 0kb left. That is a case we would have to catch in every possible `open()` call.. That's way too much.

The new Assembler code will stop downloading before writing, preventing really running to 0kb.

**Comment by labrys** [comment]
It looks like it only starts scrolling the errors after I log in to the UI.  Also SAB is the only process that was accessing that drive during the test (i filled the drive to less than 200mb first then launched SAB).

**Comment by labrys** [comment]
Possibly related due to running so low on space:
```
2017-08-13 18:51:19,729::ERROR::[__init__:924] Loading G:\tmp\nzb\downloads\Preacher.S02E08.Holes.1080p.REPACK.AMZN.WEB-D\__ADMIN__\SABnzbd_nzo_7_fxp2 failed
2017-08-13 18:51:19,744::INFO::[__init__:925] Traceback:
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\__init__.py", line 917, in load_data
    data = cPickle.load(data_file)
BadPickleGet: 145ÿ
```
A single bad unpickle on start.

**Comment by Safihre** [comment]
Will change the `get_new_id` code to not run forever, just in case.

**Comment by labrys** [comment]
That may have fixed it.  I get this now:
![image](https://user-images.githubusercontent.com/1867464/29254028-2942fcd8-805a-11e7-82b1-f9f5d6c526b6.png)
And no scrolling errors.  I'll test a few times and let you know.

**Comment by thezoggy** [comment]
why dont we just set a default (4G) for:
config > folders > Minimum Free Space for Temporary Download Folder

that way it would have prevented a lot of this from ever happening... that way people can plan ahead and know of this setting to better fine tune if they really want to run sab and download to a space starved area.

**Comment by labrys** [comment]
In my case my Temp and Completed folder are on the same drive, but my config, etc are on a different drive.  Also thoughts on making the default limit configurable?  Running SAB on a low-end machine for low-res downloads 4G may not be needed (e.g. a router/raspberry pi as the download agent).

**Comment by labrys** [comment]
Lol nvm, just noticed it already is 
![image](https://user-images.githubusercontent.com/1867464/29254164-562cc834-805d-11e7-84f5-31297f271143.png)

**Comment by thezoggy** [comment]
looks like you may just want to populate that with a value... :)

**Comment by labrys** [comment]
Not really necessary, I nearly never run out of space, the time that caused this issue was a stupid-human-error (fat-fingered target drive for a backup).  Of course it wouldn't hurt though 😄.

**Comment by thezoggy** [comment]
no good comes out of about any box when it has 0 space free on the os drive..  why i suggest we have a default value to help safeguard worse things than 'sab stopped downloading'. as when you have 0 free space.. sab wont be happy on shutting down if it cant write the .ini/admin files.

**Comment by Safihre** [comment]
4G would be too high, but I do agree that Sab wasn't very smart and just wrote to disk even though it knew it was full. I changed that now to only write when it knows there is space and already pause otherwise. 
They only thing that isn't checked is if there is enough space to unpack, before it begins unpacking.

**Comment by Safihre** [comment]
Seems we handle is sufficiently for now.

**Comment by labrys** [comment]
I did get some more `tempfile.mkstemp` errors, but they did not scroll endlessly, just a single error per occurrence.  I agree that it is now handled.
