### ISSUE TITLE
Bad Character Range error during par2_repair

### ISSUE THREAD

**Issue by Sphericus** [sabnzbd/sabnzbd#990]
Getting the following error with version 2.1.0 on Windows with Python version 2.7.13 (64-bit)

::ERROR::[newsunpack:1103] Error bad character range while running par2_repair on set [tag] Show Name! - episode [tag][1000-codec][checksum]
::INFO::[newsunpack:1104] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\newsunpack.pyo", line 1078, in par2_repair
  File "sabnzbd\newsunpack.pyo", line 1633, in MultiPar_Verify
  File "sabnzbd\misc.pyo", line 107, in globber
  File "fnmatch.pyo", line 43, in fnmatch
  File "fnmatch.pyo", line 82, in fnmatchcase
  File "re.pyo", line 194, in compile
  File "re.pyo", line 251, in _compile
error: bad character range

Thank you.

**Comment by Safihre** [comment]
Strange. Could you send me the NZB at safihre@sabnzbd.org?

**Comment by Safihre** [comment]
Problem found:
The `setname` has `[ ]` in it, which are special characters to indicate a range in `fnmatch`. 
https://bugs.python.org/issue738361

Escaping them does not seem to work in this function:
```
~\Documents\GitHub\sabnzbd [develop ≡]> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> fnmatch.fnmatch('.','[FFF] Gakkou Gurashi! - 02 [BD][1080p-FLAC][73F4A7A0].par2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "C:\Python27\lib\fnmatch.py", line 82, in fnmatchcase
    _cache[pat] = re_pat = re.compile(res)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
>>> aa='[FFF] Gakkou Gurashi! - 02 [BD][1080p-FLAC][73F4A7A0].par2'
>>> aa=aa.replace(']','\]')
>>> aa=aa.replace('[','\[')
>>> aa=aa.replace('!','\!')
>>> fnmatch.fnmatch('.',aa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "C:\Python27\lib\fnmatch.py", line 82, in fnmatchcase
    _cache[pat] = re_pat = re.compile(res)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
>>>
```
